### ISSUE TITLE
[CON-220] 💫 Good first issues 💫

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1009]
This is a maintained list of bugs/improvements that are both particularly important and that can be tackled without too much prior knowledge of the Continue codebase (or at least they are very well defined). I hope this can be a starting point for anyone interested in making a large impact. Please feel free to suggest issues that you think are a good fit.

- [X] [https://github.com/continuedev/continue/issues/1010](https://github.com/continuedev/continue/issues/1010)
- [ ] [https://github.com/continuedev/continue/issues/1011](https://github.com/continuedev/continue/issues/1011)
- [X] [https://github.com/continuedev/continue/issues/1012](https://github.com/continuedev/continue/issues/1012)
- [ ] [https://github.com/continuedev/continue/issues/1013](https://github.com/continuedev/continue/issues/1013)
- [ ] [https://github.com/continuedev/continue/issues/1042](https://github.com/continuedev/continue/issues/1042)
- [ ] [https://github.com/continuedev/continue/issues/1067](https://github.com/continuedev/continue/issues/1067)
- [ ] [https://github.com/continuedev/continue/issues/1068](https://github.com/continuedev/continue/issues/1068)
- [ ] [https://github.com/continuedev/continue/issues/1077](https://github.com/continuedev/continue/issues/1077)
- [X] [https://github.com/continuedev/continue/issues/1073](https://github.com/continuedev/continue/issues/1073)
- [X] [https://github.com/continuedev/continue/issues/1050](https://github.com/continuedev/continue/issues/1050)
- [ ] override apiKey with custom requestOptions.headers instead of other way around: [https://github.com/continuedev/continue/issues/1046#issuecomment-2027819790](https://github.com/continuedev/continue/issues/1046#issuecomment-2027819790)
- [ ] [https://github.com/continuedev/continue/issues/1106](https://github.com/continuedev/continue/issues/1106)
- [X] [https://github.com/continuedev/continue/issues/1103](https://github.com/continuedev/continue/issues/1103)
- [ ] [https://github.com/continuedev/continue/issues/1344](https://github.com/continuedev/continue/issues/1344)
- [ ] [https://github.com/continuedev/continue/issues/768](https://github.com/continuedev/continue/issues/768)
- [X] [https://github.com/continuedev/continue/issues/1346](https://github.com/continuedev/continue/issues/1346)
- [ ] [https://github.com/continuedev/continue/issues/1347](https://github.com/continuedev/continue/issues/1347)
- [ ] [https://github.com/continuedev/continue/issues/1290](https://github.com/continuedev/continue/issues/1290)
- [ ] Add support for all Bedrock models (right now only Anthropic models work, because different parameters are expected for different models): [https://github.com/continuedev/continue/issues/1260](https://github.com/continuedev/continue/issues/1260)
- [ ] [https://github.com/continuedev/continue/issues/1184](https://github.com/continuedev/continue/issues/1184)
- [ ] [https://github.com/continuedev/continue/issues/1426](https://github.com/continuedev/continue/issues/1426)
- [ ] [https://github.com/continuedev/continue/issues/1453](https://github.com/continuedev/continue/issues/1453)

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-220](https://linear.app/continue/issue/CON-220/💫-good-first-issues-💫)</sub>

**Comment by battisbog** [comment]
Hi. Is this issue still open? I want to work on this.

**Comment by sestinj** [comment]
@battisbog Many of these issues are still open, yes! Which are you interested in trying, I'm happy to point you in the right direction in the codebase

**Comment by sestinj** [comment]
Closing this in favor of filtering by "Good First Issue" or seeing the suggestions board here: https://github.com/orgs/continuedev/projects/2
