### ISSUE TITLE
[CON-222] "Headers not defined" in older versions of VS Code

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1011]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue:*
- IDE:VS Code (older versions, don't know exactly the cutoff)
```

### Description

Older versions of VS Code (presumably because they run older versions of Node.js) cause this "Headers not found" error to appear as a popup. [Here](https://github.com/continuedev/continue/issues/875) is an example of this happening to a user. Very reliably, upgrading VS Code solves this problem.

There might be an obvious change we can make to ensure compatibility.

If not, we might be able to handle the error more gracefully.

If neither, it would be useful to have brief documentation to share with folks who encounter the problem (explaining why the Node compatibility exists).

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-222](https://linear.app/continue/issue/CON-222/headers-not-defined-in-older-versions-of-vs-code)</sub>

**Comment by lokesh-couchbase** [comment]
<img width="1639" alt="image" src="https://github.com/continuedev/continue/assets/113521973/4c237cf3-e780-437c-ae4c-ccd6a0e0c0ff">

I tried running VSCode v1.70 with latest, pre-release, a couple month old release and I was not able to reproduce it.

System - MacOs Sonoma 14.3.1 - Apple Silicon (Arm based)

If possible, can anyone help me in checking if it still can be reproduced and I will try to help on this.
