### ISSUE TITLE
[CON-224] /edit doesn't acknowledge highlighted code after retrying

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1013]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Mac
- Continue:0.9.91
- IDE:VS Code
```

### Description

Retrying an /edit slash command leads to Continue thinking that no code is highlighted. This is probably related to the way that state is managed in Redux. You can see where the error is thrown [here](https://github.com/continuedev/continue/blob/221d020053ad36ca39dd156776dd711a6920f77f/core/commands/slash/edit.ts#L227-L230), so following this variable backward will lead to the root cause

https://github.com/continuedev/continue/assets/33237525/b0415256-1657-4543-a564-46cc2128e668

### To reproduce

1. Highlight code
2. Type something like "/edit add comments"
3. Let it run, then close the diff window
4. Try to edit the original message and press enter again

<sub>[CON-224](https://linear.app/continue/issue/CON-224/edit-doesnt-acknowledge-highlighted-code-after-retrying)</sub>

**Comment by Nithishvb** [comment]
Hey @sestinj i would like to work on this bug, could you please assign this to me.

**Comment by sestinj** [comment]
Absolutely! And let me know if I can help

**Comment by Nithishvb** [comment]
Sure 👍
