### ISSUE TITLE
There is a merge conflict in the 'main' branch; please resolve it.

### ISSUE THREAD

**Issue by xydz** [continuedev/continue#1019]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
```

### Description

![image](https://github.com/continuedev/continue/assets/80254186/76d5ba22-0ce6-40e8-aee6-f11065ff04b8)

**Comment by inimaz** [comment]
This one looks like it can be closed @sestinj

**Comment by xydz** [comment]
[赞]
