### ISSUE TITLE
Surpport ollama nomic-embed-text embedding model customization

### ISSUE THREAD

**Issue by mintisan** [continuedev/continue#1025]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

 By default, all embeddings are calculated locally with `all-MiniLM-L6-v2` and stored locally in `~/.continue/index`.

However, the default embedding effect is not good. Can we consider supporting custom embedding models, such as https://ollama.com/library/nomic-embed-text?

like as below:

```
{
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text",
     "apiBase": "http://100.122.227.134:11434"
  }
}
```

**Comment by shashade2012** [comment]
@mintisan 
Hi , Is it ready for support this? It seems that I configure nomic-embed-text in config.json. There is no message to 11434.
How to make it work? Thanks.
