### ISSUE TITLE
codebase error ：Error getting context items from codebase: Error: Warning: No results found for @codebase context provider.

### ISSUE THREAD

**Issue by mintisan** [continuedev/continue#1026]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: v0.8.22
- IDE:Version: 1.87.2 (Universal)
```

### Description

I encountered the following error after changing the embedding model as title.

<img width="490" alt="image" src="https://github.com/continuedev/continue/assets/9136049/42e77505-d8a0-4af7-b522-b75e39d0b945">

```
{
  "slashCommands":[
    {
      "name": "edit",
      "description": "Edit highlighted code"
    },
    {
      "name": "comment",
      "description": "Write comments for the highlighted code"
    },
    {
      "name": "share",
      "description": "Download and share this session"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a commit message for the current changes"
    },
    {
      "name": "so",
      "description": "Reference StackOverflow to answer the question"
    }
  ],
  "contextProviders":[
    { "name": "code" },
    { "name": "open", "params": { "onlyPinned": true } },
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 25,
        "nFinal": 5,
        "useReranking": true
      }
    },
    { "name": "folder" },
    { "name": "search" },
    { "name": "tree" },
    { "name": "outline" },
    { "name": "highlights" },
    { "name": "docs" },
    { "name": "terminal" },
    { "name": "diff" }
  ],
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text",
    "apiBase": "http://100.122.227.134:11434"
  },
  "models": [
    {
      "title": "DeepSeek-33b",
      "provider": "ollama",
      "model": "deepseek-coder:33b",
      "apiBase": "http://100.122.227.134:11434"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "ollama",
    "model": "deepseek-coder:33b-base-q4_K_S",
    "apiBase": "http://100.122.227.134:11434"
  }
}
```

**Comment by mintisan** [comment]
can't use * in ignore file

```
*

!*.c
!*.h
```

**Comment by maxime1992** [comment]
Hi, I've got the exact same error and I don't think I've got any ignore file at all. I noticed in your repo you have a `.continueignore` file so I've tried to put one at the root of my repo as well and just added `node_modules/**/*` but even if it's empty I still get the error message. Any idea? Thanks!

**Comment by maxime1992** [comment]
Oh, maybe it's a slightly different one? 

![image](https://github.com/continuedev/continue/assets/4950209/80772261-80e2-428a-8417-34247a6c3648)

**Comment by maxime1992** [comment]
Umh ok I thought this would be there by default but apparently you need to edit the continue config to add

```
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 25,
        "nFinal": 5,
        "useReranking": true
      }
    }
```

See https://continue.dev/docs/walkthroughs/codebase-embeddings

**Comment by matthieuHenocque** [comment]
I have the same exact problem.

I reinstall everything on my machine and noticed the config.json file was different from previous versions. For instance, there wasn't any default "embeddingsProvider" value (before that it was "transformer.js", as mentioned in Continue.dev documentation)

I can select a file in the context selector, but anything else won't work. The @code context is empty. I tried everything mentioned in the documentation without any luck.

I also tried different "embeddingsProvider".

A few weeks ago I animated a presentation of the feature for my company and it was almost working. I don't know what to do now and feel pretty embarrassed to be honest.

**Comment by gediminaskv** [comment]
> I have the same exact problem.
> 
> I reinstall everything on my machine and noticed the config.json file was different from previous versions. For instance, there wasn't any default "embeddingsProvider" value (before that it was "transformer.js", as mentioned in Continue.dev documentation)
> 
> I can select a file in the context selector, but anything else won't work. The @code context is empty. I tried everything mentioned in the documentation without any luck.
> 
> I also tried different "embeddingsProvider".
> 
> A few weeks ago I animated a presentation of the feature for my company and it was almost working. I don't know what to do now and feel pretty embarrassed to be honest.

For me helped that I have changed `embeddingsProvider` to `openai` with my `apiKey`

**Comment by maxime1992** [comment]
Honestly I don't remember and just overall stopped using local llm for dev as it was burning my laptop, good luck though

**Comment by easz** [comment]
It happens to me as well. It seldom works as I expect and only works sometimes after re-starting vs code, re-enabling continue extension or even re-indexing. It is hard to use it at all. :(

**Comment by Sci-Fist** [comment]
for me the solution is to also give it @repomap. the documentation states that depending on the model u are using they include the repo by default [https://docs.continue.dev/customize/deep-dives/codebase] -> at repository map(bottom).

Which got me thinking:
I am using local models exclusive currently and the continue/codebase/documentation states that different model familys have that capability so i used lama3.1 and told him to make a file tree structure of my codebase (@repomap entire codebase ) and with that it got way more precise.

Conclusion:
- I am currently trying out to use the @repomap in the prompt.
- Also i tried different models that derived from sayd familiys stated in the continue documentation.
it would be nice to have the option to load prompts by default in new chats like Zed does for example [https://zed.dev/]

**Comment by ecartz** [comment]
For me, restarting Visual Studio Code made the error disappear.  That doesn't seem to work for everyone, but it's something to try to see if it works for you.
