### ISSUE TITLE
apiBase is set to a different computer within Continue's config.json but I get ECONNREFUSED 127.0.0.1

### ISSUE THREAD

**Issue by LombudXa** [continuedev/continue#1047]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 23h2
- Continue: 0.8.22
- IDE: VS Code 1.87.2
```

### Description

As you can see from the screenshot (maybe you have to zoom a bit), it pretty much describes the problem. When I click on Continue, then on settings where I can edit Continue's config.json and I start editing something, it tries to connect to the LLM using 127.0.0.1:11434 instead of the configured IP. As you can see in the screenshot, I have set apiBase to my remote machine where the LLM is located. That all works fine. I can also interact with it but either I don't know how to change that localhost request or it's probably a bug. Either way, would be happy to get to know how to change it myself or that you could look into it. Thanks.
![Untitled-1](https://github.com/continuedev/continue/assets/13348327/7616da14-9cb0-44ce-ad43-a446c12abf4f)

### To reproduce

1. Ollama and LLM has to be installed on a remote computer
2. Click on Continue
3. Click on the settings button called Config (this opens the config.json)
4. Start typing something (as soon as you do, it will try to connect to 127.0.0.1, however, my LLM is not locally but on a remote machine on the same LAN)

### Log output

```Shell
console.ts:137 [Extension Host] Error generating autocompletion:  FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (c:\Users\<USERNAME>\.vscode\extensions\continue.continue-0.8.22-win32-x64\out\extension.js:25962:14)
	at ClientRequest.emit (node:events:526:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
p @ console.ts:137
notificationsAlerts.ts:42 request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
c @ notificationsAlerts.ts:42
4console.ts:137 [Extension Host] Error generating autocompletion:  FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (c:\Users\<USERNAME>\.vscode\extensions\continue.continue-0.8.22-win32-x64\out\extension.js:25962:14)
	at ClientRequest.emit (node:events:526:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by EkremSel** [comment]
yes having the same issue after updating vscode insiders.

**Comment by sestinj** [comment]
@LombudXa This is coming from Continue's tab-autocomplete feature. If you'd like to set this up there is documentation [here](https://continue.dev/docs/walkthroughs/tab-autocomplete#setting-up-with-ollama-default), or if you'd like to turn it off you can un-check the "Continue: Enable Tab-autocomplete" box in VS Code settings

**Comment by LombudXa** [comment]
Okay, thanks for the information. I look into it.

**Comment by LombudXa** [comment]
It works with the autocomplete feature now. Thanks.

**Comment by wanlou125** [comment]
這篇文章解決我現在的問題，Thanks!
