### ISSUE TITLE
Error: Execution of Slash Command without Additional Text in v0.9.99

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#1049]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: 0.9.99
- IDE: VSCode
```

### Description

When a `slashCommand` is executed without any additional text, `Continue` begins to throw an error.
This issue started with version `v0.9.99` (2024-03-29T16:51:07.103Z).

This issue is very similar to Issue #869, but I am not reopening that one.

Issue occurs regardless of my setup, `~/.continue` folder was temporarily moved.

The error message is:

```md
Cannot read properties of undefined (reading 'content')
```

<img src="https://github.com/continuedev/continue/assets/92653266/81f4494c-fa5d-48ab-9e84-79074961e8e0" width="500">

---

This issue appears to have been introduced with commit: 4053f1ad60a61a32bbd3a5543e373f4be4e36508

It is possible that `next.value` can be undefined.

https://github.com/continuedev/continue/blob/2f67ded712f15f007acae7be2a42fa5738a74364/extensions/vscode/src/webviewProtocol.ts#L78-L80

### To reproduce

1. Enter a slash command in the `continue` GUI, without adding any text or context, for example, `/edit`.
2. Press <kbd>⏎ Enter</kbd>
3. Notice the error message.

### Log output

```Shell
workbench.desktop.main.js:148 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "d318dfde-651d-451f-97e7-a86887e8cecb",
    "messageType": "command/run",
    "data": {
      "input": "/edit ",
      "history": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "/edit "
            }
          ]
        }
      ],
      "modelTitle": "GPT-4 (Free Trial)",
      "slashCommandName": "edit",
      "contextItems": [],
      "historyIndex": 0,
      "selectedCode": []
    }
  }
}
S @ workbench.desktop.main.js:148
$logExtensionHostMessage @ workbench.desktop.main.js:1615
_doInvokeHandler @ workbench.desktop.main.js:1615
_invokeHandler @ workbench.desktop.main.js:1615
_receiveRequest @ workbench.desktop.main.js:1615
_receiveOneMessage @ workbench.desktop.main.js:1615
(anonymous) @ workbench.desktop.main.js:1615
_deliver @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:624
V.onmessage @ workbench.desktop.main.js:1638
workbench.desktop.main.js:785 Cannot read properties of undefined (reading 'content')
onDidChangeNotification @ workbench.desktop.main.js:785
(anonymous) @ workbench.desktop.main.js:785
_deliver @ workbench.desktop.main.js:87
_deliverQueue @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:87
addNotification @ workbench.desktop.main.js:785
notify @ workbench.desktop.main.js:1665
(anonymous) @ workbench.desktop.main.js:1608
_showMessage @ workbench.desktop.main.js:1608
$showMessage @ workbench.desktop.main.js:1608
_doInvokeHandler @ workbench.desktop.main.js:1615
_invokeHandler @ workbench.desktop.main.js:1615
_receiveRequest @ workbench.desktop.main.js:1615
_receiveOneMessage @ workbench.desktop.main.js:1615
(anonymous) @ workbench.desktop.main.js:1615
_deliver @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:624
V.onmessage @ workbench.desktop.main.js:1638
```

**Comment by sestinj** [comment]
@LangLangBart just fixed here: https://github.com/continuedev/continue/commit/7d00d132523c5ce8b27239f367cfa9ffaf2e930b

Thanks for catching this!
