### ISSUE TITLE
@folders shows "No results" even though I have a directory in my workspace

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#1067]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS
- Continue: Latest (Pre-release)
- IDE: VS Code
```

### Description

I can't use `@folders` to add context

We should also rename `@folders` to `@folder`, since 1) you are only adding one folder at a time and 2) the config property is "folder" already

### To reproduce

1. Open VS Code with a project that contains directories
2. Type `@folders`
3. See that it says "No results"

**Comment by justinmilner1** [comment]
Starting work on this
