### ISSUE TITLE
Continue cannot be enabled in VSCode after installation

### ISSUE THREAD

**Issue by Iamgood01** [continuedev/continue#1082]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
```

### Description

After installation, there is no button to enable the Continue extension in the active bar on the left side of the Vscode interface. Could you tell me what other way can I enable Continue?
![1712303328083](https://github.com/continuedev/continue/assets/166108437/d672be3a-9830-4e22-9302-db2574694046)

**Comment by sestinj** [comment]
@Iamgood01 It may be possible that Continue has been installed before or that for some other reason it is in the right side bar. To open the Continue panel, you can use the shortcut ctrl+L, or search the command palette (ctrl+shift+p) for Continue.

If neither of these work, there may be an error preventing Continue from loading. If this is the case, there will be more details in the dev tools console (cmd+shift+p, "Toggle Developer Tools") if you wouldn't mind sharing these

**Comment by Iamgood01** [comment]
@sestinj You are right! The interface appears after I type  _ctrl+L_. Thank you! The startup icon is missing on either the left or the right side bar, but I noticed a prompt that popped up when I opened VSCode, and I wonder if it has something to do with the icon not coming out:
![1712390947445](https://github.com/continuedev/continue/assets/166108437/cf24e709-c3b2-4061-966a-d44ce015a511)
