### ISSUE TITLE
Have you heard of VS 2022?

### ISSUE THREAD

**Issue by jalle007** [continuedev/continue#1083]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

**Comment by Iamgood01** [comment]
2022 version?

**Comment by JoepKockelkorn** [comment]
Duplicate of #759
