### ISSUE TITLE
Support changing server base url for ollama 

### ISSUE THREAD

**Issue by zysimplelife** [continuedev/continue#1090]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

This is really a nice plugin for vs code and I like it very much.

However, I have served my ollama in my local network but not in same machine.  It would be more flexible to be able change the hardcoded ip and port for ollama server in this plugin.    

### Solution

Expose configuration for ollama to change ip and port.

**Comment by sestinj** [comment]
Hi @zysimplelife, glad Continue has been a good experience so far : ) Luckily we already have support for changing the base URL. This can be done in `config.json` like so:

```json
{
  "models": [
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "llama2-7b",
      "apiBase": "http://x.x.x.x"
    }
  ]
}
```

**Comment by zysimplelife** [comment]
aha, thanks  then I misunderstood code https://github.com/continuedev/continue/blob/main/core/llm/llms/Ollama.ts#L1
I will try it out and it would be even better to mention it in the document. It seems the document is missing about this parameter https://continue.dev/docs/reference/Model%20Providers/ollama.

**Comment by hs-ye** [comment]
Note that if you misspell the model name, the endpoint will respond with a 404 not found error, which is kind of unhelpful. Spent about an hour banging my head against this before I noticed the issue.

Otherwise all working perfectly!

**Comment by tjwebb** [comment]
where might one find this "config.json" file?

**Comment by hs-ye** [comment]
> where might one find this "config.json" file?

<img width="531" height="436" alt="Image" src="https://github.com/user-attachments/assets/933aa2c3-0a68-4379-9960-ab2fbef84aae" />
It's not very intuitive but this little cog here opens the config.
Should be in your home folder under a ~/.continue/ folder, mine is a config.yaml

**Comment by auspex** [comment]
> > where might one find this "config.json" file?

Should be in your home folder under a ~/.continue/ folder, mine is a config.yaml

Mine only has the YAML file. Has JSON been superceded, or will it use either (every example I've seen is JSON)
