### ISSUE TITLE
Blank screen while running continue extension on code-server

### ISSUE THREAD

**Issue by PhantomKunai** [continuedev/continue#1091]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04.4 LTS x86_64
- Continue: continue-linux-arm64-0.8.23.vsix 
- IDE: Browser based VS Code (code-server : https://github.com/coder/code-server)
```

### Description

Installed the extension and booted it up, see this in the console.
![Screenshot 2024-04-09 105740](https://github.com/continuedev/continue/assets/12585952/f4487427-1db5-45fb-9a69-55c9b1c1fa8f)

Installed the dependancy and re booted, see this error in the console.
![Screenshot 2024-04-09 110236](https://github.com/continuedev/continue/assets/12585952/be1488ed-776d-4069-98b4-1822b3bd8b66)

A video of what i see.
[2024-04-09 10-47-45.webm](https://github.com/continuedev/continue/assets/12585952/f429f01b-fe05-4036-81b9-20d1086e76c6)

### To reproduce

1. Setup a code-server.
2. Install the extension
3. Boot it up.
4. Attempt to open continue sidebar.

**Comment by Extremys** [comment]
I observed the same issue on my side.

**Comment by CHYhave** [comment]
blank too, but different error 
<img width="1380" alt="截屏2024-04-16 下午9 18 35" src="https://github.com/continuedev/continue/assets/54729911/dbba5952-bc41-4171-9175-364401735a98">
<img width="750" alt="截屏2024-04-16 下午9 18 58" src="https://github.com/continuedev/continue/assets/54729911/65790fb9-007d-48cf-9ac2-e5783edd9efb">

**Comment by PhantomKunai** [comment]
@Extremys @CHYhave, is your code-server deployed with http or https?

**Comment by Extremys** [comment]
Hello through https on my side, this is the version exactly:

```
code-server
code-server: v4.21.1
Code: 1.86.1
Commit: 76e6f757580b6c776526ba208fe39d7c86fb3e11
Date: 2024-02-08T20:12:12.739Z (2 mos ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
```

Version of Continue extension is 0.8.15 - 2024-03-05


> > @Extremys @CHYhave, is your code-server deployed with http or https?
> 
> thanks！http



> @Extremys @CHYhave, is your code-server deployed with http or https?

**Comment by CHYhave** [comment]
here is my version:
```
Code: 1.88.1
Commit: 9a28bc29dbddb6886dfe03dc1c31320249a901ce
Browser:  chrom 123.0.6312.124 arm64
```

**Comment by CHYhave** [comment]
it's work for me
I found error
![image](https://github.com/continuedev/continue/assets/54729911/d7d1c45b-52e9-49ff-833f-90b06e83146d)
then modify chrome 
<img width="864" alt="截屏2024-04-17 上午10 08 14" src="https://github.com/continuedev/continue/assets/54729911/60f319f9-0781-4d3e-a6f2-c9ca274bbdf5">
you can find in 
chrome://flags/#unsafely-treat-insecure-origin-as-secure
And then everything work

**Comment by PhantomKunai** [comment]
@CHYhave @Extremys 

Following any one of the steps [here](https://coder.com/docs/code-server/latest/guide) as suitable to the user solves this issue.
