### ISSUE TITLE
'completionOptions' not used when add a openAI compatiable local model

### ISSUE THREAD

**Issue by zhangjh** [continuedev/continue#1094]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
  MacOS 12.6.7
- Continue:
  v8.2.03
- IDE:
  VSCode 1.88.0
```

### Description

![image](https://github.com/continuedev/continue/assets/3371714/83223132-73b4-4f91-a56c-d37d8c5b8a39)
You can see on the above image that the request missed the completionOptions params that required by the model server. (model param required).
![image](https://github.com/continuedev/continue/assets/3371714/a92597c5-4dc9-41a2-a912-057db66f6265)

Did I make a wrong config? I searched the document but did not find the answer.

**Comment by sestinj** [comment]
@zhangjh I believe this will be solved by moving the "model" property out of "completionOptions" like this:

```json
"model": "qwen",
"title": "LocalTongyi",
"apiKey": "",
...
"completionOptions": { "temperature": 0.0 }
```

The error in devtools is a bit misleading, as these "completionOptions" will be merged with the ones that you set in config.json. Let me know if the above solution doesn't work and I'll take a deeper look!

**Comment by zhangjh** [comment]
yeah..the devtools misled me. That doesn't related to completionOptions params.
In my case, it's about two reasons, the first is as you metioned above, the model key should be set to 'qwen' required by the AI server, and the second reason is my vscode has set up a network proxy, caused the http request respond 503 error.
now it's ok, thank you!
![image](https://github.com/continuedev/continue/assets/3371714/90a51e4a-6c63-449c-ae54-44a390cc5c59)
