### ISSUE TITLE
Cannot index due to missing WASM file.

### ISSUE THREAD

**Issue by fictorial** [continuedev/continue#1096]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14.5
- Continue: 0.8.23
- IDE: VSCode 1.88.0
- Model: Ollama 0.1.31 with codegemma:instruct
```

### Description

Installed and used `@codebase How is RAG used?` and got an error that no backend was available.

<img width="1912" alt="Screenshot 2024-04-09 at 4 41 25 PM" src="https://github.com/continuedev/continue/assets/67219/ab99f4c2-f5db-4e2f-8438-58eab8a56b9c">

### To reproduce

1. Open VSCode
2. Install Continue extension
3. Clone the Continue repo (to poke around)
4. Open the Continue repo via Open Folder
5. In Continue sidebar, enter `@code rank`

### Log output

`Aborted(Error: ENOENT: no such file or directory, open '/Users/fictorial/Documents/projects/dot-files/vscode/extensions/continue.continue-0.8.23-darwin-arm64/dist/ort-wasm-simd-threaded.wasm')failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/Users/fictorial/Documents/projects/dot-files/vscode/extensions/continue.continue-0.8.23-darwin-arm64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/Users/fictorial/Documents/projects/dot-files/vscode/extensions/continue.continue-0.8.23-darwin-arm64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.)`

**Comment by fictorial** [comment]
Apparently the issue was an older version of ~/.continue from a previous install. I wiped that out, reinstalled the extension, restarted VSCode, and everything is working fine now.

**Comment by fictorial** [comment]
<img width="1608" alt="Screenshot 2024-04-09 at 4 45 25 PM" src="https://github.com/continuedev/continue/assets/67219/a3cbe8ff-76d2-4654-8cdb-af7760a2962c">

**Comment by sestinj** [comment]
@fictorial I believe that this is resolved in the latest pre-release version (0.9.x). We will be publishing a main release soon to fully solve the issue. If it's still not solved there, please let me know!

**Comment by fictorial** [comment]
It does work in pre-release version. Thanks!

**Comment by sestinj** [comment]
Great! Thanks for trying that out : ) I'll close the issue now, but let me know if anything else comes up!
