### ISSUE TITLE
Rate Limit for free OpenAI API Tiers

### ISSUE THREAD

**Issue by pmatos** [continuedev/continue#1103]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

My username in discord is pmatos.

I setup my OpenAI api key in Continue for GPT 4 but keep getting issues since I am on the API [free tier](https://platform.openai.com/docs/guides/rate-limits?context=tier-free), since I never really used the API much and to upgrade the API tier you need to send a monthly minimum on a regular basis.

I get this error with any OpenAI request in vscode:
![Screenshot from 2024-04-10 13-43-05](https://github.com/continuedev/continue/assets/7911/56d40502-10ec-4236-b3bc-3c18457e6b5a)

### Solution

I think Continue could use rate limits as suggested in https://platform.openai.com/docs/guides/rate-limits/retrying-with-exponential-backoff

**Comment by sestinj** [comment]
@pmatos Exponential backoff is a good idea, should be a quick fix given that we already have it used for embeddings.

Out of curiosity, how frequently does this happen?

**Comment by pmatos** [comment]
> @pmatos Exponential backoff is a good idea, should be a quick fix given that we already have it used for embeddings.
> 
> Out of curiosity, how frequently does this happen?

This seems to happen all the time. Unsure if I can obtain the data size sent to OpenAI but basically I can never get a reply. I tried with context of different sizes and then no context and just: "Are there modules in C++?" as the prompt and still got a HTTP 429 Too many requests.

I am starting to thing there's a problem on my side. Let me check if that's the case in more detail.

**Comment by pmatos** [comment]
Apparently there's a new payment system in openai where you need to add credits to your account. I had $0 in credits, so that was the problem I think. It's now working. 

But you might want to add exponential backoff if it's not implemented yet. However, I cannot reproduce the error because even with context I am not hitting the limits.

**Comment by sestinj** [comment]
@pmatos thanks for the extra details. this was a bit of a surprise by OpenAI : )

Now that it seems resolved (and exponential backoff was just merged) I'm going to close the issue

**Comment by pmatos** [comment]
> @pmatos thanks for the extra details. this was a bit of a surprise by OpenAI : )
> 
> Now that it seems resolved (and exponential backoff was just merged) I'm going to close the issue

Perfect. Thanks.
