### ISSUE TITLE
[CON-225] Allow editing JetBrains /edit diff

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1106]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When streaming an edit with "/edit" in VS Code, it is possible to edit the right side of the diff, but the editor is read-only in JetBrains.

This is likely solvable by changing some argument in the diff viewer in `Diff.kt`

<sub>[CON-225](https://linear.app/continue/issue/CON-225/allow-editing-jetbrains-edit-diff)</sub>

**Comment by AlerHugu3s** [comment]
I met this problem in Rider 2024.1 and Continue 0.0.42 also,
and i checked the log file,it contains this:
 SyntaxError: Unexpected token s in JSON at position 0

and this is the Json:

`{
  "messageId": "65a36806-1de2-408d-aaa3-995b17e43062",
  "messageType": "command/run",
  "data": {
    "input": "/edit ```EventController.cs (1-90)\nusing System;\nusing System.Collections.Generic;\nusing JetBrains.Annotations;\nusing UnityEditorInternal.VersionControl;\n\nnamespace DefaultNamespace\n{\n    public class EventController\n    {\n        private Dictionary\u003cString, List\u003cKeyValuePair\u003cAction,object[]\u003e\u003e\u003e _events;\n        private Dictionary\u003cObject, List\u003cAction\u003e\u003e _callers;\n        public static EventController instance;\n\n        public EventController()\n        {\n            _events \u003d new Dictionary\u003cString, List\u003cKeyValuePair\u003cAction, object[]\u003e\u003e\u003e();\n            _callers \u003d new Dictionary\u003cObject, List\u003cAction\u003e\u003e();\n            instance \u003d this;\n        }\n        \n        public static void AddEventListener([NotNull] string name, [NotNull] Action callBack, Object caller \u003d null,object[] param \u003d null)\n        {\n            if (name \u003d\u003d null) throw new ArgumentNullException(nameof(name));\n            if (callBack \u003d\u003d null) throw new ArgumentNullException(nameof(callBack));\n            if (!instance._events.ContainsKey(name)) \n                instance._events.Add(name,new List\u003cKeyValuePair\u003cAction, object[]\u003e\u003e());\n            instance._events[name].Add(new KeyValuePair\u003cAction, object[]\u003e(callBack,param));\n\n            if (caller \u003d\u003d null) return;\n            if (instance._callers.ContainsKey(caller))\n            {\n                instance._callers[caller].Add(callBack);\n            }\n            else\n            {\n                var newList \u003d new List\u003cAction\u003e();\n                newList.Add(callBack);\n                instance._callers.Add(caller,newList);\n            }\n        }\n        \n        public static void RemoveEventListener([NotNull] string name, [NotNull] Action callBack, Object caller)\n        {\n            if (name \u003d\u003d null) throw new ArgumentNullException(nameof(name));\n            if (callBack \u003d\u003d null) throw new ArgumentNullException(nameof(callBack));\n            if (instance._events.ContainsKey(name))\n            {\n                if (instance._events[name].Count \u003e 1)\n                {\n                    foreach (var keyValuePair in instance._events[name])\n                    {\n                        if (keyValuePair.Key \u003d\u003d callBack) instance._events[name].Remove(keyValuePair);\n                    }\n                }\n                else \n                    instance._events.Remove(name);\n            }\n\n            if (caller \u003d\u003d null) return;\n            if (instance._callers.ContainsKey(caller))\n            {\n                if (instance._callers[caller].Count \u003e 1) \n                    instance._callers[caller].Remove(callBack);\n                else \n                    instance._callers.Remove(caller);\n            }\n        }\n\n        public static void DispatchEvent(string name)\n        {\n            if (instance._events.ContainsKey(name))\n            {\n                foreach (var callBackKvp in instance._events[name])\n                {\n                    var callback \u003d callBackKvp.Key;\n                    var param \u003d callBackKvp.Value;\n                    if (param \u003d\u003d null)\n                    {\n                        callback.Invoke();\n                    }\n                    else\n                    {\n                        callback.DynamicInvoke(param);\n                    }\n                }\n            }\n        }\n    }\n}\n\n```\n�Ż������",
    "history": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "/edit ```EventController.cs (1-90)\nusing System;\nusing System.Collections.Generic;\nusing JetBrains.Annotations;\nusing UnityEditorInternal.VersionControl;\n\nnamespace DefaultNamespace\n{\n    public class EventController\n    {\n        private Dictionary\u003cString, List\u003cKeyValuePair\u003cAction,object[]\u003e\u003e\u003e _events;\n        private Dictionary\u003cObject, List\u003cAction\u003e\u003e _callers;\n        public static EventController instance;\n\n        public EventController()\n        {\n            _events \u003d new Dictionary\u003cString, List\u003cKeyValuePair\u003cAction, object[]\u003e\u003e\u003e();\n            _callers \u003d new Dictionary\u003cObject, List\u003cAction\u003e\u003e();\n            instance \u003d this;\n        }\n        \n        public static void AddEventListener([NotNull] string name, [NotNull] Action callBack, Object caller \u003d null,object[] param \u003d null)\n        {\n            if (name \u003d\u003d null) throw new ArgumentNullException(nameof(name));\n            if (callBack \u003d\u003d null) throw new ArgumentNullException(nameof(callBack));\n            if (!instance._events.ContainsKey(name)) \n                instance._events.Add(name,new List\u003cKeyValuePair\u003cAction, object[]\u003e\u003e());\n            instance._events[name].Add(new KeyValuePair\u003cAction, object[]\u003e(callBack,param));\n\n            if (caller \u003d\u003d null) return;\n            if (instance._callers.ContainsKey(caller))\n            {\n                instance._callers[caller].Add(callBack);\n            }\n            else\n            {\n                var newList \u003d new List\u003cAction\u003e();\n                newList.Add(callBack);\n                instance._callers.Add(caller,newList);\n            }\n        }\n        \n        public static void RemoveEventListener([NotNull] string name, [NotNull] Action callBack, Object caller)\n        {\n            if (name \u003d\u003d null) throw new ArgumentNullException(nameof(name));\n            if (callBack \u003d\u003d null) throw new ArgumentNullException(nameof(callBack));\n            if (instance._events.ContainsKey(name))\n            {\n                if (instance._events[name].Count \u003e 1)\n                {\n                    foreach (var keyValuePair in instance._events[name])\n                    {\n                        if (keyValuePair.Key \u003d\u003d callBack) instance._events[name].Remove(keyValuePair);\n                    }\n                }\n                else \n                    instance._events.Remove(name);\n            }\n\n            if (caller \u003d\u003d null) return;\n            if (instance._callers.ContainsKey(caller))\n            {\n                if (instance._callers[caller].Count \u003e 1) \n                    instance._callers[caller].Remove(callBack);\n                else \n                    instance._callers.Remove(caller);\n            }\n        }\n\n        public static void DispatchEvent(string name)\n        {\n            if (instance._events.ContainsKey(name))\n            {\n                foreach (var callBackKvp in instance._events[name])\n                {\n                    var callback \u003d callBackKvp.Key;\n                    var param \u003d callBackKvp.Value;\n                    if (param \u003d\u003d null)\n                    {\n                        callback.Invoke();\n                    }\n                    else\n                    {\n                        callback.DynamicInvoke(param);\n                    }\n                }\n            }\n        }\n    }\n}\n\n```\n�Ż������"
          }
        ]
      }
    ],
    "modelTitle": "DeepSeek-7b",
    "slashCommandName": "edit",
    "contextItems": [
      {
        "content": "using System;\nusing System.Collections.Generic;\nusing JetBrains.Annotations;\nusing UnityEditorInternal.VersionControl;\n\nnamespace DefaultNamespace\n{\n    public class EventController\n    {\n        private Dictionary\u003cString, List\u003cKeyValuePair\u003cAction,object[]\u003e\u003e\u003e _events;\n        private Dictionary\u003cObject, List\u003cAction\u003e\u003e _callers;\n        public static EventController instance;\n\n        public EventController()\n        {\n            _events \u003d new Dictionary\u003cString, List\u003cKeyValuePair\u003cAction, object[]\u003e\u003e\u003e();\n            _caller SyntaxError: Unexpected end of JSON input Error parsing line:  s \u003d new Dictionary\u003cObject, List\u003cAction\u003e\u003e();\n            instance \u003d this;\n        }\n        \n        public static void AddEventListener([NotNull] string name, [NotNull] Action callBack, Object caller \u003d null,object[] param \u003d null)\n        {\n            if (name \u003d\u003d null) throw new ArgumentNullException(nameof(name));\n            if (callBack \u003d\u003d null) throw new ArgumentNullException(nameof(callBack));\n            if (!instance._events.ContainsKey(name)) \n                instance._events.Add(name,new List\u003cKeyValuePair\u003cAction, object[]\u003e\u003e());\n            instance._events[name].Add(new KeyValuePair\u003cAction, object[]\u003e(callBack,param));\n\n            if (caller \u003d\u003d null) return;\n            if (instance._callers.ContainsKey(caller))\n            {\n                instance._callers[caller].Add(callBack);\n            }\n            else\n            {\n                var newList \u003d new List\u003cAction\u003e();\n                newList.Add(callBack);\n                instance._callers.Add(caller,newList);\n            }\n        }\n        \n        public static void RemoveEventListener([NotNull] string name, [NotNull] Action callBack, Object caller)\n        {\n            if (name \u003d\u003d null) throw new ArgumentNullException(nameof(name));\n            if (callBack \u003d\u003d null) throw new ArgumentNullException(nameof(callBack));\n            if (instance._events.ContainsKey(name))\n            {\n                if (instance._events[name].Count \u003e 1)\n                {\n                    foreach (var keyValuePair in instance._events[name])\n                    {\n                        if (keyValuePair.Key \u003d\u003d callBack) instance._events[name].Remove(keyValuePair);\n                    }\n                }\n                else \n                    instance._events.Remove(name);\n            }\n\n            if (caller \u003d\u003d null) return;\n            if (instance._callers.ContainsKey(caller))\n            {\n                if (instance._callers[caller].Count \u003e 1) \n                    instance._callers[caller].Remove(callBack);\n                else \n                    instance._callers.Remove(caller);\n            }\n        }\n\n        public static void DispatchEvent(string name)\n        {\n            if (instance._events.ContainsKey(name))\n            {\n                foreach (var callBackKvp in instance._events[name])\n                {\n                    var callback \u003d callBackKvp.Key;\n                    var param \u003d callBackKvp.Value;\n                    if (param \u003d\u003d null)\n                    {\n                        callback.Invoke();\n                    }\n                    else\n                    {\n                        callback.DynamicInvoke(param);\n                    }\n                }\n            }\n        }\n    }\n}\n",
        "name": "EventController.cs (1-90)",
        "description": "D:/AlerHughesFrameWork/Assets/Scripts/EventController.cs",
        "id": {
          "providerTitle": "code",
          "itemId": "D:/AlerHughesFrameWork/Assets/Scripts/EventController.cs"
        },
        "editing": true
      }
    ],
    "historyIndex": 0,
    "selectedCode": [
      {
        "filepath": "D:/AlerHughesFrameWork/Assets/Scripts/EventController.cs",
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 89,
            "character": 0
          }
        }
      }
    ]
  }
}`
