### ISSUE TITLE
Can't show the response  content in Continue Chatting zone 

### ISSUE THREAD

**Issue by dragonslayer18** [continuedev/continue#1108]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows 11
- Continue: V0.9.108
- IDE: VSCode
model:codellama-7B-Instruct
```

### Description

![微信截图_20240411180156](https://github.com/continuedev/continue/assets/42995034/b9cbbb85-9738-4c98-be6c-41f156b97cf8)

This is my config.json, I run codellama-7B-Instruct in local pc, when select the model and start chatting in vscode Continue Extension, the server can get the request json from Continue, generate the content correctly, but when  sending the OpenAi format json to continue , the continue  can't show the content in the chatting zone at all. Is the Json format is incorrect or there is some problems in config.json? I use the flask to response http post in my server
![问题](https://github.com/continuedev/continue/assets/42995034/0e561f7c-9791-437b-b14a-8e62a1caaa23)

The json content I response as follows
![微信截图_20240411180440](https://github.com/continuedev/continue/assets/42995034/ed0e428c-894d-47ad-b87f-35add007a09d)

### Log output

```Shell
This is the output of Continue :
==========================================================================
==========================================================================
Settings:
contextLength: 2048
temperature: 0
topP: null
topK: null
presencePenalty: null
frequencyPenalty: null
stop: null
maxTokens: 600
model: localCodellama

############################################

<user>
hello

==========================================================================
==========================================================================
Completion:



The completion is always empty
```

**Comment by sestinj** [comment]
@dragonslayer18 your JSON format is correct for non-streaming mode, but it looks like it is missing the "delta" property for streaming. I may be mistaken, but if it helps, here is an example server that I made, which is OpenAI-compatible and works with Continue: https://github.com/sestinj/slow-server/blob/main/main.py

It uses FastAPI instead of Flask

**Comment by dragonslayer18** [comment]
I change to fastAPI and use the mothed in you demo, it can show message in the chatting zone! Thank you for your help

**Comment by pradanaadn** [comment]
Hi @dragonslayer18 and @sestinj, I follow @sestinj  method and it worked form stream. What i want to do now, is to display non stream response, how should i format the response for non stream?
