### ISSUE TITLE
Pre-Release version wipes local config after update

### ISSUE THREAD

**Issue by d-z-m** [continuedev/continue#1110]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 20.04
- Continue: v0.9.108(pre-release)
- IDE: Vs-Code 1.86.1
```

### Description

I have continue set up to use local models for Q&A/autocomplete.  

After updating my Pre-Release version to the new one, I was prompted with a menu that asked me if I wanted to keep my configuration, or update to recommended models.

I selected the "keep my configuration" option and hit the "continue" button.  I looked at my config file, and my local configurations were all gone.  However, they were still present in the model selector window, and inference appeared to still be working.  After closing and re-opening VSCode, the model selector window was empty, and only showed the default options. Inference no longer worked, as well.

### To reproduce

1. have non-current pre-release version installed with custom config
2. update to current pre-release version and select "keep my config"
3. observe config wipe on disk, still working in memory
4. close and re-open vscode, config completely wiped, no longer working

**Comment by sestinj** [comment]
@d-z-m I'm sorry this happened—I just made a fix [here](https://github.com/continuedev/continue/commit/e453ff9768b39dad900caa8dd38010c01dd081a7) and am pushing an update immediately so other don't have the same issue.

Thanks for so quickly reporting this!

**Comment by d-z-m** [comment]
I can confirm this fixes the issue.
