### ISSUE TITLE
Malformed stop-parameter on ollama API Requenst (quotes included \"[INST]\" instead of [INST])

### ISSUE THREAD

**Issue by TheMasterFX** [continuedev/continue#1116]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 
- Continue: 0.8.24
- IDE: VSCode 1.88.1
```

### Description

The stop parameter in the API request (for the chat window) is generated incorrectly, resulting in incorrect behaviour, since the stop-parameter is not recognized by the ollama provider.
I noticed this when using the Dolphin-Mistral model, which uses <|im_end|> as a stop parameter. In the response, the <|im_end|> always appears at the end of the generated output, which should not happen.

### To reproduce

1. Go to the Continue Settings.
2. Add the Model
```
  {
      "model": "AUTODETECT",
      "title": "Ollama",
      "apiBase": "http://localhost:11434",
      "provider": "ollama"
    }
```
3. In the Dropdown select dolphin-mistral:latest
4. Enter "Hello" in the Chat and you will get an answer including the stop-string
![image](https://github.com/continuedev/continue/assets/12451336/c5d13e79-bf6b-47d4-b440-c1934bff6523)

### Log output

I have recorded the http-traffic with wireshark with mistral and dolphin-mistral (which uses diffrent stop parameters). In both cases you see the stop strings with escaped quotes.
```json
{"model":"mistral:latest","raw":true,"keep_alive":1800,"options":{"stop":["\"[INST]\"","\"[/INST]\""],"num_ctx":4096},"messages":[{"role":"user","content":"Hello"}]}
```
```json
{"model":"dolphin-mistral:latest","raw":true,"keep_alive":1800,"options":{"stop":["\"<|im_start|>\"","\"<|im_end|>\""],"num_ctx":4096},"messages":[{"role":"user","content":"Hello"}]}
```
It should be:
```json
{"model":"dolphin-mistral:latest","raw":true,"keep_alive":1800,"options":{"stop":["<|im_start|>","<|im_end|>"],"num_ctx":4096},"messages":[{"role":"user","content":"Hello"}]}
```
```

**Comment by sestinj** [comment]
@TheMasterFX thanks for pointing that out! I just fixed it here (https://github.com/continuedev/continue/commit/94b44603612ad47b7456c06a762c646c1c803096) and it'll be in the next pre-release version
