### ISSUE TITLE
Support Cohere as Embeddings Provider

### ISSUE THREAD

**Issue by maxbrunet** [continuedev/continue#1121]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

[Codebase retrieval](https://continue.dev/docs/walkthroughs/codebase-embeddings) could use Cohere's [Embed](https://docs.cohere.com/docs/embed-2) models

### Solution

Add supporting code under [core/indexing/embeddings](https://github.com/continuedev/continue/tree/main/core/indexing/embeddings).

Maybe the [bulk embed job API](https://docs.cohere.com/reference/create-embed-job) could be handy

**Comment by maxbrunet** [comment]
@sestinj feel free to assign this one to me, I will try to take care of it next :)

**Comment by sestinj** [comment]
Awesome! Let me know if there's anything I can answer. I think the embeddings provider should be fairly straightforward. Embed jobs could certainly speed things up, but might be overkill in a lot of situations, as I'm assuming you'd then have to download the results and parse the CSV? With 96 inputs per /embed call that won't be terribly slow for most codebases.
