### ISSUE TITLE
Unable to paste anythin in VS-Code extension with Ollama

### ISSUE THREAD

**Issue by cardchase** [continuedev/continue#1131]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Linux
- Continue:
- IDE:VSCode
```

### Description

I am unable to paste anything in the chat window. I am only able to type.
Nor am I able to use as the demo shows. i.e. I am unable to ask any question only to my code open in the editor

![This is the editor view](https://github.com/continuedev/continue/assets/33249394/4b93dff2-e96e-457b-8322-27ed61cecd77)

`^ L` does not work too

**Comment by sestinj** [comment]
@cardchase It sounds like the problems pasting in .ipynb files may be the same as this issue: https://github.com/continuedev/continue/issues/748

But the inability to use `^ L` sounds new—do you experience this only in notebook files, or in regular files as well? My first thought is that perhaps another keyboard shortcut (ctrl+K, ctrl+S to open settings for this) is overriding.

**Comment by cardchase** [comment]
> @cardchase It sounds like the problems pasting in .ipynb files may be the same as this issue: #748
> 
> But the inability to use `^ L` sounds new—do you experience this only in notebook files, or in regular files as well? My first thought is that perhaps another keyboard shortcut (ctrl+K, ctrl+S to open settings for this) is overriding.

Yes, I can use `Cltr + L `and the codeblock can be interacted with however I am unable to edit. 
So to speak, unable to have a conversation with Continue unless I input the code I would agree, its not the best solution, but its a bug nevertheless. I will close this issue as the problem is resolved but the problem still persists. 
Cannot copy-paste
