### ISSUE TITLE
For neovim ?

### ISSUE THREAD

**Issue by kamalkech** [continuedev/continue#1138]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
there is no plan for neovim ?
```

**Comment by Aman9das** [comment]
duplicate https://github.com/continuedev/continue/issues/917
