### ISSUE TITLE
Debug Terminal Not Working: The terminal has no selection to copy

### ISSUE THREAD

**Issue by tsegreto** [continuedev/continue#1143]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.4.1
- Continue: 0.8.24
- IDE: VSCode 1.88.0
```

### Description

When trying to Debug Terminal (Cmd + Shift + R) I receive the message: "The terminal has no selection to copy"

**Comment by sestinj** [comment]
@tsegreto Is this happening consistently?

For some background, the way that we are able to get text from the terminal is by doing the following in quick succession
- store current copy buffer contents in temp variable
- select terminal contents
- copy current selection
- unselect
- save the new copied text
- restore the old copy buffer content

It might be that something is happening in between these to disrupt, or that no terminal is currently open?

**Comment by sestinj** [comment]
Going to close this issue as it seems to have gone stale. If anyone else is still experiencing this even with a terminal being currently open, please re-open!

**Comment by Eric-SHENNONGSHI** [comment]
Face the same issue here but I cannot recreate the bug steadily. I have three terminals split from one. Only the first one appears to have this problem. The warning messages don't appear sometimes, but the text is always not copied in the first terminal.


Version: 1.6.26
VSCode Version: 1.99.3
Commit: 6af2d906e8ca91654dd7c4224a73ef17900ad730
Date: 2025-09-16T17:12:31.697Z
Electron: 34.5.8
Chromium: 132.0.6834.210
Node.js: 20.19.1
V8: 13.2.152.41-electron.0
OS: Linux x64 6.8.0-79-generic
