### ISSUE TITLE
[CON-226] File watcher on config.json to catch updates from outside the currently open window

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1148]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When I update config.json programmatically or from another VS Code/IDE window, the changes aren't automatically reflected as they are when I save the file within my current window.

### Solution

To solve this, we need to add a file watcher that can catch all changes to config.json even from outside the current window.

<sub>[CON-226](https://linear.app/continue/issue/CON-226/file-watcher-on-configjson-to-catch-updates-from-outside-the-currently)</sub>

**Comment by amfred** [comment]
In fact, if I change config.json in a VSCode editing pane (and not through the Continue wizard that modifies the file), I will sometimes get error messages similar to this until I exit VSCode and re-start it: 
<img width="317" alt="image" src="https://github.com/continuedev/continue/assets/1302432/e5a014b3-a69e-4ebd-bd2c-f13363cf7b8d">
So, this is primarily a feature request, but it would hopefully also fix a bug.

**Comment by sestinj** [comment]
Good to know! I just made an update to add a global file watcher in [this commit](https://github.com/continuedev/continue/commit/e0f4c128da4baf43e04c2c2bf60ffa18461d2027), and it should be in pre-release later today. Will be curious to see if this solves the URL problem

**Comment by fbricon** [comment]
Pre-release worked for me. The model I added (actually some ollama autodetect url) from my extension was detected/listed in the models combo. Now waiting for a solution to #1149

**Comment by fbricon** [comment]
You'll prolly want the IJ extension to watch the config file as well

**Comment by sestinj** [comment]
Absolutely. Will be making the corresponding IntelliJ update for release 0.0.46 later this week. I'll keep this issue open until that is completed
