### ISSUE TITLE
[CON-227] Model Roles

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1149]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

There's currently no way to specify a model to use for Cmd+I or other specific features (currently it uses whatever is manually selected in the dropdown).

### Solution

Add a "modelRoles" section to config.json that allows specification of model titles for each of several tasks. For example, this might look like:

```json
{
  "models": [
    {
      "title": "Claude 3 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-sonnet-20240229",
      "apiKey": "ANTHROPIC_API_KEY"
    },
    {
      "title": "Llama 3",
      "provider": "ollama",
      "model": "llama3"
    },
    {
      "title": "Starcoder 2 3b",
      "provider": "ollama",
      "model": "starcoder2:3b"
    }
  ],
  "modelRoles": {
    "cmdI": "Llama 3",
    "chat": "Claude 3 Sonnet",
    "autocomplete": "Starcoder 2 3b"
  }
}
```

<sub>[CON-227](https://linear.app/continue/issue/CON-227/model-roles)</sub>

**Comment by fbricon** [comment]
modelRoles in config.json should be the default for all IDEs, but the model roles should be overrideable in vscode settings.json and in jetbrains preferences respectively

**Comment by fbricon** [comment]
I'd avoid using `cmdI` as it's a Mac-specific shortcut. `interactive` maybe?

**Comment by buck-0x** [comment]
> Model title as modelrole key is a no-go. When using ollama autodetect, the models are not listed in the config.json file. e.g. I have:
> 
> ```
>     {
>       "model": "AUTODETECT",
>       "title": "Ollama",
>       "completionOptions": {},
>       "apiBase": "http://localhost:11434",
>       "provider": "ollama"
>     }
> ```
> 
> But I can select: <img alt="Screenshot 2024-04-19 at 11 07 53" width="235" src="https://private-user-images.githubusercontent.com/148698/323901353-8bf58de0-c941-4ecb-a8d4-ba8c1c0fe5ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDQ1NTMsIm5iZiI6MTcxMzg0NDI1MywicGF0aCI6Ii8xNDg2OTgvMzIzOTAxMzUzLThiZjU4ZGUwLWM5NDEtNGVjYi1hOGQ0LWJhOGMxYzBmZTVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwMzUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWMwZWJmYWJjYjA0MjY3NjIwYTRkZjZkY2U3NDZkMGEyNTcxODFmMzdiMDRkNzBiZDZiYmNhNmVhZDExNGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q853GS6RccASz-mkTF-xOeRCedHlGVC_YEUIs6PjjNA">
> 
> You might want to support at least `<model title>:<actual model key>`

Agreed this is a problem. Autodetect is the way to go but it blocks using modelRoles.

**Comment by buck-0x** [comment]
Ideally we would be able to set `modelRoles` in the UI as well.

**Comment by sestinj** [comment]
@fbricon @buck-0x I just made this commit (https://github.com/continuedev/continue/commit/721ce6c7992de326f2a4e6bfb9c092247244ce6d) which introduces a model role called "inlineEdit", rather than "cmdI" for the reason you mentioned.

> You might want to support at least <model title>:<actual model key>

If you are using AUTODETECT, you can follow the pattern used in the UI. For example, with "title": "Ollama" and the name of the autodetected model being "llama3:latest", you could set `"inlineEdit": "Ollama - llama3:latest"`

**Comment by fbricon** [comment]
I still think these properties should be overrideable per IDE. At the very least, provide the model role properties under an ide parent node, using keys as vscode, idea, ....

**Comment by fbricon** [comment]
Tried the pre-release. I selected an invalid model, then requested something, the extension didn't error, provided some response, but I don't know which model was used. So did it really work? was it accidental fallback? I think there should be some feedback, in the form of a notification, in case the model is invalid/unreachable
