### ISSUE TITLE
Using llama3 for causes never ending response.

### ISSUE THREAD

**Issue by adamzenith** [continuedev/continue#1152]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubunutu 22.04
- Continue:0.8.24
- IDE: VScode 1.88.1
- Model: Llama 3 8b:instruct
```

### Description

![image](https://github.com/continuedev/continue/assets/49098682/03922f2c-1c7a-468b-9552-0bbd60afe3a3)
I think the llama3 version that Ollama uses has a different stop string than continue is expecting.  As seen in the screenshot, it outputs an <|eot_id|>, but then continues. I have seen this go on until no more token can be generated.

### To reproduce

use llama3 8b as a chat model and ask it anything.

**Comment by sestinj** [comment]
As mentioned this should be solved in pre-release, but if you are still having the problem it can be fixed by adding the stop token to your config.json manually:

```json
{
  "title": "Llama 3",
  "provider": "ollama",
  "model": "llama3",
  "completionOptions": {
    "stop": ["<|eot_id|>"]
  }
}
```

**Comment by sestinj** [comment]
This is now long past merged, so closing the issue : )

I do believe that Ollama has also patched the problem, but if anyone sees it again don't hesitate to re-open
