### ISSUE TITLE
After selecting 'run fully local' it appears to still send my code to a server

### ISSUE THREAD

**Issue by JKHSDTV** [continuedev/continue#1165]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 with WSL2 / Ubuntu 22.04 LTS
- Continue: v0.8.24
- IDE: VSCode 1.88.1
```

### Description

I installed `continue`, which then in the side bar prompted me which mode I want it to run into. As we are working on proprietary code with strict rules about sending it out to LLMs (which I did not use to test this extension with, so no actual harm done), I selected the 'fully offline' version.

Next, I was prompted with a tutorial where a step was 'select the code and ask a question about it'. From the interface, it seems clear that my selected code was then sent to `Claude 3 Sonnet`. That seems the opposite of what I clicked earlier.

I am unsure whether this is a bug and should not have happened, or whether it is a 'bug' in the sense of a confusing, misleading our outdated user interface.

**Comment by sestinj** [comment]
The fix has now been released in the latest pre-release (0.9.x). I'm sorry this happened, but grateful that you took the time to open an issue! Feel free to re-open or start a new thread if you're still having any problems
