### ISSUE TITLE
Error: Hovering over code block can cause error in v0.9.114+

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#1166]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue:  v0.9.115
- IDE: VSCode
```

### Description

When hovering over a `CodeBlock` with your mouse cursor, it can happen that the text suddenly disappears and an error message shows up.

```md
Something went wrong:
Cannot read properties of undefined (reading 'length')
```

<img src="https://github.com/continuedev/continue/assets/92653266/7eca8c43-8ae2-4542-ab1f-5b0aa020736b" width="400">

--- 

The issue came with version `0.9.114` (2024-04-20T01:47:33.607Z) through commit 49cb06df70016af4b6081122fa2737560abaf7ce in the `CodeBlockToolbar.tsx` file.

```bash
git log --since=2024-04-18T23:38:01.27Z --format=oneline \
  -L :isTerminalCodeBlock:gui/src/components/markdown/CodeBlockToolbar.tsx
```

```diff
49cb06df70016af4b6081122fa2737560abaf7ce ✨ Improved onboarding experience (#1155)

--- a/gui/src/components/markdown/CodeBlockToolbar.tsx
+++ b/gui/src/components/markdown/CodeBlockToolbar.tsx
@@ -60,8 +64,9 @@
 function isTerminalCodeBlock(language: string | undefined, text: string) {
   return (
     terminalLanguages.includes(language) ||
-    (text.trim().split("\n").length === 1 &&
-      commonTerminalCommands.some((c) => text.trim().startsWith(c)))
+    (language.length === 0 &&
+      (text.trim().split("\n").length === 1 ||
+        commonTerminalCommands.some((c) => text.trim().startsWith(c))))
   );
 }
 ```

---

### Possible Solution

It is possible that `language` is undefined. 
```diff
--- a/gui/src/components/markdown/CodeBlockToolbar.tsx
+++ b/gui/src/components/markdown/CodeBlockToolbar.tsx
@@ -65,5 +65,5 @@ function isTerminalCodeBlock(language: string | undefined, text: string) {
   return (
     terminalLanguages.includes(language) ||
-    (language.length === 0 &&
+    (language?.length === 0 &&
       (text.trim().split("\n").length === 1 ||
         commonTerminalCommands.some((c) => text.trim().startsWith(c))))
```

### To reproduce

1. Request command instructions from the LLM
2. Hover over the code block
3. Be patient as it might take some time to appear

### Log output

```Shell
CodeBlockToolbar.tsx:67 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at isTerminalCodeBlock (CodeBlockToolbar.tsx:67:15)
    at CodeBlockToolBar (CodeBlockToolbar.tsx:84:17)
    at renderWithHooks (chunk-J47ZQ47U.js?v=d745c807:12171:26)
    at mountIndeterminateComponent (chunk-J47ZQ47U.js?v=d745c807:14921:21)
    at beginWork (chunk-J47ZQ47U.js?v=d745c807:15902:22)
    at HTMLUnknownElement.callCallback2 (chunk-J47ZQ47U.js?v=d745c807:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-J47ZQ47U.js?v=d745c807:3699:24)
    at invokeGuardedCallback (chunk-J47ZQ47U.js?v=d745c807:3733:39)
    at beginWork$1 (chunk-J47ZQ47U.js?v=d745c807:19761:15)
    at performUnitOfWork (chunk-J47ZQ47U.js?v=d745c807:19194:20)
```

**Comment by sestinj** [comment]
@LangLangBart thank you for going as far as providing the fix! Just made it here and will publish tonight: https://github.com/continuedev/continue/commit/9007b8fed3ce9dfd23b16ba1a4fd845f4e76a844

**Comment by LangLangBart** [comment]
0.9.118
