### ISSUE TITLE
configuration not reloading in pycharm

### ISSUE THREAD

**Issue by cyb3rd0g01** [continuedev/continue#1167]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:MAC
- Continue:0.0.45
- IDE: pycharm
```

### Description

I put lm-studio in the model however continue is not getting the lm-studio model

core.log
Error listing models:  TypeError: fetch failed                                                                           
Error calling Ollama /api/show endpoint: TypeError: fetch failed       

config.json
  "models": [                                                                                                            
    {                                                                                                                    
      "model": "AUTODETECT",                                                                                             
      "title": "LM Studio",                                                                                              
      "apiBase": "http://192.168.1.179:1234/v1/",                                                                        
      "completionOptions": {},                                                                                           
      "provider": "lmstudio"                                                                                             
    }                                                                                                                    
  ],                                                                                                                     
...
  "allowAnonymousTelemetry": false      

### To reproduce

1. click on configure
2. add lm-studio
3. change lm-studio model in config.json and add remote server and port
4. note that the added model is not showing up in the pull down in continue

### Log output

```Shell
core.log
Error listing models:  TypeError: fetch failed                                                                           
Error calling Ollama /api/show endpoint: TypeError: fetch failed
```

**Comment by sestinj** [comment]
Looks like this was happening because we made the request in the constructor before setting the custom node-fetch.

I made the fix [here](https://github.com/continuedev/continue/commit/f233844818b9331b7a754d06481267c65d5ed490), and it will be ready in the next release! (0.0.46, probably Monday)

**Comment by sestinj** [comment]
In the meantime, if you set a specific model rather than AUTODETECT, this problem won't occur

**Comment by cyb3rd0g01** [comment]
Awesome thank you exactly what the workaround was Regards, Igor On Apr 26, 2024, at 5:03 AM, Nate Sesti ***@***.***> wrote:﻿
In the meantime, if you set a specific model rather than AUTODETECT, this problem won't occur
