### ISSUE TITLE
New model wizard should not add duplicate models

### ISSUE THREAD

**Issue by fbricon** [continuedev/continue#1172]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

If I add an Ollama/Autodetect provider via the Model wizard, Continue doesn't check the exact same model configuration exists and then blindly adds a second model.

<img width="776" alt="Screenshot 2024-04-23 at 11 06 38" src="https://github.com/continuedev/continue/assets/148698/1db04504-c4a6-4ddd-9be4-cd2687eb14c7">

### Solution

If the exact same model configuration is already set in the config.json file, continue should either ignore it, or ask the user to add it anyway

**Comment by sestinj** [comment]
@fbricon good idea! Made the change [here](https://github.com/continuedev/continue/commit/c5fef125da75050bb52e9fbb97192c45c7aae1a7), to be included in the next releases
