### ISSUE TITLE
Configure ollama remotely

### ISSUE THREAD

**Issue by myrulezzz** [continuedev/continue#1175]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Mac
- Continue:
- IDE: Visual Studio Code
```

### Description

Ollama is running on remote machine. i want to be able to configure ollama remote server. however i couldn't find such an option

**Comment by sestinj** [comment]
@myrulezzz You can change the `apiBase` property on the object in the "models" array to wherever you serve Ollama

https://continue.dev/docs/reference/config <- Here is the full reference for config.json where you can find such options. We'll do a better job in our docs of explaining this though. I understand that this should definitely be on the Ollama reference page

**Comment by myrulezzz** [comment]
Ok thanks.Also the prompt setup is a bit confusing.How to identify hiw to format prompt in the Modelfile?

Regards,
Andreas Stylianou
________________________________
