### ISSUE TITLE
VS Code extension globally binds `Ctrl-K Ctrl+C` to open Continue Config

### ISSUE THREAD

**Issue by one-lithe-rune** [continuedev/continue#1179]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux (OpenSUSE Tumbleweed/Plasma 6)
- Continue: v0.9.118
- IDE: VSCode 1.88.1
- Model: N/A
```

### Description

By default `Ctrl+K Ctrl+C` is bound in Visual Code to comment out code, with a condition of it being active only within a non-readonly editor tab.

This is a reasonably common operation for me when iterating over my code.

However Continue also adds a binding for `Ctrl+K Ctrl+C` to open its config file, but with no condition at all. This means it takes priority over editor tab specific bindings.

IMO you should at least restrict this to being within the Continue panel. Ideally there probably shouldn't be an automatic key binding setup by Continue for this at all, as changing the config shouldn't really be a common operation once you have it set up, and it is easily accessed from the UI anyway.

If I disable Continue the key binding is removed.
If I re-enable Continue the key binding is re-added.

Screenshot of keybindings for Ctrl + K, Ctrl + C with Continue Enabled:

![Screenshot_20240424_135828](https://github.com/continuedev/continue/assets/121311569/4aeba615-f1c0-4989-90cd-e449fe99eb5b)

### To reproduce

1. Enable Continue extension in VS Code.
2. Open a file with some code in a language of your choice.
3. Select some code in the editor tab for that file.
4. Do `Ctrl+K` `Ctrl+C`.
5. Continue config file is opened, rather than the selected code being commented out.

### Log output

```Shell
N/A
```

**Comment by sestinj** [comment]
Fair enough! I hadn't realized how common this can be in addition to cmd+/. No intention of messing with people's shortcuts : )

Change here: https://github.com/continuedev/continue/commit/ae766d3ff71b9aa3b21cc3b41c061da9c3e3991d

Will be in the next releases!

**Comment by 9r1nc3w1ll** [comment]
I still experienced this issue as recent as June 26th. I uninstalled the extension after trying to change the keybinding with no success. I use Tweeny for now but I'll reinstall when this is actually resolved.
