### ISSUE TITLE
model gpt-4-turbo-2024-04-09 not working in continue

### ISSUE THREAD

**Issue by namen3645** [continuedev/continue#1180]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 Pro 22H2
- Continue: 
- IDE: vscode
```

### Description

Error: HTTP 403 Forbidden from https://api.openai.com/v1/chat/completions  {     "error": {         "message": "Project `proj_4JtGMmfzA` does not have access to model `gpt-4-turbo-2024-04-09`",         "type": "invalid_request_error",         "param": null,         "code": "model_not_found"     } }

<img width="747" alt="Снимок" src="https://github.com/continuedev/continue/assets/62731881/a35c34fb-ea61-4eba-8bed-140f80d2b403">

{
  "models": [
    {
      "model": "gpt-4-turbo-2024-04-09",
      "title": "GPT-4",
      "apiKey": "sk-proj-...3Wd0E",
      "completionOptions": {},
      "provider": "openai"
    }
  ],
  "modelRoles": {
    "default": "GPT-4",
    "chat": "GPT-4",
    "edit": "GPT-4",
    "summarize": "GPT-4"
  },
  "systemMessage": "",
  "completionOptions": {
    "temperature": 0.5
  },
  "allowAnonymousTelemetry": false,
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    }
  ]
}

### To reproduce

1. Go to continue config and replace gpt-4 to:

gpt-4-turbo
gpt-4-turbo-2024-04-09
gpt-4-turbo-preview
gpt-4-0125-preview
gpt-4-1106-preview

or any other non-standard gpt-3 model

**Comment by sestinj** [comment]
@namen3645 Do you have paid credits on your account? OpenAI recently switched to a model that requires pre-paying, and this may be a cause. Another might be that they simply haven't equally distributed access to the newer models.

Unless you are able to make the following curl request successfully with your API key, this seems likely to be an issue with OpenAI

curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'

**Comment by sestinj** [comment]
Hi @namen3645, have you had a chance to look into this? Would love to know whether this ended up being the solution. I'll probably close the issue soon if I don't hear back

**Comment by xtfer** [comment]
I'm getting this issue, and call in https://github.com/continuedev/continue/issues/1180#issuecomment-2076302401 works for me.
