### ISSUE TITLE
Not able to connect with ANTHROPIC models(Claude 3 Haiku, Claude 3 opus)

### ISSUE THREAD

**Issue by hardihood** [continuedev/continue#1185]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:windows
- Continue:
- IDE:intellij
```

### Description

getting this exception when ever sending any message :
request to https://api.anthropic.com/v1/messages failed, reason: self-signed certificate in certificate chain

**Comment by sestinj** [comment]
@hardihood Can you tell me more about your network environment and the version of Continue you are using?

**Comment by tndevDE** [comment]
I have the same problem with Claude and with Gemini.

```
- OS:MacOS
- Continue:
- IDE:vscode
```

Could this have something to do with a free API?
Codestral works.

### Messages

- Claude:
  `HTTP 400 Bad Request from https://api.anthropic.com/v1/messages`
- Gemini:
  `HTTP 400 Bad Request from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?key={my-key}`

**Comment by tndevDE** [comment]
@sestinj Sorry, it's because of a free api key. 
```
400 {type:error,error:{type:invalid_request_error,message:Your credit balance is too low to access the Claude API. Please go to Plans & Billing to upgrade or purchase credits.}}
```

**Comment by sestinj** [comment]
ah ok thanks for the update. I'll close the issue
