### ISSUE TITLE
Groq api uses incorrect apibase on refactor mode (cmd+I)

### ISSUE THREAD

**Issue by Altroo** [continuedev/continue#1186]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.45
- IDE: Pycharm 2024.1
```

### Description

Alright so, this is my first time using this plugin, it is really interesting.

i've configured Groq using an api key with the model llama3-70b : 
config.json : 

```
{
    "model": "Llama3-70b-8192",
    "title": "Groq : Llama3-70b-8192",
    "apiKey": "key",
    "provider": "groq"
}
```

It's working on the "continue" tab, however when using refactor mode with "cmd + I", it raises an error as shown in core.log : 

```
Error running handler for "command/run":  Error: HTTP 404 Not Found from https://api.groq.com/openai/v1/completions
{"error":{"message":"Unknown request URL: POST /openai/v1/completions. Please check the URL for typos, or see the docs at https://console.groq.com/docs/","type":"invalid_request_error","code":"unknown_url"}}
Error: HTTP 404 Not Found from https://api.groq.com/openai/v1/completions
```

Adding the correct "apiBase" as "https://api.groq.com/openai/v1/chat" fixes it but raises another error : 

```
Error running handler for "streamDiffLines":  Error: HTTP 400 Bad Request from https://api.groq.com/openai/v1/chat/completions
{"error":{"message":"property 'prompt' is unsupported, did you mean 'stop'?","type":"invalid_request_error"}}
Error: HTTP 400 Bad Request from https://api.groq.com/openai/v1/chat/completions
```

**Comment by EricBizet** [comment]
I can confirm I am experiencing the same issue in VS Code, thank you for opening this ticket

**Comment by sestinj** [comment]
@Altroo @EricBizet Just fixed this [here](https://github.com/continuedev/continue/commit/044b2e8453270dc76ec5c2a83749dd6d22dc559e). We were detecting from the OpenAI class but forgot to check when we made Groq it's own LLM provider.

Until this is released later today, you can use "provider": "openai" with "apiBase": "https://api.groq.com/openai/v1/" instead and it should work

Also working with Groq to hopefully add support for the completions endpoint : )

**Comment by deer1025** [comment]
'groq' provider is not working{HTTP 404 Not Found from
https://api.groq.com/openai/v1/chat/completions}
Is it because GROQ API integration uses incorrect endpoint? (I used 'https://api.groq.com/openai/v1/chat/completions' from the official website)
The reason for the model being deprecated is ruled out, because I tried all available models {https://console.groq.com/docs/models} and none of them worked
