### ISSUE TITLE
[CON-230] .continueignore doesn't respect negations

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1191]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue:*
- IDE:*
```

### Description

A pattern such as
```
**/*.*
!**/*.ts
```

should tell Continue only to index .ts files. But instead the effect is to index no files

<sub>[CON-230](https://linear.app/continue/issue/CON-230/continueignore-doesnt-respect-negations)</sub>

**Comment by Iceburgino** [comment]
Can confirm behavior on the current version v0.8.29. Using this continueignore/gitignore file:

*
!*/

!*.h
!*.c

Negates everything but does not unnegate the specified strings.

**Comment by Iceburgino** [comment]
@sestinj any activity on this?

**Comment by shannonrdunn** [comment]
```
*.*
!*.go
```


@Iceburgino 
I've found this pattern works in .continueignore
