### ISSUE TITLE
core/llm/index.ts sends duplicated TokensGenerate  events .

### ISSUE THREAD

**Issue by bright-ren** [continuedev/continue#1192]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: 0.9.118
- IDE: vscode
```

### Description

core/llm/index.ts sends duplicated events for TokensGenerate event.
 private _logTokensGenerated(model: string, completion: string) {
    let tokens = this.countTokens(completion);
    Telemetry.capture("tokens_generated", {
      model: model,
      provider: this.providerName,
      tokens: tokens,
    });
    Telemetry.capture("tokensGenerated", {
      model: model,
      provider: this.providerName,
      tokens: tokens,
    });
    DevDataSqliteDb.logTokensGenerated(model, this.providerName, tokens);
  }

### To reproduce

No need to reproduce,  easy to fix. This looks like a code merge issue.

**Comment by sestinj** [comment]
@bright-ren thanks for pointing this out—was the result of a migration, but is now fixed: https://github.com/continuedev/continue/commit/b19f45cedf215c72d70a33db34ce05948eb9feac
