### ISSUE TITLE
Sending images to gpt-4-turbo returns error

### ISSUE THREAD

**Issue by evertjr** [continuedev/continue#1201]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: Preview
- IDE: vscode
```

### Description

When using GPT-4-Turbo as a model for openai, sending a image returns a error, the image type should be image_url instead of ImageUrl. When using GPT-4-Turbo-Vision-Preview it works but this model is outdated now as the latest GPT-4 Turbo supports image input as well. 

### To reproduce

    in config json:
    
    {
      "title": "GPT-4-Turbo",
      "provider": "openai",
      "apiKey": "key",
      "model": "gpt-4-turbo"
    },
    
1 - attach an image in the chat area
2 - Send it 
3 - A popup error appears

### Log output

```Shell
HTTP 400 Bad Request from https://api.openai.com/v1/chat/completions  {   "error": {     "message": "Invalid value: 'imageUrl'. Supported values are: 'text' and 'image_url'.",     "type": "invalid_request_error",     "param": "messages[4].content[0].type",     "code": "invalid_value"   } }
```

**Comment by sestinj** [comment]
@evertjr just fixed here (https://github.com/continuedev/continue/commit/04d8d0e7650de13b5479848f24b316af82d32127). I'll release a new version later today

**Comment by dbsxdbsx** [comment]
I just realize that sending images is a feature of continue over Microsoft copilot, which has not supported the feature yet.
