### ISSUE TITLE
Ollama tab autocomplete sometimes triggers a persistent error popup in vscode

### ISSUE THREAD

**Issue by evertjr** [continuedev/continue#1202]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: Preview
- IDE: vscode
```

### Description

Sometimes when using Ollama with tab autocompletion it triggers an error about parsing the response with server status: "1". This error keeps popping even if I disable notifications from continue and it's very distracting. I think the real bug is it not respecting my notification settings.

### To reproduce

in config.json

  "tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "ollama",
    "model": "codeqwen:7b-chat-v1.5-q5_1",
    "apiBase": "http://localhost:11434"
  },

1 - enable tab autocomplete
2 - start using it and it randomly trigger this error (I've tested with multiple models)
3 - The popup will stay opened until click close
4 - Even if I click on the cog icon and turn off notification from continue it will eventually show up again

### Log output

```Shell
Error parsing Ollama response: Error: unexpected server status: 1 {"error":"unexpected server status: 1"}
```

**Comment by alexup71rus** [comment]
Intellij has the same problem. I can use chat in Intellij and all continue functions work in VSCode, but I can't use suggestions in Intellij
