### ISSUE TITLE
Git Diff ("@diff" ) could not get the diff context

### ISSUE THREAD

**Issue by bsx1990** [continuedev/continue#1205]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.4.1
- Continue: 0.0.45
- IDE: IntelliJ IDEA 2024.1 (241.14494.240)
```

### Description

When I'm trying to use the `@diff` to try to add the git diff context, it alway return empty.
Here is the request received from the LLM service:
> [2024-04-29 17:09:50.666] [INFO] Received POST request to /v1/chat/completions with body: {
  "messages": [
    {
      "role": "user",
      "content": "```git diff\n\n```\n\nGit Diff test"
    }
  ],
  "model": "deepseek-7b",
  "max_tokens": 8192,
  "stream": true
}

### To reproduce

1. Open a code repo with IntelliJ IDEA
2. Make some change of the code
3. Open Continue and input `@diff test`

### Log output

```Shell
No Log output
```

**Comment by sestinj** [comment]
@bsx1990 I believe this should be solved in the latest pre-release after [this commit](https://github.com/continuedev/continue/commit/ab55218def8fa67b58253975e14604014c7a64b3). Closing the issue, but if it turns out that I'm mistaken and this is a separate problem, please feel free to re-open
