### ISSUE TITLE
yes, the error is to accredit the account, not only to sponsor you

### ISSUE THREAD

**Issue by florinmax36** [continuedev/continue#1206]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continuaţi:
- IDE:
```

### Description

yes, the error is to accredit the account, not only to sponsor you

**Comment by florinmax36** [comment]
the error is that you do not accredit accounts and only want sponsorships

Trimis de pe Outlook pentru Android<https://aka.ms/AAb9ysg>
________________________________
From: Florea Ghinea ***@***.***>
Sent: Monday, April 29, 2024 5:39:18 PM
To: continuedev/continue ***@***.***>
Cc: Florea Ghinea ***@***.***>; Your activity ***@***.***>
Subject: [continuedev/continue] yes, the error is to accredit the account, not only to sponsor you (Issue #1206)


Before submitting your bug report

  *    I believe this is a bug. I'll try to join the Continue Discord<https://discord.gg/NWtdYexhMs> for questions
  *    I'm not able to find an open issue<https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue> that reports the same bug
  *    I've seen the troubleshooting guide<https://continue.dev/docs/troubleshooting> on the Continue Docs

Relevant environment info

- OS:
- Continuaţi:
- IDE:

Description

yes, the error is to accredit the account, not only to sponsor you

To reproduce

No response

Log output

No response

**Comment by sestinj** [comment]
Hi @florinmax36, I'm not quite catching on to the issue here, could you explain a bit more about what you're looking to improve?

**Comment by sestinj** [comment]
I'm going to close this issue because I haven't heard back, but please feel free to re-open if you have the chance to get back with me!
