### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by ibehnam** [continuedev/continue#1210]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
Happened out of the blue and the only way to get rid of this annoying issue is to completely disable the extension. It happens on the stable and pre-release branches.
```

### Description

![Kapture 2024-05-01 at 00 20 46](https://github.com/continuedev/continue/assets/58621210/8f7f3dce-41f6-426f-a0b8-c508213c273a)

**Comment by sestinj** [comment]
@ibehnam Do you happen to have a CustomLLM in your config.ts? I saw this for the first time yesterday when I was adding one of my own

**Comment by ibehnam** [comment]
@sestinj I use the following LLMs in my config if that helps:

```
{
  "allowAnonymousTelemetry": false,
  "models": [
    {
      "tabAutocompleteModel": {
        "title": "💻 Tab Autocomplete Model",
        "provider": "ollama",
        "model": "deepseek-coder:6.7b",
        "apiBase": "https://localhost:11434"
      },
      "tabAutocompleteOptions": {
        "useCopyBuffer": true,
        "useSuffix": true,
        "multilineCompletions": true,
        "maxPromptTokens": 400,
        "prefixPercentage": 0.5
      }
    },
    {
      "title": "💻OL🐢⭐ Phi-3",
      "model": "phi3",
      "provider": "ollama",
      "contextLength": 4096
    },
    {
      "title": "💻OL🐢⭐ codegemma:7b-code-q8_0",
      "model": "llama3:8b-instruct-q8_0",
      "provider": "ollama",
      "contextLength": 16384
    },
    {
      "title": "💻OL🐢⭐ Llama-3-8B",
      "model": "llama3:8b-instruct-q8_0",
      "provider": "ollama",
      "contextLength": 16384
    },
    {
      "title": "💻OL🐢⭐ DeepSeek:6.7B",
      "model": "DeepSeek-Coder:6.7B",
      "provider": "ollama",
      "contextLength": 16384
    },
    {
      "title": "🛜OR🏎️⭐ Haiku",
      "model": "anthropic/claude-3-haiku:beta",
      "provider": "openai",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "...",
      "contextLength": 200000
    },
    {
      "title": "🛜OR⭐⭐ Sonnet",
      "model": "anthropic/claude-3-sonnet:beta",
      "provider": "openai",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "...",
      "contextLength": 200000
    },
    {
      "title": "🛜OR⭐⭐⭐ Opus",
      "model": "anthropic/claude-3-opus:beta",
      "provider": "openai",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "...",
      "contextLength": 200000
    },
    {
      "title": "🛜OR⭐⭐⭐ GPT-4",
      "model": "openai/gpt-4-1106-preview",
      "contextLength": 32768,
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "...",
      "completionOptions": {
        "temperature": 0.8,
        "topK": 50,
        "topP": 0.9,
        "presencePenalty": 1,
        "frequencyPenalty": 1
      },
      "provider": "openai"
    }
  ],
  "systemMessage": "Act like a professional Python and Rust developer. Always use types, annotations, and elegant algorithms. Write clean, efficient, and maintainable code. Assume all necessary imports are already installed and imported, so do NOT import them. Don't talk---just write the code. Don't explain your code unless asked.",
  "completionOptions": {
    "temperature": 0.8,
    "topP": 0.9,
    "topK": 50,
    "presencePenalty": 1,
    "frequencyPenalty": 1,
    "maxTokens": 2048
  },
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit highlighted code"
    },
    {
      "name": "comment",
      "description": "Write comments for the highlighted code"
    },
    {
      "name": "share",
      "description": "Download and share this session"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    }
  ],
  "customCommands": [
    {
      "name": "cc",
      "prompt": "Fix the code. Keep the code comments to a minimum. Your answer should be only the fixed code.",
      "description": "fix the highlighted code"
    },
    {
      "name": "vv",
      "prompt": "What's the Vim command or shortcut to do this? Your answer should be only the Vim command or shortcut.",
      "description": "Vim How-To"
    },
    {
      "name": "test",
      "prompt": "Write a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 25,
        "nFinal": 5,
        "useReranking": true
      }
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "open",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "open"
    },
    {
      "name": "search"
    },
    {
      "name": "url",
      "params": {
        "presetUrls": [
          "https://continue.dev/docs/customization",
          "https://news.ycombinator.com"
        ]
      }
    },
    {
      "name": "tree"
    },
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete",
    "provider": "free-trial",
    "model": "starcoder-7b"
  },
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  }
}
```

**Comment by harrychih** [comment]
Hi, I have had the same situation, and my chat interface won't show up on my code-server as well. Just curious if you have solved the issue?

**Comment by juansebastianl** [comment]
Are y'all using WSL? I wonder if it's related to https://github.com/continuedev/continue/issues/2780 - I'm experiencing the same thing on WSL. I'm also getting `Error streaming response: Cannot read properties of undefined (reading 'model')` which implies I haven't defined models in my config, but when I open my config (using the button inside the extension) there are my normal models there.

**Comment by juansebastianl** [comment]
Not sure if I should make a separate issue but this only happens in `v0.8.55`.

**Comment by Sernight** [comment]
Hi! I've tried it on wsl2/ubuntu (vs code) and macOS (jet brains) and got same results.

**Comment by sestinj** [comment]
0.8.55 should fix, and given the confirmation above I'm going to close this, but if it turns out that anyone is still experiencing, please re-open!

**Comment by dominik7680** [comment]
I'm also getting Error streaming response: Cannot read properties of undefined (reading 'model')
![image](https://github.com/user-attachments/assets/86217910-c670-4d48-b0c5-584524be52d6)



Models are not loading:
![image](https://github.com/user-attachments/assets/b5ff7422-167e-4258-834b-3d7738b98ccb)

**Comment by BastianBN** [comment]
I have the same problem on 0.8.66 when I'm trying to use the ctrl+i feature on an empty file. I'm contacting a hosted on GCP Qwen 2.5 Coder 3B through vLLM with an openAI API

`Error streaming diff: TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

**Comment by YFrendo** [comment]
> I have the same problem on 0.8.66 when I'm trying to use the ctrl+i feature on an empty file. I'm contacting a Qwen 2.5 Coder 3B model hosted on GCP through vLLM with an openAI API
> 
> `Error streaming diff: TypeError: Cannot read properties of undefined (reading 'toLowerCase')`
> 

I have the exact same error on VScode with continue 0.9.286. The error only trigger with the ctrl+i feature and also only with the Qwen 2.5 Coder (The size of the model don't impact) I'm also with VLLM.

The error don't trigger with a LLAMA3.1 also on VLLM

**Comment by YFrendo** [comment]
After some invistagation it the issue don't come from the model but from the selected provider.

Everything work with "openai" provider but the error trigger with the "vllm" provider

**Comment by Kari-C** [comment]
Mine was fixed when I removed the following from config.json
```
  "reranker": {
    "name": "free-trial"
  }
```

**Comment by sharath3589** [comment]
> Mine was fixed when I removed the following from config.json
> 
> ```
>   "reranker": {
>     "name": "free-trial"
>   }
> ```
> 
> If that doesn't work, remove both of these;
> 
> ```
>   "embeddingsProvider": {
>     "provider": "free-trial"
>   },
>   "reranker": {
>     "name": "free-trial"
>   }
> ```

That worked, thank you! @Kari-C

**Comment by nothingness6** [comment]
> Mine was fixed when I removed the following from config.json
> 
> ```
>   "reranker": {
>     "name": "free-trial"
>   }
> ```
> 
> If that doesn't work, remove both of these;
> 
> ```
>   "embeddingsProvider": {
>     "provider": "free-trial"
>   },
>   "reranker": {
>     "name": "free-trial"
>   }
> ```

Oh, it works! Thank you so much!

**Comment by highly-illiquid** [comment]
> Mine was fixed when I removed the following from config.json
> 
> ```
>   "reranker": {
>     "name": "free-trial"
>   }
> ```
> 
> If that doesn't work, remove both of these;
> 
> ```
>   "embeddingsProvider": {
>     "provider": "free-trial"
>   },
>   "reranker": {
>     "name": "free-trial"
>   }
> ```

This worked!! 👍

**Comment by Ginson** [comment]
> Mine was fixed when I removed the following from config.json
> 
> ```
>   "reranker": {
>     "name": "free-trial"
>   }
> ```
> 
> If that doesn't work, remove both of these;
> 
> ```
>   "embeddingsProvider": {
>     "provider": "free-trial"
>   },
>   "reranker": {
>     "name": "free-trial"
>   }
> ```
First option worked for me. Thanks a lot!!
