### ISSUE TITLE
Custom command doesn't include code in Visual Studio

### ISSUE THREAD

**Issue by Robinsane** [continuedev/continue#1219]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows
- Continue: v0.8.25 as well as v0.9.123
- IDE:Visual Studio code
```

### Description

I'm having problems with custom commands in Visual Studio code, It sounds similar to https://github.com/continuedev/continue/issues/838 

The first time it seems to not send my selected / highlighted code together with the command to the llm. It gives some bullocks answer about the Python re module or it answers as follows: "Sure, I'd be happy to help! However, I'll need you to provide the code...". If I continue the conversation (aka second time and up) the answers do seem to make sense.

Awhile ago (weeks? months?) I did not experience this problem.
At the same time I'm not experiencing this problem in the PyCharm extension.

Update:
Starting a new Continue session /w the +-button and rightclicking my selected code + choosing "Add Highlighted Code to Context" results in the same problem.

**Comment by sestinj** [comment]
@Robinsane is this using custom commands like [here](https://docs.continue.dev/customization/slash-commands#custom-commands-use-natural-language)? We did recently change the format to be much more flexible, so that you will have to add the {{{ input }}} templating variable wherever you prefer in the prompt (typically at the start). That should also explain why it's not happening in JetBrains (hasn't been released there yet)

**Comment by Robinsane** [comment]
> @Robinsane is this using custom commands like [here](https://docs.continue.dev/customization/slash-commands#custom-commands-use-natural-language)? We did recently change the format to be much more flexible, so that you will have to add the {{{ input }}} templating variable wherever you prefer in the prompt (typically at the start). That should also explain why it's not happening in JetBrains (hasn't been released there yet)

That's it, thanks a ton for the fast reply!
I just tested and the {{{ input }}}\n\n in front of the custom command prompt doesn't seem to disrupt the older version in Pycharm much, so even if it doesn't use it yet, I can distribute this config within my company :)

Thanks again!
