### ISSUE TITLE
Cmd + I not working with Groq

### ISSUE THREAD

**Issue by Thelvaen** [continuedev/continue#1221]
Hello Cmd+I command is not working with Groq.

Looks like the URL for completions is incorrect for the groq provider (going for /openai/v1/completions instead of /openai/v1/chat/completions).

can probably get more info from #1186

**Comment by Thelvaen** [comment]
The workaround with the config.json and provider openai is still ok.

**Comment by sestinj** [comment]
@Thelvaen Can you share which version of Continue this is happening on? I believe this is currently solved in pre-release and just waiting to be pushed to the main version tomorrow

**Comment by Thelvaen** [comment]
@sestinj ahhhh that's definitely the case then, I'm on the release version published on the extension market place. I'll check further in tomorrow at work, but I believe you've nailed my issue.

**Comment by Thelvaen** [comment]
tested it works with 0.9.124.

Thanks for your support & help :)
