### ISSUE TITLE
Embedding model -reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by majuansari** [continuedev/continue#1223]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Macosx 
- Continue: v0.0.43-jetbrains
- IDE: Intellij
```

### Description

FetchError: request to https://api.voyageai.com/v1/embeddings failed, reason: unable to get local issuer certificate

### To reproduce

	"embeddingsProvider": {
		"provider": "openai",
		"model": "voyage-code-2",
		"apiBase": "https://api.voyageai.com/v1/",
		"apiKey": "--"
	},
	
	
Add voyage ai or open ai as embedding provider.

And run @codebase  explain.

Quesiton: is there a verify_ssl for embedding provider ?

### Log output

```Shell
Error running handler for "context/getContextItems":  FetchError: request to https://api.voyageai.com/v1/embeddings failed, reason: unable to get local issuer certificate
FetchError: request to https://api.voyageai.com/v1/embeddings failed, reason: unable to get local issuer certificate
```

**Comment by sestinj** [comment]
@majuansari In the next release of the JetBrains extension (0.0.47, and currently in VS Code) you will be able to use the global "requestOptions" object. It is the same as the one you can put inside of a model, but goes in the root of config.json.

**Comment by majuansari** [comment]
Thanks for the update @sestinj . Any tentative timeline for the release?

**Comment by sestinj** [comment]
Aiming for Friday!

**Comment by sestinj** [comment]
I'm going to close this issue now that the release has long since been available. Feel free to open another issue if any other problems come up!

**Comment by PerfectDark99** [comment]
> @majuansari In the next release of the JetBrains extension (0.0.47, and currently in VS Code) you will be able to use the global "requestOptions" object. It is the same as the one you can put inside of a model, but goes in the root of config.json.

What it be possible to explain in more detail what this means? I'm triying to setup an azure AI endpoint and I'm getting this exact error.
