### ISSUE TITLE
Can't make it work with LMStudio

### ISSUE THREAD

**Issue by tthierryEra** [continuedev/continue#1224]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: v0.8.25
- IDE: VsCode

I'm using LMStudio with mistral or phi or llama3 whatever
```

### Description

![image](https://github.com/continuedev/continue/assets/103579901/5329cb41-da3d-49d0-bd16-3b90915d3b5f)

![image](https://github.com/continuedev/continue/assets/103579901/ec920dc1-813f-4e25-a3b5-587b4c44e819)

Hello,

When using LMStudio as  result is the same, in the chatbot and in file I always get the system prompt back and all whatever I try on the prompt formating is not working.

Really need help here. It's working with ollama and external apis. 

Thanks

**Comment by sestinj** [comment]
@tthierryEra can you share your config.json so I can better help debug?

**Comment by tthierryEra** [comment]
Hello Thank you 

I did not changed anything else than adding models
    {
      "title": "LM Studio - Llama 8G",
      "provider": "lmstudio",
      "model": "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"
    },
    {
      "title": "Crusoeai Llama 8B - 262k",
      "provider": "lmstudio",
      "model": "crusoeai/Llama-3-8B-Instruct-262k-GGUF"
    },

**Comment by sestinj** [comment]
@tthierryEra thanks. I think maybe the best place to check would be in the "Output" tab next to the VS Code terminal, and then in the dropdown on the right select "Continue - LLM Prompts/Completions". This will show the exact prompt send to the LLM. This in addition to the logs that you see on the side of LM Studio will likely show us what we need to see (it's definitely just a prompt formatting mistake).

The first possible solution I can think of is to double-check your prompt formatting settings on the LM Studio side. I believe you can edit these in the right side panel

**Comment by tthierryEra** [comment]
So from my testing, whenever I add a system prompt wheter it's directly in LMStudio or in continue.dev code like config.ts, that system prompt will be printed back to the chat.


If I leave everything empty it's "working" but really not useful as the llm does know how to react/interact.

Exemple:

Output from continue
`==========================================================================
==========================================================================
Settings:
contextLength: 4096
model: MaziyarPanahi/WizardLM-2-7B-GGUF
maxTokens: 1024

############################################

<user>
hello
`

Completion:
`==========================================================================
==========================================================================
Completion:

You are a useful coding assistant.hello! How can I assist you today?

As a coding assistant, I'm here to help with a wide range of programming-related questions and tasks. Whether you need assistance writing or understanding code, debugging issues, learning about best practices, or exploring new technologies, feel free to ask. What do you need help with today?
`

I tried to leave everything empty. Or add <user> as the prefix for user message. 
Not working either :-(


`Settings:
contextLength: 4096
model: MaziyarPanahi/WizardLM-2-7B-GGUF
maxTokens: 1024

############################################

<user>
hello. How's it going?

==========================================================================
==========================================================================
Completion:

You are a useful coding assistant.<user>hello. How's it going?</user>Hello there! I'm doing well, thank you. It's always a pleasure to assist with any questions or tasks you might have. How can I help you today?`


Maybe I'm doing something wrong?

I tried this
![image](https://github.com/continuedev/continue/assets/103579901/0a624843-8d39-4af6-a3c8-03dc2427a713)

Or all empty
![image](https://github.com/continuedev/continue/assets/103579901/8de1eba8-a915-48d8-bbcd-0c567b790c48)


Not working still have this as result
![image](https://github.com/continuedev/continue/assets/103579901/30021663-0888-46b0-b3c5-1ae76754b95d)

**Comment by xinnod** [comment]
I just ran into this problem and fixed it on my end. The broken behavior happens when running LM Studio 0.2.22. Reverting back to the 0.2.21 version has fixed the prompting formatting.

**Comment by tthierryEra** [comment]
You closed the issue because the solution is to downgrade LMStudio? 
Or is there a fix in continue?
