### ISSUE TITLE
Codebase provider cannot get context in Intellij, but it can index normally in VS Code.

### ISSUE THREAD

**Issue by windchargerj** [continuedev/continue#1225]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 Pro 22H2
- Continue: v0.0.46
- IDE: IntelliJ IDEA, Clion
```

### Description

Codebase index does not seem to be functioning properly on the IntelliJ Platform, as the indexing progress bar is displayed at the bottom of the vscode plugin. Additionally, no search results can be retrieved from the Folders provider.

In IntelliJ:
Codebase context retrieval unsuccessful.
![image](https://github.com/continuedev/continue/assets/72346692/5820bb48-f4a0-4008-b25e-951c01451391)

In vscode:
Everything is functioning properly, including indexing.
![image](https://github.com/continuedev/continue/assets/72346692/fb90f0e1-0dc0-4c3f-ad5c-18130c37ae35)

**Comment by sestinj** [comment]
@windchargerj codebase retrieval/indexing isn't yet supported in JetBrains. I'll be releasing it this week, at which point I'll update this issue

**Comment by felix1982** [comment]
@sestinj  whether the function has been released?

**Comment by sestinj** [comment]
@felix1982 @florian-bellencontre yes I do have good news! This is now released in version 0.0.50

**Comment by windchargerj** [comment]
Thank you very much! It works exactly as anticipated.

**Comment by shubham1166** [comment]
Hey @sestinj, I’m currently using the latest version of Continue. Could you please let me know if codebase retrieval is still not functioning properly in PyCharm? I'm not encountering any errors, but I'm also not getting the desired results in PyCharm. Interestingly, the same code works perfectly in VS Code.
![image](https://github.com/user-attachments/assets/d3c78d44-b53b-4e72-ae23-7beeb0694583)
![image](https://github.com/user-attachments/assets/c2ef26b3-c529-4619-9dc9-3c1575610019)

**Comment by shubham1166** [comment]
Hello @sestinj , looks like the issue that i posted above is only in `0.0.62` version, things are working fine in `0.0.56`

**Comment by sanyue-dev** [comment]
> Did anyone get this working? Not working in IntelliJ still today with the latest version - it can't even answer simple questions like "Which classes call such and such method".
I'm also experiencing this issue in IntelliJ IDEA
