### ISSUE TITLE
SQLITE_ERROR: no such table: lance_db_cache

### ISSUE THREAD

**Issue by majuansari** [continuedev/continue#1232]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MACOSX
- Continue: v0.0.43-jetbrains
- IDE: jetbrains
```

### Description

@codebase  explain code is not working. Trying with ollama and codellama 7:b

### To reproduce

@codebase  explain code 

and use ollama and codellama 7:b as embedding provider as per the configuration

	"embeddingsProvider": {
		"provider": "ollama",
		"model": "codellama:7b",
		"apiBase": "http://localhost:11434"
	},

### Log output

```Shell
[info] Starting Continue core...
Error retrieving from FTS: Error: SQLITE_ERROR: no such table: fts
(node:46925) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created)
Error running handler for "context/getContextItems":  Error: SQLITE_ERROR: no such table: lance_db_cache
Error: SQLITE_ERROR: no such table: lance_db_cache
```

**Comment by sestinj** [comment]
@majuansari codebase retrieval isn't yet supported in JetBrains. I'll be releasing it this week and then will update this issue

**Comment by majuansari** [comment]
@sestinj  This already released ? I can see still 0.0.46 in the Jetbrains market place.

**Comment by sestinj** [comment]
Not quite yet. Sorry it's taking longer than forecasted. Reason is that I tied it to a refactor, but finishing touches are going on the PR rn, so it won't be long

**Comment by majuansari** [comment]
@sestinj  Is this completed for Jetbrains ? I am still getting the error 
Error getting context items from codebase: Error: LanceDB failed to load a native module

It's working perfectly fine on visual studio code though. I am using .49 version for Jetbrains

**Comment by Giattuck** [comment]
Hello i have the same error on vscode, any help? tryed on the pre-release too.

**Comment by sestinj** [comment]
@majuansari Version 0.0.50 was just released with the fix for this

**Comment by sestinj** [comment]
@Giattuck Would you be able to share the full error that you are seeing?

**Comment by Giattuck** [comment]
@sestinj how can i do please?

**Comment by sestinj** [comment]
@Giattuck You can find the logs here: https://docs.continue.dev/troubleshooting#jetbrains

**Comment by Giattuck** [comment]
@sestinj sorry for the late reply, i think it was a permission problem on some files, now it is working thank you very much.

**Comment by av** [comment]
To whomever experiencing this in VS Code with a brand new installation of Continue.dev - ensure that you initiated the indexing via the extension UI. 

When the extension is freshly installed, prior to configuration of the embeddings, etc - the indexing will be paused. It won't resume automatically when the configuration is performed, only when you click on the indexing status indicator
![image](https://github.com/user-attachments/assets/151645d9-0e93-4db3-8f08-ba4c550589a6)
