### ISSUE TITLE
Invalid Relative Import On Contribute Install

### ISSUE THREAD

**Issue by kivo360** [continuedev/continue#1244]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos 14.4.1
- Continue: 0.8.24
- IDE: vscode
```

### Description

Invalid relative import when installing dev environment.

### To reproduce

1. Clone repo and cd to `continue`
2. Run task: Install all dependencies
3. When the extensions package builds I encounter an error. 

### Log output

```Shell
Error: Command failed: npx vsce package --out ./build patch
 ERROR  invalid relative path: extension/../../core/node_modules/@mozilla/readability/.eslintrc.js

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:320:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npx vsce package --out ./build patch'
}
```

**Comment by sestinj** [comment]
@kivo360 This looks to be solved in the latest preview branch after I updated package-lock files. Can you confirm that it looks okay now?

**Comment by wertyac** [comment]
hi, guys. I meet the same issue. I check out the preview branch. not solved. 
Executing prepublish script 'npm run vscode:prepublish'...

> continue@0.9.96 vscode:prepublish
> npm run esbuild-base -- --minify


> continue@0.9.96 esbuild-base
> node esbuild.js --minify

This extension consists of 21827 files, out of which 12100 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 ERROR  invalid relative path: extension/../../core/node_modules/@mozilla/readability/.eslintrc.js

**Comment by sestinj** [comment]
@kivo360 we just switched to using only yarn: https://github.com/continuedev/continue/commit/b99fcbc546fcedf7bc73e266d636a065cc7057bc

which I think should actually solve this problem. You're right that the previous was a false alarm—please let me know if this one also appears to be

Furthermore we had a contributor open this PR: https://github.com/continuedev/continue/pull/1255, which should resolve the files problem completely

**Comment by xiaoxia0617** [comment]
The solution for this issue should be:
1. go to extensions/vscode folder
2. change npm to yarn, execute "yarn install"
3. then execute "npm link @continuedev/core"
4. last execute "yarn package"
Reason:
The "vsce package" use yarn to pack defaultly, there is some incompatibality unknown, but once you change npm to yarn under "extensions/vscode" to do package, that issue will not show again.

**Comment by kivo360** [comment]
Trying it when I get back home

**Comment by kivo360** [comment]
> The solution for this issue should be:
> 
> 1. go to extensions/vscode folder
> 2. change npm to yarn, execute "yarn install"
> 3. then execute "npm link @continuedev/core"
> 4. last execute "yarn package"
>    Reason:
>    The "vsce package" use yarn to pack defaultly, there is some incompatibality unknown, but once you change npm to yarn under "extensions/vscode" to do package, that issue will not show again.

I was able to get past the relative issue. Now I'm stuck with trying to download the esbuild binary for Mac M1 processors.

My next issue is listed here: https://github.com/continuedev/continue/issues/1289

**Comment by kivo360** [comment]
Since I have a new problem to deal with, I'm closing this issue as complete.
