### ISSUE TITLE
[CON-236] Context provider for "local docs" or external directories

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1251]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

There's no way to ingest and reference a local directory of documentation or code outside of what is tracked in git in the current workspace.

### Solution

A new context provider that lets you specify directories:

```json
{ "name": "externalDirectories", "params": { "directories": ["/path/to/my/local/docs"] }
```

<sub>[CON-236](https://linear.app/continue/issue/CON-236/context-provider-for-local-docs-or-external-directories)</sub>

**Comment by JoseVega** [comment]
We should be able to specify the file extensions to include and it should work recursively, for example, if we only want to include documentation files (.html, .md), or if we only want to include other file extensions for code generation (code libraries, etc).
