### ISSUE TITLE
Default config contains only code and docs context providers

### ISSUE THREAD

**Issue by spew** [continuedev/continue#1257]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux
- Continue: 0.8.27
- IDE: vscode
```

### Description

After deleting your continue folder, the default config which is created contains only the `code` and `docs` context providers. I believe this is because of `migrate("codeContextProvider", ...)` and `migrate("docsContextProvider1", ...)` in `core/config/load.ts`. The impact is that only those two context providers are enabled. Once those two are deleted from `config.json`, then all eight of the default context providers are available.

### To reproduce

1. Install continue for vscode 0.8.27.
2. Delete your `~/.continue/config.json`.
3. Observe that a new `config.json is created and only two context providers are added. Observe that only those two context providers are available in the interactive chat window.

**Comment by sestinj** [comment]
@spew good find! definitely doesn't make sense to have these migrations anymore, so I've gone ahead and deleted them: https://github.com/continuedev/continue/commit/0101e6ff5ba649657c3f4f3f6ddf53920bbb9235
