### ISSUE TITLE
Custom command is being ignored when we use any context variable in the message

### ISSUE THREAD

**Issue by JoseVega** [continuedev/continue#1259]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 Pro
- Continue: 0.9.129
- IDE: VSCode Latest
```

### Description

The custom command is ignored when we submit a message like this:
/my-custom-command-instructions What context providers exist? @URL: https://docs.continue.dev/customization/context-providers 

In this example, it will send the message to the LLM including the context of the URL and message, but the custom command is excluded from the message. It only works with one or the other but not both at the same time. I tried different context options and I noticed the same bug so it's not related to a specific context option.

**Comment by sestinj** [comment]
@JoseVega thanks for pointing this out! I just made the fix here (https://github.com/continuedev/continue/commit/61d472f86ebc95826a95fc30724b1b1ec573675b). New pre-release coming soon!
