### ISSUE TITLE
GPT-4o not working on CMD + I 

### ISSUE THREAD

**Issue by evertjr** [continuedev/continue#1276]
### Before submitting your bug report

- [ x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS Sonoma
- Continue: Pre release
- IDE: Vscode
```

### Description

I created a model to use the new GPT-4o and in the chat UI it works perfectly but to do edits using CMD + I it returns a streaming error diff

### To reproduce

in config.json

```
   {
      "title": "GPT-4o",
      "provider": "openai",
      "apiKey": "sk-",
      "model": "gpt-4o",
    },
```

Select a block of code, press CMD + I and ask for some modification, the error immediately appears.

### Log output

```Shell
Error streaming diff: Error: Error: HTTP 404 Not Found from https://api.openai.com/v1/completions { "error": { "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?", "type": "invalid_request_error", "param": "model", "code": null } }
```

**Comment by karavolt** [comment]
did you update continue?
latest gpt api using /v1/messeages not /v1/completions.

**Comment by evertjr** [comment]
> did you update continue? latest gpt api using /v1/messeages not /v1/completions.

Just downloaded the vsix version v0.9.130 from the release page and it fixed the problem.  Thanks!
