### ISSUE TITLE
Error calling Ollama /api/show endpoint: Error: Error: HTTP 404 Not Found from http://127.0.0.1:11434/api/show

### ISSUE THREAD

**Issue by Wilson-fan8877** [continuedev/continue#1279]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:ubuntu 22.04
- Continue:
- IDE:vscode
```

### Description

when use ollama LLM , why this extension call http://127.0.0.1:11434/api/show,   ollama  not have this endpoint 

error messages at dev tools:
Error calling Ollama /api/show endpoint: Error: Error: HTTP 404 Not Found from http://127.0.0.1:11434/api/show

**Comment by sestinj** [comment]
@Wilson-fan8877 Ollama does have this endpoint, at least in their documentation: https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information

Could you share what version of Ollama you are using?

One other way to test this would by try the following curl request:

```bash
curl http://localhost:11434/api/show -d '{
  "name": "llama3"
}'
```

**Comment by homeant** [comment]
Has the problem been solved?

**Comment by trinque** [comment]
This is still a problem and thwarts onboarding for people using ollama.

**Comment by sestinj** [comment]
@trinque @homeant Are you both on the latest version of Ollama? Can you share more details about your setup?

It's pretty clear from their [docs](https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information) that this endpoint should exist, so I'm left wondering what difference in environment might be causing this. Any extra info will help me solve the problem more quickly

**Comment by eklavya** [comment]
I am facing the same issue in both vscode and intellij. It was working before a month or so, I came back to code after a month and it's broken with the mentioned error message.
My tab autocomplete config:
```
"tabAutocompleteModel": {
    "title": "codegemma:7b-code",
    "provider": "ollama",
    "model": "codegemma:7b-code"
  },
  "tabAutocompleteOptions": {
    "useCopyBuffer": true,
    "maxPromptTokens": 400,
    "prefixPercentage": 0.5
  }
```

Model config:
```
{
      "title": "codegemma:7b-code",
      "model": "codegemma:7b-code",
      "contextLength": 2048,
      "completionOptions": {},
      "apiBase": "http://localhost:11434",
      "provider": "ollama"
    }
```
```
curl http://localhost:11434/api/show -d '{ 
  "name": "codegemma:7b-code"
}'
``` 
shows information about the model successfully.

**Comment by sestinj** [comment]
I finally figured out that this is happening when requesting details about a model that is in an outdated format. So unless you manually go through and delete older models, the response will be the same from Ollama. For this reason we'll be ignoring it in all future releases. Next one for JetBrains should be early this week and for VS Code it's already released in pre-release

**Comment by zolakt** [comment]
I'm still getting this error, even with the prerelease version.
`Failed to sync remote config: Error: Failed to sync remote config (HTTP 404): Not Found`

I've set the remote url to: http://127.0.0.1:11434
Model is: "deepseek-coder-v2:16b-lite-instruct-q2_K"

Here is a screenshot of a valid request in postman

![Image](https://github.com/user-attachments/assets/ad48850e-b342-495a-b05b-7ae0352c3818)
