### ISSUE TITLE
Telemetry got changed to True silently.

### ISSUE THREAD

**Issue by TiagoTiago** [continuedev/continue#1295]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux Mint 20.3 Una 64-bit Linux Mint 20.3 Una 64-bit
- Continue: v0.9.132 (pre-release)
- IDE: Version: VSCodium 1.89.0
```

### Description

While tweaking things in the config.json I noticed the Telemetry setting had reverted to "true" without warning. That's fucked up.

### To reproduce

Dunno how long it has been like this. I always opt-out of telemetry whenever presented with the choice, or otherwise see it hidden in the settings.

**Comment by sestinj** [comment]
@TiagoTiago I'm going to fix this immediately, there's absolutely no world in which we want this to happen.

If you can share any more details about what seemed to happen it would help me immensely to solve this quickly.

I will update soon! Very sorry this happened

**Comment by TiagoTiago** [comment]
I'm sorry, I don't know what more details I can give; I just noticed it was set to true while I am confident I would've left it at false. Over time I've occasionally seen the extension asking VSCodium to be restarted, I imagine to apply some update, I didn't double-check the settings every time that happened, so I don't even know if it happened recently or not. I remember there was one time maybe some weeks ago where the extension received an update and forgot the models I had set and I had to add them again, perhaps that the could have been the moment when the telemetry setting also go reset, but I didn't think to check at the time, so it's just a guess.

**Comment by sestinj** [comment]
@TiagoTiago this is good information, I appreciate that. I do recall that we had made the mistake of rewriting models in config.json for a brief instant in time. This was a release that was followed up almost immediately with a fix, but chances are that a few folks would have had the misfortune of needing to add back their old setup. What I'm looking into now is whether this would have also included resetting telemetry.

Testing is showing that the current setup does not override allowAnonymousTelemetry: false, so under the assumption that the problem happened after selecting an option on the new onboarding screen, this to me seems like the reassurance needed to know that the problem has been solved.

If you wanted to validate this, these are the steps that I am following:

1. Set `"allowAnonymousTelemetry": false` in config.json
2. Click the "?" icon in the bottom right corner of Continue
3. You'll see this screen, where you can click "Open Tutorial" in the top right

<img width="545" alt="Screenshot 2024-05-16 at 7 13 37 PM" src="https://github.com/continuedev/continue/assets/33237525/aa1e6e8c-1e4a-4e00-adda-935f0f9681c5">

4. Select any of the options on the onboarding screen (I've tested with all 3), and click "Continue"
5. Open config.json to see that we've populated the model attributes, but that `"allowAnonymousTelemetry": false` remains intact

**Comment by TiagoTiago** [comment]
Wiped out everything when I clicked on the Ollama option and tried to proceed with the wizard (I had gone the manual route before using TextGenWebUI, so I decided to try differently this time to be sure I could see if it changed anything in the json; apparently not only it did, but it did too much); telemetry remained `false` though, so at least that's good.

**Comment by sestinj** [comment]
Ok, telemetry being the same is the important part. I made a small update here to avoid overwriting the entire models list like you described: https://github.com/continuedev/continue/commit/6f8528a5346c75ddfe05abcc3f43e6076dd97791

I want to be completely sure before I go ahead and close this issue—does it seem that there is anything still outstanding?

**Comment by TiagoTiago** [comment]
I can't test the new patched version at the moment; but if both the original telemetry reset issue and the wiping of already setup models have been fixed, then I don't see need for this bug report to remain open.

I won't be asking for the little bit of data that has been collected to be erased because if the collection is as restricted as described at the ["What we track"](https://docs.continue.dev/telemetry#what-we-track) section, then providing sufficient additional data to identify what came from me will only serve to speed up de-anonymization efforts; what leaked, is already leaked, can't do anything about it that won't make matters worse.

**Comment by TiagoTiago** [comment]
> > @TiagoTiago I'm going to fix this immediately, there's absolutely no world in which we want this to happen.
> > If you can share any more details about what seemed to happen it would help me immensely to solve this quickly.
> > I will update soon! Very sorry this happened
> 
> Why isn't telemetry opt-in?

Probably a good compromise between the developer's desire to have the most telemetry possible, and the user rights, would be to have it so when the setting is not initialized, prompt the user on install/update to pick between "Enabled" and "Disabled", with both at first set as empty radio buttons, so that by default it remains uninitialized until the user makes a decision. Having a default that's either of the options will bias the end result as people have a tendency to leave settings at the default value. In short, neither opt-in nor opt-out, just plain opt :)

**Comment by sestinj** [comment]
Closing this issue because the original concern has been addressed. Thank you both for your feedback
