### ISSUE TITLE
continue don't work

### ISSUE THREAD

**Issue by skywu-qingfeng** [continuedev/continue#1297]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:windows 11
- Continue:0.46
- IDE: android studio
```

### Description

Continue don't work

### Log output

```Shell
[info] Starting Continue core...
[info] Starting Continue core... 
Failed to setup CA:  Error: Module not found in bundle: ./crypt32-x64
(node:23588) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created) 
Error calling Ollama /api/show endpoint: TypeError: fetch failed 
[info] Exiting Continue core...
```

**Comment by sestinj** [comment]
@skywu-qingfeng thanks for sharing the logs. I'm shipping a new Early Access Program version, 0.0.47, today and it should fix the error you're seeing.

**Comment by zwx219159** [comment]
When will IDEA version 0.0.47 be released?

**Comment by zwx219159** [comment]
> @skywu-qingfeng thanks for sharing the logs. I'm shipping a new Early Access Program version, 0.0.47, today and it should fix the error you're seeing.

When will IDEA version 0.0.47 be released?

**Comment by sestinj** [comment]
@zwx219159 Sorry I missed your message. 0.0.47 and and handful of newer versions have now been released
