### ISSUE TITLE
Editing the description of a slash command in config.json has no effect

### ISSUE THREAD

**Issue by giraud10** [continuedev/continue#1302]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 / Linux
- Continue: v0.9.135
- IDE: VSCode
```

### Description

Editing the description of a slash command in config.json has no effect.
The description is not overloaded in the command implementation class.

### To reproduce

1. Edit the description of a slash command (e.g. edit) in config.json
{
      "name": "edit",
      "description": "Editer le code sélectionné"
 }
2. After saving the config.json file, the description is not overloaded in the command implementation class
![image](https://github.com/continuedev/continue/assets/89643755/6a5cddda-e7ba-446a-9457-dcb739ef57e5)

**Comment by sestinj** [comment]
thanks for pointing this out! I just fixed it as a part of this commit: https://github.com/continuedev/continue/commit/4523fe6d9cb4cd70e4579b04c59c53478ce8092d, and it'll take effect in the next pre-release
