### ISSUE TITLE
Package into a vsix file, the out directory inside is missing build and node.modules

### ISSUE THREAD

**Issue by zxqkevin** [continuedev/continue#1303]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Package into a vsix file, the out directory inside is missing build and node.modules

**Comment by PaulX1029** [comment]
same problem, how u solved it?
