### ISSUE TITLE
Package into a vsix file, the out directory inside is missing build and node.modules

### ISSUE THREAD

**Issue by zxqkevin** [continuedev/continue#1304]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
```

### Description

Package into a vsix file, the out directory inside is missing build and node.modules

**Comment by sestinj** [comment]
@zxqkevin Do you have any error logs that you are able to share? I would first look at https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#vs-code to learn how to set up

**Comment by zxqkevin** [comment]
This is an environment compilation issue. Now it's resolved. Thank you for your help. @sestinj
