### ISSUE TITLE
codebase provider throwError getting context items from codebase: TypeError: part.replace is not a function

### ISSUE THREAD

**Issue by vetedde** [continuedev/continue#1306]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04
- Continue: v0.9.135 (pre-release)
- IDE: VSCode 1.89.1
```

### Description

When I enter promt with the provider Codebase, I get error "Error getting context items from codebase: TypeError: part.replace is not a function"

### To reproduce

1. Open continue
2. Enter promt `@Codebase describe project`

### Log output

There are no additional logs in the console

**Comment by riccardo-unipg** [comment]
same problem

**Comment by aldys33** [comment]
It's happening to me as well though that I'm using local vscode

**Comment by Cheizr** [comment]
Same:
Error getting context items from docs: TypeError: part.replace is not a function

**Comment by edeuser** [comment]
same:
When add a new doc site , then type @doc , ask questions, VS code will got the error.

**Comment by ku4nc4** [comment]
same:
Both of my machines, one running macOS and the other Windows, are exhibiting the same behavior in VS Code. Pre indexed docs nor self added docs are both showing `part.replace is not a function`

**Comment by ku4nc4** [comment]
It seems to be fixed on latest as of today v0.8.29, checked on both platform

**Comment by riccardo-unipg** [comment]
yes the bug has been fixed, it no longer shows the error. So here we are, can you tell me if this happens to you too? Because this other bug was not fixed with the new version 0.8.29.
https://github.com/continuedev/continue/issues/1321#issue-2305452689

**Comment by sestinj** [comment]
Thanks everyone for the confirmation of the fix. I'll close the issue now, but @riccardo-unipg the other issue you've mentioned is still open

**Comment by diana-jung** [comment]
Occurred in v0.8.47.

**Comment by mnordine** [comment]
Getting this in `v0.8.47` and `v0.9.199 (pre-release)`

**Comment by yuraneb** [comment]
Having the same issue. Tried several embeddings models. Wiped the index folder (which I assume contains the db files and forced re-indexing.

**Comment by kevin-pw** [comment]
I am seeing the same error with Continue version 0.8.47 when chatting with `@codebase`:
`Error getting context items from codebase: TypeError: db.search is not a function`

This errors appears after the indexing successfully completes on a relatively large codebase of over 1000 files.
