### ISSUE TITLE
binary build error npm error Invalid name: "continue-node_modules-@lancedb"

### ISSUE THREAD

**Issue by belief-cyf** [continuedev/continue#1311]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:macos 10.15.7
- Continue:main new
- IDE:vscode
```

### Description

node version v22.1.0

When started with the latest code on the main branch， node binary/build.js error

execCmdSync(`npm init -y && npm i -f ${package} --no-save`);

node build.js 
[info] Copied 
[info] Downloading prebuilt lancedb...
[info] Downloading darwin-x64...
Copying @lancedb/vectordb-darwin-x64 to @lancedb
npm error Invalid name: "continue-node_modules-@lancedb"

npm error A complete log of this run can be found in: /Users/xxx/.npm/_logs/2024-05-18T02_54_23_742Z-debug-0.log
Error executing command 'npm init -y && npm i -f @lancedb/vectordb-darwin-x64 --no-save':  ,
,npm error Invalid name: "continue-node_modules-@lancedb"

### Log output

```Shell
~/Desktop/continue
Installing VSCode extension dependencies...
~/Desktop/continue/extensions/vscode ~/Desktop/continue
 WARN  deprecated vsce@2.15.0: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  4 deprecated subdependencies found: @npmcli/move-file@1.1.2, @npmcli/move-file@2.0.1, har-validator@5.1.5, uuid@3.4.0
Packages: +1
+
Progress: resolved 1323, reused 1277, downloaded 0, added 1, done
Done in 7.7s

/Users/caoyf001/Library/pnpm/global/5:
+ @continuedev/core ^1.0.12

> continue@0.9.96 package /Users/caoyf001/Desktop/continue/extensions/vscode
> node scripts/package.js

vsce package completed - extension created at extensions/vscode/build/continue-patch.vsix
~/Desktop/continue
Installing binary dependencies...
~/Desktop/continue/binary ~/Desktop/continue
 WARN  4 deprecated subdependencies found: @npmcli/move-file@1.1.2, har-validator@5.1.5, request@2.88.2, uuid@3.4.0
Packages: +1
+
Progress: resolved 691, reused 665, downloaded 0, added 1, done

dependencies:
+ @lancedb/vectordb-darwin-arm64 0.4.20

Done in 3.8s

> binary@1.0.0 build /Users/caoyf001/Desktop/continue/binary
> node build.js

[info] Copied 
[info] Downloading prebuilt lancedb...
[info] Downloading darwin-x64...
Copying @lancedb/vectordb-darwin-x64 to @lancedb
npm error Invalid name: "continue-node_modules-@lancedb"

npm error A complete log of this run can be found in: /Users/caoyf001/.npm/_logs/2024-05-18T02_56_36_938Z-debug-0.log
Error executing command 'npm init -y && npm i -f @lancedb/vectordb-darwin-x64 --no-save':  ,
,npm error Invalid name: "continue-node_modules-@lancedb"

npm error A complete log of this run can be found in: /Users/caoyf001/.npm/_logs/2024-05-18T02_56_36_938Z-debug-0.log

 ELIFECYCLE  Command failed with exit code 1.

 *  终端进程“/bin/bash '-l', '-c', './scripts/install-dependencies.sh'”已终止，退出代码: 1。 
 *  终端将被任务重用，按任意键关闭。
```

**Comment by belief-cyf** [comment]
run npm init -y in /Users/caoyf001/Desktop/continue/binary/tmp/continue-node_modules-@lancedb error
npm does not support paths containing @ symbols？

**Comment by sestinj** [comment]
@belief-cyf This error should now be solved in the `preview` branch of continue after this PR: https://github.com/continuedev/continue/pull/1305
