### ISSUE TITLE
The extension doesn't show up at all. 

### ISSUE THREAD

**Issue by nothingness6** [continuedev/continue#1312]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 64bit 22H2
- Continue: The lattest version. Just updated.
- IDE: VScode
```

### Description

The extension icon and chat panel don't show up at all. 
![continue-02](https://github.com/continuedev/continue/assets/105210258/7fed7600-f7f6-4eba-885f-04ee7bb96004)

**Comment by sestinj** [comment]
@nothingness6 Would you be able to share the console logs so I can see what is going on? https://docs.continue.dev/troubleshooting#vs-code

**Comment by ipeav** [comment]
I had the same problem today after an unintended restart of VS Code. I had dragged IAV Continue to the right sidebar before. After the restart the sidebar was gone, and also the icon in the Activity Bar.
The solution was to press Ctrl+Alt+L. That pressed, the IAV Continue sidebar appeared again.

Maybe that should be added somewhere to the documentation (I found nothing about it). I had managed to solve the problem after opening the extension settings - extension keyboard shortcuts, where all shortcuts are listed.

**Comment by MAMISHO** [comment]
> I had the same problem today after an unintended restart of VS Code. I had dragged IAV Continue to the right sidebar before. After the restart the sidebar was gone, and also the icon in the Activity Bar. The solution was to press Ctrl+Alt+L. That pressed, the IAV Continue sidebar appeared again.
> 
> Maybe that should be added somewhere to the documentation (I found nothing about it). I had managed to solve the problem after opening the extension settings - extension keyboard shortcuts, where all shortcuts are listed.

Thanks, it works in Mac. So, I reproduce this issue when I install the extension and then move it to the right side, then change the profile. Then if I back or change or reinstall never showing again in the bar.

**Comment by sestinj** [comment]
We're now going to by default open the sidebar whenever the extension is first installed, which should clear up a lot of confusion. Going to close this issue, since I believe that turned out to be the core problem

**Comment by stonez56** [comment]
I'm having the same issue that continue.dev icon won't showing up on my VS Code verticle bar. 

I've tried:

1. Uninstall and then reinstall the extension
2. Remove .continue directory entirely
3. VS code updated to latest (Sep.2024 v1.94)
4. Continue.dev tried v0.8.52 & pre-release v0.9.214 and older version

My PC is a Windows 11 professional 23H2 OS 22631.4169

Here is the developer log:
`<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(65, 60, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" role="link" tabindex="-1" title="https://main.vscode-cdn.net/sourcemaps/d78a74bcdfad14d5d3b1b782f87255d802b57511/core/vs/workbench/out-vscode/vs/workbench/contrib/webview/browser/vs/workbench/contrib/webview/browser/webviewElement.ts:486" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">webviewElement.ts:486</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-on-surface-yellow);">An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(65, 60, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 1344.4px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | mountTo | @ | webviewElement.ts:486
-- | -- | -- | --
  | P | @ | overlayWebview.ts:249
  | claim | @ | overlayWebview.ts:135
  | mc | @ | webviewViewPane.ts:165
  | (anonymous) | @ | webviewViewPane.ts:96
  | B | @ | event.ts:1242
  | C | @ | event.ts:1253
  | fire | @ | event.ts:1277
  | setVisible | @ | viewPane.ts:413
  | (anonymous) | @ | viewPaneContainer.ts:691
  | setVisible | @ | viewPaneContainer.ts:691
  | setVisible | @ | panecomposite.ts:53
  | Eb | @ | compositePart.ts:281
  | Eb | @ | paneCompositePart.ts:230
  | Cb | @ | compositePart.ts:158
  | Bb | @ | compositePart.ts:122
  | Bc | @ | paneCompositePart.ts:509
  | openPaneComposite | @ | paneCompositePart.ts:489
  | await in openPaneComposite (async) |   |  
  | openPaneComposite | @ | paneCompositePartService.ts:49
  | (anonymous) | @ | layout.ts:1079
  | await in (anonymous) (async) |   |  
  | Kb | @ | layout.ts:1085
  | uc | @ | workbench.ts:434
  | (anonymous) | @ | workbench.ts:193
  | invokeFunction | @ | instantiationService.ts:109
  | startup | @ | workbench.ts:156
  | open | @ | desktop.main.ts:131
  | await in open (async) |   |  
  | zMs | @ | desktop.main.ts:403
  | u.load.configureDeveloperSettings | @ | workbench.js:381
  | $ | @ | workbench.js:225
  | (anonymous) | @ | workbench.js:158
  | Promise.then (async) |   |  
  | S | @ | workbench.js:158
  | await in S (async) |   |  
  | (anonymous) | @ | workbench.js:372
  | (anonymous) | @ | workbench.js:661

</span></div>
</body>
</html>`

**Comment by carlos-ramos-br** [comment]
I'm with this problem.
Sometimes Continue disappears and even bringing it back with the shortcut the icon in the activity bar don't come back.

**Comment by arthurmloureiro** [comment]
Same happening here and the `Cmd+Opt+L` does not seem to work anymore.

**Comment by Seefer** [comment]
If things go wacky in VS Code regarding missing Activity Bar icons and their associated panels, press `SHIFT + CTRL + P` (or Mac equivalent) for VS Code Command Bar and type **reset view** to bring up VS Code's `Reset View Locations` command and press Enter. This should restore any custom changes you made to UI layout.

To restore the VS Code Continue key bind you have to head to `Manage -> Keyboard Shortcuts`, type Continue in the search bar and look for `Continue: Add to Chat` or maybe `Continue: Focus Continue Chat` and check the active key binds there and, if empty, add your own.

All extension icons in the Activity Bar open their panels adjacent to the Activity Bar by default (`Explorer`, `Search`, `Run & Debug`, `Source Control` etc) and dragging the panel name to the right side is equivalent to dragging the icon from the Activity Bar itself over to the right. The icon will disappear as the panel is opened on the right. To get the icon back, drag the Continue panel from the right side and drop it on the Activity Bar at your chosen position.

This is a quirk of Activity Bar icons always opening their panels adjacent to the Activity Bar and there's no way to specify panel position left or right independently of the Activity Bar position.

The only other drastic option to get things on the right is to go to `View -> Appearance -> Move Primary Side Bar Right`, but I suspect that's not what people here want.
