### ISSUE TITLE
429 You exceeded your current quota, please check your plan and billing details. 

### ISSUE THREAD

**Issue by wortega285f** [continuedev/continue#1313]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
```

### Description

Error: HTTP 500 Internal Server Error from https://proxy-server-green-l6vsfbzhba-uw.a.run.app/stream_chat Error in Continue free trial server: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
When I tried the Free Trial gpt-4

**Comment by sestinj** [comment]
@wortega285f thanks for reporting this, it should now be resolved. If you'd like to set up Continue for the long run, you can see more [here](https://docs.continue.dev/reference/Model%20Providers/freetrial) about ways of going beyond the free trial

**Comment by wortega285f** [comment]
I know, but I only used it 10 times

**Comment by sestinj** [comment]
Yes! Sorry I didn't communicate super thoroughly here. The "quota" you see mentioned here wasn't your individual quota, but was a result of us running into very high traffic. You should be able to use your full 100 requests now

**Comment by coderz-expert** [comment]
You need to upgrade to a paid plan. Set up a paid account, add a credit or debit card, and generate a new API key if your old one was generated before the upgrade. It might take 10 minutes or so after you upgrade to a paid plan before the paid account becomes active and the error disappears
