### ISSUE TITLE
Self-built Continue VSCode Plugin: Auto-Update to Official Version Despite Disabled Auto-Update in VSCode

### ISSUE THREAD

**Issue by edeuser** [continuedev/continue#1315]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I added debug messages to the source code of the 'Continue' plugin and built it for Visual Studio Code (VSCode). After installing the VSIX file, the plugin successfully outputs debug messages. However, after some time, the plugin is automatically uninstalled and updated to the official release, even though I've disabled the 'Auto Update Extensions' option in VSCode settings.

### Solution

Plugin should not be updated automatically.

**Comment by sestinj** [comment]
@edeuser I've seen this before as well, and unfortunately this seems to be a problem with VS Code, as we have no control over the automatic installation/upgrade.

If you'd like to avoid that, you probably will need to change the extension id here: https://github.com/continuedev/continue/blob/main/extensions/vscode/package.json#L2-L3

**Comment by edeuser** [comment]
@sestinj Thanks, solved this problem by change the name.
