### ISSUE TITLE
Error getting context items from docs: TypeError: Tensor.data must be a typed array for numeric tensor.

### ISSUE THREAD

**Issue by nidstigator** [continuedev/continue#1316]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Mac OS 14.2.1
- Continue: v0.8.28
- IDE: VSCode
```

### Description

any attempt to reference any docs (whether built-in or newly indexed) results in the following error: 
Error getting context items from docs: TypeError: Tensor.data must be a typed array for numeric tensor.

I tried on a fresh install too on a different laptop. Same problem. 

### To reproduce

1. Go to Continue chat interface
2. @Axios or Boto or any other docs, followed by a query

Expected result:
Context will be updated with relevant results from the docs

Actual result:
1. Error getting context items from docs: TypeError: Tensor.data must be a typed array for numeric tensor.
2. the query is sent without context

### Log output

```Shell
ted local extension host with pid 92212.
log.ts:429  WARN [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
9
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
console.ts:137 [Extension Host] Codebase Indexing Complete
log.ts:439   ERR [Extension Host] (node:92212) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:92212) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
2
console.ts:137 [Extension Host] Error calling Ollama /api/show endpoint: Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
log.ts:419  INFO [perf] Render performance baseline is 16ms
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager 
Array(1)
index.html?id=4263c5…ose=webviewView:278 No service worker controller found. Waiting for controllerchange.
console.ts:137 [Extension Host] Codebase Indexing Complete
console.ts:137 [Extension Host] removing requested execution provider "wasm" from session options because it is not available: backend not found.
log.ts:439   ERR [Extension Host] An error occurred during model execution: "TypeError: Tensor.data must be a typed array for numeric tensor.".
console.ts:137 [Extension Host] An error occurred during model execution: "TypeError: Tensor.data must be a typed array for numeric tensor.".
log.ts:439   ERR [Extension Host] Inputs given to model: 
Object
console.ts:137 [Extension Host] Inputs given to model: 
Object
notificationsAlerts.ts:42 Error getting context items from docs: TypeError: Tensor.data must be a typed array for numeric tensor.
﻿
```

**Comment by nidstigator** [comment]
If this helps with debugging:
i went manually installed pre-release `0.9.129` and the issue does not happen there.
the latest pre-release as of today's date has the bug too.

**Comment by alexfncypnts** [comment]
same here on
- macOS 14.3.1  / Windows 10
- Continue: v0.8.28
- IDE: VSCode

Also, might be worth mentioning that embedding a custom Documentation  (JUCE C++ Framework) https://docs.juce.com/master/index.html does not work for some reason, can't see any errors or warnings.

**Comment by sestinj** [comment]
@nidstigator @alexfncypnts I did a git bisect to solve this and a fixed version is now released as the latest on the VS Code marketplace. This would also explain the docs context provider problem

**Comment by alexfncypnts** [comment]
perfect, the error is gone now! thanks a lot!
Any idea why https://docs.juce.com/master/index.html won't get indexed properly? there is no error but it indexes only the welcome page text, not the actual documentation.

Is there any way to index it manually somehow?
