### ISSUE TITLE
High CPU and Memory Accumulation Until Crash

### ISSUE THREAD

**Issue by evanschoffstall** [continuedev/continue#1318]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: latest (0.8.24 - 2024-04-12)
- IDE: latest (1.89.1)
```

### Description

High CPU and Memory Accumulation Until Crash

### To reproduce

1. Fresh VSCode
2. Install WSL Extension
3. Install Continue Extension
4. Connect to WSL with no vscode cache/server
5. Wait 5-10 minutes and watch as idle VSCode chugs 8-15% CPU and from 600 MB to 3GB+
6. Heap Out of Memory error
7. In turn Crashing WSL extension host 
8. Follow prompt to Reload Window and cycle repeats

### Log output

```Shell
▼ Extension Host
Debugger attached.
▼ Extension Host
localProcessExtensionHost.ts:275
localProcessExtensionHost.ts:276
localProcessExtensionHost.ts:275
localProcessExtensionHost.ts:276 [16408:00006B6C00374000]	194823 ms: Mark-Compact 3951.3 (4092.3) -> 3944.6 (4093.5) MB, 2069.99 / 0.00 ms (average mu = 0.455, current mu = 0.012) allocation failure; scavenge might
not succeed
[16408:00006B6C00374000]	196976 ms: Mark-Compact 3952.4 (4093.5) -> 3946.1 (4094.8) MB, 2133.93 / 0.00 ms (average mu = 0.304, current mu = 0.009) allocation failure; scavenge might
not succeed
<— IS stacktrace —>
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
1:	00007FF702183C36 node::SetTracingController+86134
2:	00007FF702183EA9 node::OnFatalError+585
3:	00007FF705298683 v8::Function::NewInstance+835
4:	00007FF705298613 v8::Function::NewInstance+723
5:	00007FF70535AC67 v8::CppHeap::wrapper_descriptor+66791
6:	00007FF703C62CBC v8::internal::StrongRootAllocatorBase::deallocate_impl+136348
7:	00007FF700D72CE4 v8::CppHeap::Terminate+198148
8:	00007FF700D72990 v8::CppHeap::Terminate+197296
9:	00007FF703C7FE59 v8::internal::StrongRootAllocatorBase::deallocate_impl+255545
10:	00007FF7034F9E39 UV_random+5817
11:	00007FF7034FA102 uv_random+6530
12:	00007FF700D737D8 v8::CppHeap::Terminate+200952
13:	00007FF700D6C7D1 v8::CppHeap::Terminate+172273
14:	00007FF700D666A3 v8::CppHeap::Terminate+147395
15:	00007FF700D57E23 v8::CppHeap::Terminate+87875
16:	00007FF700D574E0 v8::CppHeap::Terminate+85504
17:	00007FF700D5E66B v8::CppHeap::Terminate+114571
18:	00007FF700D5E4B4 v8::CppHeap::Terminate+114132
19:	00007FF700FA2285 cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlow+2213
© ▼ Extension host (Localprocess pid: 16408) terminated unexpectedly. Code: 134, Signal: unknown
abstractExtensionService.ts:800
yb @ abstractExtensionService.ts:800
```

**Comment by sestinj** [comment]
@evanschoffstall is this still happening on the latest version of the extension (pre-release, 0.9.x)?

Otherwise, it would be helpful to isolate whether this is a result of indexing. If you set "disableIndexing": true in your `config.json`, does the same problem occur?

I have a few leads on what might be happening, and will update soon anyway, but it would be helpful if you had the time to try this

**Comment by evanschoffstall** [comment]
@sestinj thanks for the very prompt response!

Just tried it now, it is working normally again with the pre-release! Memory and cpu usage did not look abnormal, no extension crashes etc after an hour of waiting and watching.

**Comment by sestinj** [comment]
Fantastic! I'll close the issue optimistically, but don't hesitate to reopen if you start seeing something similar again : )
