### ISSUE TITLE
terminates extention host

### ISSUE THREAD

**Issue by CancerCane** [continuedev/continue#1320]
Type: <b>Bug</b>

While the extentsion is enabled attempt to chat with continue or any other extentsion host will terminate

Extension version: 0.8.28
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.8.9-300.fc40.x86_64
Modes:
Connection to 'attached-container+7b22636f6e7461696e65724e616d65223a22777777222c2273657474696e6773223a7b22686f7374223a22756e69783a2f2f2f72756e2f757365722f313030302f706f646d616e2f706f646d616e2e736f636b227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz (12 x 3458)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|19.55GB (9.63GB free)|
|Process Argv|/run/media/lpaul/DesignStorage/projects/ipaulProject --crash-reporter-id 368dfdee-9a21-4a18-8815-9ee4e362a905|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|

Connection to 'attached-container+7b22636f6e7461696e65724e616d65223a22777777222c2273657474696e6773223a7b22686f7374223a22756e69783a2f2f2f72756e2f757365722f313030302f706f646d616e2f706f646d616e2e736f636b227d7d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
showvideot:31016892
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31049070
fchga941:31046352
pythonprc:31047982
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by sestinj** [comment]
@CancerCane A few questions to help understand what is going on:
1. Is this happening on the latest pre-release as well? (0.9.x)
2. Does this still happen if you disable indexing with `"disableIndexing": true` in `config.json`?
3. Are there any additional logs in the console?: https://docs.continue.dev/troubleshooting#check-the-logs

**Comment by CancerCane** [comment]
I apologize for having to ghost you on this one. I'll have you know though the issue has since been solved. Sorry I have no idea how, as I have been oocupied the last couple months.

**Comment by CancerCane** [comment]
Oh just a moment a fellow student has just informed me it was an issue with another extension that was causing some sort of conflict.
