### ISSUE TITLE
This model is currently overloaded. Please use another model or try again soon.

### ISSUE THREAD

**Issue by wortega285f** [continuedev/continue#1322]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
```

### Description

When I use the free trial of gpt-4, gpt-4 turbo, or any other gpt-4 series model, I will encounter an error: This model is currently overloaded Please use another model or try again soon

But my call frequency is not high, how can I solve it

**Comment by wortega285f** [comment]
Error: HTTP 500 Internal Server Error from https://proxy-server-green-l6vsfbzhba-uw.a.run.app/stream_chat Error in Continue free trial server: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received function message
When I use claude,the error appears

**Comment by sestinj** [comment]
Hi @wortega285f, I'm sorry you're getting this error. We're working through high traffic with our free trial and should have it resolved very soon, at which point we won't apply these rate limits. Until then, you can use a model like Claude Sonnet, gpt-3.5-turbo, or llama3 70b. Alternatively, by entering an API key or using Ollama there won't be any limitation at all ever.

As for the second error I'll have a fix in just a minute—will update soon!
