### ISSUE TITLE
Don't reset or ask if config file `~/.continue/config.json` exist

### ISSUE THREAD

**Issue by dalisoft** [continuedev/continue#1325]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.5
- Continue: v0.8.28
- IDE: VSCode v1.89.1
```

### Description

After folder `~/.continue`, even file exists, **continue** asks for re-configure so it resets my old config and credentials to token

### To reproduce

1. Restore `~/.continue` folder from Time Machine your macOS
2. Install VSCode then install **continue** extension on VSCode
3. It asks for re-configure even it's already has file `~/.continue/config.json`

**Comment by sestinj** [comment]
@dalisoft we now have a "skip" button but also won't overwrite existing models in the onboarding process, so I think this is solved. Thanks for sharing the issue!
