### ISSUE TITLE
Request to support Atlassian Confluence

### ISSUE THREAD

**Issue by edeuser** [continuedev/continue#1329]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Dear,

Is that possible to support Confluence as a new provider? or add to @Doc?

Thanks.

**Comment by sestinj** [comment]
@edeuser this is definitely possible! We already have a "Jira Issues" context provider (docs [here](https://docs.continue.dev/customization/context-providers#jira-issues) and code [here](https://github.com/continuedev/continue/blob/main/core/context/providers/JiraIssuesContextProvider/index.ts) ).

If this was something you were interested in contributing through a PR we'd gladly accept it, or if you wanted to do this through config.ts, you can create a ["Custom Context Provider"](https://docs.continue.dev/customization/context-providers#introductory-example)

**Comment by edeuser** [comment]
Yes, I have used the Jira issues provider and it's so amazing.  I will try to make a PR .

**Comment by garritfra** [comment]
@edeuser I'm slightly confused that you closed the issue 😄 Has this been done, or can we reopen this ticket to track the progress?

**Comment by hongbo-miao** [comment]
(I think we can continue following at https://github.com/continuedev/continue/issues/2745 ☺️)
