### ISSUE TITLE
Remote embedder Codebase doesn't work on jetbrains 

### ISSUE THREAD

**Issue by eladamittai** [continuedev/continue#1332]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:windows 10
- Continue: 0.0.46
- IDE: pycharm 2023.1.1
```

### Description

I configured a remote embedder for the codebase, and I get an error.  The same configuration worked fine on vs code with continue 0.9.130

### To reproduce

Config:
```json
{
embeddingsprovider: {
Provider: openai,
Model: codet5p-110m-embedding,
apiBase: http://my-api-base,
apiKey: my-api-key
},
contextProviders: [
{
name: codebase,
parans: {
nRetrieve: 75,
nFinal: 10,
useReranking: true
}
}
]
}
```

### Log output

```Shell
Error running handler for "context/getContextItems": Error: Warning: No results found for @codebase context provider.
```

**Comment by sestinj** [comment]
@eladamittai we've just released support for codebase context provider in the 0.0.47 EAP version of the JetBrains extension (it wasn't supported before this, though we hadn't done a great job of communicating this). You can download it with the instructions here: https://docs.continue.dev/troubleshooting#jetbrains-1

**Comment by eladamittai** [comment]
@sestinj just checked the new version. It works! Thanks!
