### ISSUE TITLE
Environment Setup for JetBrains is not correct in CONTRIBUTING.md

### ISSUE THREAD

**Issue by edeuser** [continuedev/continue#1335]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

OS: MAC 
IDE: IntelliJ IDEA CE 2024.1.1

Correction:

1. Run scripts/install-dependencies.sh  -> no scripts folder, should be Run install-dependencies.sh
2.  Continue is built with JDK version 19. -> Build in MAC , JDK should be version 17. otherwise will got error.
3. To package the extension, choose the "Build Plugin" Gradle configuration -> didn't find "Build Plugin"

**Comment by sestinj** [comment]
@edeuser Thanks for pointing this all out. Any interest in making a quick PR with these changes? Otherwise I'll gladly add them in!

**Comment by edeuser** [comment]
Thanks, i will make a PR.
