### ISSUE TITLE
[CON-239] Gemini Embeddings Provider

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1346]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Google Gemini offers text embeddings, and we don't yet have (built-in) support!

### Solution

https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding-and-embedding is their documentation.

The implementation of this feature would consist of
1. Copy the [CohereEmbeddingsProvider](https://github.com/continuedev/continue/blob/preview/core/indexing/embeddings/CohereEmbeddingsProvider.ts#L38-L53) into a new adjacent file, and rename GeminiEmbeddingsProvider
2. Alter the fetch request to fit what Google expects
3. Parse the response data to match the format that Continue expects
4. Add the class to the list [here](https://github.com/continuedev/continue/blob/preview/core/indexing/embeddings/index.ts#L8-L17)
5. Update `extensions/vscode/config_schema.json`

<sub>[CON-239](https://linear.app/continue/issue/CON-239/gemini-embeddings-provider)</sub>

**Comment by Patrick-Erichsen** [comment]
@sestinj mind assigning this one to me?

**Comment by sestinj** [comment]
You got it!
