### ISSUE TITLE
Since the 0.8.28 update, custom provider chat no longer works (return 400 Error).

### ISSUE THREAD

**Issue by kit1858644** [continuedev/continue#1350]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: v0.8.29
- IDE: VSCode lastest
OpenAI API
```

### Description

Continue Chat post request is not an OpenAI request format, This caused the request to fail:     

My settings work correctly in continue 0.8.27 version.

- Edit: I found that when using "model": "gpt-4", it works normally, but when using "model": "gpt-4o", an error occurs.

Continue Post Format:
```
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Hello"
        }
      ]
    }
  ],
  "model": "gpt-4o",
  "stream": true
}
```

OpenAI Post Format:
```
{
  "messages": [
    {
      "role": "system",
      "content": "You are ChatGPT..."
    },
    {
      "role": "user",
      "content": "Hello"
    }
  ],
  "stream": true,
  "model": "gpt-4o"
}
```

This is my config.json:
```
{
      "model": "gpt-4o",
      "title": "GPT-4o",
      "apiKey": "sk-ABCEDFG",
      "apiBase": "https://api.xxx.com/v1",
      "provider": "openai"
    }
```

### To reproduce

-

### Log output

```Shell
https://api.XXX.com/v1/chat/completions {"error":{"message":"invalid paramters (request id: xxxxxxxxxxxxx)","type":"invalid_request_error","param":"","code":null}}
```

**Comment by sestinj** [comment]
@kit1858644 just solved this here: https://github.com/continuedev/continue/commit/cc900ed9d801118aff50aa536985790eeeeb2455

It'll be in the next pre-release soon
