### ISSUE TITLE
Azure Open AI not working with inline edit

### ISSUE THREAD

**Issue by majuansari** [continuedev/continue#1351]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MACOSX
- Continue: 0.0.46
- IDE: Jetbrains
```

### Description

With Azure open ai config
{
		  "title": "Azure OpenAI",
		  "provider": "openai",
		  "model": "gpt-4o (v2024-05-13)",
		  "apiBase": "https://xxxx.openai.azure.com",
		  "engine": "gpt-4o",
		  "apiVersion": "2024-02-01",
		  "apiType": "azure",
		  "apiKey": ""
	  },
	  
We are not able to do inline edit.  Getting following error

Error: HTTP 400 Bad Request from https://majuoai-66.openai.azure.com/openai/deployments/gpt-4o/completions?api-version=2024-02-01  {"error":{"code":"OperationNotSupported","message":"The completion operation does not work with the specified model, gpt-4o. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."}}

### To reproduce

Preset command + I and do inline edit 	 . Every time this reproducible with the above config.

### Log output

```Shell
Error: HTTP 400 Bad Request from https://majuoai-66.openai.azure.com/openai/deployments/gpt-4o/completions?api-version=2024-02-01  {"error":{"code":"OperationNotSupported","message":"The completion operation does not work with the specified model, gpt-4o. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."}}
```

**Comment by Tspm1eca** [comment]
Continue format of the request sent is incorrect:
[](https://github.com/continuedev/continue/issues/1350)

**Comment by mpaine-act** [comment]
I get the same error when trying to use Completions playground with the only deployment as gpt-4o -- it is not a selectable deployment.

![image](https://github.com/continuedev/continue/assets/17752788/3b618cc1-24b6-4538-a953-2ae1b4a2b799)

**Comment by majuansari** [comment]
@mpaine-act  if you look at the logs the API URL is https://majuoai-66.openai.azure.com/openai/deployments/gpt-4o/completions?api-version=2024-02-01  which is wrong

Instead of deployments/gpt4o/completions it should be 

deployments/gpt-4o/chat/completion 

chat is missed out in uri for some reason

**Comment by majuansari** [comment]
curl --location --request POST 'https://XX.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-15-preview' \
--header 'Content-Type: application/json' \
--header 'api-key: XXX' \
--data-raw '{
  "messages": [{"role":"system","content":"You are an AI assistant that helps people find information."},{"role":"user","content":"Hi"}],
  "max_tokens": 800,
  "temperature": 0.7,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "top_p": 0.95,
  "stop": null
}'

Just for reference this Curl API also returning value fine.

**Comment by sestinj** [comment]
@majuansari just made a fix [here](https://github.com/continuedev/continue/commit/cc900ed9d801118aff50aa536985790eeeeb2455) that should solve this in the next release

**Comment by aritejhg** [comment]
im not sure if that fixes that?

**Comment by pkandarpa-cs** [comment]
This issue is still prevalent

**Comment by beall49** [comment]
Does anyone have a fix for this?
