### ISSUE TITLE
Duplicate variable declarations in `extensions/vscode/src/activation/activate.ts`

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#1361]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.5
- Continue: 0.9.140
- IDE: VSCode
```

### Description

[extensions/vscode/src/activation/activate.ts](https://github.com/continuedev/continue/blob/main/extensions/vscode/src/activation/activate.ts#L12-L20) declares `resolveVsCodeExtension` and `vscodeExtensionPromise` twice. 

This was introduced in [#1356](https://github.com/continuedev/continue/pull/1356/files#diff-ccb2651e83bb926d28195576f7f96320d33a1fa6364c4a0700c2e9db938034bfR11-R15).

### To reproduce

Run the `install-all-dependencies` task.

### Log output

```Shell
Error: Command failed: npx vsce package --out ./build patch --no-dependencies
✘ [ERROR] The symbol "resolveVsCodeExtension" has already been declared

    src/activation/activate.ts:17:4:
      17 │ let resolveVsCodeExtension = (_: VsCodeExtension): void => {};
         ╵     ~~~~~~~~~~~~~~~~~~~~~~

  The symbol "resolveVsCodeExtension" was originally declared here:

    src/activation/activate.ts:12:4:
      12 │ let resolveVsCodeExtension = (_: VsCodeExtension): void => {};

✘ [ERROR] The symbol "vscodeExtensionPromise" has already been declared

    src/activation/activate.ts:18:13:
      18 │ export const vscodeExtensionPromise: Promise<VsCodeExtension> = ne...
         ╵              ~~~~~~~~~~~~~~~~~~~~~~

  The symbol "vscodeExtensionPromise" was originally declared here:

    src/activation/activate.ts:13:13:
      13 │ export const vscodeExtensionPromise: Promise<VsCodeExtension> = ne...
```

**Comment by sestinj** [comment]
@Patrick-Erichsen this is solved in the `preview` branch, and I'll push to main later today

**Comment by spew** [comment]
Duplicate issue here: https://github.com/continuedev/continue/issues/1378
