### ISSUE TITLE
Saving config does not update core ConfigHandler

### ISSUE THREAD

**Issue by justinmilner1** [continuedev/continue#1369]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:mac
- Continue: Preview branch
- IDE: vscode
```

### Description

Saving config does not fully update both ConfigHandlers - only the one defined in extensions is updated. 

I'm curious why a singleton design pattern wasn't used. Looks like a difficult refactor now. I'm looking into other methods of fixing this.

### To reproduce

Example:
- Provide valid indexing config, see that it succeeds
- Provide an invalid indexing config, save it, see that indexing still succeeds

### Log output

```Shell
-
```

**Comment by sestinj** [comment]
@justinmilner1 The `Core` should in fact be a singleton, and should be the only owner of a `ConfigHandler`. I just made a small refactor to remove the extra configHandler in VS Code, but the second part of this issue still needs to be tacked, i.e. actually correctly refreshing when the config is saved

**Comment by justinmilner1** [comment]
@sestinj Ah okay that makes more sense - I see the change in preview.

**Comment by sestinj** [comment]
this is now refactored and solved
