### ISSUE TITLE
Autocomplete fails with openai gpt-4o model

### ISSUE THREAD

**Issue by goodosoft** [continuedev/continue#1371]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos 14.5
- Continue: v0.8.31
- IDE: vscode 1.891
```

### Description

can not use Autocomplete function, always have this error:

```
{"message":"OpenAlException - Error code: 400 - {'error':
{'message': \'Invalid 'stop': array too long. Expected an
array with maximum length 4, but got an array with length
14 instead.\', 'type': 'invalid_request_error', 'param': 'stop'
'code': 'array_above_max_length'}}}|nNumber Retries =
1","type":null,"param":null,"code":400}}
```

### To reproduce

enable autocomplete

### Log output

```Shell
{"message":"OpenAlException - Error code: 400 - {'error':
{'message': \'Invalid 'stop': array too long. Expected an
array with maximum length 4, but got an array with length
14 instead.\', 'type': 'invalid_request_error', 'param': 'stop'
'code': 'array_above_max_length'}}}|nNumber Retries =
1","type":null,"param":null,"code":400}}
```

**Comment by sestinj** [comment]
@goodosoft is there any chance you are accessing gpt-4o through a proxy server? We have code to truncate the stop words for api.openai.com, but using a different host could break this. Let me know, it should be a quick fix!

Also I understand it's very possible you are just experimenting with different models, but I wanted to share this just in case: https://docs.continue.dev/walkthroughs/tab-autocomplete#i-want-better-completions-should-i-use-gpt-4

As unintuitive as it is, you will likely get better, faster, _and_ cheaper results by using a model like deepseek-coder-6.7b, starcoder 7b, or others

**Comment by oliverseal** [comment]
Getting this, too. I use a proxy server depending on environment. I use local ollama usually, but with some more complex files, I have had gpt-4o (non-proxied) give more nuanced completions.

**Comment by tandav** [comment]
The issue is still exist for me. I use following config for autocomplete:

```json
  "tabAutocompleteModel": {
    "model": "gpt-3.5-turbo",
    "title": "GPT-3.5-Turbo",
    "provider": "openai",
    "apiBase": "https://openai-proxy.example.com/v1",
    "apiKey": "sk-xxxx"
  },
```

**Comment by Heap0017** [comment]
@goodosoft @oliverseal @tandav I worked around this issue by letting Litellm modify the request dropping excess stop words.

https://litellm.vercel.app/docs/proxy/call_hooks

```
from litellm.integrations.custom_logger import CustomLogger
from litellm.proxy.proxy_server import UserAPIKeyAuth, DualCache
from typing import Literal

class MyCustomHandler(CustomLogger):
    async def async_pre_call_hook(self, user_api_key_dict: UserAPIKeyAuth, cache: DualCache, data: dict, call_type: Literal[
            "completion",
            "text_completion",
            "embeddings",
            "image_generation",
            "moderation",
            "audio_transcription",
        ]):
        if data.get('stop'):
            data['stop'] = data['stop'][:4]
        return data

proxy_handler_instance = MyCustomHandler()
```

**Comment by AlexZhangji** [comment]
> @goodosoft is there any chance you are accessing gpt-4o through a proxy server? We have code to truncate the stop words for api.openai.com, but using a different host could break this. Let me know, it should be a quick fix!
> 
> Also I understand it's very possible you are just experimenting with different models, but I wanted to share this just in case: https://docs.continue.dev/walkthroughs/tab-autocomplete#i-want-better-completions-should-i-use-gpt-4
> 
> As unintuitive as it is, you will likely get better, faster, _and_ cheaper results by using a model like deepseek-coder-6.7b, starcoder 7b, or others

hi @sestinj , also seeing this issue while using a proxy gpt-4, think it is exactly you think: more than 4 stop words provided.

**Comment by sestinj** [comment]
For those facing this problem still, we now have a `"maxStopWords"` property in the model object that can be set in config.json

**Comment by tandav** [comment]
> For those facing this problem still, we now have a `"maxStopWords"` property in the model object that can be set in config.json

Seems like this property only added to `models`, but not to `tabAutocompleteModel`. I added `"maxStopWords": 20` to both and issue still there:

```json
{
  "models": [
    {
      "model": "AUTODETECT",
      "title": "OpenAI",
      "apiKey": "sk-xxxxxxxxxxxxxx",
      "maxStopWords": 20,
      "provider": "openai"
    }
  ],
  "tabAutocompleteModel": {
    "model": "gpt-4o-mini",
    "title": "gpt-4o-mini",
    "provider": "openai",
    "maxStopWords": 20,
    "apiBase": "https://openai-proxy.example.com/v1",
    "apiKey": "sk-xxxxxxxxxxxxxx"
  },
  "allowAnonymousTelemetry": true,
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  },
  "docs": []
}


HTTP 400 Bad Request from https://openai-proxy.example.com/v1/chat/completions { "error": { "message": "Invalid 'stop': array too long. Expected an array with maximum length 4, but got an array with length 9 instead.", "type": "invalid_request_error", "param": "stop", "code": "array_above_max_length" } }
```
