### ISSUE TITLE
tag v0.8.31-vscode cannot be built as activate.ts has a duplicate definitions for resolveVsCodeExtension

### ISSUE THREAD

**Issue by spew** [continuedev/continue#1378]
### Description

The file `extensions/vscode/src/activation/activate.ts` has two definitions for `resolveVsCodeExtension`.

I noticed this when trying to build from the tag `v0.8.31-vscode` for the latest vscode release. Are the official builds coming from another source (maybe the preview branch?) or not matching the tags?

### Log output

```
Error: Build failed with 3 errors:
src/activation/activate.ts:17:4: ERROR: The symbol "resolveVsCodeExtension" has already been declared
src/activation/activate.ts:18:13: ERROR: Multiple exports with the same name "vscodeExtensionPromise"
src/activation/activate.ts:18:13: ERROR: The symbol "vscodeExtensionPromise" has already been declared
```

**Comment by spew** [comment]
Same issue will occur with tag `v0.8.32-vscode`: https://github.com/continuedev/continue/blob/v0.8.32-vscode/extensions/vscode/src/activation/activate.ts

**Comment by spew** [comment]
I see that the code was removed from the preview branch, which makes me think the latest release was built from preview and not from tag?

**Comment by sestinj** [comment]
@spew Just realizing I missed your last message but the reason for this was that we had some client code that was a bit sensitive in protecting our free trial, and so we deployed separately. This is now no longer the case and we are deploying directly from the open source repository, as you can verify in the GitHub Actions

As for the original issue here, I believe it has been solved a ways back, so will close the issue
