### ISSUE TITLE
Unable to reference other files

### ISSUE THREAD

**Issue by userandpass** [continuedev/continue#1383]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Windows:
- Continue:v0.0.45
- pycharm
model: deepseek + vllm
```

### Description

The prompt printed in the log contains only context information and no other file code

"tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "openai",
    "model": "deepseek",
    "apiBase": "http://127.0.0.1:8000/code/v1"
  },
  "tabAutocompleteOptions": {
    "useCopyBuffer": false,
    "maxPromptTokens": 1024,
    "prefixPercentage": 0.4,
    "maxSuffixPercentage": 0.5,
    "useOtherFiles": true,
    "slidingWindowPrefixPercentage": 0.5,
    "slidingWindowSize": 300,
    "maxSnippetPercentage": 0.6,
    "recentlyEditedSimilarityThreshold": 0
  },

**Comment by sestinj** [comment]
Updates coming soon here! We had been using the Language Server Protocol, which is only available in VS Code, very heavily, but are just about to ship updates to JetBrains that use other methods to grab relevant files

**Comment by sestinj** [comment]
I'm going to close this issue now that we've done a lot of work with "Root path context" and recently edited ranges: https://blog.continue.dev/root-path-context-the-secret-ingredient-in-continues-autocomplete-prompt/

In the future we'd still love feedback in newer issues about how it can be improved, but I don't want to have the conversation stuck in an older issue
