### ISSUE TITLE
Additional fields for dev_data/autocomplete.jsonl

### ISSUE THREAD

**Issue by spew** [continuedev/continue#1390]
I think the following fields would be useful in autocomplete.jsonl:

- The 'origin' remote if the project is a git repo (i.e. `git@github.com:continuedev/continue.git`)
  - Can be used to filter out sensitive repos
  - Can be used to create fine tuned models specific to groups that have access to a given repo
  - Looks like this takes ~1ms to fetch in `completionProvider.ts` via `await ide.getRepoName(input.filepath)`, there may be something better that can be done where either the dir name -> repo name is cached OR the repo name is fetched later in an async routine that does not affect the completion latency.
- The internally generated completion id, example: [completionProvider.ts](https://github.com/continuedev/continue/blob/0746bbc5ee149ed543c73c0f9aebef1fe62c5684/core/autocomplete/completionProvider.ts#L475C7-L475C57)
  - Can be used to dedup entries, oftentimes when uploading to a data lake due to failure scenarios we can end up with duplicate entries
- The value of `os.username()`
  - Can be used to get information about how many unique users are in my organization, how they are using continue, etc.

**Comment by sestinj** [comment]
@spew Just made the change here: https://github.com/continuedev/continue/commit/6760a3060f198a1bfdbcab5509ae041ab46c1ac5 and here: https://github.com/continuedev/continue/commit/335ee7f310be04aca1015e22c9b46c666a426f4f

I chose to go with the unique machine id generate by VS Code because this is anonymized

**Comment by spew** [comment]
This looks great! Agree that vscode unique ID is better.

**Comment by sestinj** [comment]
I originally left this open because we hadn't addressed the final bullet point, but I want not to do this, for privacy preservation reasons. So closing now, but as usual, if you want more comprehensive dev data, just let us know!
