### ISSUE TITLE
Functionality to exclude TabAutoComplete on certain extensions

### ISSUE THREAD

**Issue by caffeine-coder1** [continuedev/continue#1394]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I have several configuration files where I prefer to disable the tab auto-completion feature. It complicates my workflow as it's not related to coding. It generates random content using the default model `starcoder2:3b`. I would like to turn off tab auto-completion either through a shortcut or by specifying exclusions for certain file extensions in a configuration file.

I am uncertain if this is achievable with the current settings file. My apologies if this question appears trivial.

### Solution

provide the functionality to disable autoTabComplete by using a short cut or by a config file which excludes it from auto completing for certain file extensions.

**Comment by sestinj** [comment]
@caffeine-coder1 looks like I just hadn't updated the docs after adding this but we do have the option: https://github.com/continuedev/continue/blob/main/core/index.d.ts#L730

You can set tabAutocompleteOptions.disableInFiles to a list of glob patterns and it should ignore those

**Comment by sestinj** [comment]
Docs have been updated, so I'm going to close this issue. Let me know if I shouldn't have done so!
