### ISSUE TITLE
[CON-243] systemMessage not effective for claude 3

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1399]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue:*
- IDE:*
```

### Description

It seems we're not sending the system message to Claude 3. Need to double check that this is actually the case and if so make the quick fix

<sub>[CON-243](https://linear.app/continue/issue/CON-243/systemmessage-not-effective-for-claude-3)</sub>

**Comment by lighclube** [comment]
When will this bug be fixed? systemMessage is very important to me

**Comment by sestinj** [comment]
This is now resolved!
