### ISSUE TITLE
Sample configs for diff deployments scenarios

### ISSUE THREAD

**Issue by aiseei** [continuedev/continue#1405]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi - Thanks for the awesome product!
Given the variety of config options , it would be  really helpful if we have sample configs 1) with proxy 2) multi-provider for Ollama , Llama.ccp etc by model. 3) Embedding providers , others that u think would help get the best out of this.

Thanks!

**Comment by sestinj** [comment]
@aiseei this is a great idea! I created 2 initial examples here. If you have other ideas, let me know and I'll gladly add those as well (or am welcoming of PRs) https://docs.continue.dev/setup/examples
