### ISSUE TITLE
Keep configurations after update and stop recouring on boarding

### ISSUE THREAD

**Issue by lufixSch** [continuedev/continue#1413]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I have a Laptop, which I don't use that often (once/twice a week) and nearly every time I open vscode continue prompts me for an on boarding process, wants me to log in somewhere and doesn't stop until I click through it. To make matters worse this often leads to a reset of my configuration. When that happens it also often leads to automatic indexing using the default proprietary model and reactivation of tab completion with the default configuration.

The reason, I use continue with local models is, because I don't want to send my data to some third party but every time this reset happens It happens. In my case I don't have any immediate consequences but I could imagine, someone working at a company which forbids the usage of ChatGPT or similar could get serious problems. 

### Solution

I understand that this tool is in early development and things change often but I would appreciate a setting/flag which disables the on boarding and a warning when the config hast to be overwritten because of breaking changes. And please check why tab completion is reactivated after some updates.

Additionally it would be nice if you could keep my old config as an archived version somewhere, so I don't have to write everything from scratch every time.

Thanks for you work :)

**Comment by lufixSch** [comment]
I found that #1295 addresses similar issues. It is possible, that at least the reset of the tab completion setting is related to that.

**Comment by lufixSch** [comment]
Another minor, unrelated question: For some time continue asks for access to my GitHub login. Why is that needed? I couldn't find anything in the documentation.

**Comment by sestinj** [comment]
@lufixSch thanks for bringing this up, and I'm sorry it caused you pain. I do believe that the issue you mentioned is likely related, and we're taking extra precautions to make sure that it doesn't happen again.

The onboarding process should also no longer happen on every reload and when it does for new users, in the latest versions, we've taken care to make sure that it doesn't actually overwrite existing models.

A better explanation of why we are asking for sign-in is also included in the latest update, but to explain here as well: we tried as hard as possible to support a free trial without forcing sign-in, but at the end of the day there are too many people interested in abusing the server, who may not even be Continue users. We had to require sign in to prevent this, but we are _only_ requiring sign-in for users who are using free trial models. If you remove all "provider": "free-trial" models from your config.json, we will never request this: https://docs.continue.dev/reference/Model%20Providers/freetrial#sign-in

**Comment by lufixSch** [comment]
> A better explanation of why we are asking for sign-in is also included in the latest update, but to explain here as well: we tried as hard as possible to support a free trial without forcing sign-in, but at the end of the day there are too many people interested in abusing the server, who may not even be Continue users. We had to require sign in to prevent this, but we are only requiring sign-in for users who are using free trial models. If you remove all "provider": "free-trial" models from your config.json, we will never request this: https://docs.continue.dev/reference/Model%20Providers/freetrial#sign-in

Thanks for the explanation. That totaly makes sense. I just noticed the popup and was curious why this was needed. I already observed that I can just ignore the popup but its nice to know, that I can get rid of it completely.

**Comment by sestinj** [comment]
glad to hear. I'll close the issue in a day or two if this seems resolved, since we've made a lot of improvements to the explanation since originally shipping this

but if there's anything small that could be made clearer, please lmk!
