### ISSUE TITLE
too many errors showd in devtools

### ISSUE THREAD

**Issue by xingpingcn** [continuedev/continue#1414]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: win10 ltsc 2021
- Continue: v0.8.38
- IDE: vscode
```

### Description

![image](https://github.com/continuedev/continue/assets/117259690/92e95051-695f-4132-b010-1f1228bd20ab)

### To reproduce

i do nothing but it shows

**Comment by sestinj** [comment]
@xingpingcn thanks for sharing this. These requests are from PostHog, which we use for anonymous telemetry (https://docs.continue.dev/telemetry). You can turn off telemetry with allowAnonymousTelemetry: false in config.json if you expect to be working in an environment without internet (https://docs.continue.dev/walkthroughs/running-continue-without-internet)

**Comment by sestinj** [comment]
I think that this is just a networking problem and since it is resolvable by disabling telemetry I'm going to close the issue—please let me know if there are still any problems!
