### ISSUE TITLE
[CON-244] Ability to change session title in history page

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1426]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently there is no way to change the title of a session

### Solution

On the history page, we should add a pencil icon next to the trash can icon that lets you type a new name for the session. Once you're done typing, it should save this change

[https://github.com/continuedev/continue/blob/preview/gui/src/pages/history.tsx#L129-L142](https://github.com/continuedev/continue/blob/preview/gui/src/pages/history.tsx#L129-L142) is where the pencil icon could go, using the same HeroIcons icon set as the TrashIcon

See commit [here](https://github.com/continuedev/continue/commit/04b8ada4d5da5af92f7aa99b5adab26c886f7ae8) for the getSession and updateSession functions that will be needed to save the new title

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-244](https://linear.app/continue/issue/CON-244/ability-to-change-session-title-in-history-page)</sub>

**Comment by priyashpatil** [comment]
Tasks:
1. add pencil icon alongside delete button
2. turn it into text box
3. save the title.
