### ISSUE TITLE
Folder context provider do not showing options to choose in Jetbrains IDE 2024

### ISSUE THREAD

**Issue by krystaLove** [continuedev/continue#1432]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.49
- IDE: PHPStorm 2024.1.1
```

### Description

Folder context provider doesn't retrieving folders of the project for menu items to choose from

![image](https://github.com/continuedev/continue/assets/21146483/93cfdad3-1625-493d-8721-89be251d6c28)

When i hit @folder to choose it's showing there is no results
![image](https://github.com/continuedev/continue/assets/21146483/0d9cb5fa-6002-40d3-aaa9-3dcfe33cb57e)

### Log output

```Shell
.continue/core.log shows nothing related to folder context provider

I think something in 2024 Jetbrains IDE might be changed, so this logic not working anymore

https://github.com/continuedev/continue/blob/aa18568c6096f8f2df7075ff0f1f711f6f75ed01/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt#L565
```

**Comment by sestinj** [comment]
Definitely that is the code causing the problem. I'll double check that this isn't just happening on all JetBrains versions and try to include the necessary fix in the next release. We just made one today, so I expect it will probably be next Monday

**Comment by sestinj** [comment]
Should now be solved in the latest JetBrains releases
