### ISSUE TITLE
Nonstop toasts from plugin when ollama not running

### ISSUE THREAD

**Issue by mhgrove** [continuedev/continue#1437]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 23
- Continue: 1.2
- IDE: VSC, 1.90
```

### Description

wanted to try the plugin, ollama was not running, and I can't make the toasts stop without uninstalling your plugin. 

[Screencast from 2024-06-06 12-55-37.webm](https://github.com/continuedev/continue/assets/178622/937a9dd6-24f1-4d94-87fa-5ec0fdefdff2)

### To reproduce

1. do not start ollama
2. start vsc
3. install Continue from marketplace
4. Click to use a local model
5. Enjoy toasts

**Comment by sestinj** [comment]
@mhgrove Sorry for the distraction! While I get this fixed, which I will do ASAP, you can stop the toasts by disabling autocomplete. This can be done by clicking the "Continue" button in the bottom right of VS Code

**Comment by sestinj** [comment]
@mhgrove I might actually need a bit more information to solve this. The 404 seems to mean that Ollama might already be running, but that the /generate endpoint doesn't exist. Would you be able to share the following, and I'll start testing on my computer right away?
1. Version of Ollama, and double checking whether it is running or not when you get these toasts (if you get a 404, then I think that Ollama must be running)
2. Your full config.json (any API keys or other secrets of course left out)

**Comment by sestinj** [comment]
@mhgrove got it thank you! And are you still seeing the same thing, or something slightly different after upgrading Ollama?

Also very important: I figure this might have been a typo, but you listed "1.2" as your version of Continue. Currently our latest are either 0.8.x or 0.9.x and it would be hugely helpful to know which version you are on

**Comment by mhgrove** [comment]
i hadn't tried until after the ollama upgrade. i'm on the 0.8.x line.

**Comment by sestinj** [comment]
This seems to be resolved, so closing the issue
