### ISSUE TITLE
[CON-245] Add docs through config.json

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1442]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Can't currently specify docs sites to index through config.json

### Solution

Ideally, users can write this in their config.json:

```json
"contextProviders": [{
  "name": "docs",
  "params": { "sites": [
    {
      "title": "Jinja",
      "startUrl": "https://jinja.palletsprojects.com/en/3.1.x/",
      "rootUrl": "https://jinja.palletsprojects.com/en/3.1.x/",
    },
    {
      "title": "React",
      "startUrl": "https://react.dev/reference/",
      "rootUrl": "https://react.dev/reference/",
    }
  ]}
}]
```

<sub>[CON-245](https://linear.app/continue/issue/CON-245/add-docs-through-configjson)</sub>

**Comment by priyashpatil** [comment]
Reference Links:

- https://github.com/continuedev/continue/blob/preview/core/context/providers/DocsContextProvider.ts
- https://github.com/continuedev/continue/blob/preview/core/indexing/docs/preIndexedDocs.ts
- https://github.com/continuedev/continue/blob/preview/core/indexing/docs/db.ts
- https://github.com/continuedev/continue/blob/preview/core/indexing/docs/index.ts

**Comment by glebtumen** [comment]
I believe now you can add custom docs. Tested it on aiogram lib, asking on how to write a middleware
![image](https://github.com/continuedev/continue/assets/82389655/dfa63994-e16e-44ca-812f-6e0d817ac645)
![image](https://github.com/continuedev/continue/assets/82389655/b9e89f8d-5864-4ce9-a787-cb022b5eaa60)
also it gave me example code at the end
