### ISSUE TITLE
./scripts/install-dependencies fails on new repo

### ISSUE THREAD

**Issue by spew** [continuedev/continue#1443]
### Description

The script `./scripts/install-dependencies` will fail in a new repo. It fails in the `npm run build` step of the binary directory  as the folder `build` does not exist.

This can be worked around by creating the build directory manually.

### To reproduce

Delete the build folder in `./binary` and run `./scripts/install-dependencies.sh`

**Comment by fry69** [comment]
This should be fixed in the preview branch.
