### ISSUE TITLE
Comments in config.json

### ISSUE THREAD

**Issue by Cianidos** [continuedev/continue#1452]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

It's not possible to make comments in config.json due to plain json format.

![image](https://github.com/continuedev/continue/assets/44319627/1773a80f-8286-4545-a4a7-d649d4e6064c)
![image](https://github.com/continuedev/continue/assets/44319627/1bb9f2b9-e0c2-481f-8b70-e516fef66a2b)

### Solution

Use JSON with comments format for config, or maybe somehow tune JSON Schema file of config.
Some thoughts are in discord thread https://discord.com/channels/1108621136150929458/1249077598152294430

**Comment by Trapper4888** [comment]
![image](https://github.com/continuedev/continue/assets/133875445/634188fd-271b-4593-867d-f29406e120b9)

As a workaround, you can just add dotted prefixes to your JSON fields. I have a few configs for tabAutocompleteModel, I name them with the dotted prefix (here "codestral.ollama"), and I paste the one I want in the real tabAutocompleteModel.

To "comment" a value, add a dotted prefix (here "false"), and it won't be recognized, so not used, so same result as commented.

**Comment by sestinj** [comment]
@Trapper4888 @Cianidos this is now supported in the latest pre-release!
