### ISSUE TITLE
Conflicting configs in `core/.eslintrc.json` causing the `import/extensions` linting rule to error

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#1455]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.5
- Continue: v0.9.151
- IDE: VSCode
```

### Description

`core/.eslintrc.json` contains two configuration options that are in conflict: `require-extensions` and `import/extensions`.

The third-party `require-extensions` package forces relative imports to have a `.js` extension, but we have configured the out-of-the-box `import/extensions` rule to `never` allow `.js` extensions. 

### Problem
This is causing all relative imports with a `.js` extension in the `core` directory to throw the following linting error:

> Unexpected use of file extension "js" for {FILEPATH}

### Example

Here is a screenshot of `core/indexing/indexCodebase.ts` in VSCode.

<img width="944" alt="Screenshot 2024-06-09 at 4 23 20 PM" src="https://github.com/continuedev/continue/assets/20157849/a82e6110-ac30-41b7-b985-fd2558c6af1e">

### `require-extensions` config

From the [docs](https://github.com/solana-labs/eslint-plugin-require-extensions?tab=readme-ov-file#eslint-plugin-require-extensions): 

> This is a simple eslint plugin that ensures that relative imports and exports have .js extensions.

[Our config](https://github.com/continuedev/continue/blob/main/core/.eslintrc.json#L8-L9):
```json 
"extends": ["plugin:require-extensions/recommended"],
"plugins": ["@typescript-eslint", "import", "require-extensions"],
```

### `import/extensions` config

From the [docs](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md):

> In order to provide a consistent use of file extensions across your code base, this rule can enforce or disallow the use of certain file extensions.

[Our config](https://github.com/continuedev/continue/blob/main/core/.eslintrc.json#L12-L21):
```json
"import/extensions": [
      "error",
      "always",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
    ],
```

So, what we are doing here is configuring the rule to:
- `error` on invalid values
- `always` require file extensions
- `never` allow file extensions for the list of file types we've specified

This is in conflict with what the `require-extensions` plugin is used for.

## Proposed solution

We uninstall the third-party `require-extensions` plugin, and just configure `import/extensions` to always require file extensions, except for package imports.

Here is what that config would look like:

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "import"],
  "rules": {
    "quotes": ["warn", "double", {}],
    "import/extensions": ["error", "ignorePackages"],
    "@typescript-eslint/naming-convention": "warn",
    "@typescript-eslint/semi": "warn",
    "curly": "warn",
    "eqeqeq": "warn",
    "no-throw-literal": "warn",
    "semi": "off"
  },
  "ignorePatterns": ["out", "dist", "**/*.d.ts"]
}

```

### To reproduce

1. `cd` into the `core` directory
2. Run the following command to output the number of linting errors from the `import/extensions` rule, taking note of how many errors there are:
```bash
npm run lint | grep -c "import/extensions"
```
3. Open `core/.eslintrc.json`
4. Copy & paste proposed config into `core/.eslintrc.json`. Note that this will not resolve all of the errors with `import/extensions` because we still have some imports that are not not using a `.js` extension ([here is an example](https://github.com/continuedev/continue/blob/main/core/protocol/passThrough.ts#L1-L4)).
```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "import"],
  "rules": {
    "quotes": ["warn", "double", {}],
    "import/extensions": ["error", "ignorePackages"],
    "@typescript-eslint/naming-convention": "warn",
    "@typescript-eslint/semi": "warn",
    "curly": "warn",
    "eqeqeq": "warn",
    "no-throw-literal": "warn",
    "semi": "off"
  },
  "ignorePatterns": ["out", "dist", "**/*.d.ts"]
}
```

5. Rerun our script and verify that there are less linting errors from `import/extensions` than on the original run:
```bash
npm run lint | grep -c "import/extensions"
```

To be more confident in our fix, we can run it against a specific file such as `core/indexing/indexCodebase.ts` that was breaking the `import/extensions` rule previously:
```bash
npx eslint ./indexing/indexCodebase.ts
```

**Comment by sestinj** [comment]
@Patrick-Erichsen good catch! I think what actually happened here was a misconfiguration of the import/extensions plugin. Your solution looks like a perfect path forward. Happy to accept a PR with the change!
