### ISSUE TITLE
[CON-246] fix syntax highlighting for strings in sidebar code blocks in dark mode

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1458]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue:*
- IDE: VS Code
```

### Description

![image](https://github.com/continuedev/continue/assets/33237525/3b0a298d-2ec8-4314-816e-7e25da898469)

In many dark themes (e.g. One Dark Pro), Continue uses a color for strings in the side bar that is very close to the background color. We need to select a better color [here](https://github.com/continuedev/continue/blob/preview/gui/src/hooks/useVscTheme.ts#L5-L55)

<sub>[CON-246](https://linear.app/continue/issue/CON-246/fix-syntax-highlighting-for-strings-in-sidebar-code-blocks-in-dark)</sub>

**Comment by Patrick-Erichsen** [comment]
@menjilx I got started on this today but I was unable to reproduce the issue with `Dainty - One Dark Pro`. Could you specify the theme you're using?

**Comment by dreambit** [comment]
Same issue, theme: Learn with Sumit - Vintage

**Comment by dreambit** [comment]
<img width="255" alt="image" src="https://github.com/continuedev/continue/assets/1479661/4407fb0b-e2d4-4420-a735-f20c95d9eac3">

**Comment by dreambit** [comment]
Guys any updates? tried many dark themes, same issue

**Comment by 0xBigBoss** [comment]
<img width="995" alt="Screenshot 2024-11-20 at 18 10 20" src="https://github.com/user-attachments/assets/16809980-f1f9-4b60-a1d0-aaf2f5006fe2">

just want to confirm this is impacting me as well. I'm using the default Monokai theme. `@id:vscode.theme-monokai`
