### ISSUE TITLE
fail to use deepseek api

### ISSUE THREAD

**Issue by BlackPool888** [continuedev/continue#1459]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:macos 10.15.7
- Continue:0.0.50
- IDE:WebStorm
- Model: Deepseek API
```

### Description

![image](https://github.com/continuedev/continue/assets/109952090/a4ba42ce-ecc1-43a0-9d72-f81961b124dd)

This is my configuration
"models": [
    {
      "title": "deepseek api",
      "provider": "openai",
      "model": "deepseek-coder",
      "apiBase": "https://api.deepseek.com/chat",
      "apiType": "openai",
      "apiKey": "",
      "useLegacyCompletionsEndpoint": true,
      "contextLength": 32768,
      "systemMessage": ""
    }
  ]

**Comment by mcthesw** [comment]
```json
{
      "model": "deepseek-chat",
      "title": "Deepseek Chat",
      "apiBase": "https://api.deepseek.com/v1",
      "apiKey": "",
      "completionOptions": {
        "temperature": 0
      },
      "provider": "openai",
      "useLegacyCompletionsEndpoint": false
}
```
try this

**Comment by BlackPool888** [comment]
过了,谢谢

**Comment by amtoaer** [comment]
Hi, did you figure out how to let deepseek work for auto complete and embedding?
I use the configuration below for chat:
```json
	"models": [
		{
			"apiBase": "https://api.deepseek.com/v1",
			"apiKey": "<my api key>",
			"completionOptions": {
				"temperature": 0
			},
			"contextLength": 160000,
			"model": "deepseek-coder",
			"provider": "openai",
			"title": "deepseek-coder",
			"useLegacyCompletionsEndpoint": false
		}
	],
```
Everything works fine. 

However, if I use the same configuration for auto complete:
```json
	"tabAutocompleteModel": {
		"apiBase": "https://api.deepseek.com/v1",
		"apiKey": "<my api key>",
		"completionOptions": {
			"temperature": 0
		},
		"contextLength": 160000,
		"model": "deepseek-coder",
		"provider": "openai",
		"title": "Tab Autocomplete",
		"useLegacyCompletionsEndpoint": false
	}
```
I got this error:
<img width="456" alt="image" src="https://github.com/continuedev/continue/assets/32017007/86af6ad5-be42-4a56-b153-d0456c1848ba">

And for embedding:
```json
	"embeddingsProvider": {
		"apiBase": "https://api.deepseek.com/v1",
		"apiKey": "<my api key>",
		"model": "deepseek-coder",
		"provider": "openai"
	},
```
I got this:
<img width="349" alt="image" src="https://github.com/continuedev/continue/assets/32017007/2be7a6b1-cc73-416a-a5ab-6db9ac2c5883">

**Comment by mcthesw** [comment]
Embedding config like this works for me
```json
"embeddingsProvider": {
    "provider": "transformers.js"
  }
```

For auto-completion, I utilize the local model `CodeQwen7B` or `Nxcode7B`, which suffices for my needs. However, I'm also unable to set up Deepseek for this purpose.
```json
  "tabAutocompleteModel": {
    "title": "Nxcode",
    "apiBase": "http://localhost:11434/v1",
    "provider": "lmstudio",
    "model": "bartowski/Nxcode-CQ-7B-orpo-GGUF"
  }
```

**Comment by amtoaer** [comment]
Got it, thanks for your reply! :)
