### ISSUE TITLE
"Open Files" string from context provider is carried over to prompt

### ISSUE THREAD

**Issue by kozuch** [continuedev/continue#1461]
### Relevant environment info

```Markdown
- OS: Win11
- Continue: v0.8.40
- IDE: VS Code (probably also IDEA - but not confirmed)
```

### Description

When using the @file to do "@Open Files" - the file contents are included in as context (this is OK), but the "Open Files" string is also carried over to the prompt itself, which I guess should not happen, because it is confusing the model (tested with Phi3 mini - the model mentioned there was a note about "Open files" but it could not find any info about it etc.).

Including the relevant part of the VS Code "output" where the prompt in the plugin looked like this:
```
@Open Files What do these files do?
```
@Open Files - context provider
What do these files do? - text that I wrote

I think the same problem is in IDEA (v0.50) - the model mentioned also "Open files" in response, but I could not debug the prompt since no debugging works for IDEA plugin.

### To reproduce

1. write @
2. menu will pop-up
3. select "Open files"
4. @Open Files will show up in prompt
5. Write your question to prompt
6. Enter
7. Model sometimes confused about string "Open files" within the prompt
8. Watch log

### Log output (VS Code - output pane - prompt debugging)

```Shell
...
  </component>
</module>


Open Files What do these files do?

==========================================================================
==========================================================================
Completion:

 The provided Java code snippet and accompanying files are part of ...
```

**Comment by sestinj** [comment]
@kozuch just went through and stopped the rendering of titles for certain context providers where I don't think it makes sense:  https://github.com/continuedev/continue/commit/6cf4467000d7346f083151c9ee95172f9f1c0c8b

this will be in the next release
