### ISSUE TITLE
Support multiple profile/configs when using with multiple gits /remote hosts

### ISSUE THREAD

**Issue by aiseei** [continuedev/continue#1481]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

It would be be great to separate if needed diff configs files for diff dev envs. / gits - such DEV, TESTING or codebases. 

### Solution

If we can create/point  in essence diff ~/.continue folders when setting up - that wld be super useful!

**Comment by sestinj** [comment]
@aiseei This is a cool idea. We currently have the concept of a `.continuerc.json`, which gets applied on top of your global config.json, and has the exact same syntax. How much do you think this would solve your needs if at all?

**Comment by aiseei** [comment]
@sestinj  Thanks. so a .continuerc.json per workspace? That might be workable - will give it a try.  Also came across this https://github.com/continuedev/continue/issues/792 maybe partially related to mine ?

**Comment by sestinj** [comment]
It does look somewhat related, though for the serializability reason we want to avoid that strategy.

It's unfortunate because it would be quite familiar to use module.exports, but in the end most configuration will happen from the UI for most users

**Comment by sestinj** [comment]
@aiseei I'm going to close this issue because it seems largely resolved with .continuerc.json, but please let me know if your experience is otherwise
