### ISSUE TITLE
Changing 'apiBase' for AWS Bedrock

### ISSUE THREAD

**Issue by adreamer** [continuedev/continue#1482]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I need to use AWS Bedrock with a VPC endpoint, which has a URL format like "https://vpce-12341234...bedrock-runtime.{region}.vpce.amazonaws.com".

It appears that currently only the "region" setting is supported, and the "apiBase" option cannot be modified.

Could you consider enabling the "apiBase" option for AWS Bedrock?

### Solution

Supporting "apiBase" option for AWS Bedrock configuration.

**Comment by sestinj** [comment]
@adreamer definitely, just made the update here: https://github.com/continuedev/continue/commit/6c63aeb5dc0b4eede7508cb448545d90757ee21c

You can now use the `apiBase` field and this will take priority

**Comment by adreamer** [comment]
Thank you for the support.
