### ISSUE TITLE
Non-ASCII response from Gemini is partially broken in VScode extension

### ISSUE THREAD

**Issue by reosablo** [continuedev/continue#1492]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 23H2
- Continue: v0.8.40
- IDE: VSCode 1.91.0-insider
- Model: gemini-1.5-pro-latest
```

### Description

# A description of the bug

I'm encountering an issue where responses from Gemini with non-ASCII characters are garbled. This doesn't seem to happen with responses from Groq.

# What you expected to happen

Non-ASCII character responses should be displayed correctly, without any garbled characters or replacement characters (like "�").

# What actually happened

Currently, non-ASCII characters are being replaced with the replacement character "�". This happens consistently.

For example, the following response is affected:

> zh-cn.ts���ァイルの一部ですね。 これは中国語の簡体字で������れ��コードで、音声操作に関するUIのテキストのようです。
> 
> 日本語のメッセージにする場合、どのような文脈で表示されるかを考慮する必要があります。 例えば、以下のように状況を想定して、より自然で適切な日本語���を検討できます。

# Screenshots or videos

![screenshot](https://github.com/continuedev/continue/assets/1438351/90d668bd-e410-46a8-9479-8f298887efe4)

# Possible solutions

I suspect this is because the buffer is being treated as a string, rather than an ArrayBuffer. Since Gemini responses may contain incomplete Unicode bytes, using a string buffer could be causing the corruption.

solution 1: change `buffer` from string to ArrayBuffer in `streamChatGemini` function

https://github.com/continuedev/continue/blob/aa18568c6096f8f2df7075ff0f1f711f6f75ed01/core/llm/llms/Gemini.ts#L105

solution 2: use [`TextDecoderStream`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream) instead of `TextDecoder` in `streamResponse` function.

https://github.com/continuedev/continue/blob/aa18568c6096f8f2df7075ff0f1f711f6f75ed01/core/llm/stream.ts#L12-L18

```ts
yield* response.body.pipeThrough(new TextDecoderStream());
```

### To reproduce

Ask some questions in the chat panel in Japanese.

### Log output

```Shell
No output during chat response.
```

**Comment by reosablo** [comment]
I tried `TextDecoderStream` and it seems to work fine.

I'll create PR.

```ts
// core/llm/stream.ts
export async function* streamResponse(
  response: Response,
): AsyncGenerator<string> {
  if (response.status !== 200) {
    throw new Error(await response.text());
  }

  if (!response.body) {
    throw new Error("No response body returned.");
  }

  // `response` doesn't seem to be an instance of globalThis.Response and
  // TypeScript doesn't seem to know ReadableStream has `from` method.
  const stream = (ReadableStream as any).from(response.body);

  // The type of stream is any, not ReadableStream.
  // So we don't need "DOM.AsyncIterable" lib for this line.
  yield* stream.pipeThrough(new TextDecoderStream());
}
```

**Comment by sestinj** [comment]
Thanks for the PR @reosablo !
