### ISSUE TITLE
[CON-85] Write custom slash commands in the config file, just a string

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#150]
Should be some button (or slash command) somewhere. Opens the config file. The step description explains how to do this and gives an example of what the JSON structure might look like.

Then whenever slash commands are loaded in the config object, they are also loaded from this part of the config (`custom_commands`?). Then make a really basic step which basically runs a `UserInputStep` with the custom command's prompt and any user input (?"The user also provided this additional input"?) and let function calls decide whatever else to do next.

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-85](https://linear.app/continue/issue/CON-85/write-custom-slash-commands-in-the-config-file-just-a-string)</sub>

**Comment by TyDunn** [comment]
@sestinj please review

**Comment by sestinj** [comment]
@TyDunn works like a charm, nice!
