### ISSUE TITLE
Azure OpenAI API not supported for embeddings

### ISSUE THREAD

**Issue by andrijdavid** [continuedev/continue#1515]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux X64 6.8.0
- Continue: 0.8.40
- IDE: 1.90.1
```

### Description

Currently, the OpenAIEmbeddingProvider does not support Azure OpenAI Endpoints. 

### To reproduce

1. Open the configuration file.
2. Add the Azure OpenAI Endpoint to the configuration.
3. Attempt to update the vector database.
4. Observe the following error message: `Error updating the vectordb::text-embedding-3-large index: Error: {"error":{"code":"404","message": "Resource not found"}}`

### Log output

```Shell
Error updating the vectordb::text-embedding-3-large index: Error: {"error":{"code":"404","message": "Resource not found"}}
```

**Comment by gketronDS** [comment]
I'm also encountering this issue. The Azure tutorial (shown below) in the docs does not work and swapping the provider to OpenAI as a hail-mary does not work. `"embeddingsProvider": [{
    "provider": "azure",
    "model": "text-embedding-3-large",
    "apiBase": "<YOUR_DEPLOYMENT_BASE>",
    "engine": "<YOUR_ENGINE>",
    "apiVersion": "<YOUR_API_VERSION>",
    "apiType": "azure",
    "apiKey": "<MY_API_KEY>"
}]`
