### ISSUE TITLE
Feature Request for Text Embeddings Inference

### ISSUE THREAD

**Issue by jvhgit** [continuedev/continue#1519]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi,

Thank you for your work.
I was wondering if you could add support for https://github.com/huggingface/text-embeddings-inference as an embeddingsProvider (like you did with the TGI).
Would be great.

Kind regards,

**Comment by LLukas22** [comment]
Just adding that `TEI` also provides an `/rerank` endpoint, which could also be implemented as one of the rerankers e.g. when used with models such as [jinaai/jina-reranker-v2-base-multilingual](https://huggingface.co/jinaai/jina-reranker-v2-base-multilingual). 

I would also be willing to add this feature if it is wanted 🤔

**Comment by jvhgit** [comment]
That would be real nice! I am working on a pilot within my company to see if this could increase development speed and documentation, this would be a real nice feature I can use for the setup.

**Comment by jvhgit** [comment]
I am closing this issue since it is already implemented! See: https://docs.continue.dev/walkthroughs/codebase-embeddings, the reranking part is not implemented, I suggest that you make a seperate issue.

Kind regards

**Comment by Patrick-Erichsen** [comment]
@LLukas22 - currently we do not have support for TEI as a reranker (see the available options [here](https://docs.continue.dev/walkthroughs/codebase-embeddings#reranking-providers)). 

We'd we welcome a PR to implement it though! Check out https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md to get started and feel free to reach out with any questions in Discord.
