### ISSUE TITLE
Context provider label isn't completed when interacting with a submenu

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#1540]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: v0.9.151
- IDE: VSCode
```

### Description

The user flow for interacting with a context provider that has a submenu is as follows:
- Start typing to search for the context provider, e.g. type `@se` to find the Search context provider
- Press "enter" to select the provider
- The option turns into the submenu input to allow a user to provide input

At this point, the user has selected the specific provider, so we should update the label in the main input. 

Right now, it displays as the following, which doesn't provide visual confirmation that the user has successfully selected the given context provider.

![Screenshot 2024-06-21 at 1 04 25 PM](https://github.com/continuedev/continue/assets/20157849/74c58850-4fb1-47d9-b939-b0f88bdd1f50)

**Comment by sestinj** [comment]
That's a good observation, I see what you mean now. Probably the place to solve this is [here](https://github.com/continuedev/continue/blob/dev/gui/src/components/mainInput/MentionList.tsx#L244-L249)
