### ISSUE TITLE
Autocomplete with Qwen2 returns <fim_middle>

### ISSUE THREAD

**Issue by anatoli26** [continuedev/continue#1552]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
OS: Linux x64 6.8.0-35-generic snap
Continue: v0.8.40
VS Code: 1.90.2
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
```

### Description

When using qwen2 (1.5b in my case) via ollama for autocomplete, I get issues with the proposed completions. They include `</fim_middle>`, `</code` and similar special tokens + the completion itself is not right in the sense that the suggestions include part of the already written code, instead of just its continuation.

### To reproduce

Create a new file: `test.py`, there type:
```
print(
```
It gets autocompleted to:
```
print(print()</fim_middle>
```

### Log output

```Shell
==========================================================================
==========================================================================
Settings:
contextLength: 4096
model: qwen2:1.5b
maxTokens: 1024
stop: <|im_start|>,<|im_end|>,<fim_prefix>,<fim_suffix>,<fim_middle>,<|endoftext|>,

,

,/src/,#- coding: utf-8,,
def,
class,
"""#
temperature: 0.01
raw: true
log: undefined

############################################

<fim_prefix>print()<fim_suffix>)
      <fim_middle>==========================================================================
==========================================================================
Completion:

print()
```

**Comment by felix1982** [comment]
i use codeqwen model, config "tabAutocompleteOptions“ like this ：

```
 "tabAutocompleteOptions": {
        "useCopyBuffer": false,
        "maxPromptTokens": 400,
        "prefixPercentage": 0.5,
        "template": "<fim_prefix>{{{prefix}}}<fim_suffix>{{{suffix}}}<fim_middle>"
    }
```

**Comment by sestinj** [comment]
@felix1982 This is already our [default template](https://github.com/continuedev/continue/blob/dev/core/autocomplete/templates.ts#L29-L30) for qwen so you should be able to remove the "template" property there.

And @anatoli26 I just made a fix [here](https://github.com/continuedev/continue/commit/4418e611d8f08479326a19bef7375a1695feb7e1) and [here](https://github.com/continuedev/continue/commit/fd783f2e57197c74929d68ea29794047e883da37) for the problem, so will close this issue but you can expect it in the next release

**Comment by victordonat0** [comment]
i use same model but he its a gguf and change template to chatml i fix this using "template": "<|im_start|>complete the code<|im_end|><|im_start|>user {{{prefix}}}<|im_end|><|im_start|>assistant {{{suffix}}}" on options
