### ISSUE TITLE
Jetbrains EAP release action doesn't seem to work

### ISSUE THREAD

**Issue by neominik** [continuedev/continue#1556]
### Description

Even though https://github.com/continuedev/continue/actions/runs/9607377017 was supposedly successful, publishing `v0.0.52-jetbrains` to the market place, there is no new version available at https://plugins.jetbrains.com/plugin/22707-continue/versions/eap, nor does IntelliJ find updates after setting up the EAP repo there as described in the [docs](https://docs.continue.dev/troubleshooting#jetbrains-1).

**Comment by savely-krasovsky** [comment]
v0.0.52 doesn't work at all for me, no matter it's EAP or not.

**Comment by sestinj** [comment]
@savely-krasovsky @neominik There was a defect in that particular build, so I removed the version from the store. The next build, 0.0.53, will be available both on the store and through GitHub Releases
