### ISSUE TITLE
Make crash my extension host on VSCode

### ISSUE THREAD

**Issue by MrMic** [continuedev/continue#1569]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04
- Continue: 0.8.40
- IDE: VS Code
```

### Description

At installation, it makes my Extension host

### To reproduce

When I install it the bottom bar become empty.

**Comment by sestinj** [comment]
@MrMic Are you able to share anything from the [logs](https://docs.continue.dev/troubleshooting#check-the-logs)? My guess is that the answer to the problem will be fairly obvious once we can see them, but fairly obscure before then

**Comment by cdenovo** [comment]
The bug description is lacking, but sounds like dup of https://github.com/continuedev/continue/issues/911

**Comment by sestinj** [comment]
Ah yes this is a good call, I'm going to close this in favor of condensing conversation around a single issue
