### ISSUE TITLE
Contributing guide to include Rust or just Cargo as pre-requisite

### ISSUE THREAD

**Issue by PrithviSubaraja** [continuedev/continue#1580]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

![image](https://github.com/continuedev/continue/assets/98091014/73d96873-60aa-455c-b04a-983e8b9b3c71)
Env setup only speaks about nvm, but not about rust, this leads to an error when running the `install-all-dependencies` task in VS code as seen below,
`Not Found cargo 1.79.0`

### Solution

Installing rust using rustup install the cargo package and proceeds to install the dependencies properly

**Comment by sestinj** [comment]
@PrithviSubaraja thanks for bringing this up. We actually don't 100% require cargo any longer for local development, so I've removed this from the installation script https://github.com/continuedev/continue/commit/bff8151e60b5230abb6be47a9ddf558f896fc937
