### ISSUE TITLE
ability to disable codebase retrieval

### ISSUE THREAD

**Issue by fazo96** [continuedev/continue#1583]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently codebase retrieval does not work for some users due to several open bugs:

- https://github.com/continuedev/continue/issues/1467
- https://github.com/continuedev/continue/issues/1196

These bugs seems to be tied to large codebases. On large codebases, even after the bugs are fixed, I might want to disable codebase retrieval to save battery when working on my laptop by skipping indexing, or for other reasons like saving disk space.

The more pressing need is that I would like to switch off my Github Copilot subscription in favor of using Continue with gpt-4o or other models. However, I can't do this, because the Codebase Retrieval will cause vscode to freeze, the Continue extension to stop working randomly, and very high CPU usage and disk writes as it tries to index.

### Solution

A simple switch in the configuration to turn codebase retrieval off entirely would be very much appreciated and would allow me to switch to using Continue instead of Copilot.

**Comment by sestinj** [comment]
@fazo96 this is possible already with the "disableIndexing" option in config.json: https://docs.continue.dev/reference/config

As for issue 1467, I've just solved this and it will be available in the next pre-release. Hope both of these help! Feel free to close the issue if this seems to be solved

**Comment by fazo96** [comment]
thank you @sestinj I'll try disabling indexing and seeing if it works. I look forward to trying with indexing enabled again once #1467 and/or #1196 are resolved
