### ISSUE TITLE
config.models is not iteratable

### ISSUE THREAD

**Issue by dheerajtp** [continuedev/continue#1585]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Ubuntu 20.04.6 LTS (Focal Fossa)
- Continue:0.8.24
- IDE:VSCode 1.90.2
```

### Description

I downloaded the Continue extension from VS Code, but my VS Code crashed during the installation process. I completely uninstalled VS Code using the terminal and reinstalled it, hoping to restart the installation from step 1. However, it still isn't working.

![Screenshot from 2024-06-27 12-45-19](https://github.com/continuedev/continue/assets/45311336/9f8aada6-8ce1-40b0-b609-8347b04aa1ee)
![Screenshot from 2024-06-27 14-23-46](https://github.com/continuedev/continue/assets/45311336/0d18d30b-4b0e-4c4f-b367-4280d35a0f5e)

**Comment by sestinj** [comment]
@dheerajtp 0.8.24 isn't the latest version of the extension (which is 0.8.40). Do you have any idea why only an older version might have been downloaded? Is there a special registry for example being used instead of the main VS Code Extension Marketplace?

**Comment by dheerajtp** [comment]
> @dheerajtp 0.8.24 isn't the latest version of the extension (which is 0.8.40). Do you have any idea why only an older version might have been downloaded? Is there a special registry for example being used instead of the main VS Code Extension Marketplace?

There were some issues for the VS Code. That was the reason i used an older version. But even through i updated it I'm unable to use continue. This is the error which I'm getting

**Comment by dheerajtp** [comment]
> @dheerajtp 0.8.24 isn't the latest version of the extension (which is 0.8.40). Do you have any idea why only an older version might have been downloaded? Is there a special registry for example being used instead of the main VS Code Extension Marketplace?

Sorry my mistake v0.8.40 was the version of continue. My bad. It's v0.8.40 . 

So even though i uninstalled vs code I'm still unable to integrate it into my VS Code. So what will i do ?

**Comment by fry69** [comment]
My guess is that something is wrong in your config file, see the [Troubleshooting guide](https://docs.continue.dev/troubleshooting) for details. A safe way to completely start over is to delete your Continue config directory, but you can also try to debug your config file.

**Comment by dheerajtp** [comment]
> My guess is that something is wrong in your `config.json` file, see also [Troubleshooting guide](https://docs.continue.dev/troubleshooting) for details to get more information. A safe way to completely start over is to delete your Continue config directory (`~/.continue` on Mac/Linux), but you can also try to debug your config file after thoroughly consulting the documentation.

I removed .continue folder and installed the extension again. But it still gives me the same error.

**Comment by fry69** [comment]
What are your exact step after removing your `.continue` folder (I assume you got asked to setup Continue again and chose similar settings, which lead to this error again?)

**Comment by dheerajtp** [comment]
> What are your exact steps after removing your `.continue` folder? (I assume you got asked to setup Continue again and chose similar settings, which lead to this error again?)
> 
> At this point it may also be helpful if you can post your `config.json` here (without any API keys).

I removed the .continue folder from ubuntu then installed the continue extend again from VS Code. But it didn't ask me for the setup. It directly has shown the same error message for me. Also actually I'm not able to open my config.json file from continue extensions setup.

**Comment by dheerajtp** [comment]
> My guess is that something is wrong in your `config.json` file, see also [Troubleshooting guide](https://docs.continue.dev/troubleshooting) for details to get more information. A safe way to completely start over is to delete your Continue config directory (`~/.continue` on Mac/Linux), but you can also try to debug your config file after thoroughly consulting the documentation.

[Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "2a57503b-eef7-43f0-9c8b-f6a0775967af",
    "messageType": "config/getBrowserSerialized"
  }
}

TypeError: config.models is not iterable

index.js:360 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at setConfig (index.js:360:515)
    at index.js:303:29960
    at produce (index.js:303:14765)
    at index.js:303:29936
    at Array.reduce (<anonymous>)
    at c (index.js:303:29840)
    at reducer (index.js:303:30959)
    at index.js:303:20051
    at index.js:1898:9720
    at g (index.js:303:19091)
    
    These are the errors in the console

**Comment by fry69** [comment]
This still looks like a problem with your configuration/setup (I assume you run local models?) Please post your `config.json` (without API keys).

**Comment by dheerajtp** [comment]
> This still looks like a problem with your configuration/setup (I assume you run local models?) Please post your `config.json` (without API keys).

{
  "models": [],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Starcoder2 3b",
    "provider": "ollama",
    "model": "starcoder2:3b"
  },
  "allowAnonymousTelemetry": true
}

**Comment by fry69** [comment]
You have no default model configured, I think that is the problem, try replacing the `models` property with:
```json
  "models": [
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    }
  ],
```

**Comment by fry69** [comment]
Define 'slow'. During startup your codebase gets indexed so you can ask questions about it via the `@codebase` content provider. This should not last longer than a few minutes at maximum though for medium sized projects (like the Continue repository here). This is a one time thing.

Otherwise if you run local models you will see your hardware getting used to its full potential, as LLM inference is quite demanding.

**Comment by dheerajtp** [comment]
> Define 'slow'. During startup your codebase gets indexed so you can ask questions about it via the `@codebase` content provider. This should not last longer than a few minutes at maximum though for medium sized projects (like the Continue repository here). This is a one time thing.
> 
> Otherwise if you run local models you will see your hardware getting used to its full potential, as LLM inference is quite demanding.
> 
> If your original problem got solved, feel free to close this issue/bug report and start a new one if you have another problem. This is not a support channel/chat, please join the [Discord](https://discord.gg/vapESyrFmJ) if you want to chat about problems.

It take long time to response. Since i'm using local models i think its related to my system specs. Thanks brother

**Comment by fry69** [comment]
BTW: If you reply to an issue comment, there is no need to include the previous one in your comment, that bloats the issue unnecessarily (except the comment you reply to is far, far above your comment and the context is not immediately obvious).

**Comment by dheerajtp** [comment]
Thank you. That's a new for me. Thanks. I will mark it as close as well
