### ISSUE TITLE
Getting strange reponces from model suddenly?

### ISSUE THREAD

**Issue by Emoter1979** [continuedev/continue#1596]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:w11
- Continue:latest release 0.8.24 - 2024-04-12
- IDE:vscode
```

### Description

Running Ollama and Model CodeLlama command "ollama run CodeLlama"

It prompts and works for a few minutes, then I'm getting strange responses like:

Prompt: "hi"

Output: " <s><R><unused_10><unused_12><X>▅<unused_15>▅ <unused_11><R><unused_10><unused_3><unused_14><unused_3><unused_15><unused_5><R><s><unused_7>10<unused_7><unused_7><unused_19><unused_14> <unused_16> ▅<R> <unused_13><unused_17><X><unused_10>
"

### To reproduce

see description

### Log output

```Shell
unused_17> <unused_8><unused_13><unused_2><unused_1>11<unused_8><unused_12>▅<unused_19><unused_6><unused_17><unused_19><unused_3><unused_19><unused_3>
```

**Comment by sestinj** [comment]
@Emoter1979 it looks like you might have an older release version for some reason. Our latest on the VS Code extension marketplace is 0.8.40. Is there any chance that you have an older version of VS Code than 0.1.70?

**Comment by Emoter1979** [comment]
Sorry, removed vscode and all plugins and clean all out. then reinstalled it again  and now it works.

**Comment by Emoter1979** [comment]
Sorry, removed vscode and all plugins and clean all out. then reinstalled it again  and now it works.
