### ISSUE TITLE
Broken images in JetBrains extension README

### ISSUE THREAD

**Issue by dandv** [continuedev/continue#1602]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.0.50
- IDE: All IntelliJ
```

### Description

When trying to install Continue 0.0.50 in PyCharm, I see this page, which could inspire more trust if all images loaded:

![image](https://github.com/continuedev/continue/assets/33569/ce0e2dd5-f214-4c85-8d5a-f7467d40c515)

### To reproduce

You can see this at https://plugins.jetbrains.com/plugin/22707-continue as well:

![image](https://github.com/continuedev/continue/assets/33569/b1c375cc-00c0-486f-ae3b-e0e5e6386fe3)

All images after the first screenshot are broken:

![image](https://github.com/continuedev/continue/assets/33569/57c051e9-433d-46b1-9edd-0f465c83a45b)

A bit mind-boggling that nobody has reported this yet.

**Comment by sestinj** [comment]
Solved [here](https://github.com/continuedev/continue/commit/c932bbd68db221cfb495bf3ecb12c8d89dbbb233), JetBrains is expecting relative to the public GitHub repository

**Comment by dandv** [comment]
I still see this issue in v0.0.53, is that expected? Also, I don't see any What's New information:

![image](https://github.com/continuedev/continue/assets/33569/8c38a03c-a2aa-4a90-8d8b-ed4abadad316)

**Comment by sestinj** [comment]
Ok this is actually solved now, because we decided the GIFs are a bit overloading. This file is just text now
