### ISSUE TITLE
Sidebar trapped in the documentation, no way to go back

### ISSUE THREAD

**Issue by dandv** [continuedev/continue#1606]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux
- Continue: 0.0.50
- IDE: PyCharm, WebStorm
```

### Description

Some documentation links are missing the `target="_blank"` attribute, and open in the Continue sidebar.

This makes it impossible to get back to the chat functionality.

![image](https://github.com/continuedev/continue/assets/33569/28320c92-b4e6-4e44-a27c-ef9091016909)

### To reproduce

1. Click "+" to add a model
2. From "To read more about the options, check out our [overview](https://docs.continue.dev/model-setup/overview) in the docs.", click that "overview" link

**Comment by sestinj** [comment]
Were missing a few, thanks for catching this: https://github.com/continuedev/continue/commit/9d27ce551abc0fa16ccc4adfb03c98e7c84013b0.

We'll have a new release for JetBrains early next week and I'll wait until then to close this
