### ISSUE TITLE
Add support for Claude Sonnet 3.5

### ISSUE THREAD

**Issue by dandv** [continuedev/continue#1607]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I've added my Anthropic API key, but don't see any information in the UI about the available model versions. I could replace the model string in `config.json` with `claude-3-5-sonnet-20240620` but would be nice to have a friendlier UI for this, otherwise users may think [the best model for coding](https://livebench.ai/) isn't supported yet.

### Solution

The OpenAI configuration screen has an option to "Automatically populate the model list by calling the /models endpoint of the server". Until Anthropic adds an endpoint to list available models, they could be
* [hard coded](https://github.com/enricoros/big-AGI/blob/main/src/modules/llms/server/anthropic/anthropic.models.ts#L7)
* scraped from https://docs.anthropic.com/en/api/claude-on-vertex-ai#accessing-vertex-ai
* obtained [programmatically from Amazon Bedrock](https://docs.anthropic.com/en/api/claude-on-amazon-bedrock#api-model-names)

**Comment by fry69** [comment]
Sonnet-3.5 is supported in the VSCode Pre-Release extension, see https://github.com/continuedev/continue/commit/c0705b363153d096c2e68e223c4337f9f72f0951

**Comment by sestinj** [comment]
In the next release we'll not only have Sonnet in the model selection UI, but will be encouraging users to immediately input their Claude API key for Sonnet 3.5. For now this is becoming a strongly recommended model

**Comment by sestinj** [comment]
This is now released in the latest pre-release
