### ISSUE TITLE
Explain how embeddings models are used

### ISSUE THREAD

**Issue by dandv** [continuedev/continue#1615]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

https://docs.continue.dev/setup/select-model#embeddings mentioned embeddings models without more information.

### Solution

That section could explain how embeddings models are used by Continue.

https://docs.continue.dev/walkthroughs/codebase-embeddings#embeddings-providers has a lot more information on that topic.

**Comment by sestinj** [comment]
We want to keep the select-model page pretty lean, but I definitely think it's an improvement to link to the other page: https://github.com/continuedev/continue/commit/eb288fe310c33ee7ef6fc171054982a410f8a7cd
