### ISSUE TITLE
Merge documentation pages/sections for running locally/offline/without Internet

### ISSUE THREAD

**Issue by dandv** [continuedev/continue#1616]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

https://docs.continue.dev/walkthroughs/running-continue-without-internet
and
https://docs.continue.dev/setup/examples#i-need-to-be-entirely-local--offline

Address the same problem. The second link only talks about VSCode though.

### Solution

There should be one page or section about running offline, and it should address both JetBrains IDEs and VSCode.

The easiest fix might be to fold the first page into the "I need to be entirely local" section of the second page.

**Comment by sestinj** [comment]
Totally agree, just made the change [here](https://github.com/continuedev/continue/commit/3e8d5344e083f9bc1a175bbd89df24e9960b6c44) and [here](https://github.com/continuedev/continue/commit/82345e590d127744c22058f02cf953a7f58dba01)
