### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by zcf0508** [continuedev/continue#1622]
Type: <b>Bug</b>

high cpu usage

Extension version: 0.9.168
VS Code version: Code - Insiders 1.91.0-insider (aea213b7fcc7de5c24ad797ac1af209b159d451f, 2024-06-28T05:56:20.804Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13490F (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (13.17GB free)|
|Process Argv|-n --crash-reporter-id 65a67007-710c-42e7-a767-36a3680c8ec3|
|Screen Reader|no|
|VM|14%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31071684
refactort:31084545
pythonrstrctxt:31083681

```

</details>

**Comment by fry69** [comment]
Can you confirm this is a problem with current release version of VSCode (1.90.2)?

Also, if you have a huge code base and setup local models, high CPU usage is expected for inference and also for the indexing process at start (but that should not take more than a few minutes at max for a medium sized project like this one).

**Comment by Chanstien** [comment]
Same issue here. After the vscode starts, it seems the continue plugin will create a large number of processes.  This will not happen if you uninstall the plugin.

window: win10
vscode version: 1.90.2
continue version: v0.9.168

**Comment by fry69** [comment]
That is expected, the first time Continue starts it will index your workspace so you can ask questions about it with the `@codebase` context provider. For more details see https://docs.continue.dev/walkthroughs/codebase-embeddings

**Comment by Chanstien** [comment]
> That is expected, the first time Continue starts it will index your workspace so you can ask questions about it with the `@codebase` context provider. For more details see https://docs.continue.dev/walkthroughs/codebase-embeddings

but i did not open vscode in a workspace. no code could be processed by Continue.

**Comment by fry69** [comment]
I also do not have a workspace open in my VSCode and do not see high CPU usage, even after restart. (VSCode 1.90.2 / Continue 0.9.168)

**Comment by Chanstien** [comment]
I record a video to show the issue.

https://github.com/continuedev/continue/assets/37270126/b9f37e41-a523-403b-91f1-72155c946a5e

**Comment by fry69** [comment]
Thanks for this demonstration. This should not happen of course, but I have no Windows PC to test this, so I guess you have to wait until the core developers are back to tackle this problem.

**Comment by fry69** [comment]
If you are impatient and want to help bisect this problem, you can try installing older Pre-Release versions of Continue from the releases page -> https://github.com/continuedev/continue/releases
and report which one do or no do not show this problem on your platform.

If you want to dig even deeper, you could have a look at the individual commits (see here for example -> https://github.com/continuedev/continue/compare/v0.9.167-vscode...v0.9.168-vscode) in the release version, and try to guess which commit could be the problem, once you have isolated the problematic release version.

As a general contingency I'd recommend to switch to the stable release (0.8.40) for now.

**Comment by Chanstien** [comment]
Thanks for your reply. I try to install older Pre-Release versions (from [v0.9.167](https://github.com/continuedev/continue/releases/tag/v0.9.167-vscode) to [v0.9.165](https://github.com/continuedev/continue/releases/tag/v0.9.165-vscode)) and they do not show this problem. Unfortunately, I am not familiar with TypeScript and can't resolve this problem.

**Comment by fry69** [comment]
Thank you for your time, this will it make much easier to pinpoint the problem.

**Comment by fry69** [comment]
My current best guess is that this commit might have something to do with this problem, as it is the only one I could find that seems to behave differently on Windows vs other platforms -> [`39dd88b` (#1542)](https://github.com/continuedev/continue/pull/1542/commits/39dd88b92ccb47c44234be3d6f5fffb31df78997)

**Comment by leolivier** [comment]
same here since this morning, as soon as I enable continue.dev, it spawns 10th of powershell subprocesses.
My laptop's Windows 11 has been updated during the night with KB5039327, so it might be linked.
The only info I got on this update is https://www.neowin.net/news/kb5039327-microsoft-fixing-windows-11-storage-spaces-group-policy-gpu-idle-power-bugs/
I will try uninstalling it and see if it changes something, keep you posted

**Comment by fry69** [comment]
@leolivier Can you confirm that downgrading from 0.9.168 to 0.9.167 fixes this problem (get the older Pre-Release version from here -> https://github.com/continuedev/continue/releases/tag/v0.9.167-vscode)?

**Comment by leolivier** [comment]
Currently desinstalling the windows kb and rebooting, I will 1rst tell you if this fixes the issue. 
If not, I'll try the older release

**Comment by leolivier** [comment]
Ok, desinstalling the KB does fix the issue, but reinstalling the older pre-release 0.9.167 does!

**Comment by leolivier** [comment]
Sorry, I edited above comment, desinstalling the KB does NOT fix the issue but installing 0.9.167 DOES fix it

**Comment by fry69** [comment]
Thanks for the confirmation, if you want to dig into the code, you can throw a look at my current best guess where the problem could originate from (-> https://github.com/continuedev/continue/issues/1622#issuecomment-2198203548). Otherwise we'll have to wait until this gets fixed by more knowledgeable core developers.

**Comment by leolivier** [comment]
I don't see in this commit some code triggering a powershell script except **maybe** (I don't know vscode APIs)  calls to readDirectory...
so **pure** guess: line 302 of ideUtils.ts: readDirectory call might return "." (ie the current directory) **I say might, I don't know** and this is not defined in https://vscode-api.js.org/interfaces/vscode.FileSystem.html#readDirectory => this is not tested afterwards so might lead to an infinite loop

**Comment by fry69** [comment]
For a cross check, I just downgraded to 0.9.167 on my M1 MB to see if I can spot any behavior difference on startup, to verify my assumption that this is truly a Windows problem. So far I cannot see any different behavior between these two Continue versions, both with no or different workspaces opened while starting up.

**Comment by sestinj** [comment]
Thank you all for sharing info here. I'm debugging right now on my Windows machine and hope to have a fix up by the end of today. It definitely seems related to directory traversal

**Comment by sestinj** [comment]
@leolivier @zcf0508 @Chanstien Ironically this was caused by a feature that was supposed to *decrease* CPU usage by pausing autocomplete when the battery was low. The fix is [here](https://github.com/continuedev/continue/commit/4c149ef1e21aa882be25261ee5e76215eb2ac2d1) and very obviously seemed to stop the problem on my windows machine.

I'm planning to make a main release tomorrow but it's critical that this bug is 100% squashed before I do so—can you verify that the problem is solved for you in 0.9.169? (not published yet, but as soon as this GH action is done it will be ready: https://github.com/continuedev/continue/actions/runs/9755161193)

**Comment by fry69** [comment]
FYI: The new Pre-Release 0.9.169 (with a possible fix for this bug) is now installable via regular update in VSCode, or manually here -> https://github.com/continuedev/continue/releases/tag/v0.9.169-vscode
Please test and report if this fixes this bug

**Comment by Csaba8472** [comment]
> FYI: The new Pre-Release 0.9.169 (with a possible fix for this bug) is now installable via regular update in VSCode, or manually here -> https://github.com/continuedev/continue/releases/tag/v0.9.169-vscode Please test and report if this fixes this bug

it fixed for me, thank you!

**Comment by Chanstien** [comment]
> @leolivier @zcf0508 @Chanstien Ironically this was caused by a feature that was supposed to _decrease_ CPU usage by pausing autocomplete when the battery was low. The fix is [here](https://github.com/continuedev/continue/actions/runs/9755522470) and very obviously seemed to stop the problem on my windows machine.
> 
> I'm planning to make a main release tomorrow but it's critical that this bug is 100% squashed before I do so—can you verify that the problem is solved for you in 0.9.169? (not published yet, but as soon as this GH action is done it will be ready: https://github.com/continuedev/continue/actions/runs/9755161193)

It works for me. Thank you for your hard work.

**Comment by leolivier** [comment]
Looks ok for me too. Thanks!

**Comment by zcf0508** [comment]
v0.9.169 is fixed for me

**Comment by mshakirDr** [comment]
Using Continue for the first time. I am facing the same issue. I have seen the version numbers are now in the range of 0.9.2xx (after the fix was added), but I am still facing the issue of high cpu usage. Windows 11, intel i7 13th gen. Any idea how the same bug might have returned? (or a new issue?)

**Comment by the-simian** [comment]
@mshakirDr are you using the release version or the pre-release version? release is on 0.8.59 - 2024-11-25  pre-release is v0.9.239
