### ISSUE TITLE
Customized model can't take advantage of the Ctrl+I window feature

### ISSUE THREAD

**Issue by dbsxdbsx** [continuedev/continue#1633]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Win10
- Continue:v0.8.40
- IDE:Vscdoe v1.90
```

### Description

When using the Ctrl+I feature with a customized model, it finally raise issue like this:
![image](https://github.com/continuedev/continue/assets/17372655/af4b3bfc-447c-435b-9d3f-d7d41cf181cd)

my config is like this:
```
{
  "models": [
   ...
    {
      "title": "pplx",
      "model": "llama-3-sonar-large-32k-online",
      "apiKey": "pplx-<my-token>",
      "apiBase": "https://api.perplexity.ai",
      "provider": "openai"
    }
  ],
...
}
```
while using any built-in model(For example, the free-limited usage of GPT4o),everything is fine.  And since I only got this customized model,  I am not sure if it is due to perplexity specifically or not.

### To reproduce

1. config an custoimized model
2. pressing ctrl+I
3. input any command
4. the error occurs with the msg shown at bottom right in vscode

**Comment by sestinj** [comment]
@dbsxdbsx for APIs like this that aren't actually OpenAI compatible (e.g. missing the /completions endpoint), you can set `"useLegacyCompletionsEndpoint": false` in your model in config.json

**Comment by dbsxdbsx** [comment]
>  you can set "useLegacyCompletionsEndpoint": false in your model in config.json
Nice! It is solved.

**Comment by dbsxdbsx** [comment]
By the way, one thing I think need to be improved is that I hope there could be a mechanism to hold the historical input for both the ctrl+I windows input box and the side window box.

**Comment by sestinj** [comment]
@dbsxdbsx I really like the idea actually. I made a first attempt here, and we'll probably ship it with next pre-release: https://github.com/continuedev/continue/commit/d5466532e15bc79fff2fd290e6a34bdcf63b72d8
