### ISSUE TITLE
[CON-99] Things I want as I use Continue

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#169]
* [ ] Give the model a page of documentation. Either could be a part of the explicit context selection, or a slash command
* [X] Insert at cursor button
* [ ] Look over the changes I just made in this range: were there any accidental regressions
* [ ] Use @ to require user to specify when they are highlighting new ranges, otherwise cmd+f highlights a range
* [ ] I want not to have GPT automatically take actions without me knowing beforehand. It's just springing them out on me. Even if I can reverse them, I don't immediately feel that trust and it's too large a barrier before I learn to trust. Would love links in the chat to take actions. Then can just click on them, makes it easier to read
* [ ] Instead of just copy button on code snippets, an "insert intelligently" button that will place the code where it is needed even if not a clean insertion.
* [ ] Often I want to see the documentation. Would be nice to have links provided, have the model do the searching for me.
* [ ] Autocomplete in the textarea
* [ ] I wrote some random note about why we use version 1.67.0 of @types/vscode and this is rarely ever going to be seen by someone, so want Continue to "just know about it".
* [X] Our font is slightly hard to read and small. Slightly.
* [X] Stop button instead of X
* [ ] Write my commit messages for me (/commit)
* [ ] When it goes wrong, I want to be able to just restart from scratch with something like a restart command
* [ ] Maybe the best way to use functions is to have suggested actions that can be clicked at the bottom of chat output. Like "create tsconfig.json" or "run npm i react"
* [ ] I want the code explanations to be much better; they are not super useful rn--I don't find myself really using them. probably gpt-3.5-turbo can read diffs and summarize. This is the way

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-99](https://linear.app/continue/issue/CON-99/things-i-want-as-i-use-continue)</sub>

**Comment by hgblu-sammosna** [comment]
+1 for "insert intelligently", like the autocomplete/suggest done by Codeium or Copilot
