### ISSUE TITLE
Typo in doc for section 'Codebase retrieval/Voyage AI'

### ISSUE THREAD

**Issue by Laxenade** [continuedev/continue#1693]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi, while reading the doc, there seems to be a typo in [this part](https://docs.continue.dev/walkthroughs/codebase-embeddings#voyage-ai). Should the provider be `voyage` instead of `openai`?

### Solution

Should be a quick change in these two places?

https://github.com/continuedev/continue/blob/c93f530abd0d64300c4d45a8ad8da9ee996f03f8/docs/docs/setup/configuration.md?plain=1#L74

https://github.com/continuedev/continue/blob/c93f530abd0d64300c4d45a8ad8da9ee996f03f8/docs/docs/walkthroughs/codebase-embeddings.md?plain=1#L117

**Comment by sestinj** [comment]
Hi! This isn't a typo—it is called "openai" because Voyage uses the OpenAI API format, and we switch the API Base. I can see how this would be confusing though, and perhaps we'll make a dedicated "voyage" provider
