### ISSUE TITLE
VS Code extension slows down entire vscode on startup with remote (walkDir)

### ISSUE THREAD

**Issue by Yanpas** [continuedev/continue#1705]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 / RHEL7 on remote
- Continue: 0.8.43
- IDE: VS Code 1.85
- Model:
- config.json:
  
"disableIndexing": "true"
// the rest is default: ollama providers
```

### Description

I use VSCode remote: the extension is running on extension host on windows machine, the code is located on other SSH linux machine. I ran extension host profile and it looks like "walkDir" task that runs on extension startup eats entire SSH channel between windows and linux machine, due to which other parts of vscode become unresponsive. (in profile there's "onReaddir" on top, then "filterEntry" down the stack with "match" below. Minimatch's match method seems to be pretty slow)

I'd like to be able to disable completely full project walkthrough since I don't need it. Alternatively, probably it may be better to run the extension on SSH'ed host.

### To reproduce

1. Connect using SSH to other machine with a project with a large amount of files. SSH connection shouldn't be blazingly fast
2. Run "Developer: Show Running Extensions" and click start profile
3. Open a window with continue chat, the extension will start inititalizing
4. Now go to explorer tab: try navigating through project tree (each directory opens very slow
5. Or open a terminal - there will be significant lag when you type something
6. Save the profile. Also "Continue" extension **will be marked as unresponisve**.

### Log output

```Shell
Unfortunately I can't attach info from my working PC due to company policies.
```

**Comment by SaahilClaypool** [comment]
Downgrading to `v0.8.42` fixes this for me. Also using SSH extension. 

I have indexing disabled in the indexing in the config as I could never get that to work properly

**Comment by Qualzz** [comment]
I confirm the vs code extension is slowing down everything on vs code, and even sometimes makes the editor unresponsive. 
Disabling the extension for now.

**Comment by jonnyboynewton** [comment]
I have been experiencing the same issue here.  Massive performance issues with greater than 0.8.42.  Windows laptop connected to a linux machine via remote-ssh.  I thought it was maybe the high cpu usage on the remote machine for the node process that vscode spawns off for filewatching, but even with the downgrade that process is still high usage in top (90+% cpu usage).  But vscode is now usable again.
vscode was virtually unusable in some cases - especially when there was multiple workspaces open.  One workspace would be fine, the others would come to a halt.  Keystrokes in the terminal would take minutes to come back vs less than a second normally.
So there is definitely something wrong with Continue starting w/ 0.8.43 as it's now completely fixed with the downgrade.
I'm on the latest vscode (1.91.1).
I do not have indexing disabled.
I'm on Windows 11 23H2

**Comment by sestinj** [comment]
@Qualzz @SaahilClaypool @Yanpas I have a few questions as we're trying to learn more about what's happening here. If you could share any of this it would be immensely helpful!

- Do you use git, or a different version control system like Perforce?
- If using git, is your VS Code workspace at the root directory of the git repo, or do you have a subdirectory opened?
- Is the problem at all resolved by removing the "folder" context provider from config.json?
- If you install the Continue extension on the remote host rather than on your local machine does the same problem occur?
- Is the remote connection closing, or are you exclusively seeing UI lag?

**Comment by spew** [comment]
> @Qualzz @SaahilClaypool @Yanpas I have a few questions as we're trying to learn more about what's happening here. If you could share any of this it would be immensely helpful!
> 
> * Do you use git, or a different version control system like Perforce?

git

> * If using git, is your VS Code workspace at the root directory of the git repo, or do you have a subdirectory opened?

root

> * Is the problem at all resolved by removing the "folder" context provider from config.json?

have the 'modern' config with no context providers included

> * If you install the Continue extension on the remote host rather than on your local machine does the same problem occur?

only use on local machine, no remote machine involved

> * Is the remote connection closing, or are you exclusively seeing UI lag?

My first thing to investigate would be changing `walkDir` to not block on building up an array of every file name in the repo.

**Comment by Yanpas** [comment]
> * Do you use git, or a different version control system like Perforce?

git
> * If using git, is your VS Code workspace at the root directory of the git repo, or do you have a subdirectory opened?

yes, it's in the root. Also one of my projects has submodule
> * Is the problem at all resolved by removing the "folder" context provider from config.json?

No
> * If you install the Continue extension on the remote host rather than on your local machine does the same problem occur?

It didn't work for me,
> * Is the remote connection closing, or are you exclusively seeing UI lag?

The remote connection isn't closing, it becomes bloated by some enormous amount of data that extension is using. Thus remote terminal stops responding (JFYI, terminal prints typed symbol only after receiving it). I don't observer UI freezes, but that's almost impossible since extensionhost is another process.

I'm almost sure that:
1. the extension eats way too much CPU from the extension host process.
1. apart from that it exchanges a lot of data with SSH (most likely VSCode streams filesystem events/data).

**Comment by Yanpas** [comment]
Actually seems it's impossible to disable Files provider:
```json
"contextProviders": [
 {"name":"diff"}
]
```

and I still see Files in "at" dropdown

**Comment by Patrick-Erichsen** [comment]
@Qualzz @SaahilClaypool @Yanpas  @spew 

Going to treat this as the main issue to track this fix. #1783 hopefully addresses the main issue with `walkDir` blocking the main thread. However, we'll keep this issue open until you all can confirm that the extension isn't slowing down your VS Code.

**Comment by spew** [comment]
This seems like an improvement, however, I think there is more to do.

I see this error in the console: `Error: ENOSPC: System limit for number of file watchers reached`

**Comment by spew** [comment]
Taking a look at it some more, it isn't so easy because `CodebaseIndexer` expects to operate on the list of every file in the repo and not go file by file. Taking a look to see if this can be easily split up.

**Comment by Patrick-Erichsen** [comment]
Thanks for the review! I had a similar train of thought when refactoring, #1783 was an okay quick win but the real issue is that we still don't _actually_ begin any of the work until the file list has been built up. 

Chatting with @sestinj today on this 👍

**Comment by spew** [comment]
Yeah -- I'm also looking at walkDir(...) and I suspect it can be made faster, I'm playing around with it now.

One thing I noticed, it seems like ignore files only apply to their current level in the hierarchy? Is this true? Have you had complaints about continue not respecting .gitignore? I would expect, from reading the code, that a .gitignore will only be respected for the current folder it is in and not all folders below it.

**Comment by sestinj** [comment]
Progress bar is in fact the main reason for this. Even if we were to stream in parallel to chunking/embeddings though, we'd have roughly the same problem in the case where none of the files need to be indexed, it would basically just be completing the walkDir method in the same amount of time, and all of the .gitignore matching still needs to happen.

This makes me tend to think that worker threads are the way to go

Added a test here just so we can be more confident about the .gitignore behavior: https://github.com/continuedev/continue/commit/fa8eaa200b376ea5a46238b5d7ea8b1e773d9f08

**Comment by spew** [comment]
One issue I noticed, that is definitely an issue, is in this new bit of code in `walkDir(...):

```
    for await (const walkedEntries of walker.start()) {
      entries = [...walkedEntries];
    }
 ```
 
Note that the line of for loop is actually setting `entries` EQUAL to the current value of the iterator. Thus, `entries` is always equal to the last member of the AsyncIterator, this generally works because the values returned by the AsyncIterators are Sets and I believe it is a set of every file seen up to this point (probably also an issue).

This is an O(n^2) operation.

I was able to get the tests to still pass (and a new test I added that iterated over a large directory and verified the number of files returned by changing the above code to this:

```
    let lastValue = entries
    for await (const walkedEntries of walker.start()) {
      lastValue = walkedEntries;
    }
    entries = [...lastValue];
  ```
  
  So no comments about correctness, but basically we are only returning the entries of the last Set (I think this may always end up being the right answer because the constructor for Walker uses the same `Set` if the `parent` option is passed in).

**Comment by spew** [comment]
I'm testing out some changes to see if I can get walkDir to iterate faster over a large directory tree / source tree, I'll post an updated PR if I can improve the performance (and potentially resolve the issue I noted)

**Comment by Yanpas** [comment]
Will it be possible to disable indexing the whole project?
Most of the times I'll need to attach only currently opened file as a context

**Comment by fry69** [comment]
> Will it be possible to disable indexing the whole project? Most of the times I'll need to attach only currently opened file as a context

You already can disable indexing for the whole workspace folder/project with a `.continuerc.json` file in the root:

```json
{
	"disableIndexing": true
}
```

You can also configure which files should be excluded via `.continueignore` in the root (gitignore syntax), see here -> https://docs.continue.dev/walkthroughs/codebase-embeddings#ignore-files-during-indexing

**Comment by Yanpas** [comment]
Unfortuanely ,even with disableIndexing true, this issue still exists (I disabled indexing before raising this issue)

**Comment by jonnyboynewton** [comment]
> By the way, why the extension kind was chosen to be "UI" and not "Workspace"? (https://code.visualstudio.com/api/advanced-topics/remote-extensions) It seems to me that Workspace fits better the need to access files of the project. And VSCode also has the ability of port forwarding, thus access to LLM can be configured to work both ways (e.g. if SSH doesn't have internet / or ollama is hosted natively on Windows)

If this was changed, it would need to have rock-solid connection to LLMs on the local machine.  For instance we use local (on the laptop) Ollama models for certain types of highly secure codebases and we could not, for instance, have Ollama sitting on a port bound to the IP address of the machine (vs just localhost) - so the port forwarding between the remote host and the local machine would really need to be top-notch.

**Comment by spew** [comment]
Created this PR which improves walkDir performance: https://github.com/continuedev/continue/pull/1806

**Comment by spew** [comment]
It'd be great if @Yanpas could try it

**Comment by sestinj** [comment]
@jonnyboynewton this is the main reason we plan to stick with "UI". I've tested this a few times and it's definitely not easy enough to set up the connection reliably

**Comment by jonnyboynewton** [comment]
@spew I tested the latest pre-release with your walkDir fix and it is still a bit slower interactively than 0.8.42, it's actually usable again on even extremely large workspaces (over 1M files)

**Comment by spew** [comment]
Thanks @jonnyboynewton, I have two other potential changes in flight as well.

**Comment by Yanpas** [comment]
> It'd be great if @Yanpas could try it

I've opened a problematic folder twice, didn't notice any issue (yet I had indexing disabled). Thanks, seems to work out!
Also "Developer: Show Running Extensions" doesn't show any perf issue

**Comment by thomelane** [comment]
@spew this seems to have also resolved an issue I was having with a ~5s slow Cmd+I popup (using pre-release right now). Around 500,000 files in my directory (monorepo) for reference.

**Comment by spew** [comment]
I think this issue can be closed.
