### ISSUE TITLE
Continue doesn't let me copy bulletpoints from output

### ISSUE THREAD

**Issue by Cheizr** [continuedev/continue#1735]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When i try to copy a text output from Continue chat that contains bulletpoints and paste it somewhere else, it just paste the text without the bulletpoints

![image](https://github.com/user-attachments/assets/e77b271d-a8ca-47f3-b098-133f4f5eb9c9)

### Solution

Allow to copy all the output from Continue chat

**Comment by sestinj** [comment]
@Cheizr I believe this is standard behavior for markdown content on the web, and we're mostly aiming to match this (e.g. ChatGPT doesn't copy bullets). There is an option however to copy the raw markdown below your message (if you hover the message, it's the "Clipboard" button)

**Comment by Cheizr** [comment]
> @Cheizr I believe this is standard behavior for markdown content on the web, and we're mostly aiming to match this (e.g. ChatGPT doesn't copy bullets). There is an option however to copy the raw markdown below your message (if you hover the message, it's the "Clipboard" button)

This works for me, thank you!
