### ISSUE TITLE
Add/remove @docs URLs in .continuerc.json

### ISSUE THREAD

**Issue by saosebastiao** [continuedev/continue#1747]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I have a lot of different projects, written in different languages, using different library dependencies. Ideally, I shouldn't have to scroll through dozens of docs for libraries that are not used in my project workspace. And I should be able to add docs to a workspace without having to re-add them every time I restart my IDE. 

### Solution

Add @docs urls directly in .continuerc.json (or ~/.continue/config.json).

**Comment by edenbuaa** [comment]
meet the same problem! Is there a way to remove some specific doc?

**Comment by Patrick-Erichsen** [comment]
@saosebastiao This was actually introduced in #1594 by @priyashpatil ! The docs site just hasn't been updated yet. If you're on the latest pre-release, here's an example of how you can configure this: https://github.com/continuedev/continue/pull/1594/files#diff-0e8f644283d0b94f9e49baac14466f80bad05c2e177cedaaad22ad45097fb11aR61-R82

@edenbuaa currently you can't delete pre-indexed docs, but you can delete any doc that you create through either the UI or configuration. Appreciate the feedback though!

https://github.com/continuedev/continue/commit/d9f0c4f131010bd4dae111b5e4290f3460d49e3a#diff-0a3d028e022ca75b17b9fd2bb8172022386cce823c103c43d7a4bd0611808bfaR19
