### ISSUE TITLE
Support bedrock imported model endpoints.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [continuedev/continue#1749]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Connect to the imported models hosted in AWS bedrock.

### Solution

https://docs.aws.amazon.com/bedrock/latest/userguide/model-customization-import-model.html allowed to import the models into AWS bedrock and host them there.  The model id is in the form of the arn such as arn:aws:bedrock:us-west-2:XXXXXXX:imported-model/XXXX.  The config json using that model id fails with the error: Failed to load resource: the server responded with a status of 404 ().

When the model Id use example with the cli that works:
```
aws bedrock-runtime invoke-model \    
    --model-id arn:aws:bedrock:us-west-2:XXXX:imported-model/XXX \
    --body '{"prompt": "\n\nHuman: story of two dogs\n\nAssistant:", "max_tokens_to_sample" : 300}' \
    --cli-binary-format raw-in-base64-out \
    invoke-model-output.txt
```

**Comment by mattijsdp** [comment]
Same issue, the error I get is simply a regex validation error. I expect the use of Bedrock imported models vs Bedrock foundational models to be the same so this fix could be very simple if that is true.
```code
ValidationException: 1 validation error detected: Value 'arn:aws:bedrock:us-east-1:235623703621:imported-model/jw8254ccsftz' at 'modelId' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:provisioned-model/[a-z0-9]{12})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|(([0-9a-zA-Z][_-]?)+)|(arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{1,20}):(|[0-9]{12}):model-gateway/[a-zA-Z0-9-:.]+)|([a-zA-Z0-9-:.]+)
```

**Comment by mikhail-khodorovskiy** [comment]
As we are capable of importing all kinds of models into Bedrock, can those models be configured to be used for embeddings and autocomplete trying to achieve the best experience as described here: https://docs.continue.dev/setup/configuration#best-overall-experience.

**Comment by chezsmithy** [comment]
This should be marked as resolved.

**Comment by shrijayan** [comment]
```
aws bedrock-runtime invoke-model \
    --model-id XXXX \
    --body '{"prompt": "\n\nHuman: story of two dogs\n\nAssistant:", "max_tokens_to_sample" : 300}' \
    --cli-binary-format raw-in-base64-out \
    invoke-model-output.txt

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: --body, --model-id

zsh: command not found: --model-id
```

**Comment by shrijayan** [comment]
Provided region_name 'XXXX' doesn't match a supported format.
