### ISSUE TITLE
Jetbrains plugin broke on 0.0.54

### ISSUE THREAD

**Issue by Martmists-GH** [continuedev/continue#1759]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Arch Linux
- Continue: 0.0.54
- IDE: IntelliJ 2024.2
- Model: N/A
- config.json:
  
{
  "models": [
    {
      "title": "LM Studio",
      "provider": "lmstudio",
      "model": "lmstudio-community/CodeLlama-7B-KStack-GGUF"
    },
    {
      "title": "KoboldCPP",
      "provider": "openai",
      "model": "KStack-GGUF",
      "apiKey": "EMPTY",
      "apiBase": "http://localhost:5000/v1",
      "contextLength": 16384
    }
  ],
  "tabAutocompleteModel": {
    "title": "KoboldCPP",
    "provider": "openai",
    "model": "KStack-GGUF",
    "apiKey": "EMPTY",
    "apiBase": "http://localhost:5000/v1",
    "contextLength": 16384,
    "completionOptions": {
      "stop": ["<PRE>", "<SUF>", "<MID>", "\n@"]
    }
  },
  "tabAutocompleteOptions": {
    "template": "<PRE> {{{prefix}}} <SUF> {{{suffix}}} <MID>"
  }
}
```

### Description

The following pops up:

Core process exited with output: /snapshot/continue/binary/out/index.js:50886 throw e3; ^  Error: /home/mart/.local/share/JetBrains/IntelliJIdea2024.1/continue-intellij-extension/core/build/Release/node_sqlite3.node: invalid ELF header at process.dlopen (pkg/prelude/bootstrap.js:2251:28) at Module._extensions..node (node:internal/modules/cjs/loader:1196:18) at Module.load (node:internal/modules/cjs/loader:988:32) at Module._load (node:internal/modules/cjs/loader:834:12) at Module.require (node:internal/modules/cjs/loader:1012:19) at Module.require (pkg/prelude/bootstrap.js:1851:31) at require (node:internal/modules/cjs/helpers:102:18) at bindings (/snapshot/continue/binary/out/index.js:50879:54) at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (/snapshot/continue/binary/out/index.js:50951:41) at __require (/snapshot/continue/binary/out/index.js:18:51) { code: 'ERR_DLOPEN_FAILED' }  Node.js v18.5.0

### To reproduce

Install the plugin

### Log output

```Shell
The file is empty.
```

**Comment by Martmists-GH** [comment]
Running `file /path/to/node_sqlite3.node` returns `/home/mart/.local/share/JetBrains/IntelliJIdea2024.1/continue-intellij-extension/core/build/Release/node_sqlite3.node: Mach-O 64-bit arm64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>`

It seems the bundled sqlite3 binary is built for macOS ARM64, but I'm on Linux x64.

**Comment by sestinj** [comment]
@Martmists-GH We've since made a few updates to the extension. Are you still seeing this on the latest version?

**Comment by nielskool** [comment]
i have the same error. just installed pycharm 2024.1.6
continue via the plugin marketplace in pycharm.
![image](https://github.com/user-attachments/assets/cd4817db-b56f-4828-81a0-1501832b6a2e)

**Comment by sestinj** [comment]
This should now be solved in the latest version
