### ISSUE TITLE
Editing highlighted code does not support chinese.

### ISSUE THREAD

**Issue by facelezzzz** [continuedev/continue#1767]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
windows 11
- Continue:
0.0.55
- IDE:
IntelliJ IDEA 2024.1.2 (Community Edition)
Build #IC-241.17011.79, built on May 22, 2024


Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- Model:
qwen2:7b
- config.json:
  
{
  "models": [
    {
      "title": "qwen2:7b",
      "provider": "ollama",
      "model": "qwen2:7b",
      "apiBase": "http://127.0.0.1:11434"
    }
  ],
  "contextProviders": [
    {
      "name": "docs"
    },
    {
      "name": "codebase"
    },
    {
      "name": "folder"
    },
    {
      "name": "tree"
    },
    {
      "name": "open"
    }
  ],
  "tabAutocompleteModel": {
    "title": "starcoder2",
    "provider": "ollama",
    "model": "starcoder2:3b",
    "apiBase": "http://127.0.0.1:11434"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text:latest",
    "apiBase": "http://127.0.0.1:11434"
  },
  "allowAnonymousTelemetry": false
}
```

### Description

see pic

![image](https://github.com/user-attachments/assets/6cc1d1ff-3a4b-4938-9e63-88a411f467a3)

### To reproduce

1.open Editing highlighted code with ctrl+i
2.type some chinese

**Comment by Yoenl** [comment]
It seems the default font (Arial) used by Continue does't support Chinese display, build the plugin locally and change font to Microsoft YaHei solved my problem.

**Comment by facelezzzz** [comment]
So, simply changing the font to one that supports Chinese characters is sufficient.

**Comment by facelezzzz** [comment]
`    fun makeTextArea(): JTextArea {
        val textArea = CustomTextArea( 2, 40).apply {
            lineWrap = true
            wrapStyleWord = true
            isOpaque = false
            background = GetTheme().getSecondaryDark()
            maximumSize = Dimension(400, Short.MAX_VALUE.toInt())
            margin = JBUI.insets(8)
            font = Font("Arial", Font.PLAIN, MAIN_FONT_SIZE)
        }
        textArea.putClientProperty(UIUtil.HIDE_EDITOR_FROM_DATA_CONTEXT_PROPERTY, true)

        return textArea
    }`

**Comment by yshi2fp** [comment]
Why is Intellij IDEA in macOS free from this issue? Does the "Arial" font in macOS contain Chinese?

**Comment by SuperKevinZhang** [comment]
How to build the plugin locally and change the font ?

**Comment by sestinj** [comment]
I believe this is now resolved as of this PR from a contributor: https://github.com/continuedev/continue/pull/2066.

I'm closing the issue as it now appears to work for me, but if anyone is still experiencing the problem in 0.0.65+ please re-open!
