### ISSUE TITLE
add github repo as doc should support .mdx files

### ISSUE THREAD

**Issue by jueinin** [continuedev/continue#1768]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

https://vscode.dev/github/continuedev/continue/blob/main/core/indexing/docs/crawl.ts#L56  

 maybe this line can add a .mdx check ?

**Comment by Patrick-Erichsen** [comment]
Good idea, and you are correct, just a simple one-line change! https://github.com/continuedev/continue/commit/d9f0c4f131010bd4dae111b5e4290f3460d49e3a#diff-0a3d028e022ca75b17b9fd2bb8172022386cce823c103c43d7a4bd0611808bfaR19

This will ship in the next pre-release.
