### ISSUE TITLE
Indexing with an embeddings provider spends most of its time in countTokens(...)

### ISSUE THREAD

**Issue by spew** [continuedev/continue#1775]
### Validations

- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I've done some profiling of the indexer when using the HuggingFace Embeddings provider as it can take a long time on large repos. Much of the time is spent on calling `countTokens(...)`, I believe to break up the number of tokens sent in an embed request. 

### Solution

I have a change I've made to use node.js `workerpool` to create a pool of workers which have a single function of `countTokens`. I saw a much reduced number of `Extension host (LocalProcess pid: <>) is unresponsive` messages from the VSCode developer console after implementing this. It also made indexing a bit faster (about 30%), however, there were other places in the code that blocked and didn't send enough parallel work into `countTokens(...)` to get what i think would be the full improvement value.

This change is a bit complicated and may not be the direction you would like to go in, but I can post a PR if you are interested. No hard feelings if we don't like the approach or potentially a modified version of the approach could work.

**Comment by Patrick-Erichsen** [comment]
We would definitely welcome a PR for this! Excited to see the work.

**Comment by spew** [comment]
Have submitted https://github.com/continuedev/continue/pull/1842 for this issue
