### ISSUE TITLE
Model Reloading and Excessive VRAM Usage Issues with Ollama Backend in VSCode and IDEA

### ISSUE THREAD

**Issue by ALEX000V** [continuedev/continue#1776]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 23H2
- Continue: v0.8.43 / v0.0.55
- IDE: VSCode 1.91.1 / IntelliJ IDEA 2024.1.4 (Community Edition)
- Model: deepseek-coder-v2:16b-lite-instruct-q4_0 
- ollama: v0.2.7
- CUDA: V12.3.103
- config.json:
  
{
  "models": [
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    },
    {
      "title": "deepseek-coder-v2:16b",
      "provider": "ollama",
      "model": "deepseek-coder-v2:16b",
      "apiBase": "http://localhost:11434"
    }
  ],
  "tabAutocompleteModel": {
    "title": "deepseek-coder-v2:16b",
    "provider": "ollama",
    "model": "deepseek-coder-v2:16b"
  },
  "allowAnonymousTelemetry": false
}

```

### Description

**Description:**
I am encountering two distinct but related issues when using the Continue plugin in VSCode and IDEA  with Ollama as the backend for model processing. The first issue involves models being repeatedly loaded and unloaded when accessed through different interfaces, and the second issue pertains to abnormal VRAM usage when models are accessed via the Continue plugin compared to other methods.

**VRAM Changes Example:**

When `OLLAMA_NUM_PARALLEL` is set to 4, after loading the `deepseek-coder-v2:16b-lite-instruct-q4_0` model using the Continue plugin, executing `ollama run deepseek-coder-v2:16b-lite-instruct-q4_0` via the command line, and then sending information to the model using the Continue plugin again.

![vram_load](https://github.com/user-attachments/assets/0c11355e-3107-464e-bd5e-c55594c66bb7)

### To reproduce

**Issue 1: Model Reloading**
- **Steps to Reproduce:**
  1. Open VSCode/IDEA and activate the Continue plugin.
  2. Use the Continue plugin to send a request to Ollama to load a specific model.
  3. Attempt to access the same model via another non-Continue plugin method (e.g., command line, another plugin, or web UI).
  4. Observe that the model is unloaded and then reloaded, rather than being reused from memory.
  5. Alternatively, first load the model using a non-Continue plugin method, then attempt to access it via the Continue plugin.
  6. Observe that the model is again unloaded and then reloaded.
- **Expected Behavior:**
  Once a model is loaded by any interface, it should be accessible by all other interfaces without needing to be reloaded.
- **Actual Behavior:**
  Each time the model is accessed through a different (Continue vs. non-Continue) interface, it is unloaded and then reloaded.

**Issue 2: Excessive VRAM Usage**
- **Steps to Reproduce:**
  1. Use the Continue plugin to load a model (e.g., `deepseek-coder-v2:16b-lite-instruct-q4_0`).
  2. Compare the VRAM usage with the same model loaded via other methods (e.g., command line, other plugins, or web UI).
  3. Observe that the VRAM usage is significantly higher when using the Continue plugin.
- **Expected Behavior:**
  The VRAM usage should be consistent regardless of the method used to load the model.
- **Actual Behavior:**
  The VRAM usage is higher when using the Continue plugin compared to other methods. For example, with each increment of `OLLAMA_NUM_PARALLEL` by 1, the command line method adds 0.6GiB, while the Continue plugin adds 1.2GiB.

**Comment by ALEX000V** [comment]
Setting the context size in the continue plugin to align with the Ollama backend can resolve the issue, for example, to the default 2048.

    {
      "title": "Ollama",
      "provider": "ollama",
      "contextLength": 2048,
      "model": "AUTODETECT"
    },

**Comment by gzzzzzd** [comment]
Same Issue, but not working with {
  "title": "Ollama",
  "provider": "ollama",
  "contextLength": 2048,
  "model": "AUTODETECT"
},
