### ISSUE TITLE
please add image capability field on model config

### ISSUE THREAD

**Issue by jueinin** [continuedev/continue#1789]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently, which models support images is hardcoded in https://vscode.dev/github/continuedev/continue/blob/dev/core/llm/autodetect.ts#L60-L73. However, many models are not included in this list, such as Qwen, Moonshot, ChatGLM, etc. It seems that we could add a configuration item in config.json like imageCapability: boolean, similar to the following:

```json
{
  "models": [{
    "title": "chatglm",
    "provider": "openai",
    "model": "chatglm",
    "apiKey": "sk-xxx",
    "apiBase": "https://xxxx/v1",
    "imageSupport": true
  }]
}
```

### Solution

add a imageSupport config field

**Comment by jueinin** [comment]
also it's better to support paste a image to editor

**Comment by jueinin** [comment]
maybe https://vscode.dev/github/continuedev/continue/blob/dev/core/llm/autodetect.ts#L86 this line add a extra check?
if model name is not on the list && image support is false

**Comment by Patrick-Erichsen** [comment]
@sestinj what are your thoughts here? Ideally we keep an up-to-date list to avoid manual config work for the user but that may prove to be difficult to maintain.

**Comment by jueinin** [comment]
And i have tried make a custom model, but it still not work because the custom model is not on white list too. So can not use image

**Comment by sestinj** [comment]
@jueinin I think this is a model that we would want added to our list of models that support images. Would you be interested in making a PR to update the modelSupportsImages function?

**Comment by Altroo** [comment]
How you can add image support if your model support it.
`{
      "title": "Llama 3.0",
      "provider": "openai",
      "model": "xxx",
      "apiKey": "xxx",
      "capabilities": {
        "uploadImage": true
      }
    },`

**Comment by 0xIslamTaha** [comment]
```yaml
models:
  - name: Autodetect
    provider: lmstudio
    model: AUTODETECT
    apiBase: http://192.168.0.116:1234/v1/
    capabilities:
      - tool_use
      - image_input
```
