### ISSUE TITLE
ContinueInputBox how to support Tooltip Menu like ant deisgn's AutoComplete ?

### ISSUE THREAD

**Issue by minicloudsky** [continuedev/continue#1794]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The [ContinueInputBox](https://github.com/continuedev/continue/blob/main/gui/src/components/mainInput/ContinueInputBox.tsx) developed with Tiptap Editor,I use continue to develop my custom jetbrains plugin, will Continue support Tooltip menu in the future ? for example,when i type  "/" in the input box,the box will show some menus like above the input box:
* /explain
* /optimize
* /generate unit tests
* /help
The tooltip menu looks like Ant Deisgn's [AutoComplete](https://ant-design.antgroup.com/components/auto-complete) Component, or how can i build as custom tooltip menu with ContinueInputBox? I will appreciate if any suggestions or docs, projects~

**Comment by Patrick-Erichsen** [comment]
Hi @minicloudsky , it sounds like you are trying to create a custom slash command that shows up in the editor when you type `/`? If so, you can create on following the docs here: https://docs.continue.dev/customization/context-providers#building-your-own-context-provider

**Comment by minicloudsky** [comment]
> Hi @minicloudsky , it sounds like you are trying to create a custom slash command that shows up in the editor when you type `/`? If so, you can create on following the docs here: https://docs.continue.dev/customization/context-providers#building-your-own-context-provider

Yes,I'm creating the slash command when user typed `/`,Thanks for your kindness help~

**Comment by minicloudsky** [comment]
> Hi @minicloudsky , it sounds like you are trying to create a custom slash command that shows up in the editor when you type `/`? If so, you can create on following the docs here: https://docs.continue.dev/customization/context-providers#building-your-own-context-provider

I sloved it with [tippy.js](https://atomiks.github.io/tippyjs/) menu,With [tiptap's slash command](https://codesandbox.io/p/sandbox/tiptap-react-slash-command-e3j3u?),Thanks for your solution~
