### ISSUE TITLE
Need function like `ide.listWorkspaceContents(workspaceDir)`

### ISSUE THREAD

**Issue by Mrzyxing** [continuedev/continue#1822]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

As mentioned on Discord, is here any replacement for `ide.listWorkspaceContents(workspaceDir)`?
Really need this to dev some custome context provider !
![image](https://github.com/user-attachments/assets/a5086536-8dac-424e-bf82-ce862e08029d)

### Solution

Add a function that return a list of file and directories of path .

**Comment by Mrzyxing** [comment]
Looks like version `0.8.43-vscode` have `listDir()` in `core/index.d.ts` but missed on my local `~/.continue/types/core/index.d.ts` whatever reinstall via online or vsix file.

**Comment by Patrick-Erichsen** [comment]
Hey @Mrzyxing , thanks for following up here.Unfortunately the IDE does not have any functionality to list all files and directories of a path, but I do believe you should be able to use the `getWorkspaceDirs()` method along with a library like https://www.npmjs.com/package/walkdir.

**Comment by Mrzyxing** [comment]
> Hey @Mrzyxing , thanks for following up here. Unfortunately the IDE does not have any functionality to list all files and directories of a path, but I do believe you should be able to use the `getWorkspaceDirs()` method along with a library like https://www.npmjs.com/package/walkdir.

Thanks a lot, just a newer of frontend so here a lot of beginner's questions.I worked fine with `walkdir` after your suggustion.Thanks again!
