### ISSUE TITLE
Add support for WatsonX provider/model

### ISSUE THREAD

**Issue by rishacha** [continuedev/continue#1823]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

We want to use WatsonX Models with continue.dev. There's already some work done [here](https://github.com/NoeSamaille/continue-watsonx/tree/main). We want to add it to the documentation and add in-built support for the same.

### Solution

We have already created a sample solution with an extension of the `BaseLLM` class. Will be referencing it as a PR if it's okay.

**Comment by sestinj** [comment]
@rishacha that's great work in your fork! Would be very excited to make WatsonX a first-class model in Continue—looking forward to the PR!

**Comment by rishacha** [comment]
@sestinj  - Closing this since PR has been merged ✅
