### ISSUE TITLE
Update Groq.ts file for llama 3.1

### ISSUE THREAD

**Issue by mozeryansky** [continuedev/continue#1829]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

https://github.com/continuedev/continue/blob/main/docs/docs/walkthroughs/llama3.1.md

https://github.com/continuedev/continue/blob/main/core/llm/llms/Groq.ts

### Description

The walkthrough mentions the new model, but it also needs to be added to the type definition to VSCode stop complaining.

<img width="922" alt="Screen Shot 2024-07-24 at 11 21 39 PM" src="https://github.com/user-attachments/assets/f811681d-32a5-4377-855b-87c7471a966b">

Also:
"Note: Early API access to Llama 3.1 405B is currently only available to paying customers - stay tuned for general availability. During preview launch, we are limiting all 3.1 models to max_tokens of 8k and 405b to 16k input tokens."
https://console.groq.com/docs/models

**Comment by sestinj** [comment]
@mozeryansky this is solved in pre-release: https://github.com/continuedev/continue/blob/nate/oai-adapters/extensions/vscode/config_schema.json#L968-L969

I'm going to close the issue since we'll be merging this soon
