### ISSUE TITLE
VSCode Telemetry non-compliance 

### ISSUE THREAD

**Issue by Yanpas** [continuedev/continue#1832]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
doesn't matter
```

### Description

Dear team,

Continue is a great free and open-source extension, however there's a small compliance issue regarding telemetry. According to Microsoft's "Telemetry extension authors guide":

> Extension authors who wish not to use Application Insights can utilize their own custom solution to send telemetry. In this case, it is still required that extension authors respect the user's choice by utilizing the isTelemetryEnabled and onDidChangeTelemetryEnabled API. By doing this, users will have one centralized place to control their telemetry settings

Digging through a codebase I haven't found any reference to `env.isTelemetryEnabled` and `env.onDidChangeTelemetryEnabled`. 

PS Gitlens does a good job on that with settings' note:
![image](https://github.com/user-attachments/assets/9f433b4c-7f4f-493f-8b71-ceb10c1fd6cd)

References:
https://code.visualstudio.com/docs/getstarted/telemetry#_for-extension-authors
https://code.visualstudio.com/api/extension-guides/telemetry

**Comment by sestinj** [comment]
I did not know about this, thank you for pointing it out. Fix made here: https://github.com/continuedev/continue/commit/99f50fc5f3999ee683477f9de44220c1dc4ef9eb
