### ISSUE TITLE
SQLITE_CONSTRAINT: UNIQUE constraint failed: global_cache. cacheKey, global_cache. dir, global_cache. branch, global_cache. artifactId]

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#1840]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: 
- Continue: 0.0.56 JetBrains, recent VS Code pre-releases (e.g. 0.9.188)
- IDE:
- Model:
- config.json:
```

### Description

Some users are receiving the error in the title while indexing after upgrading from previous version of Continue.

The unique constraint was introduced here: https://github.com/continuedev/continue/pull/1795/files#diff-b1fd84889028918892926feb0f8dd8c5f5b574119374d8efd474fb9438430b6aR47-R76

### User reports
https://discord.com/channels/1108621136150929458/1156679146932535376/1266320982809903186

### To reproduce

Not exactly sure when/how users are experiencing this. I need to pinpoint which versions for VS Code/JetBrains this change was introduced. 

The issue arises when attempting to insert new rows into the DB while indexing, e.g. on load, adding docs, etc.

### Log output

```Shell
Core process exited with output: .................continue\out\config. js 1.1kb .................continue\out\config. js. map 266b  Done in 4ms node:internal/ process/ promises:288 triggerUncaughtException(err, true /* fromPromise */); ^  [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: global_cache. cacheKey, global_cache. dir, global_cache. branch, global_cache. artifactId] { errno: 19, code: 'SQLITE_CONSTRAINT' }  Node. js v18.5.0
```

**Comment by Patrick-Erichsen** [comment]
Hey @joshvera, curious if you ran into this error at all? @sestinj and I ran into it a few times locally when switching between branches but I had assumed that for the regular user flow the deduplication logic you had [here](https://github.com/continuedev/continue/pull/1795/files#diff-b1fd84889028918892926feb0f8dd8c5f5b574119374d8efd474fb9438430b6aR47-R65) would prevent unique constraint errors. 

We haven't had any user reports from VS Code of this issue yet, so I'm wondering if for some reason that code path isn't being invoked in JetBrains.

**Comment by joshvera** [comment]
I didn't. I'd be surprised if the codepath isn't triggering, otherwise I assume the tables wouldn't exist to begin with.

The easiest solution would be to turn `INSERT INTO global_cache` into a `REPLACE OR INSERT INTO global_cache`, but it appears there's an old tag in global cache, and application logic calling the `GlobalCacheCodeBaseIndex.update` method is giving it a tag to add before removing.

The issue could also be the following:

```typescript
await Promise.all([
      ...remove.map(({ cacheKey }) => {
        return this.deleteOrRemoveTag(cacheKey, tag);
      }),
      ...add.map(({ cacheKey }) => {
        return this.computeOrAddTag(cacheKey, tag);
      }),
    ]);
 ```
 
 Which resolves adds and removes concurrently. If we add before we remove, then we'd see this issue. I'd check here first.
 
 AFK today, so I can't look into it but I can take a look tomorrow if it's not too pressing. I'd try removing `Promise.all` first and serializing those calls.

**Comment by levdad** [comment]
I have this error as well.
It happens when using both VS Code and Rider (in my case).
The indexing will crash and sometimes will even break Rider.
The workaround I found is to delete the cache and reopen only one IDE.

**Comment by Patrick-Erichsen** [comment]
Thanks for the writeup @joshvera - I'm leaning towards just making the `REPLACE OR INSERT INTO global_cache` change. The concurrent add/remove logic feels like it could be the culprit but even if it is, I think the upsert is a good solution to avoid anything similar in the future. 

@levdad , I will circle back here once we get this pushed to pre-release. Please let me know if you continue to have issues once you upgrade.

**Comment by JulianGerhard21** [comment]
Hi,

I am also experiencing this issue leading to an unusable plugin.

Is there a way to use the merged solution in Webstorm/JetBrains in general or do I have to wait for a new release? If so, when should I expect the latter?

Kind regards
Julian

**Comment by songcee** [comment]
已收到你的邮件，谢谢~~~

**Comment by levdad** [comment]
@Patrick-Erichsen do we need to update both plugins to prerelease?
Could you let us know which versions to install?

**Comment by sskorol** [comment]
JB plugin is still broken.
![Screenshot from 2024-08-03 14-17-47](https://github.com/user-attachments/assets/c3304cc7-e071-4753-831a-dfdb86ea17b7)

**Comment by sskorol** [comment]
Nevermind, it's easier to build it from sources... FIY, the issue is fixed in the dev branch.

**Comment by JulianGerhard21** [comment]
@Patrick-Erichsen - will there be a new version of the plugin for the JetBrains Suite at all?

**Comment by songcee** [comment]
已收到你的邮件，谢谢~~~
