### ISSUE TITLE
Could you clarify if there are plans for this project to support Eclipse?

### ISSUE THREAD

**Issue by 9cren** [continuedev/continue#1886]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Could you clarify if there are plans for this project to support Eclipse?

**Comment by sestinj** [comment]
Yes! Our current plans are to focus on JetBrains and VS Code until we are confident we've built the best experience possible and then we will begin to support as many other IDEs once we have bandwidth. I don't currently have an estimate of when this will be, but we do plan to support Eclipse at some point.

There are more details in this issue (https://github.com/continuedev/continue/issues/702) and I want to make sure that all Eclipse interest is reflected in a single issue, so I'm going to close this issue in favor of that one.
