### ISSUE TITLE
Update gpt 3.5 references to gpt 4o mini in docs 

### ISSUE THREAD

**Issue by priyashpatil** [continuedev/continue#1888]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Some tiny remark for https://docs.continue.dev/setup/select-model docs, I believe you can consider changing 3.5 turbo in favor to gpt-4o mini which sounds smart (reasoning, math, coding), reasonably fast and one of the cheapest

https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/
https://artificialanalysis.ai/models/gpt-4o-mini/providers

https://discord.com/channels/1108621136150929458/1156679146932535376/1268554290704814162

**Comment by sestinj** [comment]
Good call, just made the quick update: https://github.com/continuedev/continue/commit/3cf010171e2b7c91e8e5b35858d3551256a5fa8c
