### ISSUE TITLE
Continue on Zed.

### ISSUE THREAD

**Issue by Fastiraz** [continuedev/continue#1889]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Firstly, I love Continue!
But sadly, I'm not using VSCode or JetBrains.
Instead, I'm using Zed. It's an open source text editor written in rust available on macOS and Linux.

https://zed.dev/

### Solution

It would be amazing to have a version of Continue available on Zed!
I haven't found your roadmap and I don't know if Continue will be implemented on Zed.

You can find Zed's roadmap for extensions here: https://zed.dev/roadmap

By the way, if you don't have a public roadmap, it would be nice to have one to track your progress.

**Comment by sestinj** [comment]
Thanks for the suggestion! Right now our plan is to focus on JetBrains and VS Code to really get the experience right, and then once bandwidth allows we will expand to as many other editors as possible. For anyone who comes along this issue and wants Continue in Zed, please give a thumbs up—we'll take note of this when deciding what to prioritize!

Separately, while we won't be building a first-class extension right away, if anyone has interest in attempting to integrate Continue's autocomplete, we would potentially be open to contributions
