### ISSUE TITLE
What dataServerUrl does？

### ISSUE THREAD

**Issue by sc-lj** [continuedev/continue#1891]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I want to synchronize the call logs of the various members of the team together. How do I configure this dataServerUrl so that the back end that accepts the data should accept the data?
![image](https://github.com/user-attachments/assets/65d74e4a-05dc-4a81-9fac-4ba58a9de336)

**Comment by Patrick-Erichsen** [comment]
Hi @sc-lj , apologies but it looks like that configuration option isn't actually implemented anymore. I've updated the docs to remove that here: https://github.com/continuedev/continue/pull/1897

I believe we've moved this functionality into our [teams product](https://www.continue.dev/enterprise). 

CC @sestinj for more context however.

**Comment by sestinj** [comment]
This is in fact legacy—thanks Patrick for cleaning that up. Will close the issue now, but @sc-lj let me know if it would be okay to email you about this feature, we'd love to hear more about what you're looking for
