### ISSUE TITLE
Add a parameter for the commit slash command to only run on staged changes

### ISSUE THREAD

**Issue by FozzieHi** [continuedev/continue#1893]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I'd like to run the `/commit` slash command only on staged changes, as opposed to all changes which is the current behaviour.

### Solution

Add a boolean parameter to the commit slash command called `stagedOnly`. If true, include only the staged changes; If false, include both staged and unstaged changes. I'm happy to create a PR with this functionality.

**Comment by priyashpatil** [comment]
I don't use the `/commit`, My current workaround is "CMD+Shift+P" -> "Git: commit staged" -> "CMD+I" -> "Write commit using conventional commit standards":

![Screenshot 2024-08-02 at 4 43 29 PM](https://github.com/user-attachments/assets/5560af88-125d-43a2-bff4-60eb0b216ffd)

**Comment by Patrick-Erichsen** [comment]
Neat workflow @priyashpatil ! This could be a neat [custom quick action](https://docs.continue.dev/features/quick-actions#custom-quick-actions), although I'm unsure if there is a LSP extension for git files like this that we would need.

@FozzieHi - thanks for calling this out. I think if anything the default behavior should be to only generate the commit off of staged changes, and then we could add a param to optionally include unstaged changes. If we made that change, I think we would want to provide some sort of helpful feedback to the user in the scenario where they attempt to generate a commit but haven't staged any changes.

We would definitely welcome a PR if you're interested in taking this on!

**Comment by FozzieHi** [comment]
@Patrick-Erichsen Sounds good. I did assume it was only doing staged changes to begin with until I started to realise it was writing about unstaged changes as well. I do have a demo running locally, I'll just swap around the params and create a PR.

**Comment by Patrick-Erichsen** [comment]
Excellent, looking forward to the PR!
