### ISSUE TITLE
DeepSeek v2 API FIM Completion Support

### ISSUE THREAD

**Issue by razorback16** [continuedev/continue#1895]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

DeepseekCoder has launched a new FIM completion API. You can find the [DeepSeek v2 FIM API Documentation here](https://platform.deepseek.com/api-docs/fim_completion).

I tested the API with the legacy OpenAI completions but noticed that it doesn't utilize the suffix parameter for completions as expected. Instead, it employs FIM tokens, which aren't necessary for this API. Additionally, I occasionally observed incorrect completions during my testing.

DeepSeek Coder v2 is incredibly effective, and the API is quite affordable. Integrating support for the DeepSeek API in ContinueDev could be a significant enhancement and a potential game-changer.

**Comment by fry69** [comment]
FIM support for DeepSeek Coder V2 is` already available in Pre-Release versions, see -> https://github.com/continuedev/continue/pull/1863
