### ISSUE TITLE
Quick edit takes ~6 seconds to open

### ISSUE THREAD

**Issue by powellnorma** [continuedev/continue#1908]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: linux
- Continue: v0.8.44
- IDE: 1.91.1
- Model: Remote Inference
- config.json:
  
{
  "models": [
    {
			// remote inference API
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "disableIndexing": true,
}
```

### Description

When first opening Quick-Edit or the sidebar (via ctrl+shift+l) it takes 6-10 seconds to show up. Note that I don't have the Continue Sidebar open beforehand.

### To reproduce

1. Have Continue Sidebar closed
2. Close VSCode and reopen it
3. Use Shortcuts for Quick-Edit or Sidebar - It takes 6-10s

### Log output

```Shell
Nothing relevant shows up
```

**Comment by fry69** [comment]
Try switching to Pre-Release 0.9.193, there has been extensive work done to fix this problem, see the last comments in this issue -> https://github.com/continuedev/continue/issues/1705#issuecomment-2266651307

**Comment by powellnorma** [comment]
> Try switching to Pre-Release 0.9.193

Still happens there, unfortunately

**Comment by fry69** [comment]
Even after a full restart of VSCode?

**Comment by powellnorma** [comment]
> If so, please try with a fresh ~/.continue directory, where you only copy your config.json back in (to rule out other problems with stale data etc).

Tried that now, the lag still occurs. Note that if continue is already open (on the right via ctrl+shift+l), Quick Edit works instantly, without the lag. Even when I close it (the continue sidebar) again, it keeps working normally. But when I do "Developers: Reload window", the lag occurs again.

**Comment by fry69** [comment]
> But when I do "Developers: Reload window", the lag occurs again.

This sounds like it could be a problem with an API, can you please post your full `config.json`? (without API keys of course)

**Comment by powellnorma** [comment]
> This sounds like it could be a problem with an API

Hm, I was wondering this too. Does just opening the sidebar / quick-edit would not result in an API call to the inference API? If yes, why so?

I am using togetherAi. The chat inference has no delay currently (tested via https://get.big-agi.com/, same API-key) - But maybe continue uses some other API (e.g. to fetch available models or something)?

Here is my complete config:

```
{
  "models": [
    {
      "title": "Together Llama-3.1-405B",
      "provider": "together",
      "model": "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
      "apiKey": ""
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "disableIndexing": true,
  "allowAnonymousTelemetry": false,
  "docs": []
}
```

**Comment by powellnorma** [comment]
> If you want, can you please try my config.json from above (verbatim, with empty API keys)?

Just did so, while opening VSCode in a directory with just this file:

just-some-code.py
```
print("hello world")
```

And the lag still occurred.

[..] Ok now I even tried it witih a fresh ~/.vscode, and just installed the continue addon. But it still happened (this time tried ctrl+shift+L, which lags as well). It shows an error `Error: SQLITE_ERROR: no such column: baseUrl`, not sure if relevant

![image](https://github.com/user-attachments/assets/cc3976e6-ab5b-418b-8d5d-e182c5223344)

**Comment by powellnorma** [comment]
Hm.. When I open the sidebar via 'View > open view > Continue", no lag occurs ..

**Comment by powellnorma** [comment]
I made a short screen-recording:



https://github.com/user-attachments/assets/b431a8f9-a152-48ee-9cfb-bc385545b56f

**Comment by fry69** [comment]
Your screenshot of the SQLite error and your other findings are helpful, thank you for testing and reporting. I'll try to reproduce.

**Comment by fry69** [comment]
So, here is what I tried to reproduce:

Moved my `~/.vscode` and `~/.continue` to a safe location and created those folders new.
Copied `config.json` back into `~/.continue`.
Started VSCode + installed Continue (0.8.44).
Opened the Linux kernel repository.
Pressed Cmd+I for Quick Edit and it opened without any lag.

My VSCode "About": 

```
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by fry69** [comment]
CORRECTION: I finally managed to reproduce the lag with the configuration from my last message!

The trick is to __NOT__ open the sidebar, then the lag occurs. Once the sidebar is opened, the lag vanishes. Terribly sorry for not getting this earlier.

(But at least we now have a really, really clean slate to investigate further)

**Comment by Patrick-Erichsen** [comment]
Closed with https://github.com/continuedev/continue/pull/1942/files

Issue was a default 5s wait on the sidebar to get the users default model they configure in the UI.

**Comment by fry69** [comment]
I can confirm that this issue is fixed in Pre-Release `0.9.145`.

**Comment by powellnorma** [comment]
For me, the delay is gone when opening "Quick Edit" - thank you!

However, when opening the sidebar, the delay is still there, as shown in the previous screencast: https://github.com/continuedev/continue/issues/1908#issuecomment-2267616244

**Comment by powellnorma** [comment]
@fry69 Can you reproduce https://github.com/continuedev/continue/issues/1908#issuecomment-2275885118

It's crucial that the sidebar was closed on start (e.g. close it, then "Developers: Reload window")

**Comment by fry69** [comment]
> @fry69 Can you reproduce [#1908 (comment)](https://github.com/continuedev/continue/issues/1908#issuecomment-2275885118)
> 
> It's crucial that the sidebar was closed on start (e.g. close it, then "Developers: Reload window")

I have several iterations and permutations of starting with closed sidebar, closing sidebar, "Reload Window", etc but I cannot produce this lag, nor have I ever noticed a lag when opening the sidebar (I am 100% sure about that, because that would have annoyed me in big way).

Let's try the other way around:
- use the most recent VSCode
- create a clean slate (move your `.vscode` somewhere safe)
- start VSCode, install Continue as your only extension
- use only the free Codestral API with this minimal `config.json`

```json
{
  "models": [
    {
      "apiKey": "[private]",
      "title": "Codestral",
      "model": "codestral-latest",
      "contextLength": 32000,
      "provider": "mistral"
    }
  ],
  "customCommands": [],
  "tabAutocompleteModel": {
    "apiKey": "[private]",
    "title": "Tab Autocomplete",
    "provider": "mistral",
    "model": "codestral-latest"
  }
}
```

Please report if this lag still happens then.

See here how to get a free API key for Codestral -> https://docs.continue.dev/walkthroughs/set-up-codestral

**Comment by powellnorma** [comment]
I did that (VSCode 1.19.1 though), even with clean `.config/Code`. It does not occur with ctrl+l, only with ctrl+shift+l (aka ctrl+L)

https://github.com/user-attachments/assets/f3121fa0-b0c2-4290-8573-fe6b0bbe0bec

**Comment by fry69** [comment]
I still cannot reproduce this lag, tried everything, restarting VSCode with closed sidebar, pressing CMD+L to open it / send selection to the sidebar, but no lag, ever.

I'm using this VSCode + Continue stable `0.8.45` for my tests ->
```
Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```
