### ISSUE TITLE
Automatically identify the project development language and framework versions

### ISSUE THREAD

**Issue by Geek-Bob** [continuedev/continue#1935]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When asked about LLM, if the programming language and framework version are not included, the generated code is completely wrong

### Solution

Automatically identify the project development language and framework version, and developers can also modify it themselves to avoid identification errors. This can greatly improve coding quality and efficiency. This is necessary because different languages and different framework versions result in different code implementations

**Comment by fry69** [comment]
As a workaround, you can give a LLM this information on a per project/workspace bases with a `.continuerc.json` file in the root of the workspace that contains a custom `systemMessage` property like this:

```json
{
	"systemMessage": "[tell the LLM languages/frameworks you use/prefer for this project here]"
}
```

This will get sent to the LLM on every request, see also -> https://docs.continue.dev/reference/config

**Comment by Geek-Bob** [comment]
Thank you very much, this seems to solve the problem, before the help document did not find relevant explanations and examples, I hope the blogger can enrich the help document of each configuration item descriptions and examples
