### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by Geek-Bob** [continuedev/continue#1937]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The interactive interface and LLM response languages support common languages such as English, Chinese, French, Russian, Spanish, and Arabic

### Solution

The interactive interface and LLM response languages support common languages such as English, Chinese, French, Russian, Spanish, and Arabic

**Comment by fry69** [comment]
Please try the workaround described here -> https://github.com/continuedev/continue/issues/1935#issuecomment-2270959446 for now.

You can tell the LLM the language it should use/respond with said `systemMessage` property in your `config.json` or per project `.continuerc.json` in the workspace root.
