### ISSUE TITLE
Expect the plugin to support Visual Studio 2022

### ISSUE THREAD

**Issue by Geek-Bob** [continuedev/continue#1953]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I used JetBrains to experience this plug-in in JAVA development, this plug-in is very useful, flexible and convenient, but with Visual Studio 2022 to develop c#, c++, c found this plug-in is not supported, very sad

### Solution

Expect the plugin to support Visual Studio 2022

**Comment by fry69** [comment]
Duplicate of https://github.com/continuedev/continue/issues/759
