### ISSUE TITLE
Add a way to allow users to reset indexes on failure

### ISSUE THREAD

**Issue by priyashpatil** [continuedev/continue#1991]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Recently, starting to get more sqlite errors on updates. It would be useful if there's indexing error related to sqlite to give an option to "rebuild indexing database".

**Comment by CXwudi** [comment]
I need this as well. It is very frustrating that the indexing kept failing even when I click the red icon to rebuild

**Comment by fry69** [comment]
Hope is on the way (already merged), praise @Patrick-Erichsen  -> https://github.com/continuedev/continue/pull/1993

**Comment by Patrick-Erichsen** [comment]
@fry69 thanks for the follow up here, forgot to link in the PR.
