### ISSUE TITLE
Inline chat (Ctrl+I) is not available, and it is not found in the shortcut settings.

### ISSUE THREAD

**Issue by imoyy** [continuedev/continue#2005]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 24H2
- Continue: v0.9.197
- IDE: VSCode 1.92.1
- Model: ALL
- config.json:
  ```json
{
  "models": [
    {
      "model": "gpt-4o-extended",
      "contextLength": 128000,
      "title": "GPT-4o",
      "provider": "openai",
      "apiBase": "**",
      "apiKey": "**"
    },
    {
      "model": "claude-3-5-sonnet",
      "contextLength": 200000,
      "title": "Claude 3.5 Sonnet",
      "provider": "openai",
      "apiBase": "**",
      "apiKey": "**"
    },
    {
      "model": "gemini-1.5-pro-latest",
      "title": "Gemini 1.5 Pro",
      "contextLength": 2000000,
      "apiKey": "**",
      "provider": "gemini"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "model": "deepseek-coder",
    "title": "Deepseek",
    "provider": "openai",
    "apiBase": "**",
    "apiKey": "**"
  },
  // "tabAutocompleteModel": {
  //   "title": "Codestral",
  //   "provider": "mistral",
  //   "model": "codestral-latest",
  //   "apiKey": "**"
  // },
  "embeddingsProvider": {
    "provider": "openai",
    "model": "voyage-large-2-instruct",
    "apiBase": "**",
    "apiKey": "**"
  },
  "reranker": {
    "name": "voyage",
    "params": {
      "model": "rerank-lite-1",
      "apiKey": "**"
    }
  },
  // "embeddingsProvider": {
  //   "provider": "openai",
  //   "model": "text-embedding-3-large",
  //   "apiBase": "**",
  //   "apiKey": "**"
  // },
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    { "name": "tree" },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 30,
        "nFinal": 5,
        "useReranking": true
      }
    },
    { "name": "url" }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    },
    {
      "name": "http",
      "description": "Does something custom",
      "params": { "url": "**" }
    }
  ],
  "experimental": {
    "quickActions": [
      {
        "title": "Detailed explanation",
        "prompt": "Explain the following code in detail, including all methods and properties.",
        "sendToChat": true
      }
    ]
  }
}

  ```

### Description

Everything works fine except for the inline chat triggered by Ctrl+I (see picture). I can't find any related settings for this shortcut key either.                                               
![image](https://github.com/user-attachments/assets/2f635465-29ff-4615-94f4-29b13f119c31)
![image](https://github.com/user-attachments/assets/306b825c-2694-44f4-87d5-21df6b3363e0)

### To reproduce

1. open the editor
2. Can't use Ctrl+I to bring up the chat.

**Comment by fry69** [comment]
Check if not other extension and VSCode extensions block Continue, see here for a list -> https://docs.continue.dev/features/tab-autocomplete#im-not-seeing-any-completions

You can also reverse search in the keybindings for a key press like `Ctrl+I` so see where it ends up currently, my guess is that something else grabs this with a higher priority than Continue.

**Comment by imoyy** [comment]
> Check if not other extension and VSCode extensions block Continue, see here for a check list -> https://docs.continue.dev/features/tab-autocomplete#im-not-seeing-any-completions检查是否有其他扩展和 VSCode 扩展阻止 Continue，请参见此处的检查列表 -> https://docs.continue.dev/features/tab-autocomplete#im-not-seeing-any-completions (ignore Ollama entries in this list if you are not using this) (如果您没有使用此功能，请忽略此列表中的 Ollama 条目）
> 
> You can also reverse search in the keybindings for a key press like `Ctrl+I` so see where it ends up currently, my guess is that something else grabs this with a higher priority than Continue.你也可以在按键绑定中反向搜索 `Ctrl+I` 这样的按键，看看它目前的最终位置，我猜是其他东西以比 Continue 更高的优先级抓取了它。

The issue is that I've already removed all the shortcuts bound to Ctrl+I, but the inline chat box still doesn't appear. Autocomplete is working fine though.

**Comment by imoyy** [comment]
> That is a bit strange. Maybe you can add the necessary keyboard shortcut manually?
> 
> * search for "generate code" in the keyboard setting dialog
> * click on the row to change the keyboard shortcut
> * press your shortcut combination (`Ctrl+I`)
> * make sure that the `When` column shows `-` so it will trigger always
> 
> To verify you can make a reverse keyboard search like this (with `"ctrl+i"` instead of my macOS `"cmd+i"` of course)
> 
> <img alt="shortcut" width="973" src="https://private-user-images.githubusercontent.com/142489379/357728479-2c67563f-e81a-42cc-9ec6-fb02df0dbc6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjcxMzYsIm5iZiI6MTcyMzYyNjgzNiwicGF0aCI6Ii8xNDI0ODkzNzkvMzU3NzI4NDc5LTJjNjc1NjNmLWU4MWEtNDJjYy05ZWM2LWZiMDJkZjBkYmM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGQ0NGQ3YjcyZmIxNDAwN2M5M2FhZGJjNTljN2M1Njk0ZmQ1MzFiNDMxNGJlMjcyN2YxMmQ5NGYzYWFjMDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2brlddBNrkdieCy83IfS6qDh_5BZhwn-wwEUl0QZryw">

I misunderstanding something? Is the continue plugin not yet able to do inline chat within VSCode like in the image, not just like what this command does to generate code？
![image](https://github.com/user-attachments/assets/e9935694-bea0-4957-9e67-c381e3ee0ba7)

**Comment by Patrick-Erichsen** [comment]
![Screenshot 2024-08-14 at 9 25 40 AM](https://github.com/user-attachments/assets/0cbfced2-2624-42cc-83b7-ce98bbf7503a)

Here is what Cmd+I should open up in VS Code. We don't have the ability to do true "inline chat" in VS Code since it isn't exposed through the API. 

I am not sure what extension would be triggering the other inline chat, but you could attempt a bisect to determine: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by imoyy** [comment]
> ![Screenshot 2024-08-14 at 9 25 40 AM](https://private-user-images.githubusercontent.com/20157849/357908051-0cbfced2-2624-42cc-83b7-ce98bbf7503a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTQ2ODUsIm5iZiI6MTcyMzY1NDM4NSwicGF0aCI6Ii8yMDE1Nzg0OS8zNTc5MDgwNTEtMGNiZmNlZDItMjYyNC00MmNjLTgzYjctY2U5OGJiZjc1MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE2NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZGIwOGU2YzI4ZDdiZjcwN2EwNjQ0MTFkMDU3MzkzYWM4NGQ4NzgwMGUyZmEzOWIxMTcwNjA4Y2MxYzdhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FjzBckBPcH0yWlSI5i7hDt80wy65zOcCdeZdimNjJbw)
> 
> Here is what Cmd+I should open up in VS Code. We don't have the ability to do true "inline chat" in VS Code since it isn't exposed through the API.
> 
> I am not sure what extension would be triggering the other inline chat, but you could attempt a bisect to determine: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

Thanks for your reply. I saw a similar inline chatbox to Copilot in the documentation for JetBrains's ide and mistakenly thought it was also available in VSCode.

**Comment by Patrick-Erichsen** [comment]
Got it, yeah it's unfortunate that VS Code doesn't provide that capability but hopefully they will enable it in the near future.
