### ISSUE TITLE
HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

### ISSUE THREAD

**Issue by Kiril-Stoilov919** [continuedev/continue#2006]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS Sonoma 14.6.1
- Continue: 0.0.56
- IDE: IntelliJ Ultimate 2024.2.0.1
- Model: Claude 3.5 Sonnet
- config.json:
  {
  "models": [
    {
      "title": "Llama 3",
      "provider": "ollama",
      "model": "llama3"
    },
    {
      "title": "Mistral",
      "provider": "ollama",
      "model": "mistral:latest",
      "apiBase": "http://localhost:11434/"
    },
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    },
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "completionOptions": {}
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Claude 3.5 Sonnet",
    "provider": "anthropic",
    "model": "claude-3-5-sonnet-20240620",
    "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  "allowAnonymousTelemetry": true,
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  }
}

  ```
```


### Description

After the latest updates I receive:

```
HTTP 400 Bad Request from https://api.anthropic.com/v1/messages
{"type":"error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}
```

I've got enough credit in my Anthropic account, apparently Continue is not creating proper requests (see above)

### To reproduce

Try prompting Claude 3.5 Sonnet with latest updates in IntelliJ

### Log output

```Shell
{"type":"error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}
```

**Comment by fry69** [comment]
Sonnet-3.5 does not work as an autocomplete model, see here for model recommendations that work -> https://docs.continue.dev/setup/select-model#autocomplete

**Comment by Kiril-Stoilov919** [comment]
> Sonnet-3.5 does not work as an autocomplete model, see here for model recommendations that work -> https://docs.continue.dev/setup/select-model#autocomplete

It is not (just) the autocomplete that it is not working, the general chat does not work, the error is from there. I've changed the tabAutocompleteModel but the issue persists.

**Comment by fry69** [comment]
Last thing I see is remove the `embeddingsProvider` and `reranker` blocks from your config. You'll use defaults that work well and the free trial will stop working soon anyway (could also be source for the empty fields error when those fail).

**Comment by Kiril-Stoilov919** [comment]
> Last thing I see is remove the `embeddingsProvider` and `reranker` blocks from your config. You'll use defaults that work well and the free trial will stop working soon anyway (could also be source for the empty fields error when those fail).

I removed them, but this seems to break something else, see attached screenshot. I also provide an attachment with the original error.

![original_error](https://github.com/user-attachments/assets/6f47fcf5-2fe0-4f8c-affb-85e9b213b184)
![after_removal_embeddingsProvider_reranker](https://github.com/user-attachments/assets/ebfe2694-16c9-48cd-9358-d232e626af6f)

**Comment by fry69** [comment]
Sorry, I forgot that you are on JetBrains, where the the default `transformers.js` based embeddings model does not work (VSCode only). Try disabling indexing completely for now, add
```json
	"disableIndexing": true,
```
to your `config.json` file.

You can enable indexing later by either running a local embeddings model (does not use much compute) or by using an online API for that, see here -> https://docs.continue.dev/features/codebase-embeddings#ollama

**Comment by fry69** [comment]
Also I just notice that the
```json
	"completionOptions": {}
```
inside your model block for "Claude 3.5 Sonnet" seems odd and unnecessary, can you remove that too?

**Comment by Kiril-Stoilov919** [comment]
Hi, I've removed the completionOptions, and added the disableIndexing, still no luck. I also tried putting back (and then removing again the allowAnonymousTelemetry and reranker parameters. My goal is to use Claude Sonnet as the main model with tab auto completion and indexing, but can sacrifice the tab autocompletion for a local model (I got mistral, llama3 and codestral locally). This worked fine until the end of last week, this week a bunch of updates for both Continue and a major update for IntelliJ were installed, which apparently broke all. About the indexing, it still had issues before, but I could remedy them by closing some of the projects (IntelliJ instances) I don't currently use and restarting the IDE/Plugin. Here is the current config.json I use:

`{
  "models": [
    {
      "title": "Llama 3",
      "provider": "ollama",
      "model": "llama3"
    },
    {
      "title": "Mistral",
      "provider": "ollama",
      "model": "mistral:latest",
      "apiBase": "http://localhost:11434/"
    },
    {
      "title": "Codestral",
      "provider": "ollama",
      "model": "codestral:latest",
      "apiBase": "http://localhost:11434/"
    },
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    },
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Mistral",
    "provider": "ollama",
    "model": "mistral:latest",
    "apiBase": "http://localhost:11434/"
  },
  "disableIndexing": true
}`

And last but not least thanks for your efforts!

**Comment by Kiril-Stoilov919** [comment]
Dang it, the code formatting didn't work.

**Comment by fry69** [comment]
> Dang it, the code formatting didn't work.

In doubt, if such a thing happens copy the unreadable blob and put it in this command line ->
```shell
jq . - <<EOF
[paste your unformatted JSON here, without the square brackets of course]
EOF
```
This should produce ->
```json
{
  "models": [
    {
      "title": "Llama 3",
      "provider": "ollama",
      "model": "llama3"
    },
    {
      "title": "Mistral",
      "provider": "ollama",
      "model": "mistral:latest",
      "apiBase": "http://localhost:11434/"
    },
    {
      "title": "Codestral",
      "provider": "ollama",
      "model": "codestral:latest",
      "apiBase": "http://localhost:11434/"
    },
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    },
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Mistral",
    "provider": "ollama",
    "model": "mistral:latest",
    "apiBase": "http://localhost:11434/"
  },
  "disableIndexing": true
}
```
(the [here document](https://en.wikipedia.org/wiki/Here_document#Unix_shells) gymnastic is necessary because otherwise you'll run into quote/escaping problems)

**Comment by Kiril-Stoilov919** [comment]
Any ideas however about the 400 from the Anthropic api?

**Comment by fry69** [comment]
> Any ideas however about the 400 from the Anthropic api?

No real clue. Another thing you could try is to reset Continue's state by moving your `~/.continue` folder out of the way, the create it new with
```shell
mkdir ~/.continue
```
and copy only the `config.json` file from your copied Continue folder back into this newly created one. Of course stop the IDE for this and start it afterwards.

**Comment by Kiril-Stoilov919** [comment]
> > Any ideas however about the 400 from the Anthropic api?
> 
> No real clue. Another thing you could try is to reset Continue's state by moving your `~/.continue` folder out of the way, the create it new with
> 
> ```shell
> mkdir ~/.continue
> ```
> 
> and copy only the `config.json` file from your copied Continue folder back into this newly created one. Of course stop the IDE for this and start it afterwards.

tried, still the 400 when contacting the anthropic api, re-enabled indexing, this time doesn't hang

**Comment by Kiril-Stoilov919** [comment]
Can someone please provide me with a minimalistic (and tested to work) config.json for Claude 3.5 Sonnet (where I only have to insert my API key), not tab auto complete or anything else is needed. Thanks in advance!

**Comment by jlewi** [comment]
@Kiril-Stoilov919 Where do you see the 400 error? When I type a chat message into Continue in GoLand nothing happens. I'm not seeing any errors and not sure where to look to see if its the same issue.

**Comment by Kiril-Stoilov919** [comment]
@jlewi - look at the middle of the screenshot (the green rectangle in the middle) from my answer above: https://github.com/continuedev/continue/issues/2006#issuecomment-2288773830

**Comment by fayvor** [comment]
@Kiril-Stoilov919 I'm getting the same error in VSCode with the Claude config from the Continue docs:

```
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "xxx"
    }
```

In the VSCode Console log, I see this:

```
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "b0a970ca-77bc-4166-895d-65d0574882e9",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hello"
            }
          ]
        }
      ],
      "title": "Claude 3.5 Sonnet",
      "completionOptions": {}
    }
  }
}

Error: HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"Your credit balance is too low to access the Claude API. Please go to Plans & Billing to upgrade or purchase credits."}}
```

Maybe you have to purchase credits as well?

**Comment by Kiril-Stoilov919** [comment]
@fayvor I've bought myself credits, have enough; will generate myself a new API key today and try with it, but as far as I remember the no credits message was different (after my free 5$ were depleted).

**Comment by jpchavat** [comment]
Any news about it? I'm facing exactly the same error. It happens to me only when using files as context in pycharm.

**Comment by Kiril-Stoilov919** [comment]
> Any news about it? I'm facing exactly the same error. It happens to me only when using files as context in pycharm.

Didn't find a workaround. However I installed another plugin - CodeGPT (works fine with the Anthrpic API, supports local models as well) on my IntelliJ, never looked back. Also continue was leaving dead processes which consumed 100% cpu, caused IntelliJ to crash and the indexing never worked properly, no matter how many times I deleted the .continue folder. Shame, looked promising at the beginning.

Cheers.

**Comment by jpchavat** [comment]
> Didn't find a workaround. However I installed another plugin - CodeGPT (works fine with the Anthrpic API, supports local models as well) on my IntelliJ, never looked back. Also continue was leaving dead processes which consumed 100% cpu, caused IntelliJ to crash and the indexing never worked properly, no matter how many times I deleted the .continue folder. Shame, looked promising at the beginning.

I'm sorry about that @Kiril-Stoilov919. Thanks for the response.

---

To contribute to the diagnose of the issue, this is what I got in my core.log file:

```
[2024-08-28T14:02:26] HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}
    at customFetch (/snapshot/continue/binary/out/index.js:385701:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (/snapshot/continue/binary/out/index.js:384609:22)
    at async Anthropic._streamChat (/snapshot/continue/binary/out/index.js:386198:22)
    at async Anthropic.streamChat (/snapshot/continue/binary/out/index.js:385902:26)
    at async llmStreamChat (/snapshot/continue/binary/out/index.js:393680:19)
    at async /snapshot/continue/binary/out/index.js:394230:30 
[2024-08-28T14:02:26] Error: HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}} 
[2024-08-28T14:02:26] Error running handler for "llm/streamChat":  Error: HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}
[2024-08-28T14:02:26] Error: HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}} 

```

while in the prompt.log I got a slightly different one:

```
[2024-08-28T14:02:26] HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 400 Bad Request from https://api.anthropic.com/v1/messages

{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}
    at customFetch (/snapshot/continue/binary/out/index.js:385701:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (/snapshot/continue/binary/out/index.js:384609:22)
    at async Anthropic._streamChat (/snapshot/continue/binary/out/index.js:386198:22)
    at async Anthropic.streamChat (/snapshot/continue/binary/out/index.js:385902:26)

Completion:


Error in Continue free trial server: 429 "request rate limit exceeded"
```

Something caught my attention: **Error in Continue free trial server: 429 "request rate limit exceeded"**

I just installed the continue.dev pluging and start using it, with an anthropic api kay and the free credits. 

Another thing was that, after setting api keys for the autocomplete/embedding/reranker as suggested [here](https://docs.continue.dev/setup/configuration#best-overall-experience) and restarting the chat session, it worked again.

"rate limit exceeded" couldn't be exceeded since I tested it spread out over time. Maybe there are many requests in a single call to continue.dev?

**Comment by strowk** [comment]
Also having the same issue "Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits". 
Does not seem to make any sense to me since I haven't made any requests in several days now and Plans & Billing tells me that on my plan have 5 requests per minute. Claude in web works fine, so seems that continue is broken
