### ISSUE TITLE
Support of apiKey in Ollama embeddings provider

### ISSUE THREAD

**Issue by vills** [continuedev/continue#2008]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.5
- Continue: v0.9.197 (pre-release)
- IDE: VSCode 1.92.1
- Model: nomic-embed-text
- config.json:
  
{
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text",
    "apiBase": "https://remote-ollama-instance-behind-open-webui/ollama",
    "apiKey": "api-token-from-open-webui"
  }
}
```

### Description

Ollama embeddings provider return 401 unauthorized. As i can see in OllamaEmbeddingsProvider.ts file there are no support of apiKey for Ollama when used as embeddings provider. Could you please add this header also?

**Comment by Le-Syl21** [comment]
Hi, try this it work

https://docs.openwebui.com/tutorial/continue-dev/

**Comment by vills** [comment]
> Hi, try this it work
> 
> https://docs.openwebui.com/tutorial/continue-dev/

It works with models and tabautocomplete sections, but not in embeddings.

**Comment by vills** [comment]
@Le-Syl21 i just found out, that you encouraged me to try openai compatible api? for some reason i got 404 response from ollama in /v1/embeddings endpoint

```
"embeddingsProvider": {
  "provider": "openai",
  "model": "mxbai-embed-large",
  "apiBase": "https://remote-ollama-instance-behind-open-webui/ollama/v1",
  "apiKey": "api-token-from-open-webui"
}

"POST /ollama/v1/embeddings HTTP/1.1" 404 Not Found
```

**Comment by andrew-stclair** [comment]
According to the ollama docs for open-webui (`http://open-webui/ollama/docs`), there is no `http://open-webui/ollama/v1/embeddings`, And ollama has no v1 path in [their api](https://github.com/ollama/ollama/blob/main/docs/api.md)

There is an `http://open-webui/ollama/api/embeddings` which requires auth when it's enabled and expects the following in the request:

```json
{
  "model": "string",
  "prompt": "string",
  "options": {},
  "keep_alive": "string"
}
```

**Comment by sestinj** [comment]
@vills @andrew-stclair just made a fix here: https://github.com/continuedev/continue/commit/07853463c8b2b1d9b2de850bd47e28454db98a03

This will be in the next pre-release!
