### ISSUE TITLE
"Invalid ELF Header Error on PyCharm with Continue Plugin - Node SQLite3 Module Load Failure"

### ISSUE THREAD

**Issue by abhinav-aq** [continuedev/continue#2023]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
- Model:
- config.json:
```

### Description

Whenever I open PyCharm (version 2024.2), I encounter a persistent error pop-up related to the Continue Plugin (version 0.0.59). The error points to a failure in loading the node_sqlite3.node due to an "invalid ELF header". This error disrupts the functionality of the plugin and affects the startup of the IDE.

Error Message: 
Error: /home/abhinav/.local/share/JetBrains/PyCharmCE2024.2/continue-intellij-extension/core/build/Release/node_sqlite3.node: invalid ELF header at process.dlopen (pkg/prelude/bootstrap.js:2251:28) at Module._extensions..node (node:internal/modules/cjs/loader:1196:18) at Module.load (node:internal/modules/cjs/loader:988:32) at Module._load (node:internal/modules/cjs/loader:834:12) at Module.require (node:internal/modules/cjs/loader:1012:19) at Module.require (pkg/prelude/bootstrap.js:1851:31) at require (node:internal/modules/cjs/helpers:102:18) at bindings (/snapshot/continue/binary/out/index.js:49608:54) at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (/snapshot/continue/binary/out/index.js:49680:41) at __require (/snapshot/continue/binary/out/index.js:18:51) { code: 'ERR_DLOPEN_FAILED' }

### To reproduce

1. Install Continue Plugin version 0.0.59 on PyCharm 2024.2.
2. Open PyCharm.
3. Error prompts at startup.

**Comment by fry69** [comment]
`0.0.59` is broken, use `0.0.56` for now

**Comment by sestinj** [comment]
@abhinav-aq if you have the chance, let me know how version 0.0.62 goes for you. It is an EAP version, which you can download like here: https://docs.continue.dev/troubleshooting#jetbrains-1.

We're looking to get feedback on this, as it's the first of many auto-deployed releases. If it goes well, then we can assume much higher reliability going forward

**Comment by abhinav-aq** [comment]
Yeah, thanks!!

Now, working great.
________________________________
