### ISSUE TITLE
No commands (continue.X) are found in VSCode

### ISSUE THREAD

**Issue by vegardsoerlie** [continuedev/continue#2024]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS Sonoma 14.6.1
- Continue: v0.8.46 (also tried pre-release)
- IDE: VSCode 1.92.1 & 1.92.2
- Model: Not relevant (deepseek-coder)
- config.json: 
{
  "models": [
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    }
  ],
  "systemMessage": "You are an english chatbot and you will always answer in english",
  "allowAnonymousTelemetry": false,
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  },
  "tabAutocompleteModel": {
    "title": "codegemma",
    "provider": "ollama",
    "model": "codegemma:2b"
  }
}
```

### Description

Note, it is seemingly not a "Keyboard shortcuts not resolving"-issue as seen in the troubleshooting guide, as nothing works. Every action I hit in the context menu (CMD+shift+P) result in this 
<img width="267" alt="image" src="https://github.com/user-attachments/assets/e10f64df-f1ec-41a7-a50e-2c081ecfb8ec">

Steps I have tried to solve the issue:
- Restart machine
- Restart Extensions
- Restart VSCode
- Reinstall extension
- Try pre-release version of Continue
- Restart ollama
- Running Extension Bisect identifies continue as the issue
- Deleting extensions.json

### To reproduce

1. Try to do anything using Continue in VSCode

### Log output

```Shell
mainThreadExtensionService.ts:107 Activating extension 'Continue.continue' failed: Unexpected non-whitespace character after JSON at position 193 (line 7 column 2).
$onExtensionActivationError	@	mainThreadExtensionService.ts:107
```

**Comment by fry69** [comment]
Your `config.json` seems broken.

**Comment by vegardsoerlie** [comment]
I could access the config fine while navigating in the file system. I edited my original post and added it above

**Comment by fry69** [comment]
It the above `config.json` is the complete `config.json` it is missing the final closing `}`

**Comment by fry69** [comment]
At this point I suspect something else is wrong. Can you please try with a fresh `~/.continue` folder as I described above? If that works, then try copying in your `config.json` file in this fresh Continue folder and see if it still works.

**Comment by vegardsoerlie** [comment]
Sorry, I missed that from the first message somehow. 
 
 Thank you! That worked.
