### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes. error in vscode

### ISSUE THREAD

**Issue by kedimuzafer** [continuedev/continue#2040]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:pop os linux
- Continue:lastest
- IDE:vscode latest
```

### Description

i want to use this application but i couldn't start it. 
there's an error that i get:
"Extension host terminated unexpectedly 3 times within the last 5 minutes. "
how can i fix this issue? i tried in jetbrains and vscode in docker it works but in normal desktop vscode i get this error.

### To reproduce

> install continue dev.
> wait for the error.

**Comment by amirhossein-ka** [comment]
I get the same error when i'm installing extension on a freshly installed vscode for my coworker.
And strange part is that the same version works perfectly fine on my pc.
I even tried to copy extensions from my pc to my another one, and i still get same error. 
Also tried to move all of this extension config in ~/.continue to another pc and still didnt worked.
Even the vscode version is same.

**Comment by sestinj** [comment]
@amirhossein-ka are you also on PopOS?

@kedimuzafer Can you both try to set `disableIndexing` in config.json and let me know if this resolves the problem? This would help us narrow down the problem to this area, which we've been putting a lot of time into recently

Also, I'm assuming that you both are on the latest pre-release version of the extension (0.9.197+). Let me know if otherwise

**Comment by kedimuzafer** [comment]
> @amirhossein-ka are you also on PopOS?
> 
> @kedimuzafer Can you both try to set `disableIndexing` in config.json and let me know if this resolves the problem? This would help us narrow down the problem to this area, which we've been putting a lot of time into recently
> 
> Also, I'm assuming that you both are on the latest pre-release version of the extension (0.9.197+). Let me know if otherwise

I tried both pre and normal release version. In /.vscode/extentions/continue.continue-0.8.46-linux-x64 folder but there's no config.json file. there is a config-schema.json, I tried changing the name to config.json still doesn't work. also i made disableIndexing to true but still doesn't work. I changed the name again as config-schema.json.

**Comment by amirhossein-ka** [comment]
> @amirhossein-ka are you also on PopOS?

I am on linux mint right now, but i tested the plugin on 3 other OS, 2 xubuntu 20.04 and another linux mint.


> @kedimuzafer Can you both try to set `disableIndexing` in config.json and let me know if this resolves the problem? This would help us narrow down the problem to this area, which we've been putting a lot of time into recently

I did it and it fixed issue, Thank you !

@kedimuzafer 
You can set it in ~/.continue/config.json. 

> Also, I'm assuming that you both are on the latest pre-release version of the extension (0.9.197+). Let me know if otherwise

I tried both pre release and 0.8.46 and Those two had this problem.
I'm currently on 0.8.46.

**Comment by kedimuzafer** [comment]
That didn't fixed my problem. I added disableIndexing line to the ~/.continue/config.json.
`{
  "disableIndexing": true,
}
`
I tried using code-insiders version, it didn't help.
