### ISSUE TITLE
Local `.continueignore`s

### ISSUE THREAD

**Issue by muliyul** [continuedev/continue#2070]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I have a mono-repo structured as each folder is a micro service. I'd like to have `.continueignore` file per folder (similar to how .gitignore works).

### Solution

Scan project for all `.continueignore` files, build an aggregated internal model of the merged `.continueignore`s using each location as a prefix, then use that to apply to the codebase from the root.

**Comment by spew** [comment]
I believe it already [works this way](https://github.com/continuedev/continue/blob/dev/core/indexing/walkDir.ts#L209). Are we talking about .continueignore for indexing?

**Comment by muliyul** [comment]
Both. I guess I missed that in the docs or it isn't documented.

**Comment by sestinj** [comment]
Linking to the docs [here](https://docs.continue.dev/features/codebase-embeddings#ignore-files-during-indexing). We'll also be making it more prominent as we do a rewrite soon.
