### ISSUE TITLE
Slow startup debugging

### ISSUE THREAD

**Issue by 980468094** [continuedev/continue#2074]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hello, every time I use F5 to start the plug-in for debugging, this step is very slow and takes about ten minutes. Is there any way to start the project faster?
![image](https://github.com/user-attachments/assets/1c3f09a2-0473-41a2-96d3-c013bee38208)

**Comment by Patrick-Erichsen** [comment]
Is it that slow on every attempt, or just on startup? It should be well under 1 minute to start up. Could you share some info on the machine you're building on?

**Comment by 980468094** [comment]
Thank you very much for your reply. I have found the reason because I encountered this problem when compiling and executing npm install in China, and the installation of dependencies was relatively slow. Later, after configuring the image source, the speed was very fast
