### ISSUE TITLE
Add access to internet for accessing latest documentation from within continue

### ISSUE THREAD

**Issue by a7t0fwa7** [continuedev/continue#2081]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Is there a plan to implement internet access in order to access and pull documentation so that we can consult directly from the continue chat interface?

**Comment by gregbarbosa** [comment]
@a7t0fwa7 Might want to check out the existing [Docs feature](https://docs.continue.dev/customization/context-providers#documentation). You can add links to online docs and it'll grab them for you.

**Comment by a7t0fwa7** [comment]
@gregbarbosa Thank you ! I will check it out
