### ISSUE TITLE
embedding provider incorrect for voyage?

### ISSUE THREAD

**Issue by dannysteenman** [continuedev/continue#2094]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
not applicable
```

### Description

On your embeddings docs page, there is a typo on the provider for voyage, it says the provider is openai, but I guess that must be called voyage? see: https://docs.continue.dev/features/codebase-embeddings#voyage-ai

I shared a screenshot of the part of the docs.
<img width="846" alt="SCR-20240824-jimf" src="https://github.com/user-attachments/assets/c079486a-92fb-4ae4-96d0-246df6010482">

**Comment by Lizzy223** [comment]
Hello,
Can this be assigned to me?
I've fixed it. 
https://github.com/continuedev/continue/pull/2125

**Comment by sestinj** [comment]
@dannysteenman There actually isn't a voyage provider right now, so "openai" is correct. That said, we probably should have a Voyage provider

**Comment by dannysteenman** [comment]
all right makes sense, from the docs it wasn't really clear, hence the creation of this issue.
