### ISSUE TITLE
[CON-21] Nate and Ty to iterate on a 2-sentence description here. Move task to review once you've written something, then we'll move it back as needed.

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#21]
https://bookface.ycombinator.com/knowledge/9X-two-sentence-description

<sub>[CON-21](https://linear.app/continue/issue/CON-21/nate-and-ty-to-iterate-on-a-2-sentence-description-here-move-task-to)</sub>

**Comment by sestinj** [comment]
Format 1: Sentence one, what we do. Sentence two, example.

Example: Airbnb is a marketplace where you can book a home or apartment when travelling for work or vacation. When you visit New York City with your family, instead of staying in a cramped and expensive hotel room, you can stay in a comfortable 3 bedroom apartment at the same price.

**Continue is an AI autopilot for coding which is fully open-source, making it easy for developers to write their own team/codebase-specific automations. For example, write tests or documentation that falls in line with team best practices.**

Format 2: Sentence one, the problem we solve. Sentence two, how we solve it.

Example: Stripe makes it easy for developers to accept payments on their websites or mobile apps. We do this by providing a simple and well documented payments API that any developer can instantly start using straight from our website.

**Continue makes it easy to extend AI coding tools so they can act directly in your IDE. We do this by providing a simple SDK where developers can write automations that are then usable in our VS Code extension.**

**Comment by sestinj** [comment]
Continue is an AI autopilot for software development which is fully open-source, making it easy for developers to write their own codebase-specific automations. For example, zip through database migrations, construct data pipelines, or write unit tests that fall in line with team best practices.

**Comment by sestinj** [comment]
Continue is an open-source AI autopilot for software development that empowers developers to easily write their own codebase-specific automations. For example, zip through database migrations, construct data pipelines, or write unit tests that fall in line with team best practices.

**Comment by sestinj** [comment]
Continue is an open-source AI autopilot for software development that empowers developers to easily write custom automations. For example, zip through database migrations, construct data pipelines, or write unit tests that fall in line with team best practices.

**Comment by sestinj** [comment]
Continue is an open-source AI autopilot for software development that makes it easy to create and use custom automations. For example, zip through database migrations, construct data pipelines, or write unit tests that fall in line with team best practices.

**Comment by TyDunn** [comment]
Continue is an open-source AI autopilot for software development, which makes it easy to create and use custom automations. For example, developers use it to zip through database migrations, construct data pipelines, and write unit tests that fall in line with team and company best practices
