### ISSUE TITLE
Error: SQLITE_CONSTRAINT

### ISSUE THREAD

**Issue by mims1234** [continuedev/continue#2100]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE: VScode
- Model: 
- config.json:
```

### To reproduce

![error](https://github.com/user-attachments/assets/f3f3da22-8ee4-4c11-a885-4fafc53bfb74)

**Comment by kuflash** [comment]
Maybe it's duplicate issue? https://github.com/continuedev/continue/issues/2078

**Comment by priyashpatil** [comment]
There are some improvements being made in code indexing these should be resolved sooner. For a workaround see if there is any popup for rebuilding the index if not then deleting the `~/.continue/index` folder should fix the issue (after deleting make sure to reindex by clicking on the indexing indicator or `CMD+Shift+P` -> `Continue: Codebase force re-index)`.

**Comment by sestinj** [comment]
This should now be resolved in the latest pre-release version of VS Code and Jetbrains
