### ISSUE TITLE
Local folder references aren't passed correctly to Claude 3.5 at Jetbrains plugin

### ISSUE THREAD

**Issue by ishai-1** [continuedev/continue#2105]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.62
- IDE: Pycharm Pro 2024.1.3
- Model: Claude 3.5
- config.json:
  {
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "INSERT_ANTROPIC_API_KEY_HERE"
    }
  ],
  "embeddingsProvider": {
    "provider": "openai",
    "model": "text-embedding-3-small",
    "apiKey": "INSERT_OPENAI_API_KEY_HERE"
  }
}

  ```
```


### Description

While asking a question about a code while providing a reference to an existing local folder (e.g., @the_local_folder) in the context in PyCharm plugin, the following error appear: "Error getting context items from folder. TypeError: db.search is not a function"
Claude 3.5 answer specifies that he don't have information about the_local_folder.

When I try to provide a local file reference, it's being accurately resolved and properly referenced in questions about it. 

### To reproduce

1. Install Continue.Dev PyCharm Plugin (v0.0.62)
2.  Load the abovementioned configuration, replacing INSERT_ANTROPIC_API_KEY_HERE and  INSERT_OPENAI_API_KEY_HERE with valid and working api keys.
3. Open a local project of a local git repository
4. Ask a question relating the code, providing a sub-folder of the local repository

### Log output

```Shell
[2024-08-26T11:42:16] Error retrieving from FTS: Error: SQLITE_ERROR: no such table: fts
[2024-08-26T11:42:35] (node:18516) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created)
```

**Comment by JCraigWasTaken** [comment]
This is also happening with v0.9.199 (pre-release) of the vscode extension on windows 11.

**Comment by yuduok** [comment]
I also encountered the same error in WebStorm when I used the chat command @codebase, and the error "db.search is not a function" popped up

**Comment by JCraigWasTaken** [comment]
I was able to fix the error by downgrading to the stable release version (v0.8.46) in vscode

**Comment by ishai-1** [comment]
For Jetbrains plugin, the bug replicates also on the latest stable release (currently 0.0.62), downloaded from within PyCharm Pro.

**Comment by meanderix** [comment]
I can replicate this as well. No files are provided with the @codebase context.

**Comment by jfiore-im** [comment]
I can also replicate this.
This was working fine on Tuesday August 27th. So I think the release on August 27th perhaps broke this.

**Comment by jfiore-im** [comment]
Here is some hopefully helpful information.
In version `0.8.46` of the VSCode plugin, the `~/.continue/index/index.sqlite` database has the following tables:
- fts
- fts_config
- fts_content
- fts_data
- fts_docsize
- fts_idx
- fts_metadata

In version `0.8.47` those tables do NOT exist.

**Comment by sestinj** [comment]
the db.search problem should now be solved in the latest pre-release for VS Code. The update will make its way to main release and Jetbrains in the next 1-2 days
