### ISSUE TITLE
Ollama embedding API structure mismatch

### ISSUE THREAD

**Issue by jackpots28** [continuedev/continue#2109]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: OSX
- Continue: 0.64
- IDE: Jetbrains PyCharm and IntelliJ
- Model: 
- config.json:
  
{
  "models": [
    {
      "model": "ibm/granite-13b-chat-v2",
      "contextLength": 7500,
      "title": "Granite Chat",
      "watsonxUrl": "",
      "watsonxProjectId": "",
      "watsonxCreds": "",
      "watsonxApiVersion": "2023-05-29",
      "provider": "watsonx",
      "requestOptions": {
        "caBundlePath": ""
      }
    }
  ],
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "all-minilm:l6-v2",
    "apiBase": "https://x.x.x.x:11434/"
  }
}
```

### Description

When reviewing the error:

./logs/core.log:[2024-08-26T18:26:41] error when indexing:  Error: Failed to generate embeddings for 138 chunks with provider: OllamaEmbeddingsProvider::all-minilm:l6-v2: FetchError: request to https://x.x.x.x:11434/api/embeddings failed, reason: write EPROTO 404F37F301000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

I noticed the api url references "/api/embeddings"

Looking at the [Ollama API documentation](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings
) and source code it references
"/api/embed"

https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings

### Log output

```Shell
./logs/core.log:[2024-08-26T18:26:41] error when indexing:  Error: Failed to generate embeddings for 138 chunks with provider: OllamaEmbeddingsProvider::all-minilm:l6-v2: FetchError: request to https://x.x.x.x:11434/api/embeddings failed, reason: write EPROTO 404F37F301000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
```

**Comment by jackpots28** [comment]
I believe the mistype is here:

core/indexing/embeddings/OllamaEmbeddingsProvider.ts ->
https://github.com/continuedev/continue/blob/main/core/indexing/embeddings/OllamaEmbeddingsProvider.ts

`const resp = await customFetch(new URL("api/embeddings", apiBase), {
      method: "POST",
      body: JSON.stringify({
        model: options.model,
        prompt: chunk,
      }),
      headers: {
        "Content-Type": "application/json",
      },
    });`

api/embeddings doesn't appear in the ollama api documentation - it is instead referred to as api/embed

**Comment by serious-snow** [comment]
> I believe the mistype is here:我相信错误输入在这里：
> 
> core/indexing/embeddings/OllamaEmbeddingsProvider.ts ->核心/索引/嵌入/OllamaEmbeddingsProvider.ts -> https://github.com/continuedev/continue/blob/main/core/indexing/embeddings/OllamaEmbeddingsProvider.ts
> 
> `const resp = await customFetch(new URL("api/embeddings", apiBase), { method: "POST", body: JSON.stringify({ model: options.model, prompt: chunk, }), headers: { "Content-Type": "application/json", }, });`
> 
> api/embeddings doesn't appear in the ollama api documentation - it is instead referred to as api/embedapi/embeddings 没有出现在 OLLAMA API 文档中 - 它被称为 api/embed


I thought so at first, but there was no problem with visiting.
see https://github.com/ollama/ollama/issues/6533
```
curl -s -X POST localhost:11434/api/embeddings | jq
```
{
  "error": "missing request body"
}

**Comment by sestinj** [comment]
https://github.com/continuedev/continue/commit/afb099004bf3ce2187d480bf9e9664077b610498
