### ISSUE TITLE
Using a symlink for ".continuerc.json" does not work

### ISSUE THREAD

**Issue by knedlsepp** [continuedev/continue#2121]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Description

I tried setting up the file `.continuerc.json` at the root level of my project by means of a symlink to a config file in a subdirectory. This doesn't seem to work. The configuration in that file is not applied.
I cross checked and it seems to work as soon as I directly put the configuration in the file as opposed to creating a symlink.
I think the following code part probably will need adapting:

https://github.com/continuedev/continue/blob/54c24fd8e0213d377b58b1a6cdce451d03172ee5/extensions/vscode/src/ideProtocol.ts#L317

**Comment by sestinj** [comment]
Fixed [here](https://github.com/continuedev/continue/commit/e5a7e78ee4e204170bdb7c6d802eaa85cf4c50ea), thanks for finding the line!

**Comment by knedlsepp** [comment]
> Fixed [here](https://github.com/continuedev/continue/commit/e5a7e78ee4e204170bdb7c6d802eaa85cf4c50ea), thanks for finding the line!

Thanks for the swift fix!

**Comment by knedlsepp** [comment]
@sestinj I just checked if the issue is resolved in `v0.9.205` (which [should include this fix](https://github.com/continuedev/continue/commit/e5a7e78ee4e204170bdb7c6d802eaa85cf4c50ea)) but it is still not working for me. The models that I define in my `.continuerc.json` don't show up in VSCode.
Apparently the line I mentioned wasn't sufficent to resolve this. Could you reopen this issue?
I sadly have neither VSCode extension nor TypeScript experience, so I don't quite have the capability to debug this extension locally.
