### ISSUE TITLE
Jetbrains tooltip popup is sticky, gets cloned.

### ISSUE THREAD

**Issue by gogo199432** [continuedev/continue#2132]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.64
- IDE: Jetbrains Rider
```

### Description

Randomly the new popup in Rider gets frozen to the editor, and duplicated when a new one appears after selecting a new section. These old sections still respond to the new selection, so if I click on the "Ctrll Editor" for example the new text is added. But these remnants are over the actual code and are pretty irritating

![grafik](https://github.com/user-attachments/assets/fc6a2c2e-b34d-4f56-bf3f-8fa83c7746b3)

### To reproduce

1. Create 2 Split editors next to each other with text
2. Select something in the first
3. Switch over and select something else in the second
4. The popup remains active in the first editor

**Comment by sestinj** [comment]
@gogo199432 I've made a few important changes in version 0.0.65, is this still occurring there?

**Comment by gogo199432** [comment]
hey, yeah it is still occuring in 0.0.65 . It might be slightly better, but the duplication is still occuring when switching between 2 docked editor windows (vertical split)

**Comment by tobiajung** [comment]
We are also facing the problem. But in Windows and Linux whereas it is more rare under Linux

**Comment by GregDomzalski** [comment]
I'm encountering this as well on Kubuntu Linux.

PhpStorm 2024.2.1
Rider 2024.2.3
Continue 0.0.65
KDE Plasma 5.27.11

**Comment by sestinj** [comment]
This is now solved in the latest versions of Continue!
