### ISSUE TITLE
`@folder` always uses the same context as `@codebase`, does not restrict to only the chosen folder.

### ISSUE THREAD

**Issue by lendle** [continuedev/continue#2151]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos 14.6.1
- Continue: v0.9.202, but I've never seen it work correctly on any prerelease or release version I've tried. I've been using continue for 4-6 weeks.
- IDE: VSCode
- Model: Sonnet 3.5, Voyage for embeddings & reranking
- config.json:
  
{
  "models": [
    {
      "title": "Anthropic",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "..."
    }
  ],
  "embeddingsProvider": {
    "model": "voyage-code-2",
    "apiBase": "https://api.voyageai.com/v1",
    "apiKey": "..."
  },
  "reranker": {
    "name": "voyage",
    "params": {
      "apiKey": "..."
    }
  },
  "contextProviders": [
    {
      "name": "folder",
      "params": {
        "useReranking": false,
        "nFinal": 25,
        "nRetrieve": 100
      }
    },
    {
      "name": "codebase",
      "params": {
        "useReranking": true,
        "nFinal": 25,
        "nRetrieve": 100
      }
    }
  ],
```

### Description

Regardless of what folder I choose with `@folder`, the same snippets are always included in context, and they are the same snippets I get with `@codebase`. They are not restricted to files in the folder I choose. If I change the message, I get different snippets, so RAG seems to be working, but they are not restricted to 

The relevant parts of my config are above. At various times I've also tried with default configs, without reranking, and with other embedding providers. 

### To reproduce

1. Use `@codebase` or `@folder` with any folder and any message
2. Look at the 'Context items' dropdown under the message input box, they're always the same for the same message at least.

**Comment by sestinj** [comment]
Thanks for sharing this! I've just made the needed fix here: https://github.com/continuedev/continue/commit/eb0fb82dc2fdf1b4784c8e3de5e66da9febc9398

This will be in a new release very soon

**Comment by sestinj** [comment]
New release is now available, please don't hesitate to re-open if you encounter anything similar

**Comment by lendle** [comment]
@sestinj this is happening for me again on prerelease 0.9.268.
