### ISSUE TITLE
0.8.48 Introduced the contextProviders failure issue

### ISSUE THREAD

**Issue by supuwoerc** [continuedev/continue#2160]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos
- Continue: 0.8.48
- IDE: vscode
- Model: qwen2-72b
- config.json:
  
{
    "contextProviders": [
    { "name": "file" },
    { "name": "diff" },
    { "name": "terminal" },
    { "name": "open", "params": { "onlyPinned": true } },
    { "name": "codebase" },
    { "name": "folder" },
    { "name": "tree" }
  ]
}
```

### Description

The new version introduces a problem where contextProviders are not working, the problem disappears after installing the previous version.

### To reproduce

After installing 0.8.48 typing @file doesn't have the input file option and there are other context providers that are not working

**Comment by sestinj** [comment]
Hotfix on the way: https://github.com/continuedev/continue/releases/tag/v0.8.49-vscode

Thanks for bringing this up so quickly!

**Comment by supuwoerc** [comment]
> Hotfix on the way: https://github.com/continuedev/continue/releases/tag/v0.8.49-vscode正在修复： https://github.com/continuedev/continue/releases/tag/v0.8.49-vscode
> 
> Thanks for bringing this up so quickly!感谢您这么快提出这个问题！

It's a quick fix, too. It's great.
