### ISSUE TITLE
look into why continue replies with I need more info while chatgpt gives a good answer

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#219]
situation: https://continuedev.slack.com/archives/C057XNXUUNT/p1688757126257839

**Comment by sestinj** [comment]
This is happening when the file is too large and is then being cut from the chat messages.
- We have an option to provide a summary, so could make this summary include extra information from the file.
- Could use GPT-32k, but not everyone has access
- Could try to get the model to tell the user that the file is too large for it to read
