### ISSUE TITLE
How to show the quickstart again?

### ISSUE THREAD

**Issue by hitzhangjie** [continuedev/continue#2190]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

After I click 'I have complete the onboard', there's no way to say how to setup from start.
No matter I delete all config or reinstall continue extension.

I hope there's a way to show the quickstart again.

**Comment by Patrick-Erichsen** [comment]
Hi @hitzhangjie, the setting for showing the quickstart/onboarding is in localStorage. You can clear the value and restart with the following steps (in VS Code):
- Open the command palette (`cmd/ctrl + shift + p`)
- Type `Developer: Toggle Developer Tools`
- Click `Application` in the top toolbar
- In the lefthand pane, clear the values under `Storage > Local storage`

I'm curious what your need to revisit the quickstart is for?

**Comment by hitzhangjie** [comment]
Thanks very much.
