### ISSUE TITLE
GUI overlap

### ISSUE THREAD

**Issue by Wolframko** [continuedev/continue#2228]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Ubuntu 24.04
- Continue: 0.0.68
- IDE: Jetbrains RubyMine 2024.2.1
```

### Description

![image](https://github.com/user-attachments/assets/911e8a8a-6f4f-434d-9404-cfbd3c3501a6)
When response is several sentence long and model list contains a lot of models, response text input element overlaps model list, making model selection inconvenient.

### To reproduce

1. Add more than 3 models
2. Ask anything with short response, like "Hi"

**Comment by sestinj** [comment]
Thanks for sharing this! Just made the fix here: https://github.com/continuedev/continue/commit/438b76462727364069b26addb2b298601b91394d

Will be in the next release!
