### ISSUE TITLE
Jetbrains db.search is not a function (Add Codebase to Chat)

### ISSUE THREAD

**Issue by scpedicini** [continuedev/continue#2269]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS Monterey 12.7.4
- Continue: 0.0.64
- IDE: Jetbrains Webstorm 2024.2.1
- Model: Claude Sonnet 3.5 (API Key supplied)
- config.json:


{
  "models": [
    {
      "model": "claude-3-5-sonnet-20240620",
      "contextLength": 200000,
      "title": "Claude 3.5 Sonnet",
      "apiKey": "sk-ant-******",
      "provider": "anthropic"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": "FAKE"
  },
  "model_roles": {
    "default": "LLM"
  },
  "system_message": "",
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  }
}
```

### Description

Every time I use either ⌘-Enter in the Continue Chat or `@codebase` it throws `Error getting context items from codebase: TypeError: db.search is not a function`.

Here is the core.log file, it looks like it starts to index the codebase and then maybe just gives up at 50%? I've replicated this issue on every project I've tried so I don't think its tied to a specific one.

```
info] Starting Continue core...
[2024-09-15T15:17:15] [info] Starting Continue core... 
[2024-09-15T15:17:15] Setup 
[2024-09-15T15:17:15] Core started 
[2024-09-15T15:17:15] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-15T15:17:15] Indexing: 25.0% complete, elapsed time: 0s, Infinity file/sec 
[2024-09-15T15:17:15] Indexing: 25.0% complete, elapsed time: 0s, Infinity file/sec 
[2024-09-15T15:17:16] Indexing: 25.0% complete, elapsed time: 1s, 1.00 file/sec 
[2024-09-15T15:17:16] Indexing: 50.0% complete, elapsed time: 1s, 3.00 file/sec 
[2024-09-15T15:17:16] Indexing: 50.0% complete, elapsed time: 1s, 3.00 file/sec 
[2024-09-15T15:17:16] Indexing: 50.0% complete, elapsed time: 1s, 3.00 file/sec 
[2024-09-15T15:17:16] Indexing: 50.0% complete, elapsed time: 1s, 3.00 file/sec 
```

Looking at the `index.sqlite` SQLite file I can see it that it has chunked the right files.

```
583,aa34fd12b3fff393a191d4b86ad32340c0ccab26276530b4c588a5a3c5b262ce,/Users/shaun/dev/other/webstorm-continue-test/src/greeter.ts,1,0,19,"class Student {
    fullName: string;
    constructor(public firstName, public middleInitial, public lastName) {
        this.fullName = firstName + "" "" + middleInitial + "" "" + lastName;
    }
}

interface Person {
    firstName: string;
    lastName: string;
}

function greeter(person : Person) {
    return ""Hello, "" + person.firstName + "" "" + person.lastName;
}

var user = new Student(""Jane"", ""M."", ""User"");

document.body.innerHTML = greeter(user);
"
```

Adding actual files / active file / etc works fine - but any attempts to use `@codebase` give this error, is it possibly related to the Lance vector database?

I've also added the Continue extension to VSCodium and codebase context works fine. _It seems directly related to the Jetbrains Webstorm extension._

**ALSO: Trying to visit the troubleshooting documentation at https://docs.continue.dev/troubleshooting results in infinite redirects.**

### To reproduce

1. Create a new sample project folder with any code
2. Install Continue plugin into Webstorm
3. Open folder using Webstorm
4. Wait for logs (Core) to indicate it has finished indexing/etc.
5. Open Continue sidebar
6. Ask question and append `codebase`
7. Observe `db.search is not a function` error

**Comment by scpedicini** [comment]
I think we may be able to close this ticket out although the infinite redirect of troubleshooting site remains:
https://docs.continue.dev/troubleshooting

**Steps to fix:**

1. Completely uninstall plugin (VSCodium, Jetbrains)
2. Manually delete the `~/.continue` folder.
3. Reinstall plugin in Jetbrains Webstorm
4. Logs now show a reference to being unable to find MiniLM
5. Searching across Continue docs shows that MiniLM is only supported in VSCode
6. Manually add ollama nomic embeddings provider to config.json
7. Restart Webstorm
8. Open project and wait for indexing to finish
9. Ask question with `@codebase` 
10. Observe it correctly adds the context related files

**Comment by bigyoo** [comment]
I had the same issue and I was able to resolve it by deleting the local sqlite database. So try the following steps:

1. Shutdown Webstorm
2. Remove these two file: `~\.continue\index\index.sqlite` and `~\.continue\index\index.sqlite-wal`
3. Restart Webstorm and let Continue to rebuild the index.

**Comment by scpedicini** [comment]
Looks like the infinite redirect issue was fixed - so I'm going to close this issue out.
