### ISSUE TITLE
[CON-148] Diff accept/reject keyboard shortcuts broken

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#227]
null

<sub>[CON-148](https://linear.app/continue/issue/CON-148/diff-acceptreject-keyboard-shortcuts-broken)</sub>

**Comment by dandv** [comment]
Still broken for me in PyCharm on Linux: Alt+Y does nothing, Alt+N activates the Navigate menu.

Was following the tutorial in 0.0.50.

![image](https://github.com/continuedev/continue/assets/33569/479ab744-220e-4d6b-9feb-50fbcdfdc52d)
