### ISSUE TITLE
"Nothing to show" on Continue chat window

### ISSUE THREAD

**Issue by MESTIKAMAZAYA** [continuedev/continue#2280]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: 14.6.1 (23G93)
- Continue: 0.0.64
- IDE: Android Studio Koala Feature Drop | 2024.1.2
- Model: Deepseek
- config.json:
  {
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": "removed"
    },
    {
      "title": "DeepSeek Coder",
      "model": "deepseek-coder",
      "contextLength": 128000,
      "apiKey": "removed",
      "provider": "deepseek"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  },
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": "removed"
  }
}```
```

### Description

I use VS code & Android Studio, in VS code the Continue works fine but not in Android Studio. All I have is just a window showing "Nothing to show".

### To reproduce

Just click the Continue icon on the sidebar

**Comment by bigyoo** [comment]
I have the very same issue.

Tried the suggested solution from this artice, but unfortunately it didn't help: 
https://medium.com/@Syex/getting-continue-plugin-running-in-android-studio-4683b1b09115

**Comment by raniczny** [comment]
Hey, no need to disable `ide.browser.jcef.sandbox.enable` as that article suggests. 

Actions > `Choose Boot runtime for the IDE` > Choose the latest version (see below in the AS info and on the screenshot).

After restarting AS, the plugin will load.

```
Android Studio Koala Feature Drop | 2024.1.2 Patch 1
Build #AI-241.19072.14.2412.12360217, built on September 12, 2024
Runtime version: 21.0.2+13-b375.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.browser.jcef.jsQueryPoolSize=200
  ide.browser.jcef.contextMenu.devTools.enabled=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.continuedev.continueintellijextension (0.0.64)
```

<img width="758" alt="Screenshot 2024-09-21 at 17 36 54" src="https://github.com/user-attachments/assets/e32d157e-302e-400c-90ab-2815453bf10e">

**Comment by raniczny** [comment]
Ahhh, so looks like the default JBR in AndroidStudio doesn't include JCEF. 

I've tried 17 17.0.11+1-b1207.30-jcef and that one works fine too.

IntelliJ IDEA's default runtime already comes with JCEF, so that just works out of the box.

**Comment by MESTIKAMAZAYA** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/35fc03e4-cf57-4ae4-9878-513575c64b90">
I've tried to change it before with no luck

**Comment by MESTIKAMAZAYA** [comment]
After restoring all the AS registry to default, Continue works fine.

**Comment by Patrick-Erichsen** [comment]
Hi all, added some troubleshooting docs on this here: https://github.com/continuedev/continue/pull/2366

Thanks for the writeup @raniczny !

**Comment by raniczny** [comment]
Hey, a bit more info on this.

- It should be sufficient to use the current runtime version (e.g. 17), just with the JCEF
- It's probably a good idea to stick with the runtimes marked as `(bundled by default)`
- `JBRSDK` is not meant to be used for running the IDE, it will likely break the Android Studio (at least it broke mine)

If the Studio breaks completely and you can't get to the `Choose runtime` settings, you can revert to the default runtime by removing the chosen version from the `studio.jdk` file, e.g on macOS it's located at `/Users/<YOUR_USER>/Library/Application Support/Google/AndroidStudio<VERSION>/studio.jdk`.
