### ISSUE TITLE
The edit and ask tabs appear over the code and dont disappear

### ISSUE THREAD

**Issue by wilferraciolli** [continuedev/continue#2297]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.64
- IDE: Webstorm 2024 or inteliJ 2024
- Model:any
- config.json: any
```

### Description

When moving mouse over code, the tabs for edit and ask appears and do not go away, also it keeps coming more and more making the actual code hidden
![Untitled](https://github.com/user-attachments/assets/21c0f372-822d-40a9-a2bf-3effc1b25a7d)

### To reproduce

just move your mouse over any code and it starts stacking up

**Comment by coltonmccormack** [comment]
We are also seeing this behavior. It's been annoying enough that we had to disable Continue as it kept covering up code with frozen tooltips.

**Comment by pgrennin** [comment]
I am also seeing this issue.  Intellij, Mac.

**Comment by Patrick-Erichsen** [comment]
Thanks for the feedback all, tracking this in a main issue here: https://github.com/continuedev/continue/issues/2325
