### ISSUE TITLE
Issue when trying to integrate with custom RAG

### ISSUE THREAD

**Issue by ya-ds-web** [continuedev/continue#2298]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: windows / wsl
- Continue: 0.8.52
- IDE: vscode / intelij
- Model:
- config.json:
  

{
  "models": [
    {
      "model": "hugging-quants/Meta-Llama-3.99-405B-Instruct-AWQ-INT4",
      "title": "neterra",
      "apiBase": "http://127.0.0.1:8000/",
      "provider": "openai",
      "apiKey": "sk-c230a9f538fa4dd6afe0b3ef152dd8f7",
      "completionOptions": {
        "maxTokens": 1000,
        "stream": true
      }
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Starcoder 3b",
    "provider": "ollama",
    "model": "starcoder2:3b"
  },
  "contextProviders": [
    {
      "name": "http",
      "params": {
        "url": "http://127.0.0.1:8000/chat/completions",
        "title": "http",
        "description": "Custom HTTP Context Provider",
        "displayTitle": "My Custom Context"
      }
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
}
```

### Description

I am trying to configure the continue plugin to use our custom service for RAG. He have fast api service running in WSL which have 8000 port exposed. I read the documentation and make the service return result with correct object but the when I send request for completion the returned text from the object is not shown in the continue plugin.  

### To reproduce

1. Create fast api service with enpoint that will return object like: 

    context_items = []
    context_items.append({
        "name": "test text",
        "description": "test text",
        "content": "test text",
    }
    2. Send request from continue vs code plugin configured with the config above to the fast api service and make sure there are no errors
    3. Check the result, there should be some text in the plugin from the response of the service
    
    
![image](https://github.com/user-attachments/assets/52cec1f2-c02d-4611-af03-610bcbdda6b8)

additional: 

I try the IntelliJ plugin and the behavior was same, I was thinking that the issue was with the streaming of the response but I notice that in vs coder you can set :

      "completionOptions": {
        "maxTokens": 1000,
        "stream": false
      }
      
      and in vs code this property was applied but in intelij "stream": false is ignored it was aways true no matter what I set. 
      Also when i set "stream": false in vs code the it seems the whole communication with fast api beacks and I am not able to do other request untill I restart the whole wsl. 

### Log output

```Shell
I don't know how to get the logs
```

**Comment by dora-wang-x** [comment]
I have built a self-hosted knowledge base using ragflow + mcp and integrated it into continue. For detailed information, you can refer to this link https://mp.weixin.qq.com/s/_1tVMzH9NQY5TUIsBKvS0Q.
