### ISSUE TITLE
Update add new model form to include all required inputs

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#2323]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
- Model:
- config.json:
```

### Description

The current `AddModelForm` is missing required inputs for providers like `watsonx`.

![image](https://github.com/user-attachments/assets/79654d4a-d688-42b7-a406-65bea11d5d8e)

This is because we are only checking if the the given model has a `apiKeyUrl` requirement: https://github.com/continuedev/continue/blob/728e7767ca010726a533b1f768666b37f6ff6b9c/gui/src/forms/AddModelForm.tsx#L177-L203

This should be updated to instead iterate over all the input values in [`collectInputFor`](https://github.com/continuedev/continue/blob/728e7767ca010726a533b1f768666b37f6ff6b9c/gui/src/pages/AddNewModel/configs/providers.ts#L33-L34) that have a `"required": true` key/val. 

For some providers like watsonx that have multiple inputs this will likely cause some UI jank as the dialog expands in height to accommodate the new fields, so we should make sure to scroll the dialog rather than expand.

**Comment by ajshedivy** [comment]
@Patrick-Erichsen I opened a draft PR for a proposed fix: #2326. Let me know what you think and if there are other design elements that need to be taken into account. This should hopefully keep the functionality the same for providers that only require a `apiKey`. watsonx is one of the few "unique" providers where additional config options are needed
