### ISSUE TITLE
feature request - allow local Ollama server config.

### ISSUE THREAD

**Issue by WillCodeForEver** [continuedev/continue#2337]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When selecting Local models via Ollama it assumes that you'll run Ollama on the same machine as the IDE, Ollama also runs as a server on a LAN, would be nice to provide that as an option as well if possible.

### Solution

I like to run Ollama server on a separate machine and access it from my IDE. It would be nice to be able to provide a URL for local Ollama server: `http://<ip>:11434` and offload the model evaluation to another LAN connected machine.

**Comment by Patrick-Erichsen** [comment]
I might be naive here but could this be accomplished by setting the `apiBase`? 

https://github.com/continuedev/continue/blob/bc9ab739519f696c6ab77ff5c3b5e7913bd0232c/core/llm/llms/Ollama.ts#L14-L15

```json

{
  "models": [
    {
      "title": "Llama3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b",
      "apiBase": "<YOUR_API_BASE>"
    }
  ]
}

**Comment by WillCodeForEver** [comment]
@Patrick-Erichsen that worked! thanks, closing this issue

**Comment by Patrick-Erichsen** [comment]
It would be helpful if we included the ability to configure the API base here as part of onboarding with local models. Currently we hard code that to localhost which would make it impossible to actually finish local setup onboarding if you wanted to connect to a remote.

Curious if this is what you experienced?

**Comment by WillCodeForEver** [comment]
yep that is what i experienced, it would be great to show the `apiBase` property set to the localhost:port with a little note about it being the default and ability to change it if you are running Ollama elsewhere in your network. 
I did find the JSON config but didn't see any default config, so thought maybe it wasn't using the server but the CLI to issue the commands....either exposing the baseApi in the JSON or UI would be helpful

**Comment by hundrix** [comment]
It would be more convenient to use multiple remote servers for different purposes. For instance, one could have a remote Ollama server running a 1.5B model for autocomplete tasks on a continuously running home server, while another server could utilize a larger model with a bigger context size for more demanding jobs.
