### ISSUE TITLE
Continue switches to first model when force reloading window in VSC

### ISSUE THREAD

**Issue by moesmufti** [continuedev/continue#2344]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14.6.1
- Continue: v0.9.211
- IDE: Visual Studio Code
```

### Description

When force reloading the window (e.g. to refresh index) in VSC - the model reverts back to the first model in the config.json. At least, it looks like that in the output screen of VSC.

### To reproduce

1. Select another model (in my case o1-mini) that is not the first in the config.json
2. Force reload using CMD Shift P
3. Re-run (in my case codebase) prompt - it reverts to first model

**Comment by Patrick-Erichsen** [comment]
Hi @moesmufti , this isn't the behavior I'm experiencing. When I select the last model from the model dropdown and then refresh, that model is still my default. 

<img width="532" alt="Screenshot 2024-09-23 at 4 32 42 PM" src="https://github.com/user-attachments/assets/15e0a1e3-4585-4ddb-b7aa-a00f29ce9e0c">

Could you clarify what you mean by "the output screen of VSC"?

**Comment by moesmufti** [comment]
Hi @Patrick-Erichsen, the output screen I'm referring to is the tab next to terminal. See image below:
![Screenshot 2024-09-24 at 15 03 52](https://github.com/user-attachments/assets/44311f04-bb54-4263-bddf-f0a4c7d42cc7)
There, when I do a reload - even though the default model stays the same as you demonstrated - in the output tab of VSC I see a different model. Only after switching back and forth, it will return to the model I had selected before.

I hope that makes more sense?

**Comment by moesmufti** [comment]
It seems that it has been fixed by now, thanks anyway!
