### ISSUE TITLE
Model Pixtral 12B is missing image upload feature on continue

### ISSUE THREAD

**Issue by Altroo** [continuedev/continue#2354]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
windows 11
- Continue:
0.0.64 
- IDE:
pycharm
- Model:
pixtral-12b
- config.json:
  
    {
      "model": "mistralai/pixtral-12b:free",
      "title": "Pixtral 12B (images)",
      "provider": "openai",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "xxx"
    },
```

### Description

As explained in the title Model Pixtral 12B is missing image upload feature on continue.

**Comment by Patrick-Erichsen** [comment]
Thanks for mentioning this! Done: https://github.com/continuedev/continue/pull/2364
