### ISSUE TITLE
Add support for model providers in china

### ISSUE THREAD

**Issue by Kannmu** [continuedev/continue#2397]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I found the model providers supported in config.json are still limited. It would be better to add more model providers, particularly chinese companies.

### Solution

I listed a few of chinese model providers website in below:
[Moonshot](https://www.moonshot.cn/)
[ChatGLM](https://chatglm.cn/)
[Qwen](https://tongyi.aliyun.com/)

**Comment by Patrick-Erichsen** [comment]
Hi @Kannmu , agreed! We do support [DeepSeek](https://docs.continue.dev/customize/model-providers/deepseek) currently, and any given provider that is [OpenAI compatible](https://docs.continue.dev/customize/model-providers/openai#openai-compatible-servers--apis). 

In the meantime, it's relatively straightforward to contribute a new provider if you'd be interested! Docs here: https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#adding-an-llm-provider

**Comment by smxsm** [comment]
I can't get DeepseekCoder  locally via ollama to output anything useful for autocomplete ... what are the "template" settings required? This is what I tried to guess from the Deepseek docs, but it doesn't work:
```json
  "tabAutocompleteModel": {
    "title": "Deepseek Coder",
    "provider": "ollama",
    "model": "deepseek-coder:6.7b-base"
  },
  "tabAutocompleteOptions": {
    "useCopyBuffer": false,
    "maxPromptTokens": 1024,
    "prefixPercentage": 0.3,
    "useOtherFiles": true,
    "multilineCompletions": "always",
    "template": "<|fim_begin|>{{{prefix}}}<|fim_hole|>{{{suffix}}}<|fim_end|>"
  },
```
Is there a list somewhere with "template" values for the different models?

**Comment by Patrick-Erichsen** [comment]
@smxsm this is the template we are using: https://github.com/continuedev/continue/blob/cf8b4bdc4391e5c027cf72756fee21843bd1e9d4/core/autocomplete/templates.ts#L170-L171

`<｜fim▁begin｜>{{{prefix}}}<｜fim▁hole｜>{{{suffix}}}<｜fim▁end｜>`

Looks identical to what you have. 

Anything in the [logs](https://docs.continue.dev/troubleshooting#check-the-logs) you could share?

**Comment by smxsm** [comment]
@Patrick-Erichsen weird, tried again, without setting any options (tried that before, too) and it works now ... no idea what has changed. Sorry for the confusion! The only thing making problems seems to be if the model is too large (that's my guess at least) and the response seems to take too long, then I see a correct and full completion in the Continue log, but it is not added to the source / editor  - may that be a timing / timeout issue, can I configure that? Happens with e.g. "codebooga:latest" (19GB) on an M3 Max with 64GB RAM.

**Comment by Patrick-Erichsen** [comment]
Thanks for the followup here! My hunch is that you're correct about model size/latency being an issue here. I think this is probably a good opportunity for us to improve the logs to try and make this more clear, e.g. the issue isn't due to configuration but instead latency.
