### ISSUE TITLE
ff

### ISSUE THREAD

**Issue by jaydenbellmusic** [continuedev/continue#2398]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
- Model:
- config.json:
```

**Comment by Altroo** [comment]
Press F to pay respect.

**Comment by sestinj** [comment]
Closing the issue for obvious reasons : ) But please feel free to re-open with more details!
