### ISSUE TITLE
Experimental release lost model selection list

### ISSUE THREAD

**Issue by surak** [continuedev/continue#2400]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Mac
- Continue:today's experimental
- IDE:vscode
- Model:none
- Config:

  "models": [
    {
      "model": "AUTODETECT",
      "title": "Blablador",
      "apiKey": "glpat-blabla",
      "apiBase": "https://helmholtz-blablador.fz-juelich.de:8000/v1",
      "provider": "openai"
    },
```
```


### Description

There was a model list for the multiple models on my openai-compatible server. This selection list is gone.

### To reproduce

-do a new session
- the model list is gone
- 

### Log output

_No response_

**Comment by sestinj** [comment]
@surak Is this the dropdown that you are referencing?

<img width="554" alt="Screenshot 2024-09-26 at 8 28 49 AM" src="https://github.com/user-attachments/assets/ab3ba435-d298-4c60-8d73-c585ff7fb7f3">

**Comment by surak** [comment]
Exactly. It went missing in the latest experimental update. Reverting to the production release brought it back.

**Comment by surak** [comment]
Is it known? Is it desired to remove the list? Do I close this, what do I do? :-)

**Comment by sestinj** [comment]
@surak I think what happened is that it's just disappearing when the sidebar is too narrow—we recently did a lot of work to make the UI more responsive. Let me know if this is the case. We'd then probably want to change which buttons disappear first for users with extremely narrow sidebars

**Comment by surak** [comment]
Damn, you are right! It disappears when using the laptop screen, which is smaller and makes continue smaller.

Yes, it's exactly that and it's a very strange design decision. I would not know where to look for it, it's unexpected and inconsistent. But now I know. Thanks!

**Comment by Patrick-Erichsen** [comment]
@surak thanks for the feedback here! Updated so that the model selector is always visible: https://github.com/continuedev/continue/pull/2431

**Comment by surak** [comment]
Great, thanks!
