### ISSUE TITLE
Add Llama 3.2 to Chat models

### ISSUE THREAD

**Issue by XavierElon** [continuedev/continue#2459]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Meta just released the 3.2 with Lightweight 1B & 3B and Multimodal 11B & 90B. It would be nice to have the option to use this as one of the models.]
[https://www.llama.com/](llama)

**Comment by RomneyDa** [comment]
@Patrick-Erichsen
@sestinj 
- should 3.2 replace 3.1 as default for onboarding, docs, etc.?
- should/can support be added for multimodal?
- does llm-info package need to be maintained? `packages/llm-info`

**Comment by RomneyDa** [comment]
@sestinj adding your other comment on replacing llama 3.1 with 3.2 here:
> Llama3.2 was more focused on multi-modal and edge (small) models, so they didn’t turn out to be as good for code. The one of comparable size to llama3.1 8b that we would recommend (llama 3.2 11b) does much worse on coding benchmarks:
https://ai.meta.com/blog/meta-llama-3-1/
https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/
Meta AIMeta AI
[Llama 3.2: Revolutionizing edge AI and vision with open, customizable models](https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/)
Today, we’re releasing Llama 3.2, which includes small and medium-sized vision LLMs, and lightweight, text-only models that fit onto edge and mobile devices.

**Comment by RomneyDa** [comment]
TODO
- update [Prompt Templates](https://github.com/continuedev/continue/blob/main/core/llm/index.ts) `autodetectTemplateType` function to return correct template type per model
- update `ModelName` in [index.d.ts](https://github.com/continuedev/continue/blob/main/core/index.d.ts) 
- update core/llm/llms/<provider> (model name translation), `config_schema.json`,  `config_rc_schema.json` for providers:
  - Groq
  - Cerebras
  - [Ollama](https://ollama.ai/library)
  - [Replicate](https://replicate.com/collections/streaming-language-models)
  - SambaNova
  - [Together](https://github.com/continuedev/continue/blob/main/core/llm/llms/Together.ts)
- update gui/AddNewModel with ModelPackage and add to providers
- update autodetect.ts - matchers for models that support multi-modal
- add note to docs/customize/tutorials llama 3.1 page about 3.2 also being supported but not recommended
- update docs/customize/model-providers/more cerebras.md with note about 3.2
- gui/src/pages/addNewModal/configs/providers sambanova cloud copy about llama 3.1?
- docs/customize deepdives - note 3.2 also includes repo map
- update core/llm/llms/freetrial? prob not
- update llm-info package including Bedrock provider models
- test
