### ISSUE TITLE
[CON-163] And this tooltip is a bit confusing because the paper with a plus icon next to it says add to context on hover? Not really sure what the context is here

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#249]
![Linear-hosted image](https://user-images.githubusercontent.com/13314504/253058112-ffc3cef8-1886-456a-9f2c-2e5d085fc018.jpeg)
[Image source](https://user-images.githubusercontent.com/13314504/253058112-ffc3cef8-1886-456a-9f2c-2e5d085fc018.jpeg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-163](https://linear.app/continue/issue/CON-163/and-this-tooltip-is-a-bit-confusing-because-the-paper-with-a-plus-icon)</sub>

**Comment by sestinj** [comment]
Alternate words for context:
- Chat history
- Context window
- Model Input
- Prompt
- Preamble
- Background information
- System message
- History

I think context is best of these. When this discussion was happening, was the confusion ONLY that they didn't know what context meant, or were the tooltips unclear for additional reasons?

**Comment by TyDunn** [comment]
I opted for clarity: `Add more code to context` -> `Highlight code section`
