### ISSUE TITLE
/commit only for files in staged status

### ISSUE THREAD

**Issue by mike2003** [continuedev/continue#2500]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The current command \commit `git diff` collects data about all files and changes. It would be better if it (or another new command) collected information only about the files I have staged for commit, rather than just ALL files.

### Solution

use git diff --staged (or git diff --cached) to see the diff that will be used when committing.

**Comment by mike2003** [comment]
```
          const staged = await repo.diff(true);
          const unstaged = await repo.diff(false);
          diffs.push(`${staged}
${unstaged}`);
        }
```
maybe it would be good to have a setting here for those who need it

**Comment by Patrick-Erichsen** [comment]
We actually have a PR open for this right now! https://github.com/continuedev/continue/pull/1948

Should be merged shortly.

**Comment by MahbodHastam** [comment]
@Patrick-Erichsen Do you know how do I customize the commit message template?

**Comment by sestinj** [comment]
You can write a prompt file to achieve this @MahbodHastam: https://github.com/continuedev/continue/blob/f19cec4e0944773142b3d6414e2b76f38bcf3f66/docs/docs/customize/deep-dives/prompt-files.md
