### ISSUE TITLE
Error generating autocompletion - OpenWebUI with Codestral

### ISSUE THREAD

**Issue by tajchert** [continuedev/continue#2502]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:MacOS 15.0.1
- Continue version: v0.9.215 
- IDE version: VS Code 1.94.0
- Model: Codestral thru OpenWebUI
- config.json:
  
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "openai",
    "model": "mistralai/codestral-mamba",
    "apiBase": "https://{DELETED_DOMAIN}/api/chat/",
    "apiKey": "{DELETED}",
    "contextLength": 256000
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 500,
    "maxPromptTokens": 1500,
    "disableInFiles": ["*.md"]
  },
```

### Description

I'm using OpenWebUI as a proxy/authentication for my models, it works well with chat but doesn't work with autocomplete. Seems like a request has a different schema than one `/completions` [endpoint with OpenWebUI can accept](https://docs.openwebui.com/api/#-chat-completions) and it is returning 500 Internal Server error. This is unexpected as chat feature that is using the same endpoint works without any issue.

### Log output

```Shell
Console:

[Extension Host] Error generating autocompletion:  Error: HTTP 500 Internal Server Error from https://{DELETED_DOMAIN}/api/chat/completions

{"detail":"'messages'"}
	at customFetch (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:106005:19)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:105687:26)
	at async OpenAI2._legacystreamComplete (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:485680:26)
	at async OpenAI2._streamChat (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:485696:28)
	at async OpenAI2._streamComplete (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:485669:26)
	at async OpenAI2.streamComplete (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:106102:26)
	at async ListenableGenerator._start (/Users/mtajchert/.vscode/extensions/continue.continue-0.9.215-darwin-arm64/out/extension.js:97638:28)
G_i @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
```

Also Output from VS Code:
```
==========================================================================
==========================================================================
##### Completion options #####
{
  "contextLength": 256000,
  "model": "mistralai/codestral-mamba",
  "maxTokens": 2048,
  "temperature": 0.01,
  "stop": [
    "[PREFIX]",
    "[SUFFIX]",
    "\n\n",
    "\r\n\r\n",
    "/src/",
    "#- coding: utf-8",
    "```",
    "\ndef",
    "\nclass",
    "\n\"\"\"#"
  ],
  "raw": true
}

##### Prompt #####
[SUFFIX]




https://{DELETED_DOMAIN}/api/chat/completions {"detail":"'messages'"}[PREFIX]# List of numbers
numbers = [6, 9, 1, 7, 3, 5, 2, 8, 4]

# Sort the list
numbers.sort()

# Print the sorted list
 
```
```

**Comment by Patrick-Erichsen** [comment]
Hi @tajchert , it sounds like you are attempting to use the `/completions` endpoint in OpenWebUI for autocomplete? 

Autocomplete requires a specific message template that is different from chat and the two are not compatible ([see the docs](https://docs.continue.dev/customize/model-types/autocomplete)). 

If you're looking for a local experience Ollama might be a good option: https://docs.continue.dev/autocomplete/model-setup#local-offline--self-hosted-experience

**Comment by tajchert** [comment]
Thanks. I thought this endpoint could be used also for autocomplete.
So in such this if a lack of this feature support on OpenWebUI site (if any, as this might or might not be supported in the future by them). Thanks, I will consider my options on exposing such endpoint.
