### ISSUE TITLE
Azure embeddings provider seems not to be supported even though it's mentioned in the docs

### ISSUE THREAD

**Issue by KramPiotr** [continuedev/continue#2510]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version:
- IDE version:
- Model: text-embedding-3-large
- config.json:
  
  "embeddingsProvider": {
    "provider": "azure",
    "model": "text-embedding-3-large",
    "apiBase": "https://<something>.openai.azure.com",
    "engine": "text-embedding-3-large",
    "apiVersion": "2023-05-15",
    "apiType": "azure",
    "apiKey": "<something>"
  },
```

### Description

The error I am getting:
`Error getting context items from folder: TypeError: this.embeddingsProvider.embed is not a function.`

I checked in the codebase that azure is not mentioned as an embeddings provider, is that the case?
https://github.com/continuedev/continue/blob/4124c214eb885842d6b5d975dfc00650a518bd7f/core/indexing/embeddings/index.ts#L24

**Comment by KramPiotr** [comment]
Ahh, I read through the code more and it just seems that the provider should be set to "openai" in the config and then all works. Sorry for the trouble. I hope other people will find this useful

**Comment by KramPiotr** [comment]
You should fix your docs though to mention "openai" as the provider

**Comment by victorlin** [comment]
c2157a410bbd858056331ea077115c483b88f735 updated the docs with `"provider": "openai"`, however it also removed `"engine": "text-embedding-3-large"` which I found to be necessary.
