### ISSUE TITLE
Partly accept in JetBrains IDE

### ISSUE THREAD

**Issue by facelezzzz** [continuedev/continue#2516]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Does JetBrains IDE support partly accept?

**Comment by sestinj** [comment]
@facelezzzz Currently this is possible with option+command+right

**Comment by facelezzzz** [comment]
It works, thank you
