### ISSUE TITLE
Autocomplete should work simultaneously when triggering the IDE's built-in completion in Intellij IDEA

### ISSUE THREAD

**Issue by facelezzzz** [continuedev/continue#2518]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When triggering the IDE's built-in completion in Intellij IDEA, simultaneously trigger and display completions from Continue.

The image shows Baidu's Comate, and the continue does not display the grayed-out part in this case. Is it because I made a mistake or overlooked something?

![20241014171924](https://github.com/user-attachments/assets/a0ac9068-f272-443f-9ac7-e23f228a8ea3)

**Comment by tobiajung** [comment]
I have the same problem with CLion.
Whenever the suggestions of the IDE pop up, the suggested completion from Continue disappers.
