### ISSUE TITLE
When using /edit, the first line above the marked code area disappears.

### ISSUE THREAD

**Issue by goveebee** [continuedev/continue#2520]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Win 10 Enterprise
- Continue version:v0.9.215
- IDE version: VSCode
- Model: Same for all models, We run on local Ollama
- config.json:
  
{
  "models": [
    {
      "title": "CodeLlama",
      "provider": "ollama",
      "model": "codellama:latest",
      "apiBase": "xxx"
    },
    {
      "title": "Default (llama3-8b Q4)",
      "provider": "ollama",
      "model": "llama3:latest",
      "apiBase": "xxx"
    },
    {
      "title": "Llama3-70b-Q8_0",
      "provider": "ollama",
      "model": "llama3:70b-instruct-q8_0",
      "apiBase": "xxx"
    },
    {
      "title": "Llama3.1",
      "provider": "ollama",
      "model": "llama3.1:latest",
      "apiBase": "xxx"
    },
    {
      "title": "codegeex4",
      "provider": "ollama",
      "model": "codegeex4",
      "apiBase": "xxx"
    }
  ],
  "tabAutocompleteModel": {
    "title": "codegeex4",
    "provider": "ollama",
    "model": "codegeex4",
    "apiBase": "xxx"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text",
    "apiBase": "xxx"
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "open",
      "params": {
        "onlyPinned": true
      }
    },
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
}
```

### Description

I mark a piece of code and use crtl + l to open Continue, then use /edit and prompt the LLM. In the diff-window, the first row  of code (and the last) is deleted.
I've tested with different models, different type of code. Same result.
![continue-error](https://github.com/user-attachments/assets/00bf4699-ca31-469a-ba7c-5453512232dc)

### To reproduce

1. Open file to edit
2. Mark code to ask questions about.
3. Ctrl + L to open Continue and insert the marked code.
4. "/edit" to edit the code. Ask the LLM  question.
5. Check the edits.
6. First row missing in right window. See image above.

**Comment by sestinj** [comment]
Hey @goveebee! Thanks for the report. This should be solved now along with our new cmd+I UI for making edits

**Comment by hug-sch** [comment]
@sestinj @goveebee Hi, using the Edit-mode (cmd+i) with markdown text,  I noticed that the new cmd+I now displays the complete original text but crammed into one line. You can scroll horizontally to the end of the text, but this is of course not handy. The changed text is displayed on multiple lines.
Is there a work-around for this inconvenience?
