### ISSUE TITLE
Make the maximum files to index configurable (currently fixed to 500)

### ISSUE THREAD

**Issue by tbressers** [continuedev/continue#2532]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The maximum files to index is not configurable (currently fixed to 500)

### Solution

Can you make it configurable?

**Comment by malaki12003** [comment]
@tbressers, are you certain that 500 is the maximum number of files that can be indexed? From what I’ve seen in the indexing section, we have filesPerBatch = 500, which is intended to limit memory usage during indexing and minimize the number of requests made to the embedding providers. However, this doesn't mean the total number of files that can be indexed is limited to 500.

**Comment by tbressers** [comment]
Ah! I must have misunderstood, I’ll check it but you can close this one. 

Thank you!!
