### ISSUE TITLE
'inferenceConfig.stopSequences' failed to satisfy constraint: Member must have length less than or equal to 4

### ISSUE THREAD

**Issue by hongbo-miao** [continuedev/continue#2538]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

- OS: macOS 15.0 (24A335)
- Continue version: 0.0.75
- IDE version: IntelliJ IDEA 2024.1.4 & VSCode 1.94.1
- Model: Claude 3.5 Sonnet through provider AWS Bedrock
- config.json:
  
```json
{
  "models": [
    {
      "title": "claude-3-5-sonnet",
      "provider": "openai",
      "apiBase": "https://litellm.example.com",
      "apiKey": "xxx",
      "model": "claude-3-5-sonnet"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete",
    "provider": "openai",
    "apiBase": "https://litellm.example.com",
    "apiKey": "xxx",
    "model": "claude-3-5-sonnet",
    "maxStopWords": 4
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 500,
    "maxPromptTokens": 1500
  },
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit highlighted code"
    },
    {
      "name": "comment",
      "description": "Write comments for the highlighted code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "open",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    }
  ],
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  }
}
```

### Description

My Continue "chat" and "edit" functions work well. Thanks! ☺️

Now I am trying to set up autocomplete now. Here is my setup:

AWS Bedrock -> LiteLLM (proxy & gateway) -> Continue

Based on the error I got

> inferenceConfig.stopSequences' failed to satisfy constraint: Member must have length less than or equal to 4

I tried to add `"maxStopWords": 4` based on https://github.com/continuedev/continue/blob/4124c214eb885842d6b5d975dfc00650a518bd7f/extensions/vscode/config_schema.json#L267-L271

which looks like

```json
  ...
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete",
    "provider": "openai",
    "apiBase": "https://litellm.example.com",
    "apiKey": "xxx",
    "model": "claude-3-5-sonnet",
    "maxStopWords": 4
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 500,
    "maxPromptTokens": 1500
  },
  ...
```

But I still got same error. So this `"maxStopWords": 4` seems not functioning.

### To reproduce

1. Go to any code like Python file
2. Continue typing some code to wait Continue to auto complete

### Log output

Continue log (Jetbrains `~/.continue/logs/core.log`):

```sh
[2024-10-15T21:10:31] Error generating autocompletion:  Error: Malformed JSON sent from server: {"error": {"message": "litellm.BadRequestError: BedrockException - {\"message\":\"1 validation error detected: Value '[</COMPLETION>, \\n\\n, \\r\\n\\r\\n, /src/, #- coding: utf-8, , \\ndef, \\nclass, \\n\\\"\\\"\\\"#]' at 'inferenceConfig.stopSequences' failed to satisfy constraint: Member must have length less than or equal to 4\"}", "type": null, "param": null, "code": "400"}}
```

LiteLLM log: https://gist.github.com/hongbo-miao/b10b9785997e6078b9290cb30af5ccf2

### Potential Related Issues

- https://github.com/continuedev/continue/issues/2296

**Comment by malaki12003** [comment]
@hongbo-miao, it appears that the issue is related to stopSequences. According to the AWS documentation, the number of stopSequences should be between 0 and 4. The values for stopSequences are derived from stop. I believe if you add completionOptions as shown below, the issue might be resolved.

  "tabAutocompleteModel": {
    "title": "Tab Autocomplete",
    "provider": "openai",
    "apiBase": "https://litellm.example.com",
    "apiKey": "xxx",
    "model": "claude-3-5-sonnet",
    "maxStopWords": 4,
    "completionOptions": {
      "stop": []
    }
  }

**Comment by malaki12003** [comment]
@sestinj @Patrick-Erichsen, I believe the issue lies in the following lines:
https://github.com/continuedev/continue/blob/4124c214eb885842d6b5d975dfc00650a518bd7f/core/autocomplete/completionProvider.ts#L637-L646

We likely need to limit the number of items in the stop array by introducing something like maxStopWords here:
https://github.com/continuedev/continue/blob/4124c214eb885842d6b5d975dfc00650a518bd7f/core/llm/llms/Bedrock.ts#L114
If you'd like, I'm happy to take care of the fix. :)

**Comment by hongbo-miao** [comment]
Thanks @malaki12003 I can confirm adding extra `completionOptions` still not work. So may need some source code updates.

```json
  "tabAutocompleteModel": {
    ...
    "maxStopWords": 4,
    "completionOptions": {
      "stop": []
    }
  }
```

**Comment by Patrick-Erichsen** [comment]
Hi @malaki12003 , that would be awesome! 😁  I think your proposed solution makes sense.

**Comment by malaki12003** [comment]
@Patrick-Erichsen I’ve added comments in the code to highlight areas for potential future improvements.

**Comment by Lash-L** [comment]
I did a little debugging on this as I was facing the same issue with a different provider. The BaseLLM class set maxStopWords correctly. But when _convertArgs() is called, maxStopWords is back to undefined. Perhaps there is a incorrect copying of the object or something along those lines?

**Comment by hongbo-miao** [comment]
I can confirm

- v0.0.80 works well on my IntellIJ IDEA
- v0.8.57 works well on my VSCode

Thanks! ☺️
