### ISSUE TITLE
Unable to use it in VS code Arm 64 PC

### ISSUE THREAD

**Issue by vikrantSinghOnGithub** [continuedev/continue#2546]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version: 0.8.54 - 2024-10-15
- IDE version: vs code 1.94.2
- Model: surface laptop 7
- config.json:
```

### Description

continue-0.8.54-win32-arm64\out\build\Release\node_sqlite3.node is not a valid Win32 application.
\\?\c:\Users\vikra\.vscode\extensions\continue.continue-0.8.54-win32-arm64\out\build\Release\node_sqlite3.node

### Log output

```Shell
continue-0.8.54-win32-arm64\out\build\Release\node_sqlite3.node is not a valid Win32 application.
\\?\c:\Users\vikra\.vscode\extensions\continue.continue-0.8.54-win32-arm64\out\build\Release\node_sqlite3.node
```

**Comment by sestinj** [comment]
@vikrantSinghOnGithub Thanks for the report—I'm going to close this in favor of a pre-existing duplicate, where I'll be giving updates as we work on the solution: https://github.com/continuedev/continue/issues/839
