### ISSUE TITLE
last lines not showing up

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#256]
I ask it to `/edit change this code to load the csv into a python dict object and then print it out with indent-4`. It tells me it "Indented the print statement by 4 spaces to match the requested output format.", but that is not in the diff. I try again: "/edit edit this code to print out the data dict", and it titles it "Print Data Dict" and I can see print code flash for a second before it all turns green on the last three lines

![Image](https://user-images.githubusercontent.com/13314504/252859942-226a4a28-65a2-463b-a388-029867fa0614.png)

**Comment by sestinj** [comment]
@TyDunn has this ever happened since? I have reason to believe I've fixed it by force refreshing the contents of the file, but want to make sure

**Comment by TyDunn** [comment]
@sestinj I have not seen it again
