### ISSUE TITLE
Inquiry on Release Timeline for Bug Fix #2554

### ISSUE THREAD

**Issue by bsnmldb** [continuedev/continue#2565]
Hello,

I noticed that the bug fix in [#2554](https://github.com/continuedev/continue/pull/2554) was recently merged. I understand that the preferred channel for such inquiries is the "Something else? Message us on Discord :)" section, but I’ve been unable to join the Discord group.

This bug is significantly impacting my work, and I would greatly appreciate it if you could provide an estimated timeline for when the fix will be included in a new release on the Visual Studio Code Marketplace.

Thank you for your time and for all the hard work you do on this project!

Best regards!

**Comment by Patrick-Erichsen** [comment]
Hi @bsnmldb , apologies for the delay here. Just merged that bugfix and will have a new pre-release out by end of day. The main release will be available by end of day Friday (Oct 25).

**Comment by bsnmldb** [comment]
Thank you for response and update! Your hard work on this project is greatly appreciated!
