### ISSUE TITLE
[CON-170] This example didn’t do what I expected for a large refactor. Deleted a ton of relevant code (the write model). Command: /edit Modify all the `ReadModel` types so the only thing they do is extend SequelizeFields, leave the rest of the code as is. 436 lines of code

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#257]
null

<sub>[CON-170](https://linear.app/continue/issue/CON-170/this-example-didnt-do-what-i-expected-for-a-large-refactor-deleted-a)</sub>

**Comment by sestinj** [comment]
@TyDunn is this something you did, or someone else?

**Comment by sestinj** [comment]
@TyDunn bumping. Sorry if you answered my q somewhere else

**Comment by TyDunn** [comment]
@sestinj Let's discuss on the call
