### ISSUE TITLE
No handler for message type "config/getSerializedProfileInfo"

### ISSUE THREAD

**Issue by nikhil-swamix** [continuedev/continue#2578]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: Every version update
- IDE version: Vscode X.X
- Model:
- config.json:
```

### Description

# this is happening since last 8 years! nobody is paying attention
![image](https://github.com/user-attachments/assets/c4ed0076-e3cb-4554-9846-b7bef116fed4)

### To reproduce

just wait for next version to release

**Comment by sestinj** [comment]
@nikhil-swamix I'm going to close this in favor of the other issue you had opened here: https://github.com/continuedev/continue/issues/2295
