### ISSUE TITLE
[CON-283] cmd+L to toggle chat window

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#2585]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

If the focus is on input box, cmd+L should close the chat sidebar

<sub>[CON-283](https://linear.app/continue/issue/CON-283/cmdl-to-toggle-chat-window)</sub>

**Comment by RomneyDa** [comment]
fixed by https://github.com/continuedev/continue/pull/2834
