### ISSUE TITLE
Gemini Pro/Flash 1.5 - slow output token rendering

### ISSUE THREAD

**Issue by robertpiosik** [continuedev/continue#2586]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model: Gemini Flash 1.5
- config.json:
```

### Description

Tokens are displayed slower than the API sends them. I'm comparing to using Gemini models via API in other frontends like Open WebUI and AI Studio.

**Comment by sestinj** [comment]
Well this is kind of embarrassing, but there's a very explicit reason for this. We used to buffer the responses from Gemini and stream them at a consistent rate to avoid the jumpiness of the API. But haven't checked back in on this code in a while and now it's streaming much slower than gemini flash. Here's the fix, which will be in the next release: https://github.com/continuedev/continue/commit/47c9034e810a66e6c4a1485b82ffde89d3dad13e

**Comment by sestinj** [comment]
thanks for calling this out!
