### ISSUE TITLE
Copy context and prompt to clipboard

### ISSUE THREAD

**Issue by robertpiosik** [continuedev/continue#2591]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I would like to use specific chatbot UI in the browser for the same prompt and context.

### Solution

User can copy prompt and context to clipboard in the same form continue sends to LLM internally.

**Comment by sestinj** [comment]
@robertpiosik Do the prompt logs solve this? https://docs.continue.dev/troubleshooting#llm-prompt-logs
