### ISSUE TITLE
Support text embedding from LM Studio

### ISSUE THREAD

**Issue by joselael** [continuedev/continue#2599]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

continue doesn't support lm studio as an embedding model provider, although lm studio supports serving embedding endpoint. related: #2149

### Solution

Implement support for lm studio embedding models

**Comment by RomneyDa** [comment]
TODO
- add lmstudio to `embeddingsProvider` section of `config_schema.json`
- add embeddings model section to docs `customize/model-providers/more/lmstudio`
- add LM Studio section to `customize/model-types/embeddings` which links to ^
- check #2149 and #2527, maybe all related

**Comment by RomneyDa** [comment]
fixed by https://github.com/continuedev/continue/pull/2847
