### ISSUE TITLE
qwen2.5-coder-7b autocomplete not working

### ISSUE THREAD

**Issue by xiaolucy1** [continuedev/continue#2616]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: windows
- Continue version: 0.9.217
- IDE version: vscode 1.93.1
- Model: qwen2.5-coder-7b
- config.json:
  
     "tabAutocompleteModel": {
        "title": "qwen",
        "provider": "openai",
        "model": "qwen2.5-coder-7b",
        "apiKey": "xxxx",
        "apiBase": "http://xxxx/v1"
  },
  "tabAutocompleteOptions": {
     "debounceDelay": 100,
     "maxPromptTokens": 512,
     "multilineCompletions": "always",
     "disableInFiles": ["*.md"]
  },
```
qwen2.5-coder-7b is deployed by vllm.

### Description

continue doesn't autocomplete the code, check the prompt log, the completion is not code

### Log output

```Shell
##### Completion options #####
{
  "contextLength": 8096,
  "model": "qwen2.5-coder-7b",
  "maxTokens": 2048,
  "temperature": 0.01,
  "stop": [
    "<|endoftext|>",
    "<|fim_prefix|>",
    "<|fim_middle|>",
    "<|fim_suffix|>",
    "<|fim_pad|>",
    "<|repo_name|>",
    "<|file_sep|>",
    "<|im_start|>",
    "<|im_end|>",
    "\n\n",
    "\r\n\r\n",
    "/src/",
    "#- coding: utf-8",
    "",
    "\ndef",
    "\nclass",
    "\n\"\"\"#"
  ],
  "raw": true
}

##### Prompt #####
<|fim_prefix|>
def main():
    print("hello world")
    print<|fim_suffix|>

    <|fim_middle|>==========================================================================
==========================================================================
Completion:

 It looks like your code is incomplete. Here's a more complete version of the `main` function that prints "hello world" and then prints a newline:
```

**Comment by xiaolucy1** [comment]
> You can set "vllm" as a provider instead of openai. It might not be the problem though.

we use openrouter as gateway, which forward requests to model deployed by vllm. The provider is  openrouter or vllm?

**Comment by xiaolucy1** [comment]
found the reason of problem. could close it.

**Comment by bibendi** [comment]
Hey @xiaolucy1! What was the reason? I faced that as well.

**Comment by SkyTik** [comment]
I hate this kind of guy, who found the solution and just left

**Comment by sameleff** [comment]
> found the reason of problem. could close it.

@xiaolucy1 what was the solution?
