### ISSUE TITLE
Grok AI support

### ISSUE THREAD

**Issue by baoduy** [continuedev/continue#2631]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Grok recently release a beta version of ai model. Hope continue is support Grok API soon.

**Comment by RomneyDa** [comment]
@baoduy just to be clear, you mean Grok?
https://docs.x.ai/docs

**Comment by baoduy** [comment]
Yes correct. Sorry for wrong spelling 😊

**Comment by dixpix** [comment]
+1 for adding this provider as soon as you can.
Actually tested on Cline, X.AI's model grok-beta is accurate and VERY fast...

**Comment by G3mha** [comment]
Is there someone working this issue? I would like to contribute, if it's available.

**Comment by RomneyDa** [comment]
Hi @G3mha sorry forgot to close!
Fixed by #2817

**Comment by zhaohan-dong** [comment]
Any ideas on when this would be released?
