### ISSUE TITLE
[STYLE]The drop-down box is not visible

### ISSUE THREAD

**Issue by rwerplus** [continuedev/continue#2634]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

### Description

After I open the pop-up window to switch models, the text in the drop-down box is not visible, the theme I am using is vitesse dark.
![image](https://github.com/user-attachments/assets/dd7cd425-9e86-4864-92d0-62e4afcd81a0)

### To reproduce

1. click left menu's continue function
2. click model select
3. see the Add Chat model
4. click select,only see icon,but the text invisible

**Comment by Parth4git** [comment]
@sestinj Can I work on this issue.

**Comment by sestinj** [comment]
We just merged a fix for this before I saw your comment. Let me know if there are other issues you're interested in and I'll gladly assign you!
