### ISSUE TITLE
The config.json configuration in the.continue directory cannot be read during Jetbrains debugging. How can I modify the debugging?

### ISSUE THREAD

**Issue by who52023** [continuedev/continue#2640]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When debugging with Run Extension in intellij, the config.json file in the.continue directory could not be read, causing the configuration to be invalid

**Comment by who52023** [comment]
Modify the binary /. Continue/config. Json has been solved

**Comment by Patrick-Erichsen** [comment]
Good callout here! I've updated the contributing docs to make this more clear: https://github.com/continuedev/continue/pull/2646/files#diff-fa29d4d1de60c09fb0de8d56aae928d9c6371a6477dd3d05d1ff79937c578acbR79-R82
