### ISSUE TITLE
Add current file to chat on Ctrl + L shortcut.

### ISSUE THREAD

**Issue by shinebarbhuiya** [continuedev/continue#2673]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When I use the shortcut Ctrl + L, it is not adding the current file to the chat. It would be really helpful to get this feature(or fixed if it's a bug). Also, I am unable to see most of my files when I search using @ . Let's suppose I am working on a go project and I have a file name /internal/validation/validation.go then if I search @validation.go nothing shows up.

**Comment by Nithishvb** [comment]
hi @shinebarbhuiya, to add the current file to the chat, try selecting the entire code in the current file and then press `Ctrl + v`; it will work. For searching files using the `@` command, type `@`, select the `Files` options, and start typing the name of the file you want to search for.

**Comment by RomneyDa** [comment]
You can now add the **active file** to the chat by using `option/alt` `enter` to submit.

**Comment by RomneyDa** [comment]
https://github.com/continuedev/continue/pull/2191
