### ISSUE TITLE
Allow to use PyCharm built-in local inline code completion together with Continue

### ISSUE THREAD

**Issue by wienand** [continuedev/continue#2726]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When using Continue it is not possible to use the inline code completion from PyCharm together with Continue Chat and Edit functions.

During working the inline code suggestions are sometimes great but also often annoying as they interfere with normal editing (e.g. just change a word or number) and cursor navigation with the keyboard.

![image](https://github.com/user-attachments/assets/1f71b21e-bfba-463c-9fa0-50f3d0eefa53)

### Solution

Just have a configuration option to allow PyCharm to activate the built-in inline code completions and deactivate the ones from Continue.

**Comment by Lash-L** [comment]
I believe this is a duplicate of: https://github.com/continuedev/continue/issues/2061

For this to work, Continue has to switch to jetbrains API instead of how they are currently doing it.

**Comment by Patrick-Erichsen** [comment]
^Correct, but appreciate the +1 here.

**Comment by wienand** [comment]
You are right. Sorry for the duplicate.

Closing since duplicate of #2061
