### ISSUE TITLE
Ollama models use json output format

### ISSUE THREAD

**Issue by kohlerm** [continuedev/continue#2727]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: dev branch
- IDE version: 1.95 insider
- Model: all ollama models
- config.json:
```

### Description

https://github.com/continuedev/continue/blob/694a044a608e0700cab027dec9ad580f111a234a/core/llm/llms/Ollama.ts#L248 forces the model to output json

**Comment by kohlerm** [comment]
removing the line fixes it

**Comment by 123Haynes** [comment]
I'm also experiencing this bug on IntelliJ.

Continue@IntelliJ 0.0.79 running on IntelliJ Ultimate 2024.2.4

every chat response I get is in Json format.  

I'll add a screenshot in a minute

**Comment by RomneyDa** [comment]
@kohlerm good find
0.79 is broken for a couple issues, we're gonna hide it

**Comment by RomneyDa** [comment]
Fixed by https://github.com/continuedev/continue/pull/2759
