### ISSUE TITLE
[CON-185] people don’t know that the context above and below cursor is included

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#276]
`vscode.window.showInformationMessage()`, see other example in diff.ts where it checks before telling about the accept/reject keyboard shortcuts.

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-185](https://linear.app/continue/issue/CON-185/people-dont-know-that-the-context-above-and-below-cursor-is-included)</sub>

**Comment by TyDunn** [comment]
I thought about this more, and I think this enough for now:

![Image](https://github.com/continuedev/continue/assets/13314504/2cef0d54-82be-43fe-a660-ec80d12bb9e1)

We should not use too many popups. They are annoying and many people don't read them, especially if they happen too often
