### ISSUE TITLE
Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by juanfcocontreras** [continuedev/continue#2790]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: 0.8.55
- IDE version: VSCode 1.95.1
- config.json:
  
{
  "models": [
    {
      "model": "gpt-4o-mini",
      "contextLength": 128000,
      "title": "GPT-4o Mini",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses. Always respond in English.",
      "provider": "openai",
      "apiKey": "xxx"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "allowAnonymousTelemetry": false,
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    }
  ],
  "experimental": {
    "contextMenuPrompts": {
      "docstring": "Write a docstring for this code in English. Do not change anything about the code itself.",
      "comment": "Write comments for this code in English. Do not change anything about the code itself.",
      "fix": "Fix this code and explain the fixes in English.",
      "optimize": "Optimize this code and explain the optimizations in English.",
      "fixGrammar": "If there are any grammar or spelling mistakes in this writing, fix them and explain the corrections in English. Do not make other large changes to the writing."
    }
  },
  "docs": []
}
```

### Description

Since version 0.8.53, whenever I click the continue button in the status bar, I get this message:

```
Cannot read properties of undefined (reading 'title').
```

I have checked that if I install earlier versions, I don't have this problem. Version 0.8.53 and later do.

### To reproduce

1. Go to Status Bar
2. Click on "Continue" button
3. See error: Cannot read properties of undefined (reading 'title').

**Comment by 0xStuart** [comment]
I'm a first time user, and I am getting the same on both vs code and jetbrains.

**Comment by 0xStuart** [comment]
It's ok now that I completed setup by clicking on the icon on the left.

**Comment by juanfcocontreras** [comment]
> It's ok now that I completed setup by clicking on the icon on the left.

What icon exactly?

**Comment by 0xStuart** [comment]
![image](https://github.com/user-attachments/assets/0ad685ff-eb83-4883-bbd9-f82d3a10dc0a)

**Comment by juanfcocontreras** [comment]
Ok, thanks. No change here, I still the error.

**Comment by brucevoin** [comment]
Just remove config.json ,  it will reset config.json,  then you can reconfigure it , and the error should go

**Comment by juanfcocontreras** [comment]
> Just remove config.json , it will reset config.json, then you can reconfigure it , and the error should go

But what is wrong with my configuration file? Because if I delete it and configure it exactly the same it will have the same error, right? I have attached the file in the first message.

**Comment by brucevoin** [comment]
> > Just remove config.json , it will reset config.json, then you can reconfigure it , and the error should go
> 
> But what is wrong with my configuration file? Because if I delete it and configure it exactly the same it will have the same error, right? I have attached the file in the first message.

For me, The reason may be that I deleted the 'tabAutocompleteModel' in json config.

**Comment by eakkawat** [comment]
Try add "tabAutocompleteModel": {}  in config file

**Comment by juanfcocontreras** [comment]
The configuration file complained that the property title, provider, model, apibase was missing in the .json configuration file.

Finally I have put this configuration, which is supposed to be the default, and it seems that everything works, but I think it is a bug, because this did not happen before, and to set a default configuration should not be necessary to set it manually, right? Also this behavior did not happen in previous versions of the plugin.

```
    "tabAutocompleteModel": {
        "title": "Tab Autocomplete Model",
        "provider": "ollama",
        "model": "starcoder2:3b",
    }
```

**Comment by eakkawat** [comment]
> The configuration file complained that the property title, provider, model, apibase was missing in the .json configuration file.
> 
> Finally I have put this configuration, which is supposed to be the default, and it seems that everything works, but I think it is a bug, because this did not happen before, and to set a default configuration should not be necessary to set it manually, right? Also this behavior did not happen in previous versions of the plugin.
> 
> ```
>     "tabAutocompleteModel": {
>         "title": "Tab Autocomplete Model",
>         "provider": "ollama",
>         "model": "starcoder2:3b",
>     }
> ```

This function actually should be set default config as most developers use it, and it should be 'disabled' by default, If you need it you can click on 'continue' near status bar and select 'enable'. If you think it not necessary just select 'disable'.

**Comment by sestinj** [comment]
Fixed: https://github.com/continuedev/continue/pull/2965/commits/5b85cad7a9e292ca4060d8188ec60f7d4060de40
