### ISSUE TITLE
Missing scrollbar

### ISSUE THREAD

**Issue by robertpiosik** [continuedev/continue#2795]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

### Description

Hi! Conversations, especially those involving code blocks typically gets a bit longer. Long enough to put some uncomfortable strain on a scroll wheel. Bringing back a scrollbar should be considered, especially as it doesn't take any horizontal space.

**Comment by PRANJALRANA11** [comment]
@sestinj /assign

**Comment by sestinj** [comment]
@robertpiosik As of now this is configurable in config.json's "ui" section. We will definitely look to make it more obvious when we build a full GUI for the config

**Comment by dandv** [comment]
@sestinj could `config.json` ship with [that setting](https://docs.continue.dev/reference#ui), even if set to false (which I also think is a bad idea)? I don't see anything about "scrollbar" in my config.json (though I installed the extension a while back) (or [here](https://github.com/continuedev/continue/blob/main/extensions/vscode/e2e/test-continue/config.json)) so I had to spend extra time referring to the docs.
