### ISSUE TITLE
Context provider "Active file" (ex Alt+Enter) doesn't work for unsaved files

### ISSUE THREAD

**Issue by Astlaan** [continuedev/continue#2798]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: v0.8.55
- IDE version: VS Code 1.95.1
```

### Description

ContextProvider for active file (ex. when submitting prompt about the file in Chat with Alt+Enter) doesn't work for unsaved files. This happens despite the UI saying that it has been passed as context, however it is seen as an Object content, not visible by the model.

This is the behaviour I get:

![image](https://github.com/user-attachments/assets/d75dc0bf-5fbc-4cfe-949f-6cfa3e272243)

I haven't tested if this is also the case for the Quick Edits (Ctrl+I) since my Ctrl+I isn't working due to another bug (#2346 , https://github.com/continuedev/continue/issues/2346#issuecomment-2439655702 ).

### To reproduce

1. Open a new file, write some stuff, but don't save to disk
2. Open Chat, make a query about the file, add the active file as context with Alt+Enter

**Comment by sestinj** [comment]
Thanks for bringing this up @Astlaan. My guess is that the solution to https://github.com/continuedev/continue/issues/1226 will be the same as for this, and it's something we plan to fix later this week

**Comment by RomneyDa** [comment]
Looks like it does check open text document case here
https://github.com/continuedev/continue/blob/885e7c138d725dfed88d9165df99f1f692c49fb8/extensions/vscode/src/VsCodeIde.ts#L450-L457

Wondering if path issue, will debug

**Comment by RomneyDa** [comment]
just for clarity it does work for unsaved files that already exist, just not for brand new unsaved files like in @Astlaan's case

**Comment by RomneyDa** [comment]
Fixed by https://github.com/continuedev/continue/pull/2841

**Comment by Astlaan** [comment]
> just for clarity it does work for unsaved files that already exist, just not for brand new unsaved files like in @Astlaan's case

Yes, sorry, could have been clearer
