### ISSUE TITLE
@Codebase should use the LATEST version of the code/files

### ISSUE THREAD

**Issue by RVFET** [continuedev/continue#2803]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently if you do updates to files mid-conversation it does not use the most recent version of the code. This might be due to save some tokens by "caching" the files, but comes with the issue of making the user to mess around to feed the most recent data to the ai.

### Solution

Make the `@codebase` using the current state of the file/code, rather than ignoring the ones that already been fed or using the previously saved state.

**Comment by sestinj** [comment]
@RVFET thanks for your feedback here. Before we jump into doing this, my concern isn't actually with cost, but with creating potentially contradictory chat history (where the LLM answers something about the old state of the file that is no longer true when the file updates). It may be that this concern is lesser than the one you have raised

**Comment by RVFET** [comment]
It makes sense, but the thing is, if I used the codebase for a chat and create a new one, the changes that I've done before opening the new chat is ignored, and Continue uses the codebase in the old conversation. Some kind of caching is going on, I'm not quite sure. Only workarounds I found are: `Developer: Restart Extension Host` or manually copy paste the code or straight up restart the vscode

**Comment by RomneyDa** [comment]
This should be fixed by
https://github.com/continuedev/continue/pull/2946

Index is now updated on file saves, creations
