### ISSUE TITLE
Embeddings SQlite gets larger than entire repo

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#2807]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
OS - Windows_NT x64 10.0.22631 (Windows 11 Home)
VSCode: 1.94.2 (user setup)
Continue: I think v0.8.55, I got this from checking the extension page. Not sure if it s showing currently instaleld or latest version
```

### Description

https://discord.com/channels/1108621136150929458/1299410727114903613

3 gb sqlite file for a 600mb repo
Perhaps not getting deleted files?

**Comment by RomneyDa** [comment]
Might be fixed by https://github.com/continuedev/continue/pull/2717

Which watches for file deletions

**Comment by RomneyDa** [comment]
https://github.com/continuedev/continue/issues/2688 occured in same instance/user

**Comment by RomneyDa** [comment]
My initial premise was incorrect, db can be way larger than repo because indexing is per workspace, git, model, etc. Grows over time

**Comment by linnnff** [comment]
so  hou to fix it
