### ISSUE TITLE
Azure Open AI: Adding images to prompt no longer works 

### ISSUE THREAD

**Issue by ntaylor-ads** [continuedev/continue#2830]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: 0.9.225
- IDE version:1.95.1
- Model: gpt-4o
- config.json:
  
{
      "title": "Azure GPT-4o",
      "provider": "azure",
      "model": "gpt-4o",
      "apiBase": "***",
      "engine": "gpt-4o",
      "apiVersion": "2024-08-01-preview",
      "apiType": "azure",
      "apiKey": "***"
}
```

### Description

I was using an Azure gpt-4o model with "openai" set as the provider. This was working perfectly and allowed me to use images in the prompts. I noticed today that that config now throws a 404 error, generating a bad url like this: https://***/openai/deployments/undefined/chat/completions?api-version=2024-02-15-preview (note the "undefined")

I then changed the model config to use the provider "azure". This fixes the 404 error and I am able to do text based prompts and get responses, but it also removes the ability to add images to the prompt.

**Comment by ntaylor-ads** [comment]
I fixed this issue by changing the provider back to "openai" and changing the key "engine" to "deployment", i.e.:

```json
{
      "title": "Azure GPT-4o",
      "provider": "openai",
      "model": "gpt-4o",
      "apiBase": "***",
      "apiVersion": "2024-08-01-preview",
      "apiType": "azure",
      "deployment": "gpt-4o",
      "apiKey": "***"
    }
   ```
  I guess something changed in how the config should be specified? With the natural follow up: what is the right way to be staying abreast of the current correct way of specifying the config?

**Comment by sestinj** [comment]
@ntaylor-ads thanks for bringing this up, I just made the required change here: https://github.com/continuedev/continue/pull/2937/commits/14b406075cc0db5101c71e7ab42be896eb38428a

The config you have here is correct, though you should also be able to remove apiType and apiVersion when using the azure provider

This is what I verified to work with my own deployment/key:
```json
{
      "title": "Azure GPT-4o",
      "provider": "azure",
      "model": "gpt-4o",
      "apiBase": "https://xxx.cognitiveservices.azure.com",
      "deployment": "gpt-4o",
      "apiKey": "xxx"
    }
```

This should be reflected in the docs: https://github.com/continuedev/continue/blob/14b406075cc0db5101c71e7ab42be896eb38428a/docs/docs/customize/model-providers/top-level/azure.md#L19-L26

**Comment by ntaylor-ads** [comment]
It's worth noting per the original issue that using the config you have specified removes the ability to add images to the prompt. It seems that the provider has to be "openai" and not "azure" to do image prompt on models hosted on azure.
