### ISSUE TITLE
Add Github Copilot as Chat option

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#2831]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

People want one chat experience
Github copilot has a public api for chat
People that pay $10 for github copilot could save hundreds a month by using copilot as their chat, since it's virtually unlimited

### Solution

Check for vscode.lm registered models, specifically "copilot" vendor for now
Include those models as options in the model dropdown

**Comment by PRANJALRANA11** [comment]
@RomneyDa /assign

**Comment by RomneyDa** [comment]
Hi @PRANJALRANA11 
We're not sure if we can do this without violating github terms, will backlog for now and look into it.
Thanks!

**Comment by esoternic89** [comment]
@RomneyDa https://docs.github.com/en/copilot/building-copilot-extensions/building-a-copilot-agent-for-your-copilot-extension/using-copilots-llm-for-your-agent
It's official for agents

**Comment by sestinj** [comment]
Closing this issue as not planned due to terms

**Comment by vivekrp** [comment]
@sestinj Could you please clarify why this enhancement is not planned? Specifically, what terms are causing the issue?

**Comment by sestinj** [comment]
Sorry, terms meaning Terms and Conditions

**Comment by vivekrp** [comment]
I got that part but I was asking which terms and conditions are the reason for not implementing this. A lot of other editors are adding the GitHub Copilot option for example Zed has an option to select GitHub Copilot as my AI for the IDE.
