### ISSUE TITLE
Add support for provider-specific image resolutions

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#2832]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Images are all scaled down, with no provider-specific handling for image resolution or ability to allow full resolution

@FallDown on [discord](https://discord.com/channels/1108621136150929458/1156679146932535376/1303839511318495232)
> Does Continue scale down images? Whenever I ask paste in an image with text and ask it to extract the text, it gets it horribly wrong, but on the Web UI for ChatGPT it does fine

### Solution
Allow defining provider and model image resolution capabilities

If provider image capabilities are known,
could either _NOT_ scale down by default and add `completionOptions` boolean for `scaleImagesDown` or similar
OR scale down by default and add `allowFullImageResolution` option or similar 

Otherwise, use default (scale down or not)

**Comment by sestinj** [comment]
My preference here to avoid adding any complexity at all to the config would be to just increase the default resolution. I've done that here: https://github.com/continuedev/continue/commit/20831dbd61b7849de01d44f95e6fe130b3e30306
