### ISSUE TITLE
Supporting Azure openai

### ISSUE THREAD

**Issue by Brooks-was-here** [continuedev/continue#2835]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Can't connect with azure openai 

### Solution

support azure openai

**Comment by RomneyDa** [comment]
Hi @Brooks-was-here 

Azure OpenAI is supported, check out the docs here!
https://docs.continue.dev/customize/model-providers/azure

Let me know if you have any questions

**Comment by Brooks-was-here** [comment]
> Hi @Brooks-was-here
> 
> Azure OpenAI is supported, check out the docs here! https://docs.continue.dev/customize/model-providers/azure
> 
> Let me know if you have any questions

OMG. Thanks!!

**Comment by Brooks-was-here** [comment]
Hey. I've found some mistakes in your document. 

For succesful execution, the config should be like this. 

 {
      "apiKey": "{YOUR_API_KEY}",
      "engine": "gpt-4o",
      "apiBase": "{YOUR_API_BASE_URI}",
      "apiType": "azure",
      "model": "{YOUR_AZURE_MODEL_DEPLOYMENTS}",
      "title": "GPT-4o",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses.",
      "provider": "azure",
      "apiVersion": "2023-07-01-preview"
    }
