### ISSUE TITLE
System prompt file

### ISSUE THREAD

**Issue by StructByLightning** [continuedev/continue#2846]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Advanced prompts tend to be extremely long, especially with how cheap inference has gotten. For software engineering in particular, prompts often have double quotes in them as part of code examples. All of this makes it difficult and tedious to use JSON to define the system prompt — I have to replace all the double quotes with escaped quotes, remove all the newlines, and copy/paste the new prompt into the JSON (and if I ever want to edit it, I have to reverse the process and then do it all over again).

### Solution

Prompt files already solve all of these problems and are a much cleaner way to organize prompts than JSON fields. A field called `systemPrompt` could be added that overrides `systemMessage` and is just the path to the prompt file.

**Comment by Patrick-Erichsen** [comment]
This could be quite straightforward with the existing prompt files format we have: https://docs.continue.dev/customize/deep-dives/prompt-files

There's a few ways I think we could identify that a particular prompt file should be used as the system message:
- A special attribute in the [preamble](https://docs.continue.dev/customize/deep-dives/prompt-files#preamble), eg "- system"
- A special file name, eg "system.prompt"
- Specify which file in the config.json, eg "systemPrompt: .prompts/system.prompt"

Any reasons you'd lean towards one or the other?

**Comment by StructByLightning** [comment]
I have a minor preference towards #3; the rest of the default config goes in config.json and it makes sense to me that there would at least be a reference to the system prompt from there? 

But if you guys think #1 or #2 is better that'd be fine too. My only concern with is that can use multiple models and have separate prompts for them. So if there was a `system` field in the preamble, it should be like: `system: sonnet` or `system: codestral`. Same for the filename.

**Comment by sestinj** [comment]
@StructByLightning we now support `.continuerules` in the root of a repository to define a system prompt. I think you may have already gotten the chance to try this and given feedback if I remember correctly. Going to close this issue, but open others if needed!

https://docs.continue.dev/customize/deep-dives/rules

**Comment by DanielBeck93** [comment]
Will solution #3 also be supported at a point?
