### ISSUE TITLE
Empty messages - Anthropic etc.

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#2852]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
current version nov 8
- config.json:
  
{
  "models": [
    {
      "model": "claude-3-5-sonnet-20240620",
      "provider": "anthropic",
      "apiKey": "MYAPIKEY",
      "title": "Claude 3.5 Sonnet"
    }
  ],
}
```

### Description

OpenAI provider converts "" messages to " " to avoid issues with various providers
Providers that don't extend OpenAI still have the empty message bug
Find a way to either filter out / don't create empty messages in the first place,
Or elegantly remove this problem for all providers ("" -> " ")

### To reproduce

Sometimes empty messages are sent

**Comment by sestinj** [comment]
Fixed here: https://github.com/continuedev/continue/pull/2937/commits/3e4580d9f9a2dfaf200abfb1b8cdbc99cad60a11
