### ISSUE TITLE
Getting "Error in config.json: The 'allowAnonymousTelemetry' field should be a boolean if defined

### ISSUE THREAD

**Issue by troy256** [continuedev/continue#2863]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version: 0.8.56
- IDE version: VS Code 
- Model: various
```

### Description

My config.json has this line:
```
{
  "allowAnonymousTelemetry": "false",
...
}
```

Which seems to match the syntax as defined in https://docs.continue.dev/telemetry.

Am I missing something?

**Comment by RomneyDa** [comment]
Hi @troy256!

Thanks for the post. In this case set false to `false` without quotation marks, instead of `"false"`. Json booleans don't need quotes. Let me know if any issues!
