### ISSUE TITLE
[CON-331] Pasting text ending with "@..." opens context dropdown

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#2868]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue version:*
- IDE version:*
```

### Description

Solution is probably to manually close dropdown after paste events

### To reproduce

Paste the following into the input:

```
This
is
a
test @testing123
```

and see that the dropdown is opened

<sub>[CON-331](https://linear.app/continue/issue/CON-331/pasting-text-ending-with-opens-context-dropdown)</sub>

**Comment by sestinj** [comment]
Reported by @tomasz-stefaniak, @RomneyDa this might fit well into your work. Worth attempting the 60sec fix described above

**Comment by RomneyDa** [comment]
Note, on current main has changed to only if ends in " @" with a space
