### ISSUE TITLE
Continue: Generate Code resulted in an error (Cannot read properties of undefined (reading 'range'))

### ISSUE THREAD

**Issue by shrikrishnaholla** [continuedev/continue#2903]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux
- Continue version: 0.8.55
- IDE version: 1.74.2
- Model: openai provider hooked to an mlx server with openai compatible endpoint: https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md
- config.json:
  
{
  "models": [
    {
      "model": "mlx-community/Qwen2.5-Coder-14B-Instruct-4bit",
      "title": "MLX - Qwen2.5.1",
      "completionOptions": {},
      "apiKey": "EMPTY",
      "apiBase": "http://<private endpoint>:8080/v1",
      "provider": "openai"
    }
...
}
```

### Description

Regression in "Generate code" action (is this because I'm using an openai-compatible server? I have previously used this successfully, when pointing it to an Ollama server)

### To reproduce

1. Point continue.dev extension to an openai-compatible local service (mlx.server in my case)
2. Use "Generate code" on any file. The above error is produced. I haven't been able to check whether it's produced with Ollama as well, in this version, but I've used this feature with Ollama in the past

**Comment by carmelomigliore** [comment]
I ran in the same problem, I solved adding `"useLegacyCompletionsEndpoint": false` to the model configuration.
Tab completion is still not working though

**Comment by eakkawat** [comment]
Me too after update to new version of countinuedev.

**Comment by akd-io** [comment]
I'm getting `Cannot read properties of undefined (reading 'range')` too, when running the `Continue: Generate Code` command on `v0.8.57` and `v0.9.231 (pre-release)`.

**Comment by willypaz243** [comment]
- OS: Linux
- Continue version: 0.8.57
- vscode version: 1.95.3

I encountered the same bug but it has been happening to me since v0.8.56, since in v0.8.55 the "Continue: Generate Code" command works correctly, until they fix this I recommend installing this version, by the way I am using the default continue configuration and even with that I get this error in the current version.

**Comment by sestinj** [comment]
Thanks all for the report—this is a real bug, but will not be fixed as we are removing cmd+shift+I in favor of the new cmd+I experience to "Generate code" in the next pre-release

**Comment by Patrick-Erichsen** [comment]
Hey @willypaz243 , appreciate the feedback! Mind sharing a bit more around what you liked about the previous interface/dislike about the new one?

**Comment by developer3-hospy** [comment]
I like this:
![image](https://github.com/user-attachments/assets/ff228e70-670d-49e8-b15a-009728fb8506)

I use the Ctrl + i for open it.

I would like to have more improvements to that interface, I would like it to look like the chat but as a popup.

![image](https://github.com/user-attachments/assets/c50d8ddb-5385-42ee-a147-565976b2e1a7)

**Comment by Patrick-Erichsen** [comment]
A popup would be great but unfortunately VS Code hasn't exposed that capability to third party extensions.
