### ISSUE TITLE
VSCode/VSCodium extension overrides built-in keybinding

### ISSUE THREAD

**Issue by rcambrj** [continuedev/continue#2913]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS
- Continue version: v0.9.212
- IDE version: VSCodium Version: 1.94.1 Release: 24283
- Model: not relevant
- config.json: not relevant
```

### Description

VSCode and VSCodium both have a default keybinding of `cmd+shift+enter` or `ctrl+shift+enter` to insert a new line above the cursor (`editor.action.insertLineBefore`), but continue's extension [overrides this for `continue.acceptDiff`](https://github.com/continuedev/continue/blob/ae331af31360dd22c4fe46f207736bd2156d8bd6/extensions/vscode/package.json#L332).

I recommend changing this keybinding to something which doesn't conflict with the defaults.

To temporarily workaround this, one can delete or remap the continue keybinding, but if using nix home-manager to configure VSCode/VSCodium, then declaring the original function as a user keybinding also works (these don't get overridden by extension keybindings):

```
  programs.vscode.userSettings.keybindings = [
    {
      command = "editor.action.insertLineBefore";
      key = "shift+cmd+enter";
    }
    {
      command = "continue.acceptDiff";
      key = "shift+cmd+option+enter";
    }
  ];
```

### To reproduce

1. install continue
2. go to edit any file
3. `cmd+shift+enter` or `ctrl+shift+enter`

expected: a new line is inserted above the cursor
observe: nothing happens

**Comment by sestinj** [comment]
Thanks for the feedback @rcambrj! There's something even better than changing it we can do, which is to scope the command to only situations where there is actually a diff to accept.

I made the change here and it will be in the next version! https://github.com/continuedev/continue/pull/2934/commits/39a8e158cf737910cd4950d947bb5e439ec7de6d

**Comment by rcambrj** [comment]
@sestinj that was a fast response! thanks :)

I'm still concerned about `"when": "continue.diffVisible"` though, because even when a diff is visible, I would expect this keybinding to adhere to the builtin behaviour - as I might be customising/fixing a diff and I might need a new line. There's also some cognitive load introduced by having to remember that this particular keybinding does something different when a diff is visible. When relying on muscle memory, I might inadvertently use this keybinding with the wrong intention, leading to unexpected results (accepting a diff when I meant to insert a new line).

I think, personally, I would still override this shortcut with the fix I put in the issue description.

What do you think?

**Comment by sestinj** [comment]
The unfortunate truth is that if we use anything more esoteric than cmd+shift+enter (we could have used cmd+enter but are already avoiding this), then many users just won't use it. I totally see where you're coming from, but in situations like this I am kind of just stuck doing a quick calculation given the number of issues opened and +1s to determine how many people it is affecting, and compare that to the aggregate suffering of users who don't mind cmd+shift+enter now having to reach for the option key or something. In the end, the best solution here would be to remap the shortcut for yourself individually (cmd+K, S, search for continue.acceptDiff, and choose a new shortcut)

**Comment by rcambrj** [comment]
Loud and clear :)

I'll continue with my override!

Feel free to close.

**Comment by sestinj** [comment]
Appreciate the understanding : ) Always good to know about things like this
