### ISSUE TITLE
"Accept" and "Rejected" reversed

### ISSUE THREAD

**Issue by godsakurapeng** [continuedev/continue#2947]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

### Description

![image](https://github.com/user-attachments/assets/280eac6b-015d-48a7-83b9-c557f4b6e853)
![image](https://github.com/user-attachments/assets/3c74f5c4-2d20-42cb-ab09-eb4243ed55c9)
just a small bug
https://github.com/continuedev/continue/blob/main/gui/src/pages/edit/EditInputHeader.tsx#L79

### To reproduce

1.select code
2.ctrl + i
3.send question

**Comment by Patrick-Erichsen** [comment]
Thanks for the heads up here! We have a fix for this in the upcoming release.

**Comment by RomneyDa** [comment]
Fixed by https://github.com/continuedev/continue/pull/2915
