### ISSUE TITLE
Prompt caching for providers (other than Claude)

### ISSUE THREAD

**Issue by dalisoft** [continuedev/continue#2962]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently supports only Claude prompt caching per [documentation](https://docs.continue.dev/customize/model-providers/anthropic#prompt-caching) and did not find (from search) for other providers such as [DeepSeek](https://docs.continue.dev/customize/model-providers/deepseek), [OpenAI](https://docs.continue.dev/customize/model-providers/openai).
Or this is effectively for other providers too?

Previously used `cacheSystemMessage: true` for all providers but not sure it did help or not. Would be helpful to enable caching (especially for chat) for more cheaper solution

**Comment by sestinj** [comment]
@dalisoft prompt caching is entirely automatic for both DeepSeek and OpenAI so everything will be cached without any necessary modification to your config (or our API request)
