### ISSUE TITLE
Get error when run Core Binary  : Could not locate the bindings file. No debugger available, can not send 'variables'

### ISSUE THREAD

**Issue by AfterStories** [continuedev/continue#2986]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:WINDOWS X64
- Continue version:main branch
- IDE version:ideaIC-2021.1.3.win
- NODEJS ：V22.11.0
```

### Description

**I want to try to run the JetBrains extension locally. According to the description in the CONTRIBUTING.md file in the main branch, I first executed the `install-all-dependencies` task. Then, according to the description in the extensions\intellij\CONTRIBUTING.md file, I started "Core Binary" in VS Code
Then I got following error message :**
C:\node-v22.11.0-win-x64\node.exe .\out\index.js
Process exited with code 1
Uncaught Error Error: Could not locate the bindings file. Tried:
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\Debug\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\Release\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\out\Debug\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\Debug\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\out\Release\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\Release\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\default\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\compiled\22.11.0\win32\x64\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\addon-build\release\install-root\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\addon-build\debug\install-root\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\addon-build\default\install-root\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\lib\binding\node-v127-win32-x64\node_sqlite3.node
    at bindings (c:\Users\hzheng057\Desktop\Code\continue\core\node_modules\bindings\bindings.js:126:9)
    at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (c:\Users\hzheng057\Desktop\Code\continue\core\node_modules\sqlite3\lib\sqlite3-binding.js:1:18)
    at __require (c:\Users\hzheng057\Desktop\Code\continue\binary\out\index.js:18:51)
    at ../core/node_modules/sqlite3/lib/sqlite3.js (c:\Users\hzheng057\Desktop\Code\continue\core\node_modules\sqlite3\lib\sqlite3.js:2:17)
    at __require (c:\Users\hzheng057\Desktop\Code\continue\binary\out\index.js:18:51)
    at <anonymous> (c:\Users\hzheng057\Desktop\Code\continue\core\util\devdataSqlite.ts:3:21)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1546:14)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1689:10)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1318:32)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1128:12)
    at traceSync (<node_internals>/diagnostics_channel:315:14)
    at wrapModuleLoad (<node_internals>/internal/modules/cjs/loader:218:24)
    at executeUserEntryPoint (<node_internals>/internal/modules/run_main:170:5)
    at <anonymous> (<node_internals>/internal/main/run_main_module:36:49)
bindings.js:126

**From the error content, I think the required files are not built in the binary folder, so I went to the binary folder and executed the npm run build command, and the following error message :**

(base) PS C:\Users\hzheng057\Desktop\Code\continue\binary> npm run build

> binary@1.0.0 build
> node build.js

[info] Downloading prebuilt lancedb...
[info] Downloading for win32-x64...
Copying @lancedb/vectordb-win32-x64-msvc to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-win32-x64-msvc [ 'vectordb-win32-x64-msvc' ]
[info] Copied tree-sitter.wasm
[info] Copied llamaTokenizerWorkerPool.mjs
[info] Copied llamaTokenizer.mjs
[info] Copied tiktokenWorkerPool.mjs
[info] Cleaning up artifacts from previous builds...
[info] Building with esbuild...
[info] Building binaries with pkg...
[info] Building win32-x64...
(node:24792) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error executing command 'npx pkg --no-bytecode --public-packages "*" --public pkgJson/win32-x64 --out-path bin/win32-x64':  ,> pkg@5.8.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
> Not found in remote cache:
  **{"tag":"v3.4","name":"node-v18.5.0-win-x64"}**
> Building base binary from source:
  built-v18.5.0-win-x64
> Fetching Node.js source archive from nodejs.org...
> Error! AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(!this.bar)

    at Log.enableProgress (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\log.js:64:30)
    at C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:58:31
    at step (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at downloadUrl (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:53:12)
    at C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\build.js:142:66
    at step (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\build.js:44:23)
,(node:24792) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**The node version I use is V22, and I also set the node version in binary\package.json:**
"targets": [
    "node22-win-x64"
],

**But I saw in the error message that it seems to be looking for the v18 version of node {"tag":"v3.4","name":"node-v18.5.0-win-x64"}

I don't know if this error is caused by  node version , or the pkg config issues ? For the current problem I'm facing, could  you help me check how I can solve this error and Launchthe plugin?**

### To reproduce

install-all-dependencies
then,
Core Binary

### Log output

```Shell
Launch"Core Binary" in VS Code:
C:\node-v22.11.0-win-x64\node.exe .\out\index.js
Process exited with code 1
Uncaught Error Error: Could not locate the bindings file. Tried:
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\Debug\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\Release\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\out\Debug\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\Debug\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\out\Release\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\Release\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\build\default\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\compiled\22.11.0\win32\x64\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\addon-build\release\install-root\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\addon-build\debug\install-root\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\addon-build\default\install-root\node_sqlite3.node
 → C:\Users\hzheng057\Desktop\Code\continue\binary\lib\binding\node-v127-win32-x64\node_sqlite3.node
    at bindings (c:\Users\hzheng057\Desktop\Code\continue\core\node_modules\bindings\bindings.js:126:9)
    at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (c:\Users\hzheng057\Desktop\Code\continue\core\node_modules\sqlite3\lib\sqlite3-binding.js:1:18)
    at __require (c:\Users\hzheng057\Desktop\Code\continue\binary\out\index.js:18:51)
    at ../core/node_modules/sqlite3/lib/sqlite3.js (c:\Users\hzheng057\Desktop\Code\continue\core\node_modules\sqlite3\lib\sqlite3.js:2:17)
    at __require (c:\Users\hzheng057\Desktop\Code\continue\binary\out\index.js:18:51)
    at <anonymous> (c:\Users\hzheng057\Desktop\Code\continue\core\util\devdataSqlite.ts:3:21)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1546:14)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1689:10)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1318:32)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1128:12)
    at traceSync (<node_internals>/diagnostics_channel:315:14)
    at wrapModuleLoad (<node_internals>/internal/modules/cjs/loader:218:24)
    at executeUserEntryPoint (<node_internals>/internal/modules/run_main:170:5)
    at <anonymous> (<node_internals>/internal/main/run_main_module:36:49)
bindings.js:126

=====================================================


npm run build in the binary folder:


(base) PS C:\Users\hzheng057\Desktop\Code\continue\binary> npm run build

> binary@1.0.0 build
> node build.js

[info] Downloading prebuilt lancedb...
[info] Downloading for win32-x64...
Copying @lancedb/vectordb-win32-x64-msvc to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-win32-x64-msvc [ 'vectordb-win32-x64-msvc' ]
[info] Copied tree-sitter.wasm
[info] Copied llamaTokenizerWorkerPool.mjs
[info] Copied llamaTokenizer.mjs
[info] Copied tiktokenWorkerPool.mjs
[info] Cleaning up artifacts from previous builds...
[info] Building with esbuild...
[info] Building binaries with pkg...
[info] Building win32-x64...
(node:24792) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error executing command 'npx pkg --no-bytecode --public-packages "*" --public pkgJson/win32-x64 --out-path bin/win32-x64':  ,> pkg@5.8.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
> Not found in remote cache:
  **{"tag":"v3.4","name":"node-v18.5.0-win-x64"}**
> Building base binary from source:
  built-v18.5.0-win-x64
> Fetching Node.js source archive from nodejs.org...
> Error! AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(!this.bar)

    at Log.enableProgress (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\log.js:64:30)
    at C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:58:31
    at step (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at downloadUrl (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\utils.js:53:12)
    at C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\build.js:142:66
    at step (C:\Users\hzheng057\Desktop\Code\continue\binary\node_modules\pkg-fetch\lib-es5\build.js:44:23)
,(node:24792) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Patrick-Erichsen** [comment]
It seems like the install scripts may not have completed. Were you able to run the IntelliJ configuration tasks mentioned here? https://github.com/continuedev/continue/blob/main/extensions/intellij/CONTRIBUTING.md#running-the-extension-in-debug-mode

**Comment by fulco813** [comment]
Same Problem.
When I run Start Core Dev Server, got following error message:
`/bin/zsh -c "export CONTINUE_DEVELOPMENT=true && export CONTINUE_GLOBAL_DIR=/Users/fulco/Desktop/Project/TypeScript/continue/extensions/.continue-debug && node out/index.js"
/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:51611
      throw err2;
      ^

Error: Could not locate the bindings file. Tried:
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/Debug/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/Release/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/out/Debug/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/Debug/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/out/Release/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/Release/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/default/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/compiled/20.17.0/darwin/x64/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/addon-build/release/install-root/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/addon-build/debug/install-root/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/addon-build/default/install-root/node_sqlite3.node
 → /Users/fulco/Desktop/Project/TypeScript/continue/binary/out/lib/binding/node-v115-darwin-x64/node_sqlite3.node
    at bindings (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:51605:14)
    at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:51666:41)
    at __require (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:18:51)
    at ../core/node_modules/sqlite3/lib/sqlite3.js (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:51716:20)
    at __require (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:18:51)
    at ../core/util/devdataSqlite.ts (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:51895:30)
    at __init (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:15:56)
    at ../core/llm/index.ts (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:72692:5)
    at __init (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:15:56)
    at Object.<anonymous> (/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/index.js:547283:1) {
  tries: [
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/Debug/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/Release/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/out/Debug/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/Debug/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/out/Release/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/Release/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/build/default/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/compiled/20.17.0/darwin/x64/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/addon-build/release/install-root/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/addon-build/debug/install-root/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/addon-build/default/install-root/node_sqlite3.node',
    '/Users/fulco/Desktop/Project/TypeScript/continue/binary/out/lib/binding/node-v115-darwin-x64/node_sqlite3.node'
  ]
}

Node.js v20.17.0

Process finished with exit code 1

`
But I successfully installed binary dependencies:
`Installing binary dependencies...
~/Desktop/Project/TypeScript/continue/binary ~/Desktop/Project/TypeScript/continue

changed 5 packages in 3s

65 packages are looking for funding
  run `npm fund` for details

> binary@1.0.0 build
> node build.js

[info] Downloading prebuilt lancedb...
[info] Downloading for darwin-x64...
Copying @lancedb/vectordb-darwin-x64 to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-darwin-x64 [ 'vectordb-darwin-x64' ]
[info] Downloading for darwin-arm64...
Copying @lancedb/vectordb-darwin-arm64 to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-darwin-arm64 [ 'vectordb-darwin-arm64' ]
[info] Downloading for linux-x64...
Copying @lancedb/vectordb-linux-x64-gnu to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-linux-x64-gnu [ 'vectordb-linux-x64-gnu' ]
[info] Downloading for linux-arm64...
Copying @lancedb/vectordb-linux-arm64-gnu to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-linux-arm64-gnu [ 'vectordb-linux-arm64-gnu' ]
[info] Downloading for win32-x64...
Copying @lancedb/vectordb-win32-x64-msvc to @lancedb
npm warn using --force Recommended protections disabled.
Contents of: @lancedb/vectordb-win32-x64-msvc [ 'vectordb-win32-x64-msvc' ]
[info] Copied tree-sitter.wasm
[info] Copied llamaTokenizerWorkerPool.mjs
[info] Copied llamaTokenizer.mjs
[info] Copied tiktokenWorkerPool.mjs
[info] Cleaning up artifacts from previous builds...
[info] Building with esbuild...
[info] Building binaries with pkg...
[info] Building darwin-x64...
[info] Downloading node-sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0     32      0  0:00:05  0:00:04  0:00:01    33
100   401  100   401    0     0     60      0  0:00:06  0:00:06 --:--:--   269
100 1051k  100 1051k    0     0  51262      0  0:00:21  0:00:21 --:--:--  126k
x build/Release/node_sqlite3.node
[info] Copying @lancedb files to bin
[info] Building darwin-arm64...
[info] Downloading node-sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0     54      0  0:00:03  0:00:02  0:00:01    54
100   405  100   405    0     0     75      0  0:00:05  0:00:05 --:--:--   213
100  963k  100  963k    0     0  72392      0  0:00:13  0:00:13 --:--:--  155k
x build/Release/node_sqlite3.node
[info] Copying @lancedb files to bin
[info] Building linux-x64...
[info] Downloading node-sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0     82      0  0:00:01  0:00:01 --:--:--    82
100   399  100   399    0     0    123      0  0:00:03  0:00:03 --:--:--   892
100 1066k  100 1066k    0     0   131k      0  0:00:08  0:00:08 --:--:--  276k
x build/Release/node_sqlite3.node
[info] Copying @lancedb files to bin
[info] Building linux-arm64...
[info] Downloading node-sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0      1      0  0:02:42  0:02:16  0:00:26    36
100   403  100   403    0     0      2      0  0:03:21  0:02:18  0:01:03   264
100 1033k  100 1033k    0     0   7407      0  0:02:22  0:02:22 --:--:--  291k
x build/Release/node_sqlite3.node
[info] Copying @lancedb files to bin
[info] Building win32-x64...
[info] Downloading node-sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0     15      0  0:00:10  0:00:10 --:--:--    35
100   399  100   399    0     0     30      0  0:00:13  0:00:12  0:00:01   207
100  981k  100  981k    0     0  47391      0  0:00:21  0:00:21 --:--:--  191k
x build/Release/node_sqlite3.node
[info] Copying @lancedb files to bin
All paths exist
[info] Done!
~/Desktop/Project/TypeScript/continue
`
And I can successfully run 【Start GUI Dev Server】, 【Run Extension】, 【Prompt Logs】, only except the 【Start Core Dev Server】

**Comment by fulco813** [comment]
Is there any temporary solution?

**Comment by lijiaao9617** [comment]
**Same Problem.**
**Excuse me, is there any solution**
Error: Could not locate the bindings file. Tried:
 → D:\code\continue\continue-main\binary\build\node_sqlite3.node
 → D:\code\continue\continue-main\binary\build\Debug\node_sqlite3.node
 → D:\code\continue\continue-main\binary\build\Release\node_sqlite3.node
 → D:\code\continue\continue-main\binary\out\Debug\node_sqlite3.node
 → D:\code\continue\continue-main\binary\Debug\node_sqlite3.node
 → D:\code\continue\continue-main\binary\out\Release\node_sqlite3.node
 → D:\code\continue\continue-main\binary\Release\node_sqlite3.node
 → D:\code\continue\continue-main\binary\build\default\node_sqlite3.node
 → D:\code\continue\continue-main\binary\compiled\20.11.0\win32\x64\node_sqlite3.node
 → D:\code\continue\continue-main\binary\addon-build\release\install-root\node_sqlite3.node
 → D:\code\continue\continue-main\binary\addon-build\debug\install-root\node_sqlite3.node
 → D:\code\continue\continue-main\binary\addon-build\default\install-root\node_sqlite3.node
 → D:\code\continue\continue-main\binary\lib\binding\node-v115-win32-x64\node_sqlite3.node
    at uVi (D:\code\continue\continue-main\binary\out\index.js:80:5645)
    at D:\code\continue\continue-main\binary\out\index.js:82:751
    at D:\code\continue\continue-main\binary\out\index.js:1:357
    at D:\code\continue\continue-main\binary\out\index.js:87:112
    at D:\code\continue\continue-main\binary\out\index.js:1:357
    at Object.<anonymous> (D:\code\continue\continue-main\binary\out\index.js:6536:8108)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  tries: [
    'D:\\code\\continue\\continue-main\\binary\\build\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\build\\Debug\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\build\\Release\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\out\\Debug\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\Debug\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\out\\Release\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\Release\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\build\\default\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\compiled\\20.11.0\\win32\\x64\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\addon-build\\release\\install-root\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\addon-build\\debug\\install-root\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\addon-build\\default\\install-root\\node_sqlite3.node',
    'D:\\code\\continue\\continue-main\\binary\\lib\\binding\\node-v115-win32-x64\\node_sqlite3.node'
  ]
}

Node.js v20.11.0

Process finished with exit code 1

**Comment by lijiaao9617** [comment]
Find the download URL (line 364) from extensions/vscode/scripts/utilis.js. For example, here I am: "win32-x64":
" https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.7/sqlite3-v5.1.7-napi-v3-win32-x64.tar.gz After downloading, unzip it to binary/build and replace it

**Comment by lijiaao9617** [comment]
Find the download URL (line 364) from extensions/vscode/scripts/utilis.js. For example, here I am: "win32-x64":
" https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.7/sqlite3-v5.1.7-napi-v3-win32-x64.tar.gz After downloading, unzip it to binary/build and replace it
