### ISSUE TITLE
Add MDN as a doc provider

### ISSUE THREAD

**Issue by lendle** [continuedev/continue#2993]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I see w3schools is used as doc provider for html, css, etc.  [MDN](https://developer.mozilla.org/en-US/) is more detailed and more up to date.

### Solution

Include mdn as a doc provider.

It's pretty big, so it may make sense to break it down by topic. 
* [Web API Reference](https://developer.mozilla.org/en-US/docs/Web)
  * [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML)
  * [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS)
  * etc.
* [Guides](https://developer.mozilla.org/en-US/docs/Learn)
  * [HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML)
  * [CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS)
  * [Javascript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript)
  * etc.

**Comment by sestinj** [comment]
Hey @lendle this is a great idea! Would you be interested in making a PR to this file?

https://github.com/continuedev/continue/blob/6013e6e0d551c14dbbe28fa1f11bcadc684e39a5/core/indexing/docs/preIndexedDocs.ts

**Comment by lendle** [comment]
Sure! I'll try it locally first and if it seems useful I'll submit a pr. I haven't tried adding custom doc indexes in a while, do you recommend breaking them down by topic, or would just do one big MDN provider?

**Comment by lendle** [comment]
I've been trying to index MDN by adding it in my local config. I've tried different embedding providers and reranking configs but generally haven't been getting very good results. In particular it seems that the pages included in context aren't very related to my chat questions.

I haven't tried the built in doc indexes much so I am not sure how it compares, but at this point I don't think it would be worth it to add.

**Comment by sestinj** [comment]
Ok, I'm going to close the issue then for now. I do think this could generally be a useful reference, so I will keep it in mind when we add a ton more docs in the next month
