### ISSUE TITLE
Regression on custom slash commands and context provider display since V0.8.56

### ISSUE THREAD

**Issue by glppfr** [continuedev/continue#3003]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue version: 0.8.56 & 0.8.57
- IDE version: vscode 1.95.3
```

### Description

 Since V0.8.56, custom slash commands declared .prompts folder or default context provider are not displayed in chat window.

### To reproduce

1/ When typing "/" in chat window
1.1/ only default slash commands display, custom prompts in .prompts are not displayed

2/ When typing "@" in chat window
2.1/ no dropdown is displayed with context like Files / codebase etc...
2.2/ to make it work, need to start a first chat and click send, then edit the chat and when typing "@" it will display the list of available contexts

### Log output

```Shell
No log in continue output even in debug mode
```

**Comment by ali0une** [comment]
Same here on a Debian 12 system.

Used to work perfectly with 0.9.229, then it stopped.

**Comment by Patrick-Erichsen** [comment]
@alanwilter - are your prompts in a `/.prompts` folder at the root of your workspace? In the latest release we moved the default prompt file location to `.continue/prompts`, but you can set `version: 1` in the front matter and we'll look in the previous location 

https://docs.continue.dev/customize/deep-dives/prompt-files#preamble

**Comment by alanwilter** [comment]
@Patrick-Erichsen thanks. Indeed, I read the documentation can opted to go with version 2, though / is quicker. It's all working anyway with the latest pre-release version.

**Comment by ali0une** [comment]
Works 100% again on my Debian 12 box.

Many thanks! Keep up the good work ...
