### ISSUE TITLE
OLLAMA_KEEP_ALIVE not working with continue extension

### ISSUE THREAD

**Issue by xgdgsc** [continuedev/continue#3033]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Window on arm
- Continue version:v0.8.57
- IDE version:VSCode 1.95.3
- Model:qwen2.5-coder
- config.json:
  
{
  "models": [
    {
      "model": "claude-3-5-sonnet-latest",
      "provider": "anthropic",
      "apiKey": "",
      "title": "Claude 3.5 Sonnet"
    },
    {
      "model": "AUTODETECT",
      "title": "Autodetect",
      "provider": "ollama"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": ""
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
}
```

### Description

OLLAMA_KEEP_ALIVE not working with continue extension. See https://github.com/ollama/ollama/issues/5272#issuecomment-2489940273 and following comment.

### To reproduce

Start ollama serve with OLLAMA_KEEP_ALIVE=-1 environment variable.
Chat inside Conitnue Extension.
Ollama release model memory after a while instead of keeping it in memory.

**Comment by tranquochuy645** [comment]
Hi @xgdgsc,

There is a configuration for sending the "keep_alive" param to Ollama, the default value is 60*30 (30 minutes) if you leave it omitted

Take a look at their documentation: https://docs.continue.dev/reference#completionoptions

I'm not sure how Ollama handle this value, but if you want to keep it alive forever, try something like this:

{
"models":[
"title": "Ollama",
"provider": "ollama",
"model": "AUTODETECT"
"completionOptions":{
"keepAlive": 9999999,
}
]
}

**Comment by xgdgsc** [comment]
Thanks!

**Comment by ctwardy** [comment]
Digging into this. From the Ollama [MR #2146 (Keep-Alive)](https://github.com/ollama/ollama/pull/2146): 

> Also, maybe most importantly, subsequent calls to the /api/generate will change the load duration, so even if you called it once with a negative value **and the next caller omits it**, it will still only stay in memory for 5 minutes after the second call. 

Suspect this is behind our Ollama server unloading despite launching with KEEP_ALIVE=-1.  Going to try adding `"keepAlive": -1` to our `tabAutocompleteModel` etc.

**Comment by simfinite** [comment]
It seems this option was lost in the migration to YAML config as I cannot get it to work and it's not listed in the docs anymore https://docs.continue.dev/reference. It is still listed in the docs for the old JSON config: https://docs.continue.dev/json-reference

Can anyone confirm? Does this need a new ticket?

**Comment by z-aki** [comment]
@simfinite  it's explicitly mentioned to not work

https://docs.continue.dev/reference/yaml-migration#deprecated-configuration-options

>The following top-level fields from config.json still work when using config.json but have been deprecated and don’t have a YAML equivalent:

> top-level completionOptions
