### ISSUE TITLE
webview: Error: Could not register service worker: InvalidStateError

### ISSUE THREAD

**Issue by shashanknimje** [continuedev/continue#3049]
![image](https://github.com/user-attachments/assets/d4d4cf61-fe29-44a9-9db7-c97054e6caec)
![image](https://github.com/user-attachments/assets/41ab6d15-d005-4875-a390-51c1a16b885e)

I am now getting the above error after updating to ollama v0.4.4 (preview) is related to this issue.

It occurs as soon as you try to launch Continue. I tried uninstalling a reinstalling, but that didn't fix it either.

Here's the error vscode throws:

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

_Originally posted by @shashanknimje in https://github.com/continuedev/continue/issues/3048#issuecomment-2495518538_

**Comment by 69popovvlad** [comment]
Same problem

@shashanknimje 
I temporarily installed version 0.9.228 and it works for me

**Comment by Messa1** [comment]
@shashanknimje I run in the same problem -> https://github.com/continuedev/continue/issues/3062
I resolved the issue by modifying a single letter in the extension's code.

**Comment by Patrick-Erichsen** [comment]
Hi all, thanks for the quick feedback here 🙂  we've shipped a fix but our CI is broken right now due to an upstream outage in GH Actions. We'll post an update once the new version is out here: https://github.com/continuedev/continue/issues/3065

**Comment by RomneyDa** [comment]
fixed by #3059

**Comment by aahmozart** [comment]
I'm having this problem on Continue 0.8.66 with vscode 1.96.4
