### ISSUE TITLE
Stuck on "Loading Continue server..."

### ISSUE THREAD

**Issue by Explosion-Scratch** [continuedev/continue#305]
It won't go past this or show me any config options in the welcome. I've uninstalled and reinstalled the extension several times but it still doesn't work

**Comment by kabeza** [comment]
Here I'm going with the same trouble
More than 1hr waiting and still no luck

Don't know how to see debug or output info for these downloads the extension is getting ...

![imagen_1510](https://github.com/continuedev/continue/assets/274856/e2b2f681-f38c-4dd8-a6f0-9a1cc88222ca)

**Comment by sestinj** [comment]
For those experiencing this issue, we've solved a number of issues, and *more importantly* you can view the server logs now in `~/.continue/continue.log`. If you try again, it may work, and if not please send the logs and we will be able to much more quickly solve the problem! @Explosion-Scratch @kabeza

**Comment by kabeza** [comment]
@TyDunn 

OS: ElementaryOS Hera - Ubuntu 20.04 based

Python: 
 ~/.continue  python --version
Python 3.9.16
 ~/.continue  python3 --version
Python 3.6.9

Log: 
~/.continue/continue.log
wasn't available. I guess it may have been removed when uninstalling

Now I've reinstalled extension but now I get this warning

![imagen_1511](https://github.com/continuedev/continue/assets/274856/300951ef-9722-471e-8d73-d4a14bcb9f27)

When I execute the command I get
The package python3.9-venv is not available
E: The package «python3.9-venv» does not have a candidate for the installation

So I guess I'll have to solve this and find out how to get the python3.9-venv working in this OS

**Comment by sestinj** [comment]
@kabeza there are a couple things you might try to solve this:
1) first run `apt-get update`, then try the command again
2) try `apt-get install python3-venv` (potentially requiring `sudo`)

Let me know how this goes, and @kabeza, @Explosion-Scratch I'm going to close this issue unless you're still having issues with the original loading problem. Let me know. (I'll make sure to move the venv problem to a new issue before doing that if it isn't yet resolved)

**Comment by Explosion-Scratch** [comment]
I'm not getting the python3-venv error, nor did I get a notification like that. I'm using mac so I don't have APT.

**Comment by Explosion-Scratch** [comment]
It seems to be working now for me after I restarted a few times (😭)

**Comment by sestinj** [comment]
@Explosion-Scratch Glad to hear this (not that it required you restarting a few time, but that it works)—if it works consistently, I will close this issue, otherwise will continue looking into it. Lmk!
