### ISSUE TITLE
Stuck on "Loading Continue server..." from Discord

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#306]
[Discord thread](https://discord.com/channels/1108621136150929458/1120078552788893768/1134061028217471047)

**Describe the bug**

I'm trying to use the vs code extension on MacOS, python3 --version returns Python 3.9.6 , I've added my openAI key to the Continue settings, but every time I try to use the extension it gets stuck on "Loading Continue server...". I don't see any pop ups anywhere. What else can i try to get it working? Oh, and I am able to connect to the server using nc -zv localhost 65432 in my terminal.

**Environment**
- Operating System: MacOS
- Python Version: Python 3.9.6

**Console logs**

The logs in my vs code developer tools look fine to me, I did notice that there's a context in my developer console for a "pending iframe" that seems to be related to the Continue Extension.

**Comment by TyDunn** [comment]
Please let moghammed know on Discord when the issue has been closed

**Comment by sestinj** [comment]
A number of errors have been solved that should clear this up. I'll wait to close this issue until there is confirmation that things work.

If the issue comes up again, we now have a feature to view the issue logs in `~/.continue/continue.log`, and it would be extremely helpful to see them.

**Comment by juhsinto** [comment]
From - 'Toggle Developer Tools', here's my console log:

[Extension Host] Websocket import
workbench.desktop.main.js:131 [Extension Host] Using Continue version:  0.0.213
workbench.desktop.main.js:131 [Extension Host] In workspace:  /Users/jacinto/Desktop/Personal/UberClone
workbench.desktop.main.js:131 [Extension Host] Checking if server is old version
workbench.desktop.main.js:131 [Extension Host] Killing old server...
workbench.desktop.main.js:131 [Extension Host] Setting up python env for Continue extension...
workbench.desktop.main.js:131 [Extension Host] Running command:  python3 --version
workbench.desktop.main.js:131 [Extension Host] Python env already exists, skipping...
workbench.desktop.main.js:131 [Extension Host] Running command:  python3 --version
workbench.desktop.main.js:131 [Extension Host] Running command:  cd "/Users/jacinto/.continue/server" ; . env/bin/activate ; pip3 uninstall -y continuedev
workbench.desktop.main.js:131 [Extension Host] Running command:  cd "/Users/jacinto/.continue/server" ; . env/bin/activate ; pip3 install --upgrade pip ; pip3 install -r requirements.txt
workbench.desktop.main.js:131 [Extension Host] Running command:  python3 --version
workbench.desktop.main.js:131 [Extension Host] Starting Continue python server...
index.html?id=c4bd7fc1-1495-4fa8-95df-c632199163d1&origin=1bdd1f2b-df0a-4ed7-b94f-d56468614e7f&swVersion=4&extensionId=Continue.continue&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=webviewView:268 No service worker controller found. Waiting for controllerchange.
index.js:560 Starting React
2workbench.desktop.main.js:131 [Extension Host] Running onLoad
undefined.gif:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by sestinj** [comment]
Thanks so much! I'm working literally at the moment on something relevant, so I'll keep you updated. Let me know if reloading the window happens to work for you.

**Comment by juhsinto** [comment]
I was able to resolve the issue by - manually installing the python requirements ; via 
`cd Users/jacinto/.continue/server` and then `pip3 install -r requirements.txt`
**After** that, reloading vscode seemed to make the extension work.

**Comment by sestinj** [comment]
@juhsinto Glad that was able to solve it! I'm going to add this to our new troubleshooting documentation. Also don't want to close this issue yet since we haven't fixed the root problem, but I'm working [here](https://github.com/continuedev/continue/issues/320) on a solution by bundling a Python executable. I'll comment again with updates soon.

**Comment by sestinj** [comment]
root issue has been solved, closing this issue
