### ISSUE TITLE
Switch to local - o.some is not a function error

### ISSUE THREAD

**Issue by Messa1** [continuedev/continue#3062]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version:v0.8.58
- IDE version: Version: 1.95.3 (Universal)
- Model: Local
- config.json:
```

### Description

If you switcht to local you got stuck on a error.

![Local-Error](https://github.com/user-attachments/assets/2e290462-b533-4d3a-9e7d-c37211050cf3)

I found a quick soltiuon - cause there is a typerror in the code.
/.vscode/extensions/continue.continue-0.8.58-darwin-x64/out/extension.js
on line 352573 change `o.some` to `to.some`

and than you got the change to switch back from local.

### To reproduce

1. Switch to local.

**Comment by Patrick-Erichsen** [comment]
Should be resolved with this PR: https://github.com/continuedev/continue/pull/3059

**Comment by Messa1** [comment]
@Patrick-Erichsen Thank's I will check tomorrow
