### ISSUE TITLE
Sidebar crashes when clicking "Local" tab in onboarding

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#3065]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue version: v0.8.58
```

## Issue

When clicking the "Local" tab in the sidebar during onboarding, a type error is causing the UI to crash. 

![Screenshot 2024-11-25 at 11 02 02 AM](https://github.com/user-attachments/assets/6e2152c1-ee91-4a96-ab21-b0e5de62f280)

## Solution

We've merged a [PR to resolve this](https://github.com/continuedev/continue/pull/3059) and are working on getting a new release out by end of day.

In the meantime, the issue can be avoided by not clicking on the "Local" tab. If you've already clicked on the tab, you can quit out of the editor, reopen, and select a different tab or close the onboarding card.

**Comment by sestinj** [comment]
The hotfix for this has now been published in version 0.8.59
