### ISSUE TITLE
Issues with Continue

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#307]
@bhaktatejas922 reported issues in https://github.com/continuedev/continue/issues/300#issuecomment-1652954048

**Comment by TyDunn** [comment]
Are you able to share more about your situation? 

It would help us to know:
- Bug description: [i.e. A clear and concise description of what the bug is]
- Steps to reproduce: {e.g. 1. Go to '...', 2. Click on '....', 3. See error]
- Operating System: [e.g. MacOS]
- Python Version: [e.g. 3.10.6]
- Console logs

To get the console logs in VS Code:
1. `cmd+shift+p` (MacOS) / `ctrl+shift+p` (Windows)
2. Search for and then select "Developer: Toggle Developer Tools"
3. Select Console
4. Read the console logs

This would help us debug your issues!

**Comment by sestinj** [comment]
Hi @bhaktatejas922, I'd love to hear more details on the issue you were having, or whether it has already been resolved (we've been making a lot of fixes!). Let me know : )

**Comment by sestinj** [comment]
Issue resolved by #320
