### ISSUE TITLE
Always Request Github Login if using Remote Config Server Url

### ISSUE THREAD

**Issue by lovenemesis** [continuedev/continue#3082]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Fedora 41
- Continue version: v0.8.59 and v0.9.235
- IDE version: VSCodium 1.95.3
- Model: Self-hosted Qwen2.5-coder
- config.json:
```

### Description

Whenever the `Remote Config Server URL` is configured, starting VSCodium will trigger a pop-up asking signing using Github.

![Screenshot From 2024-11-26 15-24-56](https://github.com/user-attachments/assets/905353e6-5891-4cec-9ff3-5ec300578c90)

Although it appears to be something that can be safely ignored as the remote server configuration works anyway, it's a bit annoying to have to click `Cancel` when starting VSCodium.

This applies both to VS Code and VS Codium, but not the Android Studio which on v0.0.81. Putting `Remote Config Server URL` there will NOT trigger the signing pop-up.

### To reproduce

1. Go to `Settings` and put a URL pointing to the server holding remote configuration file.
2. Restart VSCodium

### Log output

```Shell
workbench.desktop.main.js:35  WARN Settings pattern "issueReporter.*" doesn't match any settings
workbench.desktop.main.js:35  INFO Started local extension host with pid 74910.
workbench.desktop.main.js:35  WARN Settings pattern "issueReporter.*" doesn't match any settings
workbench.desktop.main.js:35  INFO [perf] Render performance baseline is 42ms
workbench.desktop.main.js:613 [Extension Host] rejected promise not handled within 1 second: Error: User did not consent to login.
gqi @ workbench.desktop.main.js:613
workbench.desktop.main.js:613 [Extension Host] stack trace: Error: User did not consent to login.
    at j5t.doGetSession (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:649:74479)
    at async j5t.$getSession (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:649:75431)
gqi @ workbench.desktop.main.js:613
workbench.desktop.main.js:35   ERR User did not consent to login.: Error: User did not consent to login.
    at j5t.doGetSession (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:649:74479)
    at async j5t.$getSession (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:649:75431)
```

**Comment by sestinj** [comment]
@lovenemesis We fall back to GitHub authentication if you don't have a `userToken` defined. As long as you set the "User Token" value we won't request GitHub auth. Given that API keys are likely to be obtained through a remote server URL, we won't adding an option to remove authentication

Source code is here for reference: https://github.com/continuedev/continue/blob/ad298878cc6a00ffe32a54b80efc7ced20782ed2/extensions/vscode/src/stubs/auth.ts#L4-L17
