### ISSUE TITLE
keep_alive setting

### ISSUE THREAD

**Issue by kanoai7** [continuedev/continue#3084]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

i wonder where can i set keep_alive for ollama? seems already support

**Comment by tranquochuy645** [comment]
Hi @kanoai7 ,

You can set this value by editing your config.json, the default value is 60*30 (30 minutes)

Take a look at their documentation: https://docs.continue.dev/reference#completionoptions

It's something like this:

'''
{
  "models":[
    "title": "Ollama",
    "provider": "ollama",
    "model": "AUTODETECT"
    "completionOptions":{
      "keepAlive": 9999999,
      }
  ]
}
'''

**Comment by kanoai7** [comment]
> Hi @kanoai7 ,
> 
> You can set this value by editing your config.json, the default value is 60*30 (30 minutes)
> 
> Take a look at their documentation: https://docs.continue.dev/reference#completionoptions
> 
> It's something like this:
> 
> { "models":[ "title": "Ollama", "provider": "ollama", "model": "AUTODETECT" "completionOptions":{ "keepAlive": 9999999, } ] }

sorry, i should check doc more careful.
