### ISSUE TITLE
配置Ollama的模型，可以配置Ollama的服务地址

### ISSUE THREAD

**Issue by anyfeng** [continuedev/continue#3101]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

本地部署Ollama，通常会部署在一台性能强劲的服务器上，通常不会在本机部署。在配置模型为Ollama的时候，希望同时可以配置Ollama的服务地址。

**Comment by sestinj** [comment]
@anyfeng you can set the `apiBase` like this:

```json
{
  "models": [
    {
      "title": "Llama3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b",
      "apiBase": "https://xxx"
    }
  ]
}
```
