### ISSUE TITLE
All code snippets in chat output in vscode are applied automatically. Clicking Reject sometimes leaves code in broken state. 

### ISSUE THREAD

**Issue by lendle** [continuedev/continue#3119]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 15
- Continue version: v0.9.236 (pre-release)
- IDE version: VSCode 1.95.3 
- Model: Sonnet 3.5
```

### Description

**Edit** Seems like this is happening for all code snippets in chat replies, not just with "Ask Continue". I'll leave my original description as is and add more detail in a comment.

When I use the "Ask Continue" quick fix, any code suggestions are applied automatically, without clicking "Apply". The "Reject" button at the end does not restore code to the prior state. At least not always.

This started happening recently. I think with pre-release version v0.9.236 or maybe one prior. If it was before that, I probably would have reported it sooner though, because it's driving me nuts :)

### To reproduce

1. Write some code with an error (the easy part)
2. Cursor over the red squiggle, Cmd+. to bring up Quick Fix menu
3. "Ask Continue" 

In the example in the screenshot, when I click "Reject", I wind up with

```
export function myFunc(x?: { a: number }) {
    return x.a > 0
}


export function
```

starting from 
```
export function myFunc(x?: { a: number }) {
    return x.a > 0
}

```

<img width="994" alt="image" src="https://github.com/user-attachments/assets/8eeb6cba-0dc7-4e0a-9b8e-72b7676db4eb">

### Log output

```Shell
Nothing in the Continue output tab, nothing that looks relevant in Webview dev tools.
```

**Comment by lendle** [comment]
I just tried highlighting some code and hit Cmd+L to add it to chat context. Then, I asked a question about the code in chat. The response in chat had a snippet with my original code plus added comments. It was then automatically applied as a diff.

Additionally, it was applied at the bottom of the file rather than to the right section of the file. Though that might be an issue with "Apply diffs" in general, I haven't used that much lately so not sure.

**Comment by lendle** [comment]
Interestingly, if I say "Do not edit my code" in chat, it doesn't.

**Comment by lendle** [comment]
Hmm, it's even happening when I am not adding context to my chat at all. I asked some question about how npm works and the output had a code block with a section of a hypothetical package.json. It then automatically applied that to my package.json that happened to be open. 

<img width="481" alt="image" src="https://github.com/user-attachments/assets/f979940f-8d45-4338-9c74-4d0902108083">

**Comment by lendle** [comment]
I've tried older preview versions. I am seeing this back to 0.9.234, but so far 0.9.233 doesn't seem to have the issue.

**Comment by sestinj** [comment]
@lendle thanks for calling this out. I think it's happening in very rare cases when a localstorage variable fails to get cleared. Can you try clearing localstorage in dev tools, reloading the window, and let me know if this still happens?

We do have a potential fix on the way regardless, but that might be the temporary solution

**Comment by lendle** [comment]
Thanks @sestinj. Just updated to v0.9.239 and it doesn't seem to be happening, but I did not clear localstorage. If it happens again I'll try that and report back. Will close for now.

**Comment by iraklisg** [comment]
I run into that strange issue. While chatting and ask to help me create a web component the plugin automatically applied the proposed code and created new files without explicitly asked for. BTW I wasn't aware that Continue can create new files. I cleared the localstorage from VSCode dev tools and the issue seems to be fixed atm, however I would kindly suggest to take a closer look on that
