### ISSUE TITLE
Groq is not working 

### ISSUE THREAD

**Issue by AnuragRai017** [continuedev/continue#3129]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

### To reproduce

1. Go to Groq
2. click on the provider 
3. it files

**Comment by sestinj** [comment]
Hey @AnuragRai017, thanks for the report.  Can you share more about what is going wrong so we can help?

**Comment by AnuragRai017** [comment]
When i want to access the groq it not weoking

![image](https://github.com/user-attachments/assets/7631f4f1-2627-41ae-ab51-2204037d3217)

**Comment by sestinj** [comment]
Got it! Could you please share your config.json?

**Comment by rklasen** [comment]
I can confirm the issue. I've deleted the config.json completely and let Continue create it anew. When selecting Groq here:

![image](https://github.com/user-attachments/assets/20b13dd4-444a-4a58-a7e3-13efcef162de)

I get the error 

```
Cannot read properties of undefined (reading 'title')
```


![image](https://github.com/user-attachments/assets/7c083be3-0def-40c7-a18c-3682105721f1)

--- 

All other providers work. I wanted to test the new `llama-3.3-70b-versatile`, which so far is only available on Groq.

**Comment by mkhennoussi** [comment]
Same bugs here, I've added the model manually : 
```json
{
      "title": "Llama 3.3 70b",
      "provider": "groq",
      "model": "llama-3.3-70b-versatile",
      "apiKey": ""
}

**Comment by sestinj** [comment]
Ok! I finally understand, thank you

Fix is here: https://github.com/continuedev/continue/pull/3305

We'll have this in the next release!
