### ISSUE TITLE
Add support for Rift AI language server

### ISSUE THREAD

**Issue by jesse-michael-han** [continuedev/continue#314]
Hello! Congrats on the release. It would be great to get Continue working with [Rift](https://www.github.com/morph-labs/rift), an open-source AI-native language server written in Python. Rift also supports many popular third-party coding agents out of the box such as [smol-developer](https://www.github.com/smol-ai/developer), [gpt-engineer](https://www.github.com/antonosika/gpt-engineer), and [aider](https://www.github.com/paul-gauthier/aider) through the [Rift Agents API](https://github.com/morph-labs/rift/tree/main/rift-engine/rift/agents), which can be easily represented as `Step`s in the SDK.

**Is your feature request related to a problem? Please describe.**
Continue does not have access to language server functionality, which can power more intelligent code search and understanding.

**Describe the solution you'd like**
Rift can be spun up as a part of the Continue server as a separate process that can be communicated with via TCP, like other language servers. It can run in the main event loop:

```bash
pip install pyrift
```

```python
from rift.server.core import create_metaserver

... # other stuff in your event loop

metaserver = create_metaserver("127.0.0.1", 7797)
asyncio.create_task(metaserver.run_forever()) 
```

**Describe alternatives you've considered**
n/a

**Additional context**
I'd love to stand up a PR and get the ball rolling here! We're on [Discord](https://discord.gg/wa5sgWMfqv) as well for synchronous collaboration, ping us anytime.

**Comment by sestinj** [comment]
Hi Jesse! I think this sounds quite interesting. Could you explain a little more about how you see the language server aspect coming into play with Continue? I think it would be great to be able to offer access to "goto definition" and other related functionalities in our SDK—is this what rift is made to do, or would the integration in your mind be more about embedding agents in Continue? Also would be helpful to hear some quick examples / use cases about what such a Step would do.

Let me know! Excited to hear more

**Comment by sestinj** [comment]
Hey @jesse-michael-han, just wanted to check in on this. Would be quite cool to support Rift!

**Comment by sestinj** [comment]
It's been a minute since this issue, but I'm going through and trying to clean up. Very happy to be able to do so knowing that we were able to integrate phorm : )
