### ISSUE TITLE
"Bedrock currently does not offer any reranking models." -> Cohere 3.5 Rerank

### ISSUE THREAD

**Issue by AnnoyingTechnology** [continuedev/continue#3152]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The documentation states

> Bedrock currently does not offer any reranking models.

Which is not accurate, there is Cohere Rerank 3.5 available in multiple regions. 

The documentation therefore isn't clear on how to configure it. 

### Solution

Update the documentation to specify that at least one model does exist, and specify how to configure it with Bedrock.

**Comment by AnnoyingTechnology** [comment]
When attempting to use the same syntax as for the chat model or the embedding provider, Continue.dev throws `Cannot read properties of undefined (reading 'apiBase')`.

**Comment by AnnoyingTechnology** [comment]
Also: `amazon.rerank-v1:0`

**Comment by sestinj** [comment]
Hey! Thanks for sharing this, I wasn't aware of this model before. We're going to need to add support for a `Bedrock` reranker class before we can officially add it to the docs. Is this something you might be interested in contributing?

**Comment by AnnoyingTechnology** [comment]
Would very much like to, but I'm clueless in typescript. 

Although we kinda need it for later this month, so I might end up forking and attempting something, but it wouldn't deserve a PR.
