### ISSUE TITLE
groq model not accepted in continue

### ISSUE THREAD

**Issue by Swamyko** [continuedev/continue#3182]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

**Comment by Patrick-Erichsen** [comment]
https://docs.continue.dev/customize/model-providers/more/groq ?

**Comment by dandv** [comment]
This is a very lazy bug report. Please consider closing it, to not encourage this sort of behavior.
