### ISSUE TITLE
o1 is not working with maxTokens

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#3189]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: 0.9.239
- IDE version: 1.95.3
- Model: o1-preview
```

### Description

Says "Error in continue server" but this is an openai error
![image](https://github.com/user-attachments/assets/d8b76757-59f4-4e8e-be9d-e0660f53c946)

I suspect the bug is that `completionOptions.maxTokens` is always translated to `max_tokens`, while it should be translated to `max_completion_tokens` for o1

Related to https://github.com/janhq/jan/issues/3698

**Comment by sestinj** [comment]
My hunch is that this is only happening through an LLM proxy. We are already making the necessary translation here: https://github.com/continuedev/continue/blob/b488fe1bad65a6743312dbcbd3fc662279b71e9d/core/llm/llms/OpenAI.ts#L155-L156

If anyone can share the config.json that causes this, please do!

**Comment by RomneyDa** [comment]
This was an error that I was setting, and does appear to be just continue for teams

**Comment by sestinj** [comment]
Got it, will close for now then but if it comes back outside Continue for Teams let's re-open

**Comment by s-jse** [comment]
I'm seeing the same error:
![image](https://github.com/user-attachments/assets/3aa6b07a-28fd-42d6-a06a-737833bb3dce)

This is the model config in my config file:
```
 {
      "model": "o1",
      "title": "o1",
      "apiKey": "sk-...",
      "provider": "openai"
 }
```
- OS: Windows 11
- Continue version: 0.9.246
- IDE: VSCode 1.96.2
- Model: o1

**Comment by Millet-ML** [comment]
could we please add `o3-mini` to line 101 of [continue/core/llm/llms/OpenAI.ts](https://github.com/continuedev/continue/blob/b488fe1bad65a6743312dbcbd3fc662279b71e9d/core/llm/llms/OpenAI.ts#L155-L156)
`private isO1Model(model?: string): boolean ...`
? Perhaps preemptively add o3 as well?
Getting this same error now with o3-mini
