### ISSUE TITLE
continue server not shutdown when closing vscode

### ISSUE THREAD

**Issue by TKlerx** [continuedev/continue#322]
continue server not shutdown when closing vscode. Instead, the continue server is still running (under windows)

**To Reproduce**
1. Start vscode
2. wait for continue server to start
3. close vscode
4. find continue server still running in task manager

**Expected behavior**
continue server should be closed when vscode is closed

**Environment**
- Operating System: Windows 11
- Python Version: 3.11.4
- Continue Version: 0.0.218

**Comment by sestinj** [comment]
I can see why this would be considered incorrect behavior, but do you mind sharing a bit about why this is an issue for you? I'll check into what this would require.

**Comment by TKlerx** [comment]
Well:
If you change some config in config.py (if this file would be read by the server), then the server needs to be restarted. But if you clse vscode, the server is not restarted. So apart from killing the continue server by task manager (or something similar), there is no way to start the server with the new config.
This is not consistent with the documentation and seems a bit strange.

Additionally, it seems a bit odd to me to leave a process running in the background if it is not needed anymore.

**Comment by sestinj** [comment]
@TKlerx It might seem slightly odd, but background processes are very common, and in this case it helps with speeding up loading time when reloading VS Code. This is also a very non-intensive process.

The server does not need to be restarted in order for the config file to be reloaded: this will be done automatically each time that the VS Code window is reloaded.

The last point is interesting and maybe cause for a new issue. We attempt to kill the server if it is running the old version, and if this is failing that would be a bug. Can you share what made you aware that the server version was old?

**Comment by TKlerx** [comment]
Thanks for the clarification.

Regarding the last point:
It was my impression that the server was using the old config. Maybe, I was mistaken or it was still some old version of the extension.
You have an incredible speed of implementing fixes, so I would close this issue and would open a new issue if I can confirm this behavior with the latest version and some logs.
