### ISSUE TITLE
Plans to Support XCode?

### ISSUE THREAD

**Issue by shouldnotappearcalm** [continuedev/continue#3223]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Thank you for your excellent work on [Plugin Name]. I’m wondering if there are any plans to support the XCode editor in the future.

**Comment by tomasz-stefaniak** [comment]
@shouldnotappearcalm we don't currently have it on the roadmap but since Continue is open source, we would welcome a contribution if there is significant interest in this.

**Comment by shouldnotappearcalm** [comment]
ok thanks
