### ISSUE TITLE
CONTRIBUTING.md emoji links do not go to intended section

### ISSUE THREAD

**Issue by arifaisal123** [continuedev/continue#324]
**Describe the bug**
Clicking some of the links (ones with the emojis) does not go to the intended section in the CONTRIBUTING.md page.

**To Reproduce**
1. Go to [contributing section](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md).
2. Click on [a link with emoji](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#%F0%9F%90%9B-report-bugs).

**Expected behavior**
The link is supposed to take the user to the intended section of the page.

**Screenshots**
<img width="937" alt="continue" src="https://github.com/continuedev/continue/assets/92214243/8be1ec7e-ed04-477a-99ed-13051c6f09e3">

**Environment**
- Operating System: Windows
- Python Version: 3.11.4

**Comment by arifaisal123** [comment]
I am willing to contribute to this issue.

**Comment by TyDunn** [comment]
@arifaisal123 Fixed! Thanks for point this out :)
