### ISSUE TITLE
Issue with Multifile Contexts

### ISSUE THREAD

**Issue by 3cognito** [continuedev/continue#328]
### Description of the bug

Previously, I was able to provide multi file contexts to Continue, all I needed to do, was highlight a piece of code in one file and on the left pane of my IDE where the Continue GUI resides, I would see the file from which I have added a context and a button I could click to add more context or delete a previously added context.

However, I cannot do that anymore, there is an option to use the '@' symbol for the same purpose, but that does not do anything. 

For context, I am on a PC running Windows 11.

**To Reproduce**
1. Open VScode on a PC running Windows 11.
2. Install and run Continue
3. Try to use the multi file feature, highlight something in one file.
4. Observe that it does not indicate the file where a highlight was made and provides no option to add another context.

**Expected behavior**
Should indicate the file where a highlight was made and provide the option to add more context or delete one already added.

**Environment**
- Windows 11.
- Python Version: 3.10.11.
- Continue Version - latest.

**Console logs**
No logs as nothing breaks while I am using the extension, that feature just does not work anymore.

**Comment by 3cognito** [comment]
![Screenshot (136)](https://github.com/continuedev/continue/assets/91505386/34a53fa6-65d7-4e51-9340-54f256bb9807)

Installed Meilisearch and have it running, is there anything else I am supposed to do?

**Comment by 3cognito** [comment]
![Screenshot (137)](https://github.com/continuedev/continue/assets/91505386/e9a628d6-00d6-492b-a604-4fd62db4517c)

Installed Meilisearch and have it running, I can see some logs which seem to be related to Continue, is there something else I am supposed to do regarding this?

**Comment by sestinj** [comment]
@3cognito I'll try to reproduce this first thing tomorrow. As far as Meilisearch, if it is working correctly, then you should only need to reload VS Code, then type '@' in the Continue text box, and this would show a dropdown of files from your workspace folder. If this doesn't happen, then it would be another bug and I'll look into this as well.

**Comment by 3cognito** [comment]
Ok

**Comment by sestinj** [comment]
@3cognito I've finally gotten around to this, and the multi-file highlighting issues should be fixed in the newest versions. I'll keep this issue open until we are sure that everything is okay.

**Comment by sestinj** [comment]
Closing this issue as I think it's been solved as far as I've been able to reproduce on both a windows and mac machine. If it comes up again, feel free to reopen.
