### ISSUE TITLE
CustomLLMWithOptionals interface definition is not up-to-date

### ISSUE THREAD

**Issue by 70m4** [continuedev/continue#3316]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version: vscode 0.8.61
- IDE version:
```

### Description

Looks like signal parameter is missing in streamChat and streamCompletion definition. 
So models are not loaded properly, options (CompletionOptions) is empty.
I guess the signal value goes to options and options gets a default empty value.
 
```ts
export interface CustomLLMWithOptionals {
    options: LLMOptions;
    streamCompletion?: (
      prompt: string,
      options: CompletionOptions,
      fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
    ) => AsyncGenerator<string>;
    streamChat?: (
      messages: ChatMessage[],
      options: CompletionOptions,
      fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
    ) => AsyncGenerator<string>;
    listModels?: (
      fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
    ) => Promise<string[]>;
  }

// core/index.d.ts
streamChat(
    messages: ChatMessage[],
    signal: AbortSignal,
    options?: LLMFullCompletionOptions,
  ): AsyncGenerator<ChatMessage, PromptLog>;

```

There are signals parameters in [core/index.d.ts](https://github.com/continuedev/continue/blob/d7ef0a3b1babfd9106fae7141e48a185de3bef49/core/index.d.ts#L127), but not in [core/config/types.ts](https://github.com/continuedev/continue/blob/d7ef0a3b1babfd9106fae7141e48a185de3bef49/core/config/types.ts#L351)

**Comment by glppfr** [comment]
You are right ! This breaks when using modifyConfig in custom config.ts. Thanks
