### ISSUE TITLE
Autocomplete Toggle Status Bar Button doesn't work

### ISSUE THREAD

**Issue by cobrafast** [continuedev/continue#3330]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue version: 0.0.83 (from Jetbrains Marketplace)
- IDE version: Rider 2024.1.6
- Model: irrelevant
- config.json: barebones, ollama only
```

### Description

Status bar button to, I assume, toggle autocompletion has ~~no icon~~ a single black pixel for an icon and doesn't seem to do anything when clicked (at least the tooltip never changes from 'Continue autocomplete enabled').
![20241212-005118](https://github.com/user-attachments/assets/1668303f-0eba-471f-9e3c-627b15ab89d3)

Rider's clear caches and restart didn't help.

### To reproduce

1. Start Rider and open a project from the splash screen.
2. Wait for everything to load up.

### Log output

Nothing out of `idea.log` jumps out. Continue's getting some access denied errors to `obj/` output directories of the .NET project I'm working on, nothing else. Mouse interactions with the button don't trigger any errors.

**Comment by dandv** [comment]
This is a regression that I also see on Linux. 0.0.75 displayed the Continue icon, but 0.0.83 no longer shows it.

![image](https://github.com/user-attachments/assets/ca2d5fed-a4e8-41d7-8d29-065228553f98)

**Comment by Patrick-Erichsen** [comment]
Good catch, and thanks for providing a specific release to look into @dandv ! Not sure how this got removed but I've added it back in.

**Comment by cobrafast** [comment]
@Patrick-Erichsen will the icon being back also fix that the status bar button doesn't do anything?
