### ISSUE TITLE
[CON-195] Server hangs on `connection = CONNECTING`

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#334]
**Describe the bug**
The IDE connects to the server, but the GUI never successfully connects. Last entry in the logs is from certifi, saying `connection = CONNECTING`

**To Reproduce**
1. Download Continue

**Expected behavior**
The server should start and connect and the loader should disappear

**Environment**
- Operating System: [e.g. MacOS]
- Python Version: [e.g. 3.10.6]
- Continue Version: [e.g. v0.0.207]

**Console logs**
```
Started server process [33650]
Waiting for application startup.
Application startup complete.
Uvicorn running on http://0.0.0.0:65432/ (Press CTRL+C to quit)
= connection is CONNECTING
= connection is CONNECTING
< GET /ide/ws?session_id=50efc913-de37-46d7-ba62-de6906f0c06b HTTP/1.1
< sec-websocket-version: 13
< sec-websocket-key: 1MjS4a9rgLZ+o1TzhTwTZw==
< connection: Upgrade
< upgrade: websocket
< sec-websocket-extensions: permessage-deflate; client_max_window_bits
< host: localhost:65432
< GET /ide/ws?session_id=a39fa52e-13e7-49ba-93d8-8c2252ed9989 HTTP/1.1
< sec-websocket-version: 13
< sec-websocket-key: ZZdSvP4ahO0aXWwM4g+DhQ==
< connection: Upgrade
< upgrade: websocket
< sec-websocket-extensions: permessage-deflate; client_max_window_bits
< host: localhost:65432
load_ssl_context verify=True cert=None trust_env=True http2=False
load_verify_locations cafile='/Users/garyrob/.continue/server/env/lib/python3.10/site-packages/certifi/cacert.pem'
load_ssl_context verify=True cert=None trust_env=True http2=False
load_verify_locations cafile='/Users/garyrob/.continue/server/env/lib/python3.10/site-packages/certifi/cacert.pem'
= connection is CONNECTING
= connection is CONNECTING
= connection is CONNECTING
```

**Additional context**

<sub>[CON-195](https://linear.app/continue/issue/CON-195/server-hangs-on-connection-=-connecting)</sub>

**Comment by sestinj** [comment]
@garyrob, one thing I noticed is that the server has started on 0.0.0.0, but we changed this to be 127.0.0.1 in a recent version. Could you share which OS you are using and verify that you're on the latest version of the extension (v0.0.233)? Assuming this is the case, then we might be incorrectly updating the python package.

**Comment by garyrob** [comment]
I just now uninstalled it and reinstalled it. It said it was going to be installing .0.0.233. Same thing as before... just waiting forever while it says it may take a minute to download the python code. The latest log, from after the reinstall, seems to confirm your suspicion.

Started server process [33650]
Waiting for application startup.
Application startup complete.
Uvicorn running on http://0.0.0.0:65432 (Press CTRL+C to quit)
= connection is CONNECTING
= connection is CONNECTING

-- 

Gary Robinson
***@***.***
http://www.garyrobinson.net

**Comment by sestinj** [comment]
Thanks for the update, looking into this. If an old server version truly is the problem, a temporary solution would be to delete the `~/.continue` directory and restart VS Code. This would force Continue to reinstall the server.

**Comment by garyrob** [comment]
I think that fixed it! I'll let you know if I have more problems.

-- 

Gary Robinson
***@***.***
http://www.garyrobinson.net

**Comment by sestinj** [comment]
Fantastic! I'm going to close this issue because, though the root cause isn't solved, it will be solved once I've merged the branch that uses pyinstaller to distribute the server
