### ISSUE TITLE
/edit command broken after 0.8.5.7

### ISSUE THREAD

**Issue by shermanhuman** [continuedev/continue#3356]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: v0.8.61
- IDE version: 1.93.1
- Model: Multiple, Llama 3.1
- config.json:
  
{
  "models": [
    {
      "title": "Llama 3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b"
    },
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Starcoder 3b",
    "provider": "ollama",
    "model": "starcoder2:3b"
  },
  "contextProviders": [
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    },
    {
      "name": "open"
    },
    {
      "name": "repo-map"
    },
    {
      "name": "tree"
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  }
}
```

### Description

![image](https://github.com/user-attachments/assets/9b21adb0-3146-41b5-9310-74ca0eba5149)

/edit command fails to appear in chat input after 0.8.5.7 upgrade.  Reverting to 0.8.5.6 resolves the issue.

[Discord discussion link](https://discord.com/channels/1108621136150929458/1316615014194614333/1316615014194614333)

### To reproduce

1. Select text in the VS Code editor
2. CMD + L
3. Type `/` or `/edit` in the chat input
4. Observe that edit does not appear in the / dropdown

**Comment by shermanhuman** [comment]
0.8.5.6:

<img width="385" alt="image" src="https://github.com/user-attachments/assets/3c8d78d8-b187-46a7-890f-164c593189fb" />

0.8.6.1:

<img width="385" alt="image" src="https://github.com/user-attachments/assets/a4b23e16-1521-4070-b816-f9830e004725" />

Maybe /comment and /test are impacted as well.  /test being an odd one ... it's not in my config file.

**Comment by sestinj** [comment]
This is purposeful with the introduction of cmd+I in the sidebar. We found it confusing that there were two ways to accomplish the same thing. Going to close this as won't fix, but it might be appropriate to add another issue for side-by-side diffs if that's desired
