### ISSUE TITLE
why not show bottom photo

### ISSUE THREAD

**Issue by zhaoljgithub** [continuedev/continue#3391]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

### Description

![微信截图_20241216104408](https://github.com/user-attachments/assets/057ff035-f14e-49d5-b52f-4409d28ff365)

just,i got bottom photo
![微信截图_20241216104511](https://github.com/user-attachments/assets/37ee3087-0768-4137-b70d-d51900f9b61c)

**Comment by sestinj** [comment]
@zhaoljgithub The first photo you have shared is a screenshot of a JetBrains IDE. VS Code does not allow inline rendering like this. However you can drag the sidebar to the right side, which I would recommend (see [here](https://docs.continue.dev/getting-started/install#vs-code))
