### ISSUE TITLE
Question or Feature Request: Configuration in PyCharm

### ISSUE THREAD

**Issue by barseghyanartur** [continuedev/continue#3399]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

ATM, VS Code allows any type of configuration tweaks. PyCharm doesn't (or I could not find it).

For instance, how to add a custom `ollama` model? How to specify the embeddings? In VS Code I have this:

```
{
  "models": [
    {
      "title": "Qwen2.5-Coder 1.5B",
      "provider": "ollama",
      "model": "qwen2.5-coder:1.5b",
      "apiKey": ""
    },
    {
      "title": "Qwen 2.5 Coder 7b",
      "model": "qwen2.5-coder:7b-instruct",
      "provider": "ollama"
    },
    {
      "title": "Qwen 2.5 Coder 32b",
      "model": "qwen2.5-coder:32b-instruct-q2_K",
      "provider": "ollama"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Qwen2.5-Coder 1.5B",
    "provider": "ollama",
    "model": "qwen2.5-coder:1.5b",
    "apiKey": ""
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  },
```

Where and how do I configure that in PyCharm?

### Solution

If no such option exist, perhaps consider allowing customisation.

**Comment by Swipe4057** [comment]
You can use "Continue" in PyCharm?

**Comment by barseghyanartur** [comment]
> You can use "Continue" in PyCharm?

Yes, but it not everything as well as in VS Code yet due to configuration limitations described above.

**Comment by Patrick-Erichsen** [comment]
Hi @barseghyanartur , both JetBrains and VS Code extensions can be configured/customized through the same file: `~/.continue/config.json`

In any of the JetBrains IDEs, e.g. PyCharm, you can get to this file by clicking the gear icon in the top of the Chat panel
![Screenshot 2024-12-16 at 5 21 01 PM](https://github.com/user-attachments/assets/6fc5b352-56fc-4da2-a8b5-0e378e5f14cd)

**Comment by barseghyanartur** [comment]
@Patrick-Erichsen 

Amazing! Thank you!
