### ISSUE TITLE
Docs: Internet connection necessary?!

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [continuedev/continue#340]
I think it is always a good idea to state if the extension is using some external service or needs a internet connection for those that are behind a firewall and such :D

**Comment by TyDunn** [comment]
@sschneider-ihre-pvs Thanks for the feedback! You are right that we should be more clear about this. I updated the GitHub README as well as the VS Code extension marketplace README to say the following:

"By default, Continue uses GPT-4 and GPT-3.5-turbo via the OpenAI API.

You can adjust the config to use different LLMs, including local, private models. Read more [here](https://continue.dev/docs/customization#change-the-default-llm)."

The VS Code extension marketplace README will update when we publish a new version (likely today)
