### ISSUE TITLE
support gemini2.0

### ISSUE THREAD

**Issue by asukaminato0721** [continuedev/continue#3401]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

gemini 2.0 api is available now. But json schema hasn't added it.

"gemini-2.0-flash-exp"

```
Value is not accepted. Valid values: "chat-bison-001", "gemini-pro", "gemini-1.5-pro-latest", "gemini-1.5-pro", "gemini-1.5-flash-latest", "gemini-1.5-flash".(1)
```

but

```sh
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=$YOUR_KEY" \
                                                   -H 'Content-Type: application/json' \
                                                   -X POST \
                                                   -d '{
                                                 "contents": [{
                                                   "parts":[{"text": "Explain how AI works"}]
                                                   }]
                                                  }'
```

works.

also the "gemini-1.5-flash-8b" is usable but not listed.

### Solution

add type there.

**Comment by Patrick-Erichsen** [comment]
Good catch, thanks for the heads up!

**Comment by arvislacis** [comment]
@asukaminato0721 @Patrick-Erichsen Probably needs to add support also for `gemini-2.0-flash-thinking-exp` model.

**Comment by az7139** [comment]
Currently, gemini-2.0-flash-thinking-exp is still not supported.

**Comment by rubirubsen** [comment]
As by today gemini-2.5-flash seems unsupported :(
