### ISSUE TITLE
create a hint /  commands

### ISSUE THREAD

**Issue by irekgroup** [continuedev/continue#343]
**Is your feature request related to a problem? Please describe.**
I always get upset when I don't see the command or hint I need in the help field

**Describe the solution you'd like**
Add a +add hint button that will allow you to customize my continue

**Describe alternatives you've considered**
The hints / commands section where there will be a collection of such hints

**Additional context**

![2023-08-04_18-54-57](https://github.com/continuedev/continue/assets/70753735/5c8c9fc7-338d-4669-9113-1353a4bb6d61)

**Comment by sestinj** [comment]
@irekgroup You can do this with the /config slash command, but it's good to know that this isn't obvious. Curious whether "/customize" would be more obvious here, or whether you would still want a +add command option.

Once you select /config to open `~/.continue/config.py`, you can see the docs [here](https://continue.dev/docs/customization#custom-commands) to learn about making custom commands. After updating the config file, you'll just have to reload the window for changes to take effect.

**Comment by sestinj** [comment]
@irekgroup Checking in on this. Would love to hear how your experience with custom slash commands was, if there's anything you'd like to see to make it better

**Comment by sestinj** [comment]
Hi @irekgroup, I'm going to close this issue since it has been untouched for a week. Hopefully the proposed solution was satisfactory. Reopen if needed!

**Comment by irekgroup** [comment]
it works perfectly, the flight is normal!
