### ISSUE TITLE
add a copy response button

### ISSUE THREAD

**Issue by irekgroup** [continuedev/continue#344]
**Is your feature request related to a problem? Please describe.**
I always get upset when I can't just copy the full answer to my question

**Describe the solution you'd like**
I need to get a translation of the entire answer , so as long as there is no support for such a function out of the box , I would be able to quickly copy my answer and translate as it is convenient for me

**Describe alternatives you've considered**
An alternative is a button to translate the entire response

**Comment by sestinj** [comment]
@irekgroup You might actually be able to get the model to respond in your preferred language by changing the system message. This can be done in ~/.continue/config.py:

```python
...
config=ContinueConfig(
    ...
    system_message="Always give your responses in <PREFERRED_LANGUAGE>"
)
```

**Comment by sestinj** [comment]
Hi @irekgroup. Checking in on this out of curiosity, and will close the issue if everything is okay—did the system message turn out to be a reliable solution?

**Comment by sestinj** [comment]
@irekgroup Going to close this since it seems like the system message may have been a good solution. If it's not, please reopen and we can take a deeper look. Also am genuinely curious, feel free to leave a comment; want to know whether the quality of the model is equal in many languages
