### ISSUE TITLE
using in SSH connection doesn't starts the server

### ISSUE THREAD

**Issue by dottwatson** [continuedev/continue#348]
**Describe the bug**
Using VSCode with SSH conenction, the server does not starts.

**To Reproduce**
1. Go to Remote Explorer
2. Click on whatever conneciton with ssh and connect
3. Open Continue with the right Icon
4. Server can not connect

**Expected behavior**
The server start to work 

**Screenshots**

**Environment**
- Operating System: WIndows 11
- Python Version:  3.11

**Console logs**
```
ERR cannot open vscode-remote://ssh-remote%2Blarapackages.dev.web-dev.it/home/projects/.continue/continue.log. Detail: Unable to read file 'vscode-remote://ssh-remote+larapackages.dev.web-dev.it/home/projects/.continue/continue.log' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+my.domain.ext/home/projects/.continue/continue.log'): CodeExpectedError: cannot open vscode-remote://ssh-remote%2Bmy.domain.ext/home/projects/.continue/continue.log. Detail: Unable to read file 'vscode-remote://ssh-remote+my.domain.ext/home/projects/.continue/continue.log' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+my.domain.ext/home/projects/.continue/continue.log')
    at n.$tryOpenDocument (vscode-file://vscode-app/c:/Users/johndoe/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2313:37690)
```

**Comment by sestinj** [comment]
@dottwatson looking into this now, I think it won't be too difficult a fix. The issue was also experienced by @Hezhexi2002 [here](https://github.com/continuedev/continue/issues/338#issuecomment-1666880141).

**Comment by sestinj** [comment]
I've reproduced connecting to an Amazon Linux EC2. Attempting to start the server yields

```
Error loading Python lib '/tmp/_MEIKqUG1b/libpython3.10.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIKqUG1b/libpython3.10.so.1.0)
```

which is probably due to packaging with pyinstaller on a newer version of linux. Going to attempt building on an older version to allow compatibility.

**Comment by sestinj** [comment]
@dottwatson @Hezhexi2002 Building on an older version of Ubuntu did the trick for me. Version v0.0.266 has this update. If it still doesn't work for you let me know, and I may have to regress to an even older version for the build.

Posting some background information [here](https://stackoverflow.com/questions/55585021/does-python-pyinstaller-support-multiple-os-versions-of-linux) just for reference.

**Comment by dottwatson** [comment]
just tested and.. it works!

Really thanks to @sestinj and all the contrinutor to this great tool!!

**Comment by sestinj** [comment]
Awesome! Appreciate that. Always feel free to open an issue if there's anything else wrong with Continue or if you'd like a new feature :)

**Comment by Hezhexi2002** [comment]
> @dottwatson @Hezhexi2002 Building on an older version of Ubuntu did the trick for me. Version v0.0.266 has this update. If it still doesn't work for you let me know, and I may just need to regress to an even older version for the build.
> 
> Posting some background information [here](https://stackoverflow.com/questions/55585021/does-python-pyinstaller-support-multiple-os-versions-of-linux) just for reference.

sorry to response so lately,it also works for me when I update the version to the latest v0.0.270：
![image](https://github.com/continuedev/continue/assets/53631206/8d9a5fbd-8a56-4fbb-ab57-8125aa95367d)
