### ISSUE TITLE
Allow to run from an ollama llm endpoint. e.g (192.168.1.14:11434)

### ISSUE THREAD

**Issue by Nikvothe** [continuedev/continue#3489]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

At the moment, **Continue** allows you to specify an ollama model and assumes it is being ran from the same computer, however, what if you are hosting the model from some other endpoint in the network? This is now common as it is done in the terminal with "Ollama serve".
What if you wish to set up a dedicated server running llama 3.1 for a bunch of devs at the same time?

### Solution

Allow to specify an ollama endpoint instead of providing it locally, for example:
192.168.1.14:11434 (11434 is the default port ollama uses).

**Comment by arty-hlr** [comment]
YES! I can't believe that there is no option to change the IP or hostname for where ollama is hosted... @Nikvothe you closed this as completed, but was there any change? I don't see any option on my VS Code for an alternate IP.

**Comment by germanolira** [comment]
Upvote

**Comment by germanolira** [comment]
Same here
