### ISSUE TITLE
Highlighted file names are incorrect

### ISSUE THREAD

**Issue by ferrantejake** [continuedev/continue#350]
**Describe the bug**
When highlighting code in multiple different files, it seems as though the name of the file which the last code span is highlighted in takes over the names of all files listed as 'highlighted'. (See gif)

**To Reproduce**
1. Open at least two files to select from.
2. Select code span from File A, see file A populates extension with correct name.
2. Select code span from File B, see the name of File B takes over the file names for all code segments listed in extension. Also note the pop-up shows the correct code (and file path)

**Expected behavior**
File names should be respected when highlighting subsequent code spans. 

**Screenshots**
![Recording 2023-08-06 145849 (3)](https://github.com/continuedev/continue/assets/9873344/d0cc78b4-98dd-42ca-a975-99d05a3a2ebd)

**Environment**
- Continue Version: v0.0.266

**Comment by sestinj** [comment]
@ferrantejake (thanks to the video!) have reproduced myself and will get this fixed soon

**Comment by sestinj** [comment]
@ferrantejake Now solved! New version out later tonight
