### ISSUE TITLE
Allow ollama url to be configurable

### ISSUE THREAD

**Issue by hmoazzem** [continuedev/continue#3514]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

By default Continue vscode extension tries to connect `http://127.0.0.1:11434` for ollama provider. One might run an ollama instance on a desktop or a cloud VM, and access the same `http://ollma-machine-ip:11434` from multiple machines eg a laptop with Continue vscode extension. It's certainly not a blocker; the simplest fix I found is a proxy eg with nginx

```sh
server {
    listen 0.0.0.0:11434;

    location / {
        proxy_pass   http://ollama-machine-ip:11434;
    }
}
```

It'd be nicer to be able to configure ollama URL in `~/.continue/config.json`

**Comment by Patrick-Erichsen** [comment]
You should be able to do this using the `apiBase` config on your model: https://docs.continue.dev/reference#models

E.g.

```json
{
  "models": [
    {
      "title": "Llama3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b",
      "apiBase": "http://ollma-machine-ip"
    }
  ]
}
```

**Comment by hmoazzem** [comment]
Should've looked at reference. Closing.

**Comment by Patrick-Erichsen** [comment]
No worries! Good feedback that it isn't necessarily obvious when setting up your config.
