### ISSUE TITLE
[Bug] Incorrect URL in documentation

### ISSUE THREAD

**Issue by selfagency** [continuedev/continue#366]
**Describe the bug**
When you request help on how to provide feedback or report bugs to the Continue team, it offers a link to the incorrect URL

**To Reproduce**
`/help: how do i give continue devs feedback`

The response includes:

```
You can provide feedback or report a bug to the Continue team by visiting the [Continue GitHub repository](https://github.com/withcontinue/continue).
```

Your team name on GitHub is no longer `withcontinue` as the link has it.

**Expected behavior**
For the correct link to be there.

**Screenshots**
n/a

**Environment**
n/a

**Console logs**
n/a

**Additional context**
n/a

**Comment by sestinj** [comment]
Closing this issue, but feel free to reopen if you still find the '/help' command to be unsatisfactory
