### ISSUE TITLE
multi-file context highlighting is broken

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#368]
**Describe the bug**

I am unable to select multiple sections across two files. After trying and failing, I then am unable to delete one of the selections.

**To Reproduce**
1. Highlight code in one file
2. Add document + button
3. Switch to another file
4. See that it switches selections to both be from the second file
5. Try to delete both selection
6. See that it does not delete the second

**Expected behavior**

I should be able to select code sections from two files

**Environment**
- Operating System: MacOS
- Python Version: 3.11.4
- Continue Version: v0.0.294

**Recording**

https://drive.google.com/file/d/1tUC6c0zT5j0qOuEHvgmak1YMdM-bJRvi/view?usp=sharing

**Comment by bra1nDump** [comment]
Might be related.

When making multiple selections and switching files the selected file labels change unexpectedly to the same name (of the currently visible file). The raw context submitted to the llm is still good and is coming from different files.

<img width="560" alt="image" src="https://github.com/continuedev/continue/assets/12608159/8433cd2f-1288-4e76-9c75-13aaadb57102">

<img width="556" alt="image" src="https://github.com/continuedev/continue/assets/12608159/e3ebbfd4-2888-4d35-a907-b2c0fb73de19">

**Comment by sestinj** [comment]
Found the bug here, this is now resolved. Was comparing indices to ids where I used to track by indices and missed a spot when switching over.
