### ISSUE TITLE
Azure OpenAI model names are not recognized

### ISSUE THREAD

**Issue by vladiliescu** [continuedev/continue#374]
**Describe the bug**
When configuring an Azure OpenAI deployment, Continue uses the model name to check max tokens. However, it uses the OpenAI model names which differ from those used by Azure OpenAI (`gpt-4`, `gpt-35-turbo`, etc). As you can expect, hilarity and `KeyError` ensue. The only way to get past this is to check Continue's source code and see what model names it would expect.

**To Reproduce**
Configure Continue as per the docs, and use an Azure OpenAI model name such as `
gpt-35-turbo-16k`.

**Expected behavior**
The extension doesn't crash complaining about KeyError.

**Comment by sestinj** [comment]
@vladiliescu Changes have been made, and a new version will be on the store in ~10 minutes. Thanks for reporting this!
