### ISSUE TITLE
Staying there all the time "Continue Server Starting"

### ISSUE THREAD

**Issue by xingguang2013** [continuedev/continue#377]
**Describe the bug**
When I open vscode, find continue, and then stop at Continue Server Starting

**To Reproduce**
1. Go to 'vscode'
2. Click on 'continue'
3. See Continue Server Starting

**Expected behavior**
Can be used normally

**Screenshots**
![a](https://github.com/continuedev/continue/assets/3281216/a5dba837-3893-4639-b80e-614a130b799d)

**Environment**
- Operating System: [Windows 11  22H2]
- Python Version: [3.11.4]
- Continue Version: [v0.0.306]

**Console logs**
![图片](https://github.com/continuedev/continue/assets/3281216/11a08747-9778-4532-afbe-43283000646e)

**Comment by xingguang2013** [comment]
I also tried using [Troubleshooting](https://continue.dev/docs/troubleshooting) to solve it, but it was unsuccessful

**Comment by sestinj** [comment]
@xingguang2013 Thank you for sharing, looking into this right now, and will keep you updated. Is there any information in `~/.continue/continue.log` if you enter "Continue: View Continue Logs" in the command palette (cmd+shift+p)?

**Comment by xingguang2013** [comment]
@sestinj Only a few lines of log information
![图片](https://github.com/continuedev/continue/assets/3281216/1be3bace-05f5-4b4a-b5cc-6edc5c35384f)

**Comment by sestinj** [comment]
Ok, thank you. Definitely something wrong here, I'll make sure that whatever fix I make also includes solving this lack of logs

**Comment by xingguang2013** [comment]
Thank you very much. It was work the day before yesterday, but it should have been updated and cannot be work anymore. Continue is very useful, and I will recommend it to my friends. Thank you again to the author

**Comment by xingguang2013** [comment]
After updating to v0.0.307, everything is normal and ready for use

**Comment by sestinj** [comment]
Awesome! I was about to tell you and you beat me to it : )
