### ISSUE TITLE
Pressing stop button causes output to seem to disappear

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#378]
**Describe the bug**

Pressing the stop button causes the output to disappear for at least 3-5 seconds--long enough to sometimes think it is gone forever

**To Reproduce**

1. Enter some instructions
2. Click the Continue button
3. Click the stop button (while output is still being generated)
4. Observe that output completely disappears for 3-5 seconds

**Expected behavior**

Existing output should always remain visible

**Comment by sestinj** [comment]
Solved with a single extra `await sdk.update_ui()`, will be in next version
