### ISSUE TITLE
It seems that the code block I selected will not be used as an input parameter by continue

### ISSUE THREAD

**Issue by xigua88-66** [continuedev/continue#383]
As the title says

![image](https://github.com/continuedev/continue/assets/54090607/420defb3-f923-435e-9767-83814b508c1c)

**Comment by sestinj** [comment]
@xigua88-66 It's possible there are two separate problems here.

1) Could you first take a look at (and maybe share) your `~/.continue/config.py` file? The error on the left appears to show that it either doesn't exist or has an error. This could be our fault.
2) If you do CMD+SHIFT+P, then type "Continue: View Continue Logs", it will open `~/.continue/continue.log`. At the bottom of this file are there any errors that you could share?

**Comment by xigua88-66** [comment]
@sestinj 
Thanks for your reply and guidance.
My configuration file is not specially set. After opening the continue session in vscode, the displayed config.py seems to be consistent with the default_config in github.

The output in the log is mainly like this
![image](https://github.com/continuedev/continue/assets/54090607/b6cd6f79-4e32-4844-9952-5c46ec2e2edc)

**Comment by sestinj** [comment]
Interesting. Nothing looks wrong there, except possibly Meilisearch. Are you on Mac? One thing to try might be killing the Meilisearch process at 7700 with `lsof -i :65432` and then `kill <PID>`.

**Comment by xigua88-66** [comment]
@sestinj 
According to the way you said, continue to upgrade from version 0.311 to version 0.312 after reloading, and now it is working normally. 
Thank you for your help

**Comment by sestinj** [comment]
I'm glad to hear that! I'll close this issue, but please let me know if anything like this happens again
