### ISSUE TITLE
gui connection with server (or extension?) sporadically breaks

### ISSUE THREAD

**Issue by bra1nDump** [continuedev/continue#390]
Unfortunately the error is just empty {} on repeat errors and seems empty on first error as well
<img width="913" alt="image" src="https://github.com/continuedev/continue/assets/12608159/87f93dcf-29e9-4391-938d-4a084c1022d1">

I can't quite pinpoint the repro. Since this is sporadic I suggest
- At all times have a button to reload continue to try to recover from this or similar problems. Current workaround is to reload window, but not all are aware of the command
- Adding better error logging as step 1
- Long term creating a state machine for socket reconnection or using some library that does that for us

**Comment by sestinj** [comment]
We recently migrated to using socket.io instead of websockets, and made the connection non-stateful. I haven't seen this problem since, so am going to close the issue.

Thanks for the report! Hope all is well : )
