### ISSUE TITLE
`ctrl+d` shortcut being blocked by continue

### ISSUE THREAD

**Issue by aykutkardas** [continuedev/continue#393]
**Describe the bug**
Whenever I want to use vscode's ctrl+d shortcut, continue debug opens. This is not something I want.

**Expected behavior**
ctrl+d is one of the most commonly used vscode shortcuts. You cannot own this as an extension. With this extension installed, I cannot use the editor as I am used to.

**Screenshots**
![image](https://github.com/continuedev/continue/assets/7966133/0ff9b1b7-8a66-456f-90d7-c09c5352440b)

![image](https://github.com/continuedev/continue/assets/7966133/586e6b4d-c61e-498f-ab64-743454cb2b54)

**Comment by sestinj** [comment]
@aykutkardas You're right, this has to change—I just pushed a new version, will be ready in ~15min. I changed the shortcut to ctrl+shift+r. This in my understanding is a much more acceptable keybinding?

**Comment by aykutkardas** [comment]
Yes, great choice ⚡

**Comment by sestinj** [comment]
Awesome, thx for the feedback on this! Shortcuts that are both available and ergonomic are few and far between. Closing this issue, but if problems with other shortcuts arise, you're welcome to open another
