### ISSUE TITLE
can't save server message from vs code continue settings page

### ISSUE THREAD

**Issue by mchampanis** [continuedev/continue#405]
**Describe the bug**
Looks like there's a hardcoded config directory somewhere that is preventing `system message` from being edited directly from VS Code.

**To Reproduce**
1. Open VS Code
2. Open Continue pane
3. Click the gear icon (`settings`)
4. Change `server message`
5. Click `Save`

**Expected behavior**
Expect config to save without error.

**Screenshots**
<img width="597" alt="image" src="https://github.com/continuedev/continue/assets/45290/538387b4-7f5c-4179-bf8c-2966d7462887">

**Environment**
- Operating System: MacOS
- Python Version: 3.11.2
- Continue Version: 0.0.328

**Comment by sestinj** [comment]
Yes! This should be a quick fix, can't believe I left it in there. New version will be out in ~15 minutes

**Comment by sestinj** [comment]
@mchampanis New version just released with the fix (v0.0.329)

**Comment by mchampanis** [comment]
amazing, thanks @sestinj
