### ISSUE TITLE
Run Continue in a devcontainer

### ISSUE THREAD

**Issue by thomasaarholt** [continuedev/continue#406]
**Is your feature request related to a problem? Please describe.**
We develop our projects inside running docker containers in order to have reproducible environments. Currently, Continue doesn't work inside containers in VSCode, only in regular environments.

To setup a reproducible environment:
In VSCode:
Install the Dev Containers extension.
- Cmd/Ctrl + Shift + P: New Dev Container
- Type Python and press Enter
- Create Dev Container
- Wait ~1 min, then install the Continue Extension

Currently, the extension is just spinning with a "Continue Server Starting". "View logs" just opens an empty window at `home/vscode/.continue/continue.log`
![image](https://github.com/continuedev/continue/assets/2721423/5e1d1464-86ac-4fa5-b4a2-d3dc5ff6ecfc)

It would be nice to be able to use local models and settings (not in the container) so that one doesn't need to install things twice.

**Additional context**
This was with the latest VSCode and Continue extension on Mac.

**Comment by sestinj** [comment]
@thomasaarholt Looking into this. Could you share anything from the developer tools console? It should appear when you click "View Logs", and then click console at the top.

And to be sure, have you installed the Continue extension on your local machine, or in the devcontainer?

**Comment by Mekcyed** [comment]
Hi, just a quick info from an User using Continue on Windows/ WSL with a Python Dev Container. I had no problems so far when installing continue in the container. And till now i didn't see an option to use Continue without installing it in the Dev Container. VSCode insists to install it, due to the fact that it is a different workspace i guess.. But i would welcome OPs wish to not install thinks twice.

**Comment by thomasaarholt** [comment]
This bit is probably the relevant error. I've also pasted it into [a gist here](https://gist.github.com/thomasaarholt/18b0e3cd962accbbbc63f4e6fb642660). 
<img width="657" alt="image" src="https://github.com/continuedev/continue/assets/2721423/876cdb26-e07d-4089-acb3-39898782b97e">
Any chance this could be because I'm running on arm architecture? This would be aarch64 architecture for linux (alpine), since that's what is running in the container.

It looks like there probably is a way to tell VSCode that the extension doesn't need to be installed _within_ the container, due to the existance message highlighted in the red box:
<img width="1717" alt="image" src="https://github.com/continuedev/continue/assets/2721423/e25c206a-c87f-4448-ab69-c1f576f4103e">
That message appears when you connect to the container, but before you've installed the Continue extension inside it.

**Comment by sestinj** [comment]
Thanks for the extra info. I've actually gotten the same error to occur on my own machine. Architecture seems likely to be part of the problem.

The ETXTBSY error is actually okay, because we catch this and retry, just happen to print it out (perhaps that is misleading and should be changed).

Defining to run locally does seem like a possible fix, looking at this first

**Comment by a3957273** [comment]
I can reproduce this error when using `VS: Code Remote`.  My base architecture is ARM, whereas my remote server is `X86`.  Do you think it's related?

**Comment by sestinj** [comment]
Seems very likely. I've found a quick fix though and am pushing it out now. Allowing the extension to run locally instead of forcing it into the extension host solved the problem on my computer (which is ARM).

Will ping y'all again in ~15 minutes once the newest version is published

**Comment by sestinj** [comment]
@a3957273 @thomasaarholt @Mekcyed this is now released in v0.0.330! Hoping this solves everything here, but not counting out the possibility of additional problem, so let me know : )

**Comment by a3957273** [comment]
It's already looking much healthier, getting far further into the installation process.  The time it took you to fix / release this is really rather exceptional!

I'm not certain that installing on the host is always the best idea however.  We have 'thin' laptops we use for development with VS: Code installed.  We then use VS: Code Remote to SSH into a persistent server.  It's far better for us for continue to be installed in that dev machine, instead of our thin laptop.

**Comment by sestinj** [comment]
Does "far further" mean there's still an issue setting up?

**Comment by a3957273** [comment]
Not an issue setting up, there is still an issue with context.  Now that the extension runs on the 'host', it's not able to provide context from existing files.  For instance, if I select 'example.ts', continue errors out and says '/path/to/file/example.ts' does not exist.  It _does_ exist inside the remote SSH instance, but it doesn't on the host?

**Comment by Mekcyed** [comment]
For me it seems to run much more smoothly. Tested it on a Dev Container and i now can even use it on my RaspberryPi 3 via SSH :D Thanks for your work!

But...I now experience another strange thing that i saw last week for the first time but worked this week till now. The "@" Operator is not working and shows simply nothing when i type it in the chat. But i don't want to hijack this issue 🫣

**Comment by a3957273** [comment]
> Not an issue setting up, there is still an issue with context. Now that the extension runs on the 'host', it's not able to provide context from existing files. For instance, if I select 'example.ts', continue errors out and says '/path/to/file/example.ts' does not exist. It _does_ exist inside the remote SSH instance, but it doesn't on the host?

This does not affect `context`, but it does seem to affect commands like `/edit`.

**Comment by sestinj** [comment]
@Mekcyed I'll make a new issue for this [here](https://github.com/continuedev/continue/issues/408). Added some thoughts there on what is causing the bug

**Comment by sestinj** [comment]
@a3957273 I see the problem...I'm sure there's a way to read files from the remote. Will look into this. Inability to read files is higher-damage than the reasons so far for running on local (connecting to local GGML servers, correctly setting up given architecture, etc...), but ideally there's a solution that allows both. I'll update here soon

**Comment by sestinj** [comment]
@a3957273 I've just released another new version that solves these issues. You might notice that only top-level files are referenceable using '@', which is one last thing I need to fix, but otherwise the SSH problems should be addressed.

**Comment by thomasaarholt** [comment]
Fantastic work! What a quick turnaround too! It now works really nicely in my container!

🚀 Thanks for this!

**Comment by sestinj** [comment]
Super glad to hear!

**Comment by drmikecrowe** [comment]
@thomasaarholt  -- can you share your devcontainer configuration?

**Comment by thomasaarholt** [comment]
@drmikecrowe in my first post in this thread I show how I create a simple python devcontainer - could you use that? I do not install anything else inside this container.

**Comment by thomasaarholt** [comment]
@drmikecrowe I opened the container and extracted the `.devcontainer.json`. [Here it is](https://gist.github.com/thomasaarholt/c73266a46d0b83833d80c29d1052054c).
