### ISSUE TITLE
[CON-209] @ doesn't work on windows

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#408]
**Describe the bug**
Nothing shows up when typing '@'

**To Reproduce**
run Continue in a dev container, try to type '@'

**Expected behavior**
Should show the dropdown

**Environment**
Windows/ WSL with a Python Dev Container

<sub>[CON-209](https://linear.app/continue/issue/CON-209/doesnt-work-in-dev-container)</sub>

**Comment by sestinj** [comment]
The reason this happened once we transitioned from remote host to local is that we don't attempt to set up Meilisearch on windows yet (the download process is a bit more complicated in [their docs](https://www.meilisearch.com/docs/learn/getting_started/installation)). So I would actually expect this behavior. The goal of this issue then is to download Meilisearch when on windows

**Comment by Mekcyed** [comment]
Thanks for the quick support ❤️

Adding this for more context: Continue installed on Windows Machine. Working via SSH on Raspberrypi 3 resulting in this error in the console:

![image](https://github.com/continuedev/continue/assets/90114325/42858029-9c49-4db7-900b-e273c3784f83)

And in Dev Container resulting in this errors:

![image](https://github.com/continuedev/continue/assets/90114325/97561cbe-e092-4400-a8ca-4df743d805c5)


Let me know if you need more info or help with testing.

**Comment by sestinj** [comment]
Forgot about this issue, but it is now complete since we've published support for Meilisearch on Windows. Feel free to reopen if needed!!!

**Comment by Mekcyed** [comment]
Hey @sestinj. Reopening this issue becaus of this error in the same env when trying to use "@":
![grafik](https://github.com/continuedev/continue/assets/90114325/3efb0679-8414-4773-a0b9-70f471cd8932)

**Comment by sestinj** [comment]
The console logs shouldn't be a problem, just a slight mess.

Does this happen only when you use @search, whenever you type any context provider, or whenever you open continue?

Temporary solution if either of the latter 2: remove SearchContextProvider() from your config.py

**Comment by sestinj** [comment]
It looks like I made a bad assumption about the location where VSCode installs ripgrep on windows :\ I'll find the right path tmr and get this squared away

**Comment by Mekcyed** [comment]
The `listDirectoryContents` error from the console occures everytime i start a new continue session. 

The `@diff` function throws this error:

![grafik](https://github.com/continuedev/continue/assets/90114325/ecb1dafd-31c9-4d85-9083-7fef61e1c39f)

**Comment by sestinj** [comment]
thanks for the extra info - probably all windows filepath related problems. I'll see if I can get to them all at once today

**Comment by amihalik** [comment]
@sestinj Can I set the IP address for the meilisearch service?  I'm setting up a single continuedev container that runs both (i.e. `python -m continuedev` and meilisearch).  You have a vs code setting to configure the continuedev server url, but I'm not sure how to point to the meilisearch service.

**Comment by sestinj** [comment]
@amihalik I'm actually working on this as we speak. Hoping to release something in the next hour or two that will allow this

**Comment by sestinj** [comment]
This is now available through the pypi package with the --meilisearch-url flag. For example, if you set up meilisearch yourself on port 8000, you would run Continue with `python -m continuedev --meilisearch-url http://localhost:8000`, and then it would not attempt to setup meilisearch on its own. Can also set the flag to the usual 7700, and Continue will understand that you are running it on your own

Meilisearch has this flag if you want to change the port
```
--http-addr <HTTP_ADDR>
          Sets the HTTP address and port Meilisearch will use
          
          [env: MEILI_HTTP_ADDR=]
          [default: localhost:7700]
```

<img width="717" alt="Screen Shot 2023-09-28 at 1 32 53 AM" src="https://github.com/continuedev/continue/assets/33237525/e7d46671-9709-4791-ae1a-052e504728c9">

**Comment by amihalik** [comment]
Thanks Nate!  I can verify this works on my end.

**Comment by sestinj** [comment]
Meilisearch is responsible for powering the dropdown search experience for certain context providers, like "File". If you type '@' in the input box, select the "File" option, then if meilisearch is setup correctly you should see a list of files in your workspace like this:


<img width="429" alt="Screen Shot 2023-09-28 at 12 44 22 PM" src="https://github.com/continuedev/continue/assets/33237525/cd6862ec-a314-4271-8512-c11dc1b24b2f">

**Comment by amihalik** [comment]
Thanks for the info.  It seems like the plug-in is getting the correct meilisearch endpoint info from the server (and my meilisearch instance has data in it), but the plug-in is making a bad query to meilisearch.

From the VS Code Developer tool:
Console:
```
Error searching context items MeiliSearchApiError: Expected only comma-separated field names inside `IN[..]` but instead found ` \"c:\\Users\\--------\\projects\\continue-example\" ] AND provider_name = \'file\'`.
19:94 workspace_dir IN [ "c:\Users\----------\projects\continue-example" ] AND provider_name = 'file'
    at meilisearch.esm.js:178:23
    at l (meilisearch.esm.js:95:23)
    at Object.next (meilisearch.esm.js:76:53)
    at s (meilisearch.esm.js:66:58)
```

Request:
```
URL: http://-------------:7700/indexes/continue_context_items/search

Payload: {"q":"","filter":"workspace_dir IN [ \"c:\\Users\\-------------\\projects\\continue-example\" ] AND provider_name = 'file'"}
```

I modified the query and submitted via postman.  I got back valid results (i.e. `hits`).  Here's my query from postman exported as a curl command:

```
curl --location 'http://------:7700/indexes/continue_context_items/search' \
--header 'Content-Type: application/json' \
--data '{
    "q": "",
    "filter": "workspace_dir = \"c:\\\\Users\\\\----------\\\\projects\\\\continue-example\"  AND provider_name = \"file\""
}'
```

**Comment by sestinj** [comment]
@amihalik Thanks for taking the effort here - I notice that you changed both "IN -> =" and added extra escapes. My guess is that the escaping is the real problem and would explain why this is only seen on Windows. If that's true, then this curl request should work:

```
curl --location 'http://------:7700/indexes/continue_context_items/search' \
--header 'Content-Type: application/json' \
--data '{
    "q": "",
    "filter": "workspace_dir IN [ \"c:\\\\Users\\\\----------\\\\projects\\\\continue-example\" ]  AND provider_name = \"file\""
}'
```

If so I'll add the extra escapes in the next update

**Comment by sestinj** [comment]
@amihalik We've now found a more lightweight alternative to meilisearch that runs entirely in the browser, which means that these problems in their exact form are no longer possible. Going to close this issue, but please feel free to open another if anything else comes up !
