### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by corv89** [continuedev/continue#410]
**Describe the bug**
I've setup ggml in `config.py` like so,
```python
        default=GGML(
            max_context_length=2048,
            server_url="http://192.168.1.19:8000"
        )
```

**To Reproduce**
1. Write a prompt and click on continue
1. See error

**Expected behavior**
Expected a response (API is confirmed to be working)

**Environment**
- GGUF model file
- Operating System: Linux and MacOS
- Python Version: recent
- Continue Version: latest

**Console logs**
```
Traceback (most recent call last):

  File "continuedev/src/continuedev/core/autopilot.py", line 367, in _run_singular_step
    observation = await step(self.continue_sdk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/core/main.py", line 359, in __call__
    return await self.run(sdk)
           ^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/plugins/steps/chat.py", line 85, in run
    async for chunk in generator:

  File "continuedev/src/continuedev/libs/llm/ggml.py", line 112, in stream_chat
    async for chunk in generator():

  File "continuedev/src/continuedev/libs/llm/ggml.py", line 103, in generator
    yield json.loads(chunk[6:])["choices"][0][
          ^^^^^^^^^^^^^^^^^^^^^

  File "json/__init__.py", line 346, in loads

  File "json/decoder.py", line 337, in decode

  File "json/decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sestinj** [comment]
Are you connecting to a llama-cpp-python server that you are running? If you could share some details about how this is set up, I'll try to reproduce.

**Comment by redtier100x** [comment]
I am also having this problem. I have llama.cpp running in docker locally. I'm using VSCodium and I downloaded the latest VSIX file and installed that way. It worked with the version that is in the VSCodium marketplace but only for the first session and woudl stop working after that. I downloaded the latest version to try and fix it but ran into this:

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Every time I make a query or an edit with Continue.

**Comment by corv89** [comment]
> Are you connecting to a llama-cpp-python server that you are running? If you could share some details about how this is set up, I'll try to reproduce.

Yes, in `llama.cpp` I'm running `./server -m ../phind-codellama-34b-v1.Q4_K_S.gguf -c 2048 --port 8000 --host 0.0.0.0 -ngl 40`

I've tested this on the web app and with curl, `/completions` works.

My `config.py` looks like this:

```python
config = ContinueConfig(
    models=Models(
        default=GGML(
            max_context_length=2048,
            server_url="http://192.168.1.19:8000"
        )
    ),
```

Could it be that llama.cpp made some changes recently?

**Comment by corv89** [comment]
Okay I see this is my mistake, I'm using the server inside llama.cpp when you meant a third-party project called `llama-cpp-python`!

**Comment by sestinj** [comment]
@corv89 yes, that was the intention. I'm working right now though on support for the direct llama.cpp server like you were running. This has several benefits, including tighter control of parameters like `grammar`

@redtier100x I will share again here once I push the update tomorrow, assuming you'd still prefer to use llama.cpp directly

**Comment by corv89** [comment]
I would much prefer to run `llama.cpp` since that works well out of the box (even for AMD) whereas I have trouble compiling `llama_cpp_server`.

Thanks looking forward to it!

**Comment by fuyunzhishang** [comment]
I also have the problem, when i run llma on toghther ai , 
![image](https://github.com/continuedev/continue/assets/19215394/6a15e981-8fd0-4d60-b9a6-e2e2adc1b757)

**Comment by corv89** [comment]
That looks like a different problem. Maybe create a new issue to track the bug?

**Comment by corv89** [comment]
@sestinj I found a way to solve this

`llama.cpp` includes a proxy for OpenAI compatible completions:
`python ./examples/server/api_like_OAI.py`

Using this in conjunction with `./server -m model-name.gguf` works!

Simply point Continue at the python API and the python API at the llama C++ server

**Comment by sestinj** [comment]
@fuyunzhishang I just solved this problem, it should work now! Thanks for reporting. Let me know if it doesn't

**Comment by sestinj** [comment]
@corv89 nice find! LlamaCpp class is also ready if you'd like to use that instead. I haven't documented it yet, but you should now see the option in the model drop-down and it will connect to llama.cpp's ./server

**Comment by changeling** [comment]
@sestinj When will this be available through the VS Code Extension update flow?

**Comment by corv89** [comment]
@changeling It's already there, just reload.

@sestinj Can't quite figure out how to configure this backend, perhaps I'll have to wait for the docs to set it up directly.

Thanks for bringing this feature out so quickly

**Comment by sestinj** [comment]
It's also notable that the llama.cpp server seems to give lower quality outputs than just running ./main in llama.cpp. Haven't yet pinned down the difference, but there are tons of alternatives to get a server setup, https://github.com/oobabooga/text-generation-webui being one option, llama-cpp-python being another, Ollama if on Mac, LocalAI I've recently heard of, and maybe kobold. Lots of discussion going on in the discord about this if you're interested

**Comment by changeling** [comment]
It just updated! One thought... Given that llama.cpp has now moved to GGUF and, I believe, has dropped GGML, you might consider having that as a class going forward.

**Comment by sestinj** [comment]
Definitely—I think the naming of the classes is a bit problematic in general right now. The GGML class probably actually doesn't need to exist since it's just connecting to any OpenAI-shaped API endpoint. Will probably remove entirely at some point

**Comment by corv89** [comment]
Just for reference, I also had to rewrite the import to
`from continuedev.src.continuedev.libs.llm.llamacpp import LlamaCpp`

I noticed you're defaulting max_context_length to 2048. From my understanding Code Llamas can go to 100k and Llama.cpp handles this automatically based on the settings inside the GGUF file. So now I'm wondering how one would handle that?

**Comment by changeling** [comment]
After updating to v0.0.350 from v0.0.344, llamacpp has stopped working again. I'm getting:

```
Traceback (most recent call last):

  File "continuedev/src/continuedev/libs/util/create_async_task.py", line 21, in callback
    future.result()

  File "asyncio/futures.py", line 203, in result

  File "asyncio/tasks.py", line 267, in __step

  File "continuedev/src/continuedev/server/gui.py", line 266, in async_stuff
    models.default = MODEL_CLASSES[model_class](**model)
                     ~~~~~~~~~~~~~^^^^^^^^^^^^^

KeyError: 'LlamaCpp'
```

In addition, adding a customization to `config.py` seems to be overwritten when I choose llamacpp.

**Comment by sestinj** [comment]
@corv89 What was the import before you rewrote it?

One option is to set the context length to the max integer if you really want that, but it's useful to input a max_content_length because Continue will use it to determine how much context to keep and what to throw out. Even if Code Llama can handle a whole 50 message conversation, the previous messages might not be useful and will just confuse it / increase time to first token. So I would recommend just using 100k as the max_content_length, or moving it to be smaller if you notice really big issues

**Comment by corv89** [comment]
@sestinj Thanks for all your help

I had the import set to `from continuedev.src.continuedev.libs.llm.ggml import GGML`

For some reason the output I'm getting is purely hallucinations, nothing that matches the highlighted code. I'm assuming the prompt must be set up the wrong way.

For the record, I'm using [CodeLlama-34B-Instruct-GGUF](https://huggingface.co/TheBloke/CodeLlama-34B-Instruct-GGUF)

Shouldn't the stop word be `llama_cpp_args={"stop": ["[/INST]"]},`? (with a slash)

How do I inspect the prompt? Do I set things up in llama.cpp or in Continue? Or both?

**Comment by sestinj** [comment]
@corv89 You can see the prompt being sent if you hover the response message and click on the magnifying glass icon.

I would actually stick with the GGML class for this I think, because you already have a server using the OpenAI format. LlamaCpp class will have to deal with raw prompts: fine if that's what you want, but I also think there might be something wrong in llama.cpp's ./server because I tried it for a while yesterday and didn't have any luck: lots of hallucinations like you said.

If you're using the OpenAI-compatible server for llama.cpp, there isn't a lot of room for Continue to mess up the prompts, unless the highlighted code just isn't being included; because we just pass the array of json messages: `[{"role": "user", "content": "..."}, ...]`.

I used [INST] without a slash because this indicates the start of a user block, which should mean that the assistant is done generating.

**Comment by sestinj** [comment]
@corv89 no worries, sorry I was slow here. Which model are you using? I played around a ton with codellama today, and this response seems characteristic of it. If that's the one you're using, then I'd highly recommend using the "instruct" version instead

**Comment by corv89** [comment]
Hi,

I'm actually using [CodeLlama-34B-Instruct-GGUF](https://huggingface.co/TheBloke/CodeLlama-34B-Instruct-GGUF) now, having thought that this would be the most appropriate for this use case.

From what I recall, Phind did better (in terms of sticking to the prompt)

**Comment by corv89** [comment]
It's still taking to itself, even without a code block, now it asked itself to write tic-tac-toe lol

So both the "USER:" and "ASSISTANT:" is being filled out by the LLM and after a long while of back and forth it fills out the title

**Comment by sestinj** [comment]
lol tic-tac-toe is hilarious

@corv89 If you are using codellama-instruct, I would actually expect these nonsense responses, because it's being fed the "User: Assistant: " prompt template, which it is not trained for.

You are correct that this is a great choice of model, if not the best, but it's a limitation of the llama.cpp OpenAI server, as in the code snippet link I sent above. Assuming you still want to use this model, I think the options would be:
a) Manually alter [this code](https://github.com/ggerganov/llama.cpp/blob/92d0b751a77a089e650983e9f1564ef4d31b32b9/examples/server/api_like_OAI.py#L34C1-L53C18) to give the right prompt template format
b) Use llama.cpp ./server directly with the LlamaCpp class, which would by default use the correct prompt template
c) Use [TextGenUI](https://github.com/oobabooga/text-generation-webui/tree/main) as another way to run the model locally. I've heard users having success with this, and it provides more flexibility. It has its own [OpenAI-compatible server extension](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai), so you could still use the GGML class.

**Comment by corv89** [comment]
I've tried b) using llama.cpp ./server directly, which works with CodeLlama-Instruct so long as I don't highlight any code

Thanks for all your assistance, I can live with this for now.

Unfortunately my Mac doesn't have enough RAM otherwise I'd be using Ollama directly

**Comment by corv89** [comment]
I highlight line 44-46 in the Continue `config.py`:
Prompt is "What does this code do?"

Clearly, the comment is never made part of the prompt!

Transcript is:
```
This is a log of the prompt/completion pairs sent/received from the LLM during this step

############################################

Prompt: 

[INST] What does this code do?
[/INST]

############################################

Prompt: 

Give a short title to describe the current chat session. Do not put quotes around the title. The first message was: "What does this code do?". Do not use more than 10 words. The title is: 

############################################

Completion: 

  This code is a Python script that defines a function called `greet()` and then calls the function. The `greet()` function takes no arguments and prints a message to the console using the `print()` function.

Here's a breakdown of what the code does:

1. The first line, `def greet():`, defines a new function called `greet()`.
2. The next line, `print("Hello, world!")`, prints the message "Hello, world!" to the console using the `print()` function.
3. Finally, the last line, `greet()`, calls the `greet()` function that was defined earlier.

So when you run this code, it will print the message "Hello, world!" to the console.

############################################

Prompt: 

"  This code is a Python script that defines a function called `greet()` and then calls the function. The `greet()` function takes no arguments and prints a message to the console using the `print()` function.

Here's a breakdown of what the code does:

1. The first line, `def greet():`, defines a new function called `greet()`.
2. The next line, `print("Hello, world!")`, prints the message "Hello, world!" to the console using the `print()` function.
3. Finally, the last line, `greet()`, calls the `greet()` function that was defined earlier.

So when you run this code, it will print the message "Hello, world!" to the console."

Please write a short title summarizing the message quoted above. Use no more than 10 words:

############################################

Completion: 

 What does this code do?
\end{blockquote}

\begin{itemize}


############################################

Completion: 



"Python greet() prints Hello World"
```

My config is:

```python
config = ContinueConfig(
    models = Models(
        default=LlamaCpp(
            prompt_templates={},
            max_context_length=2048,
            server_url="http://192.168.1.15:8000",
            llama_cpp_args={'stop': ['[INST]']}
        )
    ),
```

**Comment by sestinj** [comment]
@corv89 Turns out I accidentally chose the wrong chat templating function as the default. You can actually change it like this:

```python
from continuedev.src.continuedev.libs.llm.prompts.chat import llama2_template_messages

LlamaCpp(..., template_messages=llama2_template_messages)
```

And I'll update the default in the next version I release today
