### ISSUE TITLE
CodeLlama URL Encoded responses in /edit

### ISSUE THREAD

**Issue by meganoob1337** [continuedev/continue#413]
**Describe the bug**
I am Using Continue in VsCode with the Ollama backend running codellama
When i want to /edit some file , the response seems to always be urlencoded 

**To Reproduce**
1. open a file:
```"use client"; // Error components must be Client Components

import { useEffect } from "react";

export default function Error({
  error,
  reset,
}: {
  error: Error;
  reset: () => void;
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error);
  }, [error]);

  return (
    <div>
      <h2 style={{background: 'white'}}>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  );
}```

2. run the command `/edit make the button red`
3.  The code in the diff window is urlencoded and looks weird
**Expected behavior**
It should provide a proper diff without urlecoding
**Screenshots**
<img width="1444" alt="263543209-d23fafbb-de5d-4556-a8e4-5423b33a0641" src="https://github.com/continuedev/continue/assets/5018646/3852eabf-0f60-4be2-8c7f-84c8e6ee1786">
for some reason i cannot upload an image or link to the image... you might need to copy and paste the link...
[Image](https://github.com/continuedev/continue/assets/5018646/d23fafbb-de5d-4556-a8e4-5423b33a0641)
**Environment**
- Operating System:  MacOS
- Python Version: Python 3.10.10
- Continue Version: v0.0.338

**Comment by sestinj** [comment]
Seeing the same thing. I think the responses were literally URL Encoded. Made the fix, not seeing it anymore on my end. New version (v0.0.339) should be out within 15 minutes.

I also noticed that the edit functionality was pretty slow for Ollama because we were using a longer prompt, so I changed to a simpler prompt that should also improve its results. Though it still tends to want to give English in its responses—there's prompting work to be done specifically for the CodeLlama model. Will try to fix this later today, and also considering adding the ability to pass a "prompt constructor callback" for those that want to experiment

**Comment by sestinj** [comment]
@meganoob1337 new version is ready! Let me know if you're still seeing the problem. I'll treat the English outputs problem as separate, so feel free to make a new issue there if you'd like.

**Comment by meganoob1337** [comment]
@sestinj thank you for the swift reaction, ill try it and give feedback!

With the english responses i don't really know what you mean, it was not an issue for me :D

**Comment by sestinj** [comment]
Well I'm glad to hear it wasn't an issue!

I've just found that sometimes it likes to prefix its responses with, "Ok, here's the code you asked for: " or something, which shouldn't be in the edit output

**Comment by meganoob1337** [comment]
@sestinj  looks better now for the Escaping issue! thank you!

is there a way to get rid of text inside the diff?

  <div>
       Here's the updated code:
            <button style={{ backgroundColor: &#39;red&#39; }}>Click me!</button>
      I added a new `style` attribute to the `button` element, which sets the `backgroundColor` property to `'red'`. This changes the button color to red.
    
    
    because it adds the text instead of just pasting the code there
    
    
    while i was writing this you answered, i guess thats the problem you mentioned then :D

**Comment by sestinj** [comment]
Yup, that's the one haha. You can edit the text on the right side of the diff once it's done generating, these changes will make it into the file once you click accept

**Comment by meganoob1337** [comment]
okay, i guess i can work with that, but is there any way to adjust the promt so it doesnt comment on it at all? maybe ill play around with it a bit, am quite new to this :D

**Comment by sestinj** [comment]
If you run the server yourself manually, you can change the prompt [here](https://github.com/continuedev/continue/blob/f0aa0918269addcb9e8649ae983afa9090e3b66d/continuedev/src/continuedev/plugins/steps/core/core.py#L642-L653).

Obviously this isn't ideal, so I'm going to try to make this easier. Then you can just pass your own callback or template string in the config file to construct the prompt.

Made a new issue [here](https://github.com/continuedev/continue/issues/414) to track that, closing this one. I'll likely get to it later today.
