### ISSUE TITLE
button color

### ISSUE THREAD

**Issue by tkitka** [continuedev/continue#416]
hello! Can you add abitlity to change "Continue" button color, it's too bright for dark themes.

**Comment by sestinj** [comment]
This is reasonable. I'll maybe add it as a VS Code setting. Going to think on this before doubling the number of settings we have just for a button color, but will do something by tomorrow.

**Comment by tkitka** [comment]
Thank for a reaction.  I think there is a lack of auto-scroll and buttons "home" "end" doesn't work in input field.

**Comment by sestinj** [comment]
Ok so I did a thing for now: If you type a hex code into the text input, then reload the window it will update the button color to that hex code (e.g. "#333", or "#335565"). I want to be careful about giving everyone instant access to override the most recognizable part of our extension and not too many people have requested it yet (if this changes, we'll reconsider), but I totally understand why you'd want this.

I'm also pushing a fix rn for the home+end buttons. Played around with scroll a little bit, don't have it quite yet (and doing it wrong would be really annoying), but aiming to push that out tomorrow

**Comment by sestinj** [comment]
@tkitka All of these changes are ready, now that I've just published autoscroll! I'll close this issue in about a day if this all seems good to you

**Comment by sestinj** [comment]
Going to close this issue, but feel free to reopen if needed
