### ISSUE TITLE
Recurring file includes?

### ISSUE THREAD

**Issue by scheung38** [continuedev/continue#418]
Sometimes I get all of this:

[Screenshot 2023-08-28 at 11.54.24.pdf](https://github.com/continuedev/continue/files/12453600/Screenshot.2023-08-28.at.11.54.24.pdf)

and then we need to delete hundreds of these

**Comment by sestinj** [comment]
When this happens do you have "select multiple files" turned on? (see below)

Without "select multiple files" turned on:
<img width="454" alt="Screen Shot 2023-08-28 at 10 37 37 AM" src="https://github.com/continuedev/continue/assets/33237525/7b3e20aa-f7ee-4ead-a149-dacb8e8ed46c">

With "select multiple files" turned on:
<img width="445" alt="Screen Shot 2023-08-28 at 10 38 10 AM" src="https://github.com/continuedev/continue/assets/33237525/dfc6f0a2-9fc7-4665-9f32-0148d3482dc6">

**Comment by sestinj** [comment]
@scheung38 This problem is now solved as a byproduct of the new interaction that requires using cmd+m to select context. Closing the issue, please feel free to open others as needed!
