### ISSUE TITLE
Copying lines of code from chat into Jupyter Notebook duplicates code from cell

### ISSUE THREAD

**Issue by Mekcyed** [continuedev/continue#419]
**Describe the bug**
Copying lines of code from chat into Jupyter Notebook duplicates code from current cell

**To Reproduce**
1. Open Jupyter Notebook
2. Write Code in a cell
3. Let Continue generate some code in in the Chat
4. Try to copy lines of code using CTRL+C from the Chat into the Jupyter Cell with CTRL + V

**Expected behavior**
The selected Code should be copied from the chat.

**Screenshots**
![grafik](https://github.com/continuedev/continue/assets/90114325/bb5bbd96-aaf0-40f8-8f0f-a07d15016e08)

**Environment**
- Operating System: Windws + WSL running a Python Dev Container
- Continue v0.0.344

**Console logs**
When pressing CTRL + V
![grafik](https://github.com/continuedev/continue/assets/90114325/2a384fda-a049-4ad5-b979-af34f22dd2e5)

**Additional context**
When Pasting in a simple text file the Copying works as expected.

**Comment by Mekcyed** [comment]
I tested it only with a simple text file. There it worked as intended :D

**Comment by sestinj** [comment]
I've not gotten a double paste, but instead was completely unable to even copy from Continue (or any other side bar for that matter) while an .ipynb file was open. It seems like this is a VS Code issue, as there seems to be a whole trail of issues starting [here](https://github.com/microsoft/vscode-jupyter/issues/848) related to copy/paste in python notebooks.

Is there anything in your keyboard shortcuts that might be relevant here? If you cmd+shift+p, "Keyboard Shortcuts", then search for "Notebook: " or maybe for "cmd+v", I'm wondering if there's a conflicting shortcut that only happens when notebooks are open.

**Comment by Mekcyed** [comment]
I guess it is more a "ctrl+c" problem. As long VSCode is in focus the last selected Cell in Jupyter is copied, even when text in e.g. Continue is selected. 

My Shortcuts: 
![image](https://github.com/continuedev/continue/assets/90114325/168352c2-b23a-4744-a402-fa7e4835ef6e)

So workaround for now would be to press the copy button in code sections in the chat -> paste to notebook cell -> delete unwanted stuff.

**Comment by sestinj** [comment]
Ok, what I can probably do is override ctrl+c within the webview's javascript to grab window.getSelection().toString() and throw that inside the copy buffer. I'll have to be sure there are no weird side-effects, but would expect it to work

**Comment by sestinj** [comment]
@Mekcyed Crazy enough this worked like a charm at least for me.

Just waiting 100ms and then filling in the copy buffer. New version is ready, 0.0.352.

I think I was having a slightly different issue than you though, so let me know if not fixed

**Comment by sestinj** [comment]
Mm I'm missing the keyboard event on windows 🤦🏻‍♂️ https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey

Was using just metaKey. Will change this in the morning and see if it solves things.

**Comment by sestinj** [comment]
Just made the change, new version (v0.0.352) will be out within the hour. Let me know how this goes.

**Comment by Mekcyed** [comment]
It works like a charm 💯 
Thank you for your time and work. Looking forward to see how continue develops further.

**Comment by Mekcyed** [comment]
Hey this issue is back in Version v0.0.412

**Comment by sestinj** [comment]
@Mekcyed I took a look to make sure and the solution that we implemented to fix this is still present, but I'm noticing that it might also have been necessary for you to disable all of the shortcuts like you did for it to work. Could you give a second look to the keyboard shortcut settings and see if anything new has shown up / try disabling them like you did before and let me know if this solves it?

**Comment by Mekcyed** [comment]
Hey,  sorry for my short comment. I was in a bit of a hurry...

Copying from continue to jupyter notebook is still working... My bad. But vis a vis not. I can copy from the notebook but cant paste into continue (i do it because the ctrl+m command for adding lines to the context is not working in a notebook either). Then i get also the code pasted in the notebook again like in my original description of the bug and nothing lands in the chat.

**Comment by sestinj** [comment]
ok no worries, this makes a bit more sense : ) Let me first see if I can get ctrl+m working in the notebook, since this would be the ideal solution

Can you paste into other places I would assume, just not Continue?

**Comment by Mekcyed** [comment]
Nice! 
Yes i can paste everywhere else. Copilot Chat for example also.

**Comment by sestinj** [comment]
Doing some testing (and made sure that the behavior is same on both mac and windows). What I'm seeing is that ctrl+M successfully adds the range as context to Continue, but I notice that highlighting a second range is often problematic, since the line numbers of each cell start at zero, causing apparent overlap. But it sounds like you were unable to ctrl+M even when nothing was already selected in Continue?

**Comment by WeskerC** [comment]
Same issue here, when editing .ipynb files I can highlight the codes but not able to copy the codes into the side window, it will only copy the exact code cell again and nothing happens in the side window

**Comment by sestinj** [comment]
I've just fixed this issue [here](https://github.com/continuedev/continue/commit/1b30b9e312b3f16d6504d3e03bf90df7d9b180a5) and it is available in version 0.9.124
