### ISSUE TITLE
Hope to bring the power of ChatGPT to Jetbrains

### ISSUE THREAD

**Issue by Houtx** [continuedev/continue#420]
Hope to bring the power of ChatGPT to Jetbrains.

**Comment by sestinj** [comment]
Me too! We were planning not to prioritize this for about another month, but recently there's been some work happening [here](https://github.com/bishwenduk029/continue) so maybe it won't be so long. I'll keep you updated!

**Comment by pedrosimao** [comment]
Good to know!

**Comment by pedrosimao** [comment]
Awesome stuff!!!

**Comment by sestinj** [comment]
@pedrosimao @Houtx @16francej @jmroblesh The JetBrains extension is making a lot of progress and we'll be releasing the official version very soon. I have an alpha version here that you can install from disk - would love to get early feedback! It should be mostly up to par with the VS Code extension, barring a few details:

https://discord.com/channels/1108621136150929458/1108621136830398496/1159049720799449119
