### ISSUE TITLE
Is there a way to avoid downloading the server again every time an update is made

### ISSUE THREAD

**Issue by Aincvy** [continuedev/continue#428]
**Is your feature request related to a problem? Please describe.**
Each time after updating, the server will download again. 

**Describe the solution you'd like**
I want the server to only download when it is necessary.

**Additional context**
The network in my region is not good, and every download may take a long time

**Comment by sestinj** [comment]
Yes! In VS Code settings you can search "Continue" and then check the box for "Manually running server".

This will stop Continue from trying to reinstall and stop the previous server.

**Comment by Aincvy** [comment]
Sure, I have tried it and it takes effect.
