### ISSUE TITLE
Continue  don't work or can't render in cloud based IDE

### ISSUE THREAD

**Issue by chewbh** [continuedev/continue#430]
**Describe the bug**
Tried installing the extension and using it in cloud based IDE such as Gitpod or Code Server from coder.com. Continue is not able to start up and the react components render error or not found with the following error message: "Error in Continue React App". 

**To Reproduce**
1. Go to GitPod to start a new remote development environment
2. Install continue extension
3. Click to pop up continue panel
4. Immediately the continue panel render an error message

**Expected behavior**
Continue should load and render the prompt input form with no error. Able to interact with Continue.

**Screenshots**

<img width="1318" alt="issue-screenshot" src="https://github.com/continuedev/continue/assets/5406619/ec80d3e8-01c1-4475-b926-9e3bc5253870">

**Environment**
- Operating System: [Ubuntu 22.04.3 LTS in the cloud IDE]
- Python Version: [3.11.4 on gitpod.io]
- Continue Version: [v0.0.352]

**Additional Context**
It will be useful to have this extension working on cloud IDEs.

**Comment by sestinj** [comment]
Interesting, I'm not yet sure what the difference is, but I've at least been able reproduce, so I'll keep digging in. No question this would be useful to support.

**Comment by chewbh** [comment]
After further probing, I believe the issue lies with VS Code WebView do not support typical URL based navigation. Similar issue is highlighted in https://stackoverflow.com/questions/59637276/how-to-implement-react-app-navigation-for-vscode-extension-with-webview.

Thus, using `BrowserRouter` to link and render the components might have unexpected result on certain VS code implementation.  

I am able to get the extension to work in codespace and gitpod once I switch it to use `MemoryRouter` instead in `extension/react-app/src/App.tsx`. 

```ts
// in <source>/extension/react-app/src/App.tsx
import { createMemoryRouter, RouterProvider } from "react-router-dom";
...

const router = createMemoryRouter([
  {
...
```

**Comment by sestinj** [comment]
@chewbh This is now ready in version 0.0.372! I've tested in GitPod, and it sets up successfully. I think it's likely there will be a few additional differences to iron out in the browser, so I'll leave this issue open, and please let me know if you come across any difficulties

**Comment by chewbh** [comment]
Thanks for the quick turnaround!

**Comment by gitwittidbit** [comment]
Not sure whether my issue is related:

Tried installing in web based Gitlab IDE. Gitlab IDE told me Continue doesn't even install because it can't run in browser. 

Is this just some meta data that needs updating or is Gitlab IDE fundamentally different? Can Continue be made to run in Gitlab IDE?

Thanks
