### ISSUE TITLE
Continue unnecessarily escaping characters

### ISSUE THREAD

**Issue by lucasyvas** [continuedev/continue#432]
**Describe the bug**
When printing Rust code output, Continue will escape characters like generic angle brackets to what looks like their HTML code equivalent.

**To Reproduce**
1. Generate code that has a character that might traditionally be escaped
2. Notice that the code output prints these codes instead of the expected character

**Expected behavior**
Prints the expected character

**Environment**
- MacOS
- Python Version: 3.9.6
- Continue Version: v0.0.352

**Console logs**
Sorry, had to kill the editor due to another issue so no console logs.

**Comment by sestinj** [comment]
I assume this is happening as it attempts to write code outside of code blocks? Ideally all code should be written with markdown formatting inside of single or triple backticks. I would consider that to be the root problem here; as mentioned in the other issue, I'm going to play with the prompt a bit and see if it doesn't fix this too

**Comment by lucasyvas** [comment]
> I assume this is happening as it attempts to write code outside of code blocks? Ideally all code should be written with markdown formatting inside of single or triple backticks. I would consider that to be the root problem here; as mentioned in the other issue, I'm going to play with the prompt a bit and see if it doesn't fix this too

To clarify, it actually does this within code blocks as well.

**Comment by sestinj** [comment]
Hi @lucasyvas, I think I solved this and just forgot to get back with you! I've added HTML character escaping, so you shouldn't see this either in a code block or outside anymore. Let me know if for some reason it's still showing up.

(and for your other issue, I'm currently working on a solution, so I'll give an update later today)

**Comment by sestinj** [comment]
Going to close this issue now, but please reopen if I was mistaken about solving the problem
