### ISSUE TITLE
System message breaks commands and config.py

### ISSUE THREAD

**Issue by remixer-dec** [continuedev/continue#433]
**Describe the bug**
Two bugs actually:
1) multi-line system message is inserted in `config.py` using `"` instead of `"""`
2) slash commands are ignored and treated as text inputs (probably wrapped with system message)

**To Reproduce**
1. Go to settings
2. Click on system message input
3. Change it to multi-line message
5. Save it
6. Look in config.py

Not sure how to reproduce the second bug, it happened once.

**Expected behavior**
Config is not broken.

**Screenshots**

**Environment**
- Operating System: Macos
- Python Version: not sure which one vscode uses, probably 3.8
- Continue Version: v0.0.352

**Comment by sestinj** [comment]
Good catch, this is an easy fix. The next version I release today will have this update

And I'll look for the command problem—do you remember which of the commands you were using?

**Comment by remixer-dec** [comment]
Thank you, I was using `/clear` and `/config`. Currently everything works fine, I'll try to get more info if this happens again.

**Comment by sestinj** [comment]
if you were using clear while only the welcome message was showing, we previously would replace it immediately, which could be what you were experiencing

**Comment by remixer-dec** [comment]
Possible. 

Just noticed that Continue uses system message not exactly as I expected (the model expects prompt in specific format, but it just adds system message into &lt;System> part instead of replacing the whole prompt), where should I look, to configure custom prompt format?

<img width="1017" alt="изображение" src="https://github.com/continuedev/continue/assets/6587642/43d50bc8-b17e-411e-93ee-badb56e677c1">

**Comment by sestinj** [comment]
Could you share which model class you are using? (e.g. GGML, Ollama, etc...)

It's actually misleading that it says "exact prompt" here, and I need to update that. The <System>/<User> things here are just for display and we actually format in the expected llama2 format behind the scenes (just need to make this transparent)

**Comment by remixer-dec** [comment]
Got it, thank you. I am using GGML class.

**Comment by sestinj** [comment]
Ok, good to know. In that case, the messages, including system, are just passed as json objects, so there isn't much room for error (or customization, it's up to the other server to do the formatting). I'm going to close this issue as the main problem is resolved. And if the second one comes up again I think it would probably be good to have a separate issue. Feel free to reopen if needed!
