### ISSUE TITLE
Allow configuring asyncio timeout in continue server

### ISSUE THREAD

**Issue by shrikrishnaholla** [continuedev/continue#442]
**Is your feature request related to a problem? Please describe.**
I am running inference on a local LLM on CPU RAM. Hence the inference can be slow. However, I am using the extension to automate non-time-critical work (inserting comments on code that I've just written). However, quite often, the request takes quite some time to finish and by the time it's finished, asyncio throws TimeoutError and the entire suggestion is tossed. 

```python
Traceback (most recent call last):

  File "continuedev/src/continuedev/core/autopilot.py", line 368, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev/src/continuedev/core/main.py", line 359, in __call__
    return await self.run(sdk)

  File "continuedev/src/continuedev/plugins/steps/chat.py", line 98, in run
    async for chunk in generator:

  File "continuedev/src/continuedev/libs/llm/ggml.py", line 105, in _stream_chat
    async for chunk in generator():

  File "continuedev/src/continuedev/libs/llm/ggml.py", line 79, in generator
    async for line, end in resp.content.iter_chunks():

  File "aiohttp/streams.py", line 51, in __anext__

  File "aiohttp/streams.py", line 433, in readchunk

  File "aiohttp/streams.py", line 303, in _wait

  File "aiohttp/helpers.py", line 721, in __exit__

asyncio.exceptions.TimeoutError
```

**Describe the solution you'd like**

I get why timeout exists, but I'd like a configuration that allows setting a timeout value (or 0 to disable it)

**Comment by sestinj** [comment]
First of all, this is a super cool use case. We've been thinking a lot about what better UI there might be for doing "async" tasks like this in the background, cool to see the first real example of usage

And yes, I can add this as an argument. I'll release a version soon and let you know

**Comment by sestinj** [comment]
@shrikrishnaholla I just released a new version (v0.0.362) that will allow you to do this: `GGML(..., timeout=None)` for no timeout or `GGML(..., timeout=3600)` for a one hour timeout for example

**Comment by sestinj** [comment]
update: in case you had tried v0.0.362, I realized I made a mistake, but this is now fixed in v0.0.363. If you haven't gotten to it yet, ignore this message

**Comment by shrikrishnaholla** [comment]
Thanks for the quick turnaround @sestinj . I'll try it out and let you know! :+1:

**Comment by shrikrishnaholla** [comment]
Tried changing the config in latest version (v0.0.365). However the server crashes. Where can I find the continuedev server running? (so I can check whether I have the latest ggml.py) @sestinj

**Comment by sestinj** [comment]
The server is packaged as a binary with pyinstaller, so you'd have to clone the repo and run from source to do this.

But you can check the logs and they might tell you something. Cmd+shift+p, "View Continue Server Logs".

Is it crashing only after setting timeout?

**Comment by sestinj** [comment]
The binary exists at ~/.continue/server/exe/run

Could be worth manually deleting to make sure that Continue downloads the latest version.

Also curious: which OS are you on?

**Comment by shrikrishnaholla** [comment]
@sestinj Linux. KDE Neon (debian based)

**Comment by shrikrishnaholla** [comment]
@sestinj Tried it. Same result

![Screenshot_20230904_113953](https://github.com/continuedev/continue/assets/1164410/9004f5b7-d2a8-4a00-9c9e-9a66d4a960f0)

For context, I am loading a 7B llama based model through [Oobabooga](https://github.com/oobabooga/text-generation-webui)'s OpenAI interface

**Comment by sestinj** [comment]
Ah, I have a new fix to make here, sorry about this. Will be ready in 20min

**Comment by sestinj** [comment]
@shrikrishnaholla if you enter a really large number for now that will work.

**Comment by sestinj** [comment]
New version is ready

**Comment by shrikrishnaholla** [comment]
@sestinj ah, I've been there. No worries. I've set it to a large number now and it's no longer complaining. Let me know when you have fresh version out. Love the quick responses. :heart:

**Comment by sestinj** [comment]
@shrikrishnaholla this is now ready, and on every LLM class. Appreciate the patience : )

**Comment by sestinj** [comment]
Closing assuming things seem alright now? Can ofc reopen if not!
