### ISSUE TITLE
LocalAI OpenAIServerInfo missing from Docs

### ISSUE THREAD

**Issue by lunamidori5** [continuedev/continue#446]
The LocalAI part of the docs is missing or removed... and a update killed Continue with this error

```bash
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\sdk.py", line 60, in create
    config = sdk._load_config_dot_py()

  File "continuedev\src\continuedev\core\sdk.py", line 217, in _load_config_dot_py
    spec.loader.exec_module(config)

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "C:\Users\LunaMidori5\.continue\config.py", line 16, in <module>
    from continuedev.src.continuedev.libs.llm.openai import OpenAI, OpenAIServerInfo

ImportError: cannot import name 'OpenAIServerInfo' from 'continuedev.src.continuedev.libs.llm.openai' (C:\Users\LUNAMI~1\AppData\Local\Temp\_MEI279642\continuedev\src\continuedev\libs\llm\openai.pyc)
```

**Comment by sestinj** [comment]
Yes, sorry! I'm in the process of adding docs and made a change without explaining it. This is what you can do, and I'm updating the docs as we speak:
```python
from continuedev.src.continuedev.libs.llm.openai import OpenAI

config = ContinueConfig(
    ...
    models=Models(
        default=OpenAI(
            api_key="my-api-key",
            model="gpt-3.5-turbo",
            api_base="https://my-azure-openai-instance.openai.azure.com/",
            engine="my-azure-openai-deployment",
            api_version="2023-03-15-preview",
            api_type="azure"
        )
    )
)
```

**Comment by sestinj** [comment]
Basically all of those properties are moved out of the OpenAIServerInfo because it was unnecessary to group them

**Comment by lunamidori5** [comment]
Thank you for all of your hard work!!! <3

**Comment by lunamidori5** [comment]
I will leave this open for other to see

**Comment by lunamidori5** [comment]
> Yes, sorry! I'm in the process of adding docs and made a change without explaining it. This is what you can do, and I'm updating the docs as we speak:
> 
> ```python
> from continuedev.src.continuedev.libs.llm.openai import OpenAI
> 
> config = ContinueConfig(
>     ...
>     models=Models(
>         default=OpenAI(
>             api_key="my-api-key",
>             model="gpt-3.5-turbo",
>             api_base="https://my-azure-openai-instance.openai.azure.com/",
>             engine="my-azure-openai-deployment",
>             api_version="2023-03-15-preview",
>             api_type="azure"
>         )
>     )
> )
> ```

How does this point to localai tho? do I set the api_base to my localai ip?

**Comment by lunamidori5** [comment]
yea even playing with the code and its trying to call a engines link that is not real

**Comment by lunamidori5** [comment]
**WORKING CODE**

```python
models=Models(
        default=OpenAI(
            api_key="my-api-key",
            model="gpt-3.5-turbo",
            api_base="http://localhost:8080/v1",
            api_type="openai"
        )
    )
    ```

**Comment by sestinj** [comment]
Yes, you're right, those were just example endpoints. What you've done here is perfect! You can also leave out the api_type, since it will default to "openai"

**Comment by lunamidori5** [comment]
Thank you! Ill let the localai discord ppl know if I get support questions!

**Comment by sestinj** [comment]
Of course, and feel free to ask here as well in case the questions are related to Continue : )

**Comment by lunamidori5** [comment]
Thank you Dev!!
