### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [continuedev/continue#458]
Dear continue developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
vansinhu

**Comment by sestinj** [comment]
Hi! Does InternLM have .ggml or .gguf files anywhere? If there's a way to run it locally, there is a chance we already have support. If not, would love to add support.

**Comment by sestinj** [comment]
@vansinhu Following up here - would love to discuss what Continue and InternLM can do to support each other. Let me know what you're thinking!

**Comment by sestinj** [comment]
@vansinhu I'm going to close this issue since it's gone a bit stale, but I've reached out through Discord and would love to hear your thoughts on what we can do!
