### ISSUE TITLE
/config description confusing

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#461]
/config did not open ~/.continue/config.py for a user and instead replied in the sidebar:

![image](https://github.com/continuedev/continue/assets/13314504/51d85c85-bca0-432b-9423-cb274078d2b0)

For me, it did open, but it gave a response that made me think it didn't open:

<img width="476" alt="Screenshot 2023-09-06 at 2 25 01 PM" src="https://github.com/continuedev/continue/assets/13314504/42d98fe8-b2b4-4e12-bbc1-1451e4d5e9c0">

**Comment by sestinj** [comment]
message has been updated, and haven't seen the /config being treated as input issue in a bit - closing unless it shows up again
