### ISSUE TITLE
continue in vscode can not work

### ISSUE THREAD

**Issue by xjy198903** [continuedev/continue#463]
![image](https://github.com/continuedev/continue/assets/29084288/df1366a8-3fbe-4e37-bee4-30cee94925c7)

[continue.log](https://github.com/continuedev/continue/files/12555129/continue.log)

**Comment by xjy198903** [comment]
In the previous version, I can use it directly without selecting a model, which was a very straightforward experience, but now I need to select a model, and no matter what model I select, it requires a bunch of operations and is time-consuming, and the end result is just an error!

**Comment by sestinj** [comment]
Thanks for sharing the log! I've seen something like this happening intermittently, so I'll try to figure out the issue. Are you completely blocked from using Continue right now?

**Comment by xjy198903** [comment]
yes, it can not work any more

**Comment by sestinj** [comment]
Closing this now that the latest version has solved the problem. Please re-open if needed
