### ISSUE TITLE
@diff fails on first attempt ~/.continue/diffs missing

### ISSUE THREAD

**Issue by pcuci** [continuedev/continue#467]
**Describe the bug**

First use of `@diff` fails

``` bash
FileNotFoundError: [Errno 2] No such file or directory: '/home/$HOME/.continue/diffs'
```

**To Reproduce**

Fresh install in WSL Ubuntu 2022 as per these instructions https://continue.dev/docs/how-continue-works

**Environment**

- Operating System: Windows WSL Ubuntu 2022
- Python Version: Python 3.10.12 natively, however, using poetry's .venv
- Continue Version: cloned repo, on `main` branch

**Workaround**

``` bash
mkdir -p ~/.continue/diffs
```

**Comment by sestinj** [comment]
Glad you found the workaround, I think I understand the fix that has to be made, but to be sure: this is happening when you do an /edit command?

**Comment by pcuci** [comment]
It happens when `@diff` is called, I believe you call these "context providers"?

After I manually created the ~/.continue/diffs folder, it was able to run ok

**Comment by sestinj** [comment]
Ok, thanks for the clarification, I was a bit confused because there seems to be a crossover episode playing out here (the diffs folder is used for another continue feature). I can still make the obvious fix of creating the /diffs folder immediately upon activation. Something deeper might be going on though

You don't happen to have the ~/.continue directory as the root of your workspace do you? It's either related to this, or a known problem with running commands in remote/WSL workspaces

**Comment by pcuci** [comment]
I went for point 5.a. in https://continue.dev/docs/how-continue-works (not 5.b.) since the default install inside vscode of continue didn't work out of the box

Isolating my dev environment (and continue) inside wsl is a much smoother dev experience for me, since I only use vs code in wsl mode anyway

I'm thinking of setting up a `docker-compose.yml` file with the basic dependencies sorted out (I was also missing `ripgrep`, which threw another ugly error)—would you be interested in a PR of this sort?

**Comment by sestinj** [comment]
@pcuci looks like I missed this last message...

I think this would be a really cool PR if you've set this up already

Aiming to soon solve the ripgrep problem though! We might be able to just package with this depending on its size

**Comment by sestinj** [comment]
the @ diff provider has been rewritten and has been stable for a while, so going to close this issue
