### ISSUE TITLE
"No Code Selected"

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#470]
**Describe the bug**

I am unable to highlight two sections of code from separate files and then have it edit one of them.

It tells me "No Code Selected" and to "Please highlight some code and try again."

I reloaded VS Code completely and tried again, but I ran into the same error.

**Screen recording**

Watch the video [here](https://drive.google.com/file/d/12TU5s7RoRFJXE64-VSeWkzW60ihTuYFY/view?usp=drive_link)

**Comment by sestinj** [comment]
This seems fixed from the recent round of overhauling the highlighted code management
