### ISSUE TITLE
Using `+` should add a model to your config, not replace it

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#472]
**Describe the bug**

I had GPT-4 set up with Continue. Then, I tried to add a Code Llama by clicking the `+` button, and it completely replaced my GPT-4 config settings when I selected TogetherAPI.

**To Reproduce**

1. Set up GPT-4 config
2. Click on `+` button and selected another model to add
3. See it completely replace your existing default model config

**Comment by sestinj** [comment]
fixed!
