### ISSUE TITLE
Compatibility: Migrate from Legacy Completion to Chat API (OpenAI)

### ISSUE THREAD

**Issue by adrianliechti** [continuedev/continue#487]
It seems for title generation after the completion, this extension is using the legacy /v1/completions api (non-streaming).
could you consider to use the non-streaming /v1/chat/completions version instead to simplify the needed API footprint in the OpenAI LLM?

**Comment by sestinj** [comment]
Definitely. This would be important in cases where you want to use an OpenAI-compatible API that is only compatible with the non-legacy endpoint; I assume you ran into this with the GGML class?

**Comment by adrianliechti** [comment]
wow thanks for the fast response!

i was using the 'openai' class using a custom base url (against an own implantation of a server)

**Comment by sestinj** [comment]
@adrianliechti Sorry for the lopsided responsiveness here :/ Any luck with the GGML version? I also have a way of making this work with the OpenAI class: if you set `model="gpt-4"`, then Continue will notice that it is a chat model and use the chat endpoint instead

**Comment by sestinj** [comment]
@adrianliechti wanted to check in on this - have any of the solutions been able to solve your problem?

**Comment by adrianliechti** [comment]
Ciao @sestinj, I solved it by implementing the "legacy" API too in my proxy, as I saw that other implementations are also using a mix of the APIs.
https://github.com/adrianliechti/llama/blob/main/llama-openai/pkg/server/server_legacy.go

**Comment by sestinj** [comment]
Sounds good, I'm going to close this issue since I think it's still best that we default to the normal completion endpoint - we'll have to use it for some models and I want to avoid breaking compatibility with other setups
