### ISSUE TITLE
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

### ISSUE THREAD

**Issue by xaranex1** [continuedev/continue#503]
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

I have problem with this error running llama cpp python with 70b Lllama 2 chat

**Comment by sestinj** [comment]
@xaranex1 I've had this problem before when using a 70b model (in my case the problem was that my computer wasn't strong enough to handle such a large model). Does the same problem occur when using a 7b model?

**Comment by sestinj** [comment]
@xaranex1 wanted to check in on this issue - have you had any luck with a 7b parameter model? If not it would be great to know and I'm sure there's something we can do to solve the problem!
