### ISSUE TITLE
Allow edits to an earlier prompt and resume session from edited prompt

### ISSUE THREAD

**Issue by abhinavkulkarni** [continuedev/continue#505]
Hi,

Please allow edits to an earlier prompt in a session. Here is an example: https://www.youtube.com/watch?v=cKaaQ7aJDFc&t=11m46s

**Comment by sestinj** [comment]
Hello! This is possible if you click the previous prompt, type your new version, and press enter. There was a bug with clicking the checkmark icon, but I'm pushing a fix right now

**Comment by abhinavkulkarni** [comment]
Thanks @sestinj, one minor issue, click on `continue` button is not working. One needs to press `Enter` key to send the prompt to the model.

**Comment by sestinj** [comment]
@abhinavkulkarni you are correct...fixing this now!
