### ISSUE TITLE
cmd+m doesn't work for Jupyter Notebook outputs

### ISSUE THREAD

**Issue by vividfog** [continuedev/continue#511]
Today I noticed that cmd+m works for selecting code blocks, but it does not for Jupyter Notebook outputs. I had an error as output, wanted to check what WizardCoder would do to fix it ... but the selection does not move to the chat window with cmd+m. 

Selecting the code that produced the error, for that cmd+m works as expected. For its output, not.

Try with any .ipynb if you might have the same observation.

**Comment by sestinj** [comment]
This is now solved with [this commit](https://github.com/continuedev/continue/commit/1b30b9e312b3f16d6504d3e03bf90df7d9b180a5) and available in 0.9.124
