### ISSUE TITLE
Continue doesn't seem to be getting context of highlighted code when using /edit or /comment

### ISSUE THREAD

**Issue by brandonbiggs** [continuedev/continue#512]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 13.6
- Continue: 0.0.401
- Python: 3.9.6
- IDE: VSCode 1.82.2
- phind-code-34b-v2 (https://huggingface.co/Phind/Phind-CodeLlama-34B-v2)
```

### Description

If I use the Continue sidebar and ask questions, I usually get a response to what I'm looking for. However if I highlight some code and then say `/edit` or `/comment`, a diff will open and some very irrelevant code gets produced. I don't think this is a model issue as the model does a good job when asking direct questions, however it seems that something weird is happening with Continue. This didn't seem to be happening last week.

Example of asking some basic questions:

![image](https://github.com/continuedev/continue/assets/34954680/95297059-6c4b-4a74-b7f5-fc81b0f549e9)

But if I ask for `/comment` with the following code hightlighted

```python
def print_each_character():
    user_input = input("Please enter some text: ")
    for char in user_input:
        print(char)

print_each_character()
```

This is what I got in response:
```
#include "Arduino.h"
#include "Ultrasonic.h"

Ultrasonic::Ultrasonic(int pin)
{
    pinMode(pin, OUTPUT);
    _pin = pin;
}

void Ultrasonic::pulse()
{
    digitalWrite(_pin, LOW);
    delayMicroseconds(2);
    digitalWrite(_pin, HIGH);
    delayMicroseconds(5);
    digitalWrite(_pin, LOW);
}

long Ultrasonic::timing()
{
    long duration;
    pinMode(_pin, INPUT);
    while(digitalRead(_pin) == 0);
    long startTime = micros();
    while(digitalRead(_pin) == 1);
    duration = micros() - startTime;
    return duration;
}

long Ultrasonic::Ranging()
{
    long distance;
    pulse();
    long duration = timing();
    distance = duration / 58.2;
    return distance;
}

```
![image](https://github.com/continuedev/continue/assets/34954680/1eb52710-526a-4d39-b548-7ff428d00de5)

Here's my "selected context":

This is the exact context that will be passed to the LLM

-----------------------------------

How do I print in python?

-----------------------------------

To print in Python, you use the `print()` function. This function can print any value or variable you provide to it.

Here is a simple example:

```python
print("Hello, World!")
```

This will output:

```
Hello, World!
```

You can print variables by passing them to the `print()` function. For example:

```python
name = "Alice"
print("Hello, " + name + "!")
```

This will output:

```
Hello, Alice!
```

-----------------------------------

Can you show that last example using fstrings instead?

-----------------------------------

Sure, here's the same example using f-strings in Python:

```python
name = "Alice"
print(f"Hello, {name}!")
```

This will output:

```
Hello, Alice!
```

-----------------------------------

/comment Write comments for the selected code

-----------------------------------

Code in this file is highlighted (/Users/me/projects/code-llm/hello.py):
```
def print_each_character():
    user_input = input("Please enter some text: ")
    for char in user_input:
        print(char)

print_each_character()
```

-----------------------------------

            - Included necessary libraries and header files: This allows the code to work with the Arduino platform and access the Ultrasonic sensor functionalities.
            - Defined a constructor for the `Utrasonic` class: This initializes the class with a specified pin, sets it as an output, and stores it for later use.
            - Implemented a `pulse` function: This generates an ultrasonic pulse by setting the pin to LOW for 2 microseconds, then HIGH for 5 microseconds, and finally LOW again.
            - Implemented a `timing` function: This measures the time it takes for the ultrasonic pulse to be echoed back from an object and detected by the sensor.
            - Implemented a `Ranging` function: This calculates the distance to an object by dividing the time duration measured in the `timing` function by 58.2 (the speed of sound in microseconds per cm).

The logs don't seem to be giving any errors:
```
[2023-09-26 12:12:57,528] [DEBUG] Received GUI message {"messageType":"show_logs_at_index","data":{"index":2}}
[2023-09-26 12:13:13,967] [DEBUG] Received GUI message {"messageType":"delete_at_index","data":{"index":2}}
[2023-09-26 12:13:16,748] [DEBUG] Received GUI message {"messageType":"delete_at_index","data":{"index":1}}
[2023-09-26 12:13:16,749] [DEBUG] Received GUI message {"messageType":"delete_at_index","data":{"index":2}}
[2023-09-26 12:13:25,142] [DEBUG] Received GUI message {"messageType":"main_input","data":{"input":"How do I print in python?"}}
[2023-09-26 12:13:50,342] [DEBUG] Received GUI message {"messageType":"main_input","data":{"input":"Can you show that last example using fstrings instead?"}}
[2023-09-26 12:14:05,188] [DEBUG] Received GUI message {"messageType":"show_logs_at_index","data":{"index":6}}
[2023-09-26 12:14:34,299] [DEBUG] Received GUI message {"messageType":"main_input","data":{"input":"/comment Write comments for the selected code"}}
[2023-09-26 12:34:33,707] [DEBUG] Received GUI message {"messageType":"show_context_virtual_file","data":{}}
```

This was it last week working great:
![image](https://github.com/continuedev/continue/assets/34954680/e37a1503-6ff7-4bb0-b273-5655c20e82e0)

**Comment by sestinj** [comment]
@brandonbiggs could you share which model you are using and I'll play around with the prompts a bit? Based on the [TITLE] in the session header, I would guess some variant of llama/codellama - I've seen a few issues with these understanding the /edit prompt

**Comment by brandonbiggs** [comment]
Hi @sestinj Thanks. I'm using the default phind-code-34b-v2 (https://huggingface.co/Phind/Phind-CodeLlama-34B-v2). Let me know if there's any testing I can do on my side to help. Happy to contribute what I can.

**Comment by sestinj** [comment]
If you do want to play around at all, you'll notice in `~/.continue/config.py` that there's a `prompt_templates={"edit": "..."}` property. This is the thing you can tweak to alter the edit prompt. If it's just a matter of the prompt, then this is exactly what I'll be attempting. If you find that it consistently seems unaware of the code at all, then we might have another problem : )

**Comment by brandonbiggs** [comment]
What version of continue are you using? My `prompt_templates` dict has been empty?

```
    models=Models(
    #     default=OpenAIFreeTrial(api_key="", model="gpt-4"),
    #     summarize=OpenAIFreeTrial(api_key="", model="gpt-3.5-turbo")
    default=OpenAI(
			model="Phind-CodeLlama-34B-v2",
            api_base='http://localhost:8000/v1',
            context_length=4096,
            timeout=5000,
			prompt_templates={},
			api_key=""
		),
    ),
    ```

**Comment by brandonbiggs** [comment]
Okay, I've made some progress. This isn't using `prompt_templates` like you mentioned, but I am using `template_messages`. I found this in the docs, but the path to `template_alpaca_messages` has changed from what it says in the docs - https://continue.dev/docs/customization/models#customizing-the-chat-template

I added the following to my `config.py`

```python
from continuedev.src.continuedev.libs.llm.prompts.chat import template_alpaca_messages

    models=Models(
        default=OpenAI(
                model="Phind-CodeLlama-34B-v2",
                api_base='http://localhost:8000/v1',
                context_length=4096,
                timeout=5000,
                template_messages=template_alpaca_messages,
                # prompt_templates={},
                api_key=""
            ),
    ),
```
This seems to be formatting things in the chat much better -
![image](https://github.com/continuedev/continue/assets/34954680/ae23fb33-dcf8-4a85-8203-ec2a9bf948a0)

**Comment by sestinj** [comment]
Ok this actually explains the problem. We don't set a default prompt_template or template_messages for the OpenAI or OpenAIFreeTrial classes because by default they use gpt-4, which doesn't need these. But this obviously doesn't work for other models.

For the prompt_templates, you can change it to `{"edit": simplest_edit_prompt}` where simplest_edit_prompt is imported like: `from continuedev.src.continuedev.libs.llm.prompts.edit import simplest_edit_prompt`. And then this should make edits also work well

**Comment by brandonbiggs** [comment]
Thanks @sestinj . It appears my `/edit` as well as `/comment` are working really well without the `prompt_templates`, once I just had `template_messages` configured. Does it make sense to you that it should be working without `prompt_templates`?

**Comment by sestinj** [comment]
@brandonbiggs yes, there is a good default prompt_template, so I would fully expect it to work. Does this seem to clear up the last of these issues, or any other quirks you're seeing?

**Comment by brandonbiggs** [comment]
I think we're in good shape. Thank you so much for the help!
