### ISSUE TITLE
Windows Defender False Positive

### ISSUE THREAD

**Issue by ecchichan** [continuedev/continue#514]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.403 VSCode from the extension store
```

### Description

Just wanted to report that the server exe is being falsely flagged and removed as a trojan by Windows Defender. I'm not sure if this is necessarily a bug, and I'm not sure if there's anything that can actually be done about it.

![image](https://github.com/continuedev/continue/assets/128974981/ce0ae362-ee13-4c83-a8d6-611f6924235a)

Side note: is this why every time I launch VSCode I get a popup saying the server is being downloaded/installed?

### To reproduce

1. use windows 11
2. wait for windows defender to yell at you
3. :(

**Comment by sestinj** [comment]
Thanks for sharing this. I'll look into what we might be able to do about it. I'm also planning to make it more automatic to run the server through the PyPI package, which is another route that wouldn't cause this.

I'll let you know when there's an update there, but until then the best way to proceed is [this](https://continue.dev/docs/walkthroughs/manually-run-continue).

**Comment by zeddyemmy** [comment]
I just got a Wacatac.B!ml trojan alert

**Comment by sestinj** [comment]
sorry to hear this. Same solution as above is what you will have to do for now unless you can temporarily disable or put Continue on an allow-list.

**Comment by sestinj** [comment]
@zeddyemmy @ecchichan As of yesterday, the official VS Code extension comes with the binary pre-installed so I would expect that there are no issues from Windows Defender. Can either of you verify that this is the case?

**Comment by sestinj** [comment]
We've now entirely removed the need for a separate Python binary by rewriting all of this logic in typescript, so Continue will not be flagged by Windows Defender. thanks again for sharing this!
