### ISSUE TITLE
VSCode diff editing broken because generated file name is too long

### ISSUE THREAD

**Issue by coreymux** [continuedev/continue#516]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 13.3.1
- Continue: v0.0.403
```

### Description

The generated filename for diffs can get too long for paths that are nested. It appears this is because the way escaping slashes is being handled. This breaks the diff editing feature as vs code has nothing to open
![image](https://github.com/continuedev/continue/assets/50751627/45848bc9-cd3b-4772-a8f2-dbdb05e73caf)

### To reproduce

Attempt to `/edit` a file that is in a deep enough nested directory

### Log output

```Shell
Error handling message (showDiff) from Continue server: Error: ENAMETOOLONG: name too long, open '/Users/csery/.continue/diffs/$forwardslash$Users$forwardslash$csery$forwardslash$go$forwardslash$src$forwardslash$github.com$forwardslash$muxinc$forwardslash$mux$forwardslash$my$forwardslash$really$forwardslash$long$forwardslash$nested$forwardslash$path$forwardslash$name$forwardslash$that$forwardslash$is$forwardslash$long$forwardslash$test.go'
```

**Comment by sestinj** [comment]
I hadn't considered this...but it's a super easy fix, just have to change how we escape! I'll push something later today and let you know

**Comment by sestinj** [comment]
@coreymux made this fix a couple days ago and just forgot to update here! I'm going to close this issue, but if something is still wrong please feel free to re-open

**Comment by OwenRay** [comment]
still having this issue, wouldn't it be better to just store a hash of the file or something?
