### ISSUE TITLE
Small timeline window

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#518]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: v0.0.404
```

### Description

- box size for failed command very smōl

### To reproduce

- run a bad command, e.g. `cut -3`
- press <kbd>⌘ Command</kbd> + <kbd>⇧ Shift</kbd> + <kbd>R</kbd>
- notice the size of the coloured rounded box, it is very smōl  in `v0.0.404 ` vs `v0.0.403` 

### v0.0.403

<img src="https://github.com/continuedev/continue/assets/92653266/6df6d08c-88a2-462d-b79b-fc15246aa90c" width="600">

### v0.0.404 
https://github.com/continuedev/continue/assets/92653266/40a4be65-c0fc-4579-a5e4-487105e657ff

PS: #513 is very useful with the little arrow on the right side that the user can click to see the entire message that was sent.  Good addition.

<img src="https://github.com/continuedev/continue/assets/92653266/cd1a4166-ad9b-41b5-a862-a1b17f365578" width="500">

**Comment by sestinj** [comment]
Found the problem, just a forgotten dependency in a useEffect. Thanks for pointing this out! I'll include it in the next release today, and then close the issue

**Comment by sestinj** [comment]
Found the problem, just a forgotten dependency in a useEffect. Thanks for pointing this out! I'll include it in the next release today, and then close the issue

**Comment by sestinj** [comment]
solved in v0.0.405, closing this issue unless you see it again in any other scenarios
