### ISSUE TITLE
I tried everything but no API endpoint work with continue.dev

### ISSUE THREAD

**Issue by xaranex1** [continuedev/continue#521]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

I need know how i can connect to API endpoint.. i tried everything but nothing work.. i used text-generation-webui but with --api parameter and i dont know path to this api endpoint i tried on vast.ai and on runpod.io nothing work.. maybe some proxy?? or what i can do to work?
I tried llama.cpp python it work little bit but i have error 404 on request.. i tried ggml class etc.. nothing work

**Comment by sestinj** [comment]
We have an option that is made specifically for text-generation-webui: https://continue.dev/docs/reference/Models/textgenui

Alternatively, if you use the [openai](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai#an-openedai-api-openai-like) option in text-generation-webui, you could then use the [OpenAI](https://continue.dev/docs/reference/Models/openai) class in Continue

I notice that we don't have TextGenUI as an option in the model selection page, so I will add this

**Comment by xaranex1** [comment]
Thank you very much!

**Comment by sestinj** [comment]
of course - did this end up solving your problem?

**Comment by badcodecat** [comment]
I don't know about them but, this solved the problem for me.
Thanks for planning to add it to the selection page, I thought the options there were the only ones available.

Sidenote: The "Other OpenAI-compatible API" option lists text-gen-webui as a supported.

**Comment by sestinj** [comment]
@badcodecat When you had the problem with "Other OpenAI-compatible API" option, were you using the OpenAI-compatible API extension for text-gen-webui, or just the normal "--api" flag? (https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai#an-openedai-api-openai-like)

Only the former will work with the first method, something I'll try to clarify on the model selection page

**Comment by badcodecat** [comment]
I think so (not near my pc right now), but I also recently updated/migrated to the new version so I may have broken something then.

**Comment by sestinj** [comment]
ok, no worries. I'm going to close this issue since it does seem that this is solved - I've tested with the OpenAI-compatible server and it seemed to be working, but text-generation-webui will also be a first-class option in the UI selector in our next release. Feel free to re-open if something else goes wrong
