### ISSUE TITLE
Extension does not start

### ISSUE THREAD

**Issue by lufixSch** [continuedev/continue#529]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Manjaro 6.4.3
- Continue: 0.0.409
- Python: 3.11.5 (and 3.10.12)
- IDE: Code OSS 1.82.0
```

### Description

Extension prompts the "Continue Server Starting" loading screen and this loading screen keeps on forever. 
![Screenshot_20231003_110045](https://github.com/continuedev/continue/assets/62517060/2758f69a-4a5a-4490-be03-b5e0d2363bfc)

It seems like the server is starting as expected (tried running it manually and the server starts without issues). It worked for me on a previous version (I think in August but I am not really sure, I reinstalled my OS in between and I am not sure if I used Continue after) but I tried and older version earlier and I have the same issue. 

I noticed that the server keeps running after VSCode is closed until I reopen VSCode. Then the process is killed and a new server is started.
After deleting the `.continue` folder I also noticed that the `config.py` and other files in this folder are missing.

### To reproduce

1. Install Continue extension
2. Swap to Continue extension in the side bar

### Log output

Server Logs (Restarted VSCode multiple times):
```shell
[2023-10-03 10:41:47,318] [DEBUG] ------ Begin Logs ------
[2023-10-03 10:41:47,643] [DEBUG] Downloading MeiliSearch...
[2023-10-03 10:42:02,762] [DEBUG] Starting MeiliSearch...
[2023-10-03 10:42:02,762] [DEBUG] Meilisearch started
[2023-10-03 10:50:41,299] [DEBUG] ------ Begin Logs ------
[2023-10-03 10:50:41,616] [DEBUG] Meilisearch started
[2023-10-03 10:56:47,354] [DEBUG] ------ Begin Logs ------
[2023-10-03 10:56:47,687] [DEBUG] Meilisearch started
```

VS Code console logs:
```shell
[Extension Host] Using Continue version:  0.0.409
workbench.desktop.main.js:sourcemap:132 [Extension Host] In workspace:  /run/media/lukas/linux_data/Projects/Homepage
workbench.desktop.main.js:sourcemap:132 [Extension Host] Killing server from old version of Continue
workbench.desktop.main.js:sourcemap:132 [Extension Host] Downloaded server executable at  /home/lukas/.continue/server/exe/run
workbench.desktop.main.js:sourcemap:132 [Extension Host] Looking for file at  /home/lukas/.continue/server/exe/run
workbench.desktop.main.js:sourcemap:132 [Extension Host] ---- Starting Continue server ----
workbench.desktop.main.js:sourcemap:132 [Extension Host] Error caught: Error: spawn ETXTBSY.

Retrying attempt 1...
workbench.desktop.main.js:sourcemap:132 [Extension Host] Continue server started
```

**Comment by sestinj** [comment]
Would you mind trying a few things to help characterize the situation? It's not immediately clear what the problem is but I have a few ideas

- When the "Continue Server Starting" wheel is spinning, does `lsof -i :65432` show that the server is running?
- At any point in the lifecycle of opening/reloading VS Code does ~/.continue/server/server_version.txt exist?
- When you reload the window, do you each time see the bottom right notification of "Installing Continue server..."?

And then I'm not super familiar with Manjaro, would expect that a binary built on Ubuntu would work there, but is there any reason it might not, or anything potentially relevant about the OS?

**Comment by lufixSch** [comment]
> When the "Continue Server Starting" wheel is spinning, does lsof -i :65432 show that the server is running?

Yes it does: 
```bash
COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
run     12305 lukas    8u  IPv4 142919      0t0  TCP localhost:65432 (LISTEN)
```

> At any point in the lifecycle of opening/reloading VS Code does ~/.continue/server/server_version.txt exist?

Yes it does exist

> When you reload the window, do you each time see the bottom right notification of "Installing Continue server..."?

Yes it pops up each time

> And then I'm not super familiar with Manjaro, would expect that a binary built on Ubuntu would work there, but is there any reason it might not, or anything potentially relevant about the OS?

I am myself not sure if this would work or not. As Manjaro is based on Arch instead of Debian maybe this causes problems. However it did work before without any problem

Complete system information (in case that helps):
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.3-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 20 × 13th Gen Intel® Core™ i5-13500
Memory: 31.1 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D98
System Version: 1.0
```

**Comment by sestinj** [comment]
Thanks for checking all of this. I know we've seen a problem on Arch linux before, so this could be related - the binary has a dependency on glibc, so perhaps differences could cause a problem (though I lean less toward this because the server is listening).

What would probably expose the problem is entering the `~/.continue/server/exe` directory and double-clicking (or running from terminal) the `run` binary. My guess is that there will be some useful output, perhaps that didn't show up in the logs

**Comment by lufixSch** [comment]
Out of the box I didn't had the permission to execute the binary. I changed that (`chmod 755 ./run`) and tried executing that and I get the following error.

```bash
$ ./run
[31961] Cannot open PyInstaller archive from executable (/home/lukas/.continue/server/exe/run) or external archive (/home/lukas/.continue/server/exe/run.pkg)
```

The binary exits after the error.

**Comment by sestinj** [comment]
Ok, this seems like most likely a build incompatibility (unless somehow the binary is corrupted). What I can try is building a binary on a Manjaro EC2 myself and then sharing to see if it works - though I don't think that GitHub runners support Manjaro out of the box, so staying up to date might be easier by manually running the server

**Comment by lufixSch** [comment]
Are the steps for building the binary those, described in the documentation for manually running continue?
I could try building the binary on my machine to see if it works/changes anything.

**Comment by sestinj** [comment]
Yeah, you can follow the steps here: https://continue.dev/docs/walkthroughs/manually-run-continue#build-the-server-binary-from-source

I believe this will do everything necessary to create the build - this would be amazing

**Comment by lufixSch** [comment]
I now had time to build the binary myself. It starts up just fine but the UI still shows "Continue Server Starting" (I enabled "Manually Running Server" in the settings and reloaded VSCode).

I even deleted the `.continue` folder. Here is the complete console output I got when I started the binary.

```bash
[2023-10-05 12:52:30,871] [DEBUG] ------ Begin Logs ------
Certificates at:  /tmp/_MEIpaxSKJ/ca_bundle/cacert.pem
Running Continue server version 0.0.350
INFO:     Started server process [6879]
INFO:     Waiting for application startup.
[2023-10-05 12:52:31,217] [DEBUG] Downloading MeiliSearch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4352  100  4352    0     0  13139      0 --:--:-- --:--:-- --:--:-- 13139
Downloading Meilisearch binary v1.4.0 for linux, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100  109M  100  109M    0     0  5205k      0  0:00:21  0:00:21 --:--:-- 7824k
Meilisearch v1.4.0 binary successfully downloaded as 'meilisearch' file.

Run it:
    $ ./meilisearch
Usage:
    $ ./meilisearch --help
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:65432 (Press CTRL+C to quit)
[2023-10-05 12:53:57,318] [DEBUG] Starting MeiliSearch...
[2023-10-05 12:53:57,319] [DEBUG] Meilisearch started
```

The only difference I noticed is that the dropdown in the left bottom corner of the UI now has a default value but I'm not sure if this is related.

![Screenshot_20231005_130226](https://github.com/continuedev/continue/assets/62517060/5d5d2e05-29cc-4e79-b847-53ff156b1fc4)

**Comment by lufixSch** [comment]
I just clicked on the "history" button in the UI just to see what happens and it seems like the Extension sent an request to the server successfully even though it still says "Continue Server Starting" 

```bash
Returning sessions list:  []
INFO:     127.0.0.1:47648 - "GET /sessions/list HTTP/1.1" 200 OK
```

**Comment by sestinj** [comment]
Thanks for sharing this! At this point it seems the problem has been narrowed down to an inability of the extension (outside of the webview) to connect to the server.

I've been working on a pre-release version that is now published, which ships with the binary built-in - this might be worth a try.

Otherwise, I'm going to add a few logging points throughout the server startup lifecycle that might help narrow down the problem since it's still not clear exactly how to solve this.

**Comment by lufixSch** [comment]
Today I had time to try out the pre-release. I still have the same Problem

The output in continue.log did not change but I now get the following output in the VSCode developer tools:

```
[Extension Host] Using Continue version:  0.1.8
[Extension Host] In workspace:  /run/media/lukas/linux_data/Projects/Homepage
[Extension Host] Killing server from old version of Continue
[Extension Host] ---- Starting Continue server ----
[Extension Host] Continue server started
```

I also noticed, that the bottom right notification of "Installing Continue server..." disappeared.

**Comment by lufixSch** [comment]
Out of curiosity I tried installing the official Visual Studio Code instead of Code - OSS and installed the regular Version of Continue and that seems to work.

So the problem seems to be either with my installation/setup of Code - OSS or with Code - OSS in general.

**Comment by sestinj** [comment]
@lufixSch "Installing Continue server..." disappearing is ok, since in the pre-release, and moving forward, we will be shipping with OS-specific binaries instead of downloading after-the-fact.

The Code - OSS detail is really good to know! This gives me something to test against - I'll try this myself and see if I can get to the bottom of it. Thanks again for being willing to try so much! Hopefully by the end of this there's a whole new group of users who have compatibility : )

**Comment by sestinj** [comment]
@lufixSch Unfortunately I just tried with Code - OSS and setup went smoothly. So seems to be at the intersection of Code - OSS and Manjaro Linux. I've just published a version that should be ready in ~20min (v0.1.10, a pre-release) that adds logging to the websockets setup:

```typescript
newWebsocket.addEventListener("open", () => console.log("Websocket connection opened"));
    newWebsocket.addEventListener("error", (error: any) => {
      console.error("Websocket error occurred: ", error);
    });
    newWebsocket.addEventListener("close", () => {
      console.log("Websocket connection closed");
    });
```

This seems like the best starting point I can think of to further figure out what's going on. These will show up in developer tools console

**Comment by lufixSch** [comment]
Tried the pre-release and got the following output:

```
ERR [Extension Host] Websocket error occurred:  {}
[Extension Host] Websocket error occurred:  {}
    m @ console.ts:137
    $logExtensionHostMessage @ mainThreadConsole.ts:39
    N @ rpcProtocol.ts:455
    M @ rpcProtocol.ts:440
    H @ rpcProtocol.ts:370
    G @ rpcProtocol.ts:296
    (anonymous) @ rpcProtocol.ts:161
    w @ event.ts:1107
    fire @ event.ts:1138
    fire @ ipc.net.ts:650
    X.onmessage @ localProcessExtensionHost.ts:585
[Extension Host] Websocket connection closed
```
![Screenshot_20231009_102207](https://github.com/continuedev/continue/assets/62517060/423013eb-3606-4862-a7d2-102a7e04b645)

**Comment by sestinj** [comment]
Incredibly unfortunate that the error message is empty...apparently the error is only included in the onclose event, so I'm uploading a new version that will print this. At least we know that it happened after the websocket was opened - I would be surprised if there weren't any error message on the server side to go along with this

**Comment by lufixSch** [comment]
>  I'm uploading a new version that will print this.

I am not sure, if you already uploaded this version. I'm now running `v0.1.14` but the error did not change.

**Comment by sestinj** [comment]
@lufixSch the "Websocket error occurred" would still be empty, but the object would show up with "Websocket connection closed" like here https://github.com/continuedev/continue/blob/c94053baedfad4adb5a5739e842f089c4c514552/extension/src/util/messenger.ts#L64

**Comment by lufixSch** [comment]
My bad. Did not see that.

But the output still doesn't look really useful to me. It's still an empty object

![Screenshot_20231011_215340](https://github.com/continuedev/continue/assets/62517060/ee79396a-f268-4b9f-bbf1-272991793113)

**Comment by sestinj** [comment]
@lufixSch I promise I haven't forgotten about this, it's just been unable to take priority as we've been fixing a large handful of critical bugs in the new JetBrains extension.

Someone else today came in with what appears to be a similar error on CentOS, so I'll keep you updated if any new information shows up there.

Thanks again for helping so much with debugging this, and hopefully we can find our way to a solution!

**Comment by lufixSch** [comment]
No problem. Until this is fixed I will simply use Visual Studio Code instead of Code - OSS which is fine for me.

**Comment by lufixSch** [comment]
Hey @sestinj I just used Code - OSS for something and tried Continue out of curiosity and it seems to work now.

I'm running `v0.1.33` but I have no Idea since when it is working again.

**Comment by sestinj** [comment]
@lufixSch Very odd, but not complaining.

I'm working on some changes this weekend that I expect to solve the original problem, so even in case it comes back I hope to squash the bug for good

**Comment by sestinj** [comment]
@lufixSch The changes I mentioned I was making are now released. If things work there as well, then this issue might be considered finally solved

**Comment by lufixSch** [comment]
@sestinj I tried the newest version and it still works. So I think the issue is fixed.
Thanks for your work :)

**Comment by sestinj** [comment]
Nice!! Thanks for your patience
