### ISSUE TITLE
ValueError path is on mount 'd:', start on mount 'C:'

### ISSUE THREAD

**Issue by fyyyyy** [continuedev/continue#530]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: WSL / Windows
- Continue: Version: 0.0.409
```

### Description

Getting an error when editing files with WSL / Ubuntu
Running a local openapi server over webui

```
File "continuedev\src\continuedev\plugins\context_providers\file.py", line 88, in get_context_item_for_filepath
    relative_to_workspace = os.path.relpath(

  File "ntpath.py", line 744, in relpath

ValueError: path is on mount 'd:', start on mount 'C:'
```

### To reproduce
Possible related: https://github.com/continuedev/continue/issues/412

### Log output

File "continuedev\src\continuedev\plugins\context_providers\file.py", line 88, in get_context_item_for_filepath
    relative_to_workspace = os.path.relpath(

  File "ntpath.py", line 744, in relpath

ValueError: path is on mount 'd:', start on mount 'C:'

**Comment by sestinj** [comment]
@fyyyyy making a fix for this rn - I'll let you know when I release a new version. Should be in the next hour

**Comment by sestinj** [comment]
@fyyyyy The new version is released - let me know if things seems to work

**Comment by fyyyyy** [comment]
Seems to be fixed, thanks
