### ISSUE TITLE
Hope to adapt jetbrains tools soon!

### ISSUE THREAD

**Issue by Houtx** [continuedev/continue#536]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Some problems with the **jetbrains idea**.

1.When idea's theme is Light, there is a problem with the right side logo.
![image](https://github.com/continuedev/continue/assets/17922172/794b2756-1be5-4786-b981-654fb0742af2)

2.When the theme is Light, the continue color is not compatible. Also, there is a bug in the UI when you open it for the first time.
![image](https://github.com/continuedev/continue/assets/17922172/8a9693e3-2868-4922-89d5-e170c572a50e)

3.Can't click anything! Don't work!
![image](https://github.com/continuedev/continue/assets/17922172/1adc5f98-44c5-4731-94c7-ccbaa51f8350)

### Solution

Hope to adapt jetbrains tools soon!

**Comment by sestinj** [comment]
Thanks for sharing these. I'll be working on fixing these in the next few days and will share an improved version as soon as it is released!

**Comment by sestinj** [comment]
@Houtx We're still waiting on JetBrains to accept our latest version, but if you'd like you can install it from disk using this .zip file here. This will fix the freezing problem and also match your color scheme.

To install from disk, open Intellij settings (command+comma), go to "Plugins" in the sidebar, click the gear icon at the top, and select "Install from Disk"

[continue-intellij-extension-0.0.7.zip](https://github.com/continuedev/continue/files/12838823/continue-intellij-extension-0.0.7.zip)

**Comment by sestinj** [comment]
@Houtx 0.0.8 is now available on the JetBrains store - would love to hear your feedback as we work toward an official release!
