### ISSUE TITLE
[CON-213] Can't copy Continue text to clipboard on Windows

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#538]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: *
```

### Description

Copying from a Continue response doesn't work on windows

### To reproduce

1. Enter input in Continue
2. Try to copy the response by highlighting and cmd+c
3. Paste and see that it didn't copy correctly

### Log output

```Shell
...
```

<sub>[CON-213](https://linear.app/continue/issue/CON-213/cant-copy-continue-text-to-clipboard-on-windows)</sub>

**Comment by Allan2000-Git** [comment]
Try :
- right-click and "Copy"
- If you have Clipboard History enabled, there might be a conflict causing the copy and paste issue. You can try disabling Clipboard History by going to "Settings" > "System" > "Clipboard" and turning off "Clipboard history."
