### ISSUE TITLE
was having a REAL bad time! **imports on default config are bad**

### ISSUE THREAD

**Issue by cachatj** [continuedev/continue#539]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When installing on a MacBook Pro M2, I was having a very hard time keeping any persistence btw VSCode sessions. Basically every time I closed VS Code & came back, Continue extension got reset....and worse I got:

```
It's possible this was caused by an update to the Continue config format.
Falling back to default config settings due to the following error in ~/.continue/config.py.
```
with the Traceback:
```
ModuleNotFoundError: No module named 'continuedev.src'
```

I was intially thinking that my install was wrong. started over, ran it again etc.....maybe something with my environments, esp the overlap btw miniconda and poetry. what a headache. Esp given how easy Ollama + Continue make it seem up front to get a local LLM model or several running without needing the internet.

Turns out, it is that easy. And the fact that I could still engage with the models from the terminal should have been my biggest clue. 

### Solution

Essentially, most of the imports in the `config.py` file (the _default_ one) - include an extra prefix that is apparently no longer needed. 

The solution for me ended up being - yo, take the Traceback seriously - its an issue with the imports not PATHs or conda/poetry. 

So, the default is:

```
...
...
...
from continuedev.src.continuedev.core.config import CustomCommand, SlashCommand, ContinueConfig
from continuedev.src.continuedev.plugins.context_providers.github import GitHubIssuesContextProvider
from continuedev.src.continuedev.libs.llm.openai_free_trial import OpenAIFreeTrial

from continuedev.src.continuedev.plugins.steps.open_config import OpenConfigStep
from continuedev.src.continuedev.plugins.steps.clear_history import ClearHistoryStep
from continuedev.src.continuedev.plugins.steps.comment_code import CommentCodeStep
from continuedev.src.continuedev.plugins.steps.share_session import ShareSessionStep
from continuedev.src.continuedev.plugins.steps.main import EditHighlightedCodeStep
from continuedev.src.continuedev.plugins.steps.cmd import GenerateShellCommandStep
from continuedev.src.continuedev.plugins.context_providers.diff import DiffContextProvider
from continuedev.src.continuedev.plugins.context_providers.url import URLContextProvider
from continuedev.src.continuedev.plugins.context_providers.terminal import TerminalContextProvider
```

and dropping the `continuedev.src` prefix from all those imports FIXED the persistence situation. I am no longer getting forced resets back to the default `config.py` file every time I close & open VScode. 

```
...
...
...
from continuedev.core.config import CustomCommand, SlashCommand, ContinueConfig
from continuedev.plugins.context_providers.github import GitHubIssuesContextProvider
from continuedev.libs.llm.openai_free_trial import OpenAIFreeTrial

from continuedev.plugins.steps.open_config import OpenConfigStep
from continuedev.plugins.steps.clear_history import ClearHistoryStep
from continuedev.plugins.steps.comment_code import CommentCodeStep
from continuedev.plugins.steps.share_session import ShareSessionStep
from continuedev.plugins.steps.main import EditHighlightedCodeStep
from continuedev.plugins.steps.cmd import GenerateShellCommandStep
from continuedev.plugins.context_providers.diff import DiffContextProvider
from continuedev.plugins.context_providers.url import URLContextProvider
from continuedev.plugins.context_providers.terminal import TerminalContextProvider
```

I am not sure why I ended up in this situation, but I was following the documents and README.md files pretty intently - despite their being some contradictions or mis-matched advices in there.

**Comment by sestinj** [comment]
@cachatj Very sorry this was such a painful experience. I appreciate that you were able to dig in and find the problem, though ideally nobody needs to go through the same!

The problem was a discrepancy between the import paths when running the server manually and when running from the default binary. Luckily we have an update on the way that will fix this, and can be accessed through the pre-release version on the VS Code Marketplace.

We'd also added an auto-migration intended to take care of this exact problem but unfortunately it looks like that didn't work - I will look into this.

Now that you're up and running it sounds like things are going smoothly, but let me know if there's something else!

I'll keep this issue open for others to see until we've made the pre-release version official

**Comment by cachatj** [comment]
nice, glad to hear yall know what it was. 

things have been great otherwise - very impressed, first real time I have dug into local models. Its some how weird to not have them connected to web but provide just as solid responses. 🔥

**Comment by sestinj** [comment]
Glad to hear this! It is quite a surreal experience 😄

**Comment by sestinj** [comment]
Pre-release version is now the official version, which should solve this problem for good, complete with auto-migrations even if something went wrong somehow. Closing the issue, but please open others if you find anything else!
