### ISSUE TITLE
Manually run server undetected on WSL

### ISSUE THREAD

**Issue by selfagency** [continuedev/continue#545]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
- Continue: 0.1.49
- Python: 3.11.5
- IDE: VSCode 1.83.0
```

### Description

I am manually running the Continue server via a systemd process and the VS Code extension is unable to detect it and when I run `lsof` nothing comes up. Downgrading the extension did not resolve.

```sh
❯ lsof -i :65432
```

![image](https://github.com/continuedev/continue/assets/2541728/5f63a28b-bb76-446d-bf0e-cf893dbb012a)

### To reproduce

```
[Unit]
Description=Continue.dev
After=network.target
Wants=network-online.target

[Service]
Restart=always
Type=simple
ExecStart=/home/linuxbrew/.linuxbrew/bin/python3 -m continuedev
Environment=

[Install]
WantedBy=multi-user.target
```

### Log output

```Shell
Oct 11 11:20:47 systemd[1]: Continue.dev.
Oct 11 11:20:48 python3[3745]: [2023-10-11 11:20:48,370] [DEBUG] ------ Begin Logs ------
Oct 11 11:20:49 python3[3745]: INFO:     Started server process [3745]
Oct 11 11:20:49 python3[3745]: INFO:     Waiting for application startup.
Oct 11 11:20:49 python3[3745]: INFO:     Application startup complete.
Oct 11 11:20:49 python3[3745]: INFO:     Uvicorn running on http://127.0.0.1:65432 (Press CTRL+C to quit)
Oct 11 11:20:49 python3[3745]: [2023-10-11 11:20:49,618] [DEBUG] Starting MeiliSearch...
Oct 11 11:20:49 python3[3745]: [2023-10-11 11:20:49,619] [DEBUG] Meilisearch started
```

**Comment by sestinj** [comment]
@selfagency It looks like the problem is unrelated to extension - if we can get lsof to show the process, then the extension should be able to connect.

The server definitely appears to be running on 65432 given the logs you've shared. I assume both the service and lsof are being run on Ubuntu? One possible cause is that the service isn't being run in user space, so you would have to `sudo lsof -i :65432`

**Comment by numsu** [comment]
If you're trying to connect to it from windows, you'll have to open a port.

Elevated powershell:
`netsh interface portproxy add v4tov4 listenport=65432 listenaddress=0.0.0.0 connectport=65432 connectaddress=(wsl hostname -I)`

**Comment by sestinj** [comment]
@selfagency have you had any luck getting the server to connect? I do believe that the above comment is relevant. Let me know if you're still seeing the problem. I'll keep this open for about a week if I don't hear anything

**Comment by sestinj** [comment]
@selfagency we've now completely removed the need for the separate Python server in our newest versions, which means that this error isn't possible
