### ISSUE TITLE
Continue is failing to start in Visual Studio

### ISSUE THREAD

**Issue by deannachurch** [continuedev/continue#548]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS Monterey, version 12.6.7
- Continue: v0.0.412
```

### Description

When I start VSCode, I get the following traceback error. When I click on the link to review the updated config.py, I get a 404
https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/constants/default_config.py

Error in Continue server: [Errno 2] No such file or directory
 Traceback (most recent call last):

  File "continuedev/src/continuedev/server/session_manager.py", line 92, in new_session

  File "continuedev/src/continuedev/core/autopilot.py", line 113, in start

  File "continuedev/src/continuedev/core/sdk.py", line 100, in create
    await sdk.models.start(sdk)

  File "continuedev/src/continuedev/core/models.py", line 106, in start

  File "continuedev/src/continuedev/core/sdk.py", line 131, in start_model
    await llm.start(unique_id=self.ide.unique_id, write_log=self.write_log)

  File "continuedev/src/continuedev/libs/llm/openai_free_trial.py", line 61, in start

  File "continuedev/src/continuedev/libs/llm/proxy_server.py", line 33, in start

  File "continuedev/src/continuedev/libs/llm/__init__.py", line 183, in create_client_session

  File "ssl.py", line 770, in create_default_context

FileNotFoundError: [Errno 2] No such file or directory

### To reproduce

1. Start VSCode

**Comment by sestinj** [comment]
@deannachurch I'm wondering whether this error is a misnomer from the ssl library and it actually indicates a failed SSL connection. Is there anything specific about your environment related to a firewall, proxy, etc. that might be related?

And to be sure, this was immediately upon opening VS Code the first time you installed Continue, and no changes have been made to the config.py?

**Comment by deannachurch** [comment]
I haven't changed anything about my environment (things worked fine on tuesday). The only thing that changed was a VSCode update. I tried to uninstall and reinstall continue to no avail. I've noticed I have to update the config file frequently, but there is a 404 on the link to the example config.py you have so I can't compare- but I haven't touched the config.py since the last time I needed to modify due to an update on your end (a couple of weeks ago). Thanks!

**Comment by brajshoriegzon** [comment]
Having the same issue on MacOS Sonoma 14.0. I've tried reinstalling the extension and  VSCode as well but the issue persists

**Comment by sestinj** [comment]
@deannachurch thanks for the extra info. I'll fix this link for the next release, but [here's](https://github.com/continuedev/continue/blob/main/server/continuedev/libs/constants/default_config.py) the new location

And @deannachurch @brajshoriegzon I've just released a new pre-release version to the VS Code Marketplace (v0.1.22) that makes an additional check to avoid this error. Can either of you confirm that this works?

**Comment by deannachurch** [comment]
Hi- thanks much for the quick response. I just opened VS code and switched to the pre-release version. The link to config.py still gives a 404 (https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/constants/default_config.py). I don't get the traceback error I was getting (that popped up in the main VScode window. When I go to the contrinue window, I get this.

```
Traceback (most recent call last):

  File "server/continuedev/core/sdk.py", line 73, in load

  File "server/continuedev/core/sdk.py", line 253, in _load_config_dot_py

  File "server/continuedev/core/config.py", line 114, in from_filepath

AttributeError: module 'config' has no attribute 'config'
```

Hope that is helpful- and thanks for your work on this.

**Comment by sestinj** [comment]
@deannachurch here is the intended link - I must have not pushed the update when I thought I did. Will make sure it gets in the next release. https://github.com/continuedev/continue/blob/main/server/continuedev/libs/constants/default_config.py

This error seems to indicate that `config` isn't defined in config.py - could you share what your config.py looks like and I can quickly debug?

**Comment by deannachurch** [comment]
Hi-
I've attached a copy of my config.py file where I've just gotten rid of the API keys I put in there.  I also had to change the .py to .txt in order to load it here. On my system it is config.py and it has the API keys specified. Thank you!
[config_nokeys.txt](https://github.com/continuedev/continue/files/12922036/config_nokeys.txt)

**Comment by sestinj** [comment]
@deannachurch Ok thank you I already see the problem! We need to find a better link to share the default config...the file you have is the string representation of the config, but the contents of that string should be the actual config file. 

I've just uploaded a real version to the GitHub repo and will switch to using this link in the error message:

https://github.com/continuedev/continue/blob/main/server/config.py

If you copy this literal thing into config.py, things should work!

**Comment by deannachurch** [comment]
I'm not sure how that happened- or even why things worked as they did for a while- but THANK YOU! Things seem to be humming better now.
