### ISSUE TITLE
Link broken to default config.py

### ISSUE THREAD

**Issue by klauern** [continuedev/continue#552]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
```

### Description

![CleanShot 2023-10-13 at 20 27 21](https://github.com/continuedev/continue/assets/4735/668035ca-6d6d-4b57-b237-dffa258402d3)
The link under `here`, points to https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/constants/default_config.py which doesn't appear to be right.

**Comment by sestinj** [comment]
Thanks! This has been updated in the preview branch and will soon make its way to main.

correct version of the link is https://github.com/continuedev/continue/blob/main/server/continuedev/libs/constants/default_config.py
