### ISSUE TITLE
PostHog API Key Leaked

### ISSUE THREAD

**Issue by aydinnyunus** [continuedev/continue#553]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
https://github.com/continuedev/continue/blob/main/server/continuedev/libs/util/telemetry.py
```

### Description

I found Posthog API Key in : https://github.com/continuedev/continue/blob/main/server/continuedev/libs/util/telemetry.py

 I think API Key is not valid but it should not be in the repository.

### To reproduce

- https://github.com/continuedev/continue/blob/main/server/continuedev/libs/util/telemetry.py

**Comment by sestinj** [comment]
@aydinnyunus thanks for looking out for us! Fortunately, this is a publicly shareable key. You can see [here](https://posthog.com/docs/libraries/js) that PostHog recommends placing these in the <head> section of an HTML page

**Comment by aydinnyunus** [comment]
@sestinj oh okay sorry for the misunderstanding.

**Comment by sestinj** [comment]
No worries! Of the 3 ways to handle a situation where you find a leaked key (1. report, 2. ignore, 3. use key for malicious behavior) you chose the best one, and I really appreciate that : )
