### ISSUE TITLE
QuickTextEntry auto-focus

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#562]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.0.412 and 0.1.27 (Pre-Release)
```

### Description

- the continue.quickTextEntry isn't auto-focusing in the continue extension
- the line `vscode.commands.executeCommand("continue.continueGUIView.focus");` was added with commit 926324cd4843a0476e4be5794e5d00853d455751 and removed a week later with commit c31d7169e651d9fd37cdcaf4d69859d55c5a5e49
  - there was likely a reason for this, I just couldn't figure it out :)

```diff
--- a/extension/src/commands.ts
+++ b/extension/src/commands.ts
@@ -17,6 +17,7 @@ import { acceptDiffCommand, rejectDiffCommand } from "./diffs";
 import * as bridge from "./bridge";
 import { debugPanelWebview } from "./debugPanel";
 import { sendTelemetryEvent, TelemetryEvent } from "./telemetry";
+import { ideProtocolClient } from "./activation/activate";
 
 // Copy everything over from extension.ts
 const commandsMap: { [command: string]: (...args: any) => any } = {
@@ -63,6 +64,17 @@ const commandsMap: { [command: string]: (...args: any) => any } = {
       type: "focusContinueInput",
     });
   },
+  "continue.quickTextEntry": async () => {
+    const text = await vscode.window.showInputBox({
+      placeHolder:
+        "Ask a question, give instructions, or enter a slash command",
+      title: "Continue Quick Input",
+    });
+    if (text) {
+      ideProtocolClient.sendMainUserInput(text);
+    }
+    vscode.commands.executeCommand("continue.continueGUIView.focus");
+  },
 };
 ```

- is it possible for the `continue.quickTextEntry` to focus after a query is entered and the <kbd>⏎ Enter</kbd> key is hit?

---

- if you install version `0.0.134` the focus does work 
```md
  0.0.134            2023-07-08T00:02:53.533Z ✹ 08/Jul/23
```

https://github.com/continuedev/continue/assets/92653266/598716e0-c23b-4bdf-8d4c-edac1ded1661

- in the current version no action
```md
  0.0.412            2023-10-10T02:06:04.28Z ✹ 10/Oct/23
```

https://github.com/continuedev/continue/assets/92653266/333a08d2-86c9-4fb7-a28e-6057852460c6

### To reproduce

1. hide the `Primary Side`
2. press <kbd>⌘ Command</kbd> + <kbd>⇧ Shift</kbd> + <kbd>L</kbd> and enter something
3. press <kbd>⏎ Enter</kbd>
4. notice that the `Continue` extension is not auto-focused, but the query is being processed

**Comment by sestinj** [comment]
@LangLangBart I believe I did this for the sake of /edit queries, where you probably don't want to see the sidebar, but really obvious solution I should have done is just check for /edit. Can fix this by tomorrow!

**Comment by LangLangBart** [comment]
Wow, that was like a speedrun in commenting! 

 <img src="https://github.com/continuedev/continue/assets/92653266/0eaf116f-13e6-4ae6-884a-7f0fd39672cc" width="500">

> Can fix this by tomorrow!

👍

**Comment by sestinj** [comment]
Now ready in the latest pre-release! (0.1.28)

**Comment by LangLangBart** [comment]
> Now ready in the latest pre-release! (0.1.28)

- Thank you. Confirming pressing <kbd>⌘ Command</kbd> + <kbd>⇧ Shift</kbd> + <kbd>L</kbd> auto-focuses on the `codium` extension.

```
0.1.28 Pre-Release  2023-10-18T08:24:22.657Z ✹ 10h ago
```

---

PS: I just noticed since version `0.1.27` that the <kbd>⌥ Option</kbd> + <kbd>⌘ Command</kbd> + <kbd>N</kbd> key combo no longer works in the `preview` version. The issue seemed to have been introduced between  `0.1.27` and  `0.1.26`.

```
  0.1.27 Pre-Release  2023-10-17T22:10:16.317Z ✹ 21h ago
  0.1.26 Pre-Release  2023-10-14T17:23:01.04Z ✹ 14/Oct/23
```

<img src="https://github.com/continuedev/continue/assets/92653266/b554c350-c43d-4c1b-91f2-96402c1d9a51" width="300">

PPS: I will open another ticket, if you can confirm it was unintentional.

**Comment by sestinj** [comment]
Definitely not purposeful. I think I know what caused this, so hopefully another quick fix
