### ISSUE TITLE
Hotkey for new session broken in preview version 0.1.27

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#566]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.1.28
```

### Description

follow up: https://github.com/continuedev/continue/issues/562#issuecomment-1769212955

---

- starting with `0.1.27` the <kbd>⌥ Option</kbd> + <kbd>⌘ Command</kbd> + <kbd>N</kbd> key combo no longer creates a new session

```bash
# 0.1.27 Pre-Release 2023-10-17T22:10:16.317Z ✹ 17/Oct/23
# 0.1.26 Pre-Release 2023-10-14T17:23:01.04Z ✹ 14/Oct/23

git checkout preview
git log --since='2023-10-14T17:23:01.04Z' \
	--until='2023-10-17T22:10:16.317Z' \
	--pretty=format:"%cd  %h  %s" \
	--date=short
#   2023-10-17  70313f89  ci: 💚 Update package.json version [skip ci]
#   2023-10-17  9b2bc9ae  ci: 🏷 Update PyPI version [skip ci]
#   2023-10-17  321d8799  🐛 fix jetbrains input key handling
#   2023-10-17  17954ade  🔥 remove codebase embeddings from default config
#   2023-10-17  89791476  💚 make npm run build work on windows
#   2023-10-17  662c5c4f  💚 remove ci steps for testing
#   2023-10-17  7b9562a6  Merge branch 'preview' of https://github.com/continuedev/continue into preview
#   2023-10-17  80a42c08  💚 log prepackaging error
#   2023-10-17  d253194e  ci: 🏷 Update PyPI version [skip ci]
#   2023-10-16  a0e0803f  💚 update binaries in preview workflow
#   2023-10-16  0752c15c  Initial intelliJ plugin changes to support webview (#457)
#   2023-10-15  2a58779d  ⚡️ debouncing /edit streaming
#   2023-10-15  45d19030  💄 inserting at cursor above input box
#   2023-10-14  1f9b2912  ⚡️ retry for readfile in index generation
```

- the issue starts with the big commit: 0752c15c1a7f03305c8438958ed8d405f79f274e
- there was an oneline change being made in `continue/extension/react-app/src/components/Layout.tsx`
  - see image below, when reverting the line `event.ctrlKey` back to `event.altKey` the issue seems to be fixed 
  - needs investigation why it was changed to begin with
    -  Ref: 7d4f453e

<img src="https://github.com/continuedev/continue/assets/92653266/b156c9d5-02c2-4e47-bb88-f936c10f9953" width="400">

---

PS: Optionally, you could also list all key combinations under the 'FEATURE CONTRIBUTIONS / Commands' section in the extension overview. 
Currently, there are two commands that are not listed:
- the **new session** key <kbd>⌥ Option</kbd> + <kbd>⌘ Command</kbd> + <kbd>N</kbd> and 
- the **stop active step** <kbd>⌘ Command</kbd> + <kbd>⌫ Delete</kbd>

<img src="https://github.com/continuedev/continue/assets/92653266/e0833e7e-ba03-414c-bf1a-8258554cc83b" width="400">

### To reproduce

1. use at least the `preview` version `0.1.27`
2. enter a query in the `continue` extension, try to clear the session with <kbd>⌥ Option</kbd> + <kbd>⌘ Command</kbd> + <kbd>N</kbd>
3. notice the session is not being cleared

**Comment by sestinj** [comment]
Looks like this is the problem! There's a chance this was just the result of a mis-executed find/replace, or just a mistake.

I think it's best (and maybe not possible to without some hacky workaround) not to put cmd+backspace and cmd+option+N in the extension keyboard shortcuts page because these only work through the webview window

**Comment by LangLangBart** [comment]
- I don't have the `intellij-extension` tested, but it seems the line in macOS would then be `first-keystroke="alt meta N"/>`
https://github.com/continuedev/continue/blob/64483c494e4cf6fea2cfeb2440c40dc5a3c8b8da/intellij-extension/src/main/resources/META-INF/plugin.xml#L84-L87

**Comment by LangLangBart** [comment]
> There's a chance this was just the result of a mis-executed find/replace, or just a mistake.

ok. will do a PR

**Comment by LangLangBart** [comment]
v0.1.30
