### ISSUE TITLE
Not able to load files in context for large directories

### ISSUE THREAD

**Issue by klauern** [continuedev/continue#569]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS
- IDE: IDEA Ultimate
- Continue: 0.0.13
```

### Description

I am using the JetBrains plugin for Continue and I think it's pretty good!  That said, I am having trouble loading files into context on some projects.  I am not sure why, but I wonder if it's because it's not filtering based on path or the find filter when typing the filename doesn't resolve.  Here's a screenshot of what I am trying to load.  The `yaml.py` file is in my project's `<module_name>/clients/yaml.py`, but it seems to bring in a lot of similar-but-unrelated files, and I can't select it:

![CleanShot 2023-10-19 at 20 42 37@2x](https://github.com/continuedev/continue/assets/4735/c30ddb0e-a740-4740-9366-b2b96c33be1a)

**Comment by klauern** [comment]
To add to this a bit, I recognized that there's a scrollbar that you can select other files that aren't listed in the first one, but it seems to stop after 10-15 items, none of which match the filename that I am looking for.

**Comment by sestinj** [comment]
@klauern I'm sorry, it seems I completely missed this issue. You can type to search through files.

I'm going to change the description from "Reference files in the current workspace" to "Type to search the workspace" to make this more clear.

Is this enough to clear up the issue?
