### ISSUE TITLE
Show error message when the model fails

### ISSUE THREAD

**Issue by surak** [continuedev/continue#571]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Sometimes the model throws an error code, and all we get at the UI is the error code itself. The message and detail fields are ignored.

![Screenshot 2023-10-20 at 21 07 53](https://github.com/continuedev/continue/assets/878399/60bb61d4-820c-4406-a693-f04dd5ee00c9)

In this example, if I access the server directly via fastapi, I see something different:

![Screenshot 2023-10-20 at 21 09 59](https://github.com/continuedev/continue/assets/878399/6a34d624-60d3-4d2b-9c87-c0b308404311)

Do you thing that the fields "message" or "details" from such return codes would be useful instead of just the error code?

### Solution

Print the fields "message" and/or "details", if they exist, along with the error code.

**Comment by sestinj** [comment]
No doubt this would be useful! We have it set up to show a few more details if you click the red triangle icon on the left. So two possible problems here
1. Not obvious UI
2. I don't know in this case whether the full error logs would actually get shown after clicking, and if not I should of course change this

**Comment by surak** [comment]
How about looking that if there's a message on the return, show it? It's better than the number.

If I am not mistaken, message and details are standard fields, no?

**Comment by Allan2000-Git** [comment]
use exception handling. 

try{
  // code
} catch (error){
 console.log(error.message)
}

this should work

**Comment by sestinj** [comment]
These are now reported in the latest versions as a popup in the lower right corner of VS Code, showing the full error, along with a button to view the full logs.
