### ISSUE TITLE
Support Jetbrains IDE EAP versions e.g. v2023.3

### ISSUE THREAD

**Issue by ciarancourtney** [continuedev/continue#578]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Can't use plugin if using EAP version

### Solution

May just work by bumping `Compatibility Range` to include v2023.3 https://plugins.jetbrains.com/plugin/22707-continue/versions

**Comment by sestinj** [comment]
@ciarancourtney Just updated our plugin.xml, and submitted a new version to the store. I'll let you know once they accept it! Should be by tomorrow morning

**Comment by sestinj** [comment]
@ciarancourtney They did accept the version referenced above, but just to keep you updated I felt that things were a bit buggy and not up to speed with VS Code, so took some time to make a few big reliability changes. New version will probably be out Monday, but I'll let you know!

**Comment by ciarancourtney** [comment]
Any updates here?

**Comment by sestinj** [comment]
@ciarancourtney Yes, sorry we did end up releasing a new version (0.20). The versions accepted in [plugin.xml](https://github.com/continuedev/continue/commit/fe6f945989ecda7da4bb5a8a84f76dfba8e87779) are `<idea-version since-build="223.0" until-build="233.*"/>`.

**Comment by sestinj** [comment]
@ciarancourtney Finally got around to submitting a new version (will likely be ready in the store tomorrow morning) and found the second place that I had missed to update compatibility. This one should be 223+ (so unbounded on the "until" end of the range)

**Comment by sestinj** [comment]
@ciarancourtney closing this issue as it appears to have been resolved. Let me know if you're still seeing any other problems!
