### ISSUE TITLE
Server Binary Build Issue with Python 3.12: Awaiting Fix in Tree-Sitter-Languages Repo

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#580]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- python 3.12
```

### Description

- follow up #579
- building the the server binary from source with `python 3.12` is currently not working
- need to wait for a fix to the issue in the `tree-sitter-languages` repo 

### To reproduce

see description

**Comment by LangLangBart** [comment]
- see https://github.com/grantjenks/py-tree-sitter-languages/issues/30

**Comment by sestinj** [comment]
After the move away from the Python server this issue is no longer applicable

**Comment by LangLangBart** [comment]
I forgot about it, thanks for closing it.
