### ISSUE TITLE
self hosted continue server via fast chat api - failed to register a service worker

### ISSUE THREAD

**Issue by satnair** [continuedev/continue#586]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
Server:Ubuntu
VS code client. - Windows
- Continue:
```

### Description

Hi 

I am trying to host the continue server and service it via fast chat api. Here is what I am seeing. Please help out with thoughts.

VS Code IDE Error:
Error loading web view: Error: Could not register worker: InvalidStateError: Failed to register a serviceworker: The document is in an invalid state.

On the Server side, getting this error:
![image](https://github.com/continuedev/continue/assets/497374/b2e784f7-b3aa-43d1-a153-2dc20c3988b5)

Debug logs:
<img width="477" alt="image" src="https://github.com/continuedev/continue/assets/497374/6f6134f2-a0c4-431c-8c86-d9d7a697b644">

**Comment by sestinj** [comment]
@satnair Could you share which version of the `continuedev` PyPI package you have by running `pip show continuedev`? The latest is 0.1.72 and this is an error I've seen before, so I want to verify whether I've failed to update the package, or whether it might just be out of date
