### ISSUE TITLE
This is a virus.

### ISSUE THREAD

**Issue by JamesFraserLogan** [continuedev/continue#598]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: win 11
- Continue: newest as of today
```

### Description

Even after uninstalling, your two processes "continue" and "meliesearch" (sp) persist. 

By definition, this is malicious and needs to be reported.

If you tell people that your addon installs SPYWARE that runs REGARDLESS OF YOU UNINSTALLING THE ADDON maybe they won't be so keen on using it!!!

Again, this is, by definition A VIRUS!!!!!!!

### To reproduce

Install continue
Uninstall continue
Navigate to Users/myuser/.continue 

See how you can't delete the folder because two processes are STILL RUNNING???? Because this is, by definition, a virus!

**Comment by sestinj** [comment]
@JamesFraserLogan I appreciate you sharing your concern and completely understand why this would be an issue. I'm currently working on improvements to the server startup time that will make it feasible to not run the server even after VS Code has closed.

To give some background on why this is happening, we are currently packaging the server with pyinstaller, which tends to need some time to start. If we were to stop the server and restart whenever VS Code is re-opened, our users would experience delays that we feel are unacceptable. By reducing these delays, we wouldn't have to run in the background.

Again, I'm sorry if this was a major inconvenience for you! I'll give an update if I'm able to resolve the startup time.

**Comment by simpthy** [comment]
Is this the reason comments are blocked on your main Youtube video?
https://www.youtube.com/watch?v=3Ocrc-WX4iQ

**Comment by sestinj** [comment]
@simpthy You're right that I missed a key point. In the `deactivate()` callback of the VS Code API, there's not currently a way to tell whether the extension was uninstalled or the window is just closing. If there was we would absolutely stop the server upon uninstallation (and you've inspired me to take a deeper look, perhaps there is a workaround)

Again, I'm working on figuring this out, most certainly agree about what would be ideal behavior, and am hopeful we'll find a solution that makes the right tradeoff

**Comment by jhallas** [comment]
> @JamesFraserLogan I appreciate you sharing your concern and completely understand why this would be an issue. I'm currently working on improvements to the server startup time that will make it feasible to not run the server even after VS Code has closed.
> 
> To give some background on why this is happening, we are currently packaging the server with pyinstaller, which tends to need some time to start. If we were to stop the server and restart whenever VS Code is re-opened, our users would experience delays that we feel are unacceptable. By reducing these delays, we wouldn't have to run in the background.
> 
> Again, I'm sorry if this was a major inconvenience for you! I'll give an update if I'm able to resolve the startup time.

What is the startup time?  Btw if you package it as a single exe file rather than in a folder it will be cleaner but result in longer startup time because that exe first gets extracted to a temp folder where it is run from. (As far as I remember)

**Comment by sestinj** [comment]
@jhallas Depends on OS, but sometimes >20 seconds. And yeah, we're currently packaging in single file mode (with pyinstaller) because the unzipped version takes up 3x the space. Working on cutting down dependencies, but this is essentially the tradeoff I'm trying to optimize.

**Comment by jhallas** [comment]
@sestinj Do you have a hard cut-off for file-size to upload?  Maybe you don't need to re-extract if it doesn't go to a temp folder every time? https://pyinstaller.org/en/latest/usage.html#defining-the-extraction-location.  Not sure if that helps or if it would just re-extract every time.  An alternative could be something like a 7zip self extracting executable (or just distribute the zip and have unzipping be part of install?).  I do notice that meilisearch does not seem to be a pyinstaller executable: is the issue only with continue_server?

**Comment by sestinj** [comment]
@jhallas Yeah, only with the continue_server.

Thanks for the recommendation! This might actually be a solution as long as pyinstaller has the option to reuse the extracted folder. (continue_server is in fact a self extracting executable)

**Comment by TyDunn** [comment]
> This combined with blocking comments on your main Youtube video seems very fishy.
https://www.youtube.com/watch?v=3Ocrc-WX4iQ

@simpthy Thanks for pointing out that comments were turned off! This happened because the video was accidentally set to "Yes, it's made for kids", which disabled comments by default. I have fixed that, so commenting is now possible 👍

**Comment by bioshazard** [comment]
Processes can run in memory even with the file deleted. Good on this team for responding politely.

**Comment by jocot** [comment]
It's the meilisearch process that remains running.

Might be helpful to include that it's being used and its purpose, and how to start/stop any background processes in the readme.

**Comment by sestinj** [comment]
thanks @jocot, this is a good idea. Just added it to the readme and will push that in our next version

**Comment by sestinj** [comment]
Thank you to everyone who shared ideas here. Excited to share that we are no longer using the Python binary at all, which means that Continue runs as a self-contained extension without any extra process. I hope that this takes away the potential mystery of the Python executable and makes Continue much more accessible.

**Comment by arjan2022** [comment]
this has happened to me as well. I have uninstalled this addon many times and it is still there.

**Comment by AayushSameerShah** [comment]
Woah! I had to unsintall VS code and then install it again. Is it solved yet???

**Comment by sestinj** [comment]
@AayushSameerShah thank you for sharing the screenshot, this is something we take quite seriously, so if you have the time, it would be very helpful to know more about the setup that you're working with.

To the very best of our knowledge, the concerns originally shared in this issue have been solved for more than a year, however I understand that in the case of having downloaded a much older version of the extension you might still experience older behaviors.

Is there any chance you could share more information about the version of the Continue extension that you have installed, what the eScan is telling you, and perhaps when you originally installed the Continue extension?

If you are using a version more than a year old (which would have to be manually picked out from a very long list of extension versions), then Continue will come with a locally running Python server that handles much of the logic of the extension. While no dangers exist, we heard feedback that it was confusing and so we undertook a major effort to make our extension run entirely in the normal VS Code Node runtime
