### ISSUE TITLE
Improve telemetry opt out experience

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#60]
Right now, the docs say "Create a `continue.json` file in the root of your workspace and add the following..." [here](https://continue.dev/docs/telemetry)

However, it's not clear what is meant by the root of your workspace and it's not transparent that telemetry was on in the first place if you only look at the code. 

Therefore, I think there should always be a `continue.json` file with `allow_anonymous_telemetry` set to true by default and this docs section should be updated to tell you exactly where that file is located

**Comment by sestinj** [comment]
Now on startup the .continue folder is automatically created with a config.json and allow_anonymous_telemetry = true. As we expand the options, I'll have the file created with many of them either existent or commented out.

**Comment by TyDunn** [comment]
This is an improved approach! Updated docs to reflect it
