### ISSUE TITLE
Template texts are evaluated in ollama

### ISSUE THREAD

**Issue by mrdunski** [continuedev/continue#601]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: KDE neon 5.27 (ubuntu 22.04)
- Continue: 0.0.14
- ollama: 0.1.7
- IDE: IntelliJ IDEA 2023.2.4
```

### Description

 Code generation fails: Ollama returned an error: {"error":"template: :1: function \"default\" not defined"}

### To reproduce

```
-> Create a deployment template for helm chart. Use image: `"{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"`
<- Ollama returned an error: {"error":"template: :1: function \"default\" not defined"}
```

**Comment by sestinj** [comment]
@mrdunski Just found the solution to this, it will be in the next release, and I'll let you know once that's ready

**Comment by sestinj** [comment]
@mrdunski this is now ready in the pre-release (0.3.8 and up). Let me know if you're experiencing any other issues!

**Comment by mrdunski** [comment]
@sestinj  I don't really know how to run it. I've started continue server from main, and I still get errors like:
```
[2023-11-08 11:05:52] [ERROR] Error while running step: 
Ollama returned an error: {"error":"template: :6: function \"include\" not defined"}
Invalid request to Ollama
```

I suppose you mean some other version or something different.

**Comment by sestinj** [comment]
@mrdunski The pre-release comes from the `preview` branch, or in VS Code you can download in the extensions tab by clicking "Switch to Pre-Release"
