### ISSUE TITLE
Error in Continue server: No such file or directory (py files missing)

### ISSUE THREAD

**Issue by scpedicini** [continuedev/continue#602]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 12.6.8 (M1)
- Continue: 0.0.14
IDE: Jetbrains Webstorm 2023.4 (Latest)
```

### Description

Installed plugin a few days ago and was working perfectly for a while. Booted up Webstorm (tried a few different projects) and constantly throws this error on loading the project:

```
Error in Continue server: [Errno 2] No such file or directory
Traceback (most recent call last):  
File "server/continuedev/server/session_manager.py", line 92, in new_session  
File "server/continuedev/core/autopilot.py", line 127, in start  
File "server/continuedev/core/autopilot.py", line 106, in load  
File "server/continuedev/core/sdk.py", line 124, in create  
File "server/continuedev/core/sdk.py", line 94, in load  
File "/var/folders/z4/z9_0j04x72jf0h1ldmxf8hl80000gn/T/_MEIQWpJMi/continuedev/core/models.py", line 106, in start  
File "server/continuedev/core/sdk.py", line 136, in start_model  
File "/var/folders/z4/z9_0j04x72jf0h1ldmxf8hl80000gn/T/_MEIQWpJMi/continuedev/libs/llm/openai_free_trial.py", line 61, in start  
File "/var/folders/z4/z9_0j04x72jf0h1ldmxf8hl80000gn/T/_MEIQWpJMi/continuedev/libs/llm/proxy_server.py", line 33, in start  
File "/var/folders/z4/z9_0j04x72jf0h1ldmxf8hl80000gn/T/_MEIQWpJMi/continuedev/libs/llm/base.py", line 217, in create_client_session
File "ssl.py", line 766, in create_default_context  
FileNotFoundError: [Errno 2] No such file or directory
```

At this point the plugin won't work, attempting to type any questions into the sidebar Continue textarea results in:
```
'NoneType' object has no attribute 'stream_chat'
```

### Log output

Attempting to view Continue specific logs results in 'Action not yet implemented' message in Jetbrains. The Jetbrains logs folder does not have this file either.

**Comment by sestinj** [comment]
Thanks for sharing this. It's something I fixed in VS Code but haven't yet gotten published in a new IntelliJ version. I'll let you know as soon as it's ready!

**Comment by scpedicini** [comment]
Thanks! Anything I can do in the meantime to workaround this? Incidentally, I do see that continue created a user directory under `~/.continue`. Is it possible for me to start the backend server independently of Jetbrains using my global installed Python 3x distro and then point the Jetbrains extension at it?

**Comment by bainternet** [comment]
any updates on this??
or at least anything we can do on our end for now?

**Comment by sestinj** [comment]
@scpedicini There's now a new extension version ready (0.16) that I believe will solve this, but yes! It is also an option to run the server manually. There's a quick walkthrough [here](https://continue.dev/docs/walkthroughs/manually-run-continue#recommended-use-the-continuedev-pypi-package), but basically you can `pip install continuedev`, `python -m continuedev` to start the manual server. You'll want to go to IntelliJ settings -> Tools -> Continue and select the box for "Manually Running Server" so that the extension doesn't try to start the binary on its own. Then just give the window a reload

**Comment by sestinj** [comment]
@bainternet 0.16 should solve many of these errors - were you seeing the exact same one?

**Comment by sestinj** [comment]
Going to close this issue since it has been solved in my testing, but if I've missed something please feel free to re-open!
