### ISSUE TITLE
Continuous Triggering of inputRef.current.focus()

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#606]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.3.7
- VSCode: 1.84.0
```

### Description

While I have to wait for the respone to be finished, the interaction with anything else in VSCode is impossible.

### bisect
- issue was introduced with a37e8898

```diff
--- a/gui/src/components/ComboBox.tsx
+++ b/gui/src/components/ComboBox.tsx
@@ -330,9 +330,7 @@ const ComboBox = React.forwardRef((props: ComboBoxProps, ref) => {
   const workspacePaths = useSelector(
     (state: RootStore) => state.config.workspacePaths
   );
-  const sessionHistory = useSelector(
-    (state: RootStore) => state.sessionState.history
-  );
+  const sessionState = useSelector((state: RootStore) => state.sessionState);
 
   const [history, setHistory] = React.useState<string[]>([]);
   // The position of the current command you are typing now, so the one that will be appended to history once you press enter
@@ -675,6 +673,10 @@ const ComboBox = React.forwardRef((props: ComboBoxProps, ref) => {
     };
   }, []);
 
+  const persistSession = useCallback(() => {
+    client?.persistSession(sessionState, workspacePaths[0] || "");
+  }, [client, sessionState, workspacePaths]);
+
   useEffect(() => {
     if (!inputRef.current || !props.isMainInput) {
       return;
@@ -695,6 +697,7 @@ const ComboBox = React.forwardRef((props: ComboBoxProps, ref) => {
         dispatch(setTakenActionTrue(null));
       } else if (event.data.type === "focusContinueInputWithNewSession") {
         client?.stopSession();
+        persistSession();
         dispatch(newSession());
         dispatch(setTakenActionTrue(null));
       }
@@ -703,7 +706,7 @@ const ComboBox = React.forwardRef((props: ComboBoxProps, ref) => {
     return () => {
       window.removeEventListener("message", handler);
     };
-  }, [inputRef.current, props.isMainInput]);
+  }, [inputRef.current, props.isMainInput, persistSession]);
 
   const deleteButtonDivRef = React.useRef<HTMLDivElement>(null);
 ```

The persistSession function is wrapped in a useCallback hook, with sessionState
as one of its dependencies. Therefore, the persistSession function is recreated whenever the state
updates. Moreover, persistSession is a dependency in the useEffect, which continuously triggers
`inputRef.current.focus()`.

https://github.com/continuedev/continue/blob/a8d6ff04e43a81a3c76373469ffebdfcfa8ac9f2/gui/src/components/ComboBox.tsx#L678-L707

### To reproduce

1. Write a question in Continue and hit <kbd>⏎ Enter</kbd>.
2. While the response is being generated, attempt to interact with VSCode, such as entering a command in the terminal.
3. Observe that every time you try to input something, your cursor focus is automatically redirected back into the 'Continue' textarea, as long as the response is being written.

**Comment by sestinj** [comment]
Quick fix, thank you. Publishing in pre-release now and then straight to main along with some other fairly critical fixes

**Comment by LangLangBart** [comment]
0.3.8 Pre-Release   2023-11-07T02:12:17.16Z ✹ 13h ago
