### ISSUE TITLE
Inversión en bienes raíces 

### ISSUE THREAD

**Issue by leodanys81** [continuedev/continue#607]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

**Comment by surak** [comment]
Is this spam?

**Comment by sestinj** [comment]
As far as I can tell this means "real estate investment?"

@leodanys81 Could you elaborate a bit on your issue? At the current level of detail, I will probably close this issue as it isn't actionable.

**Comment by sestinj** [comment]
Closing this issue, but if there are additional updates don't hesitate to re-open

**Comment by webknjaz** [comment]
FTR that is a relatively fresh empty account that also spammed us @ https://github.com/vshymanskyy/StandWithUkraine/issues/256.
