### ISSUE TITLE
Disabled context

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#608]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.3.10 Pre-Release  2023-11-07T07:38:45.02Z
```

### Description

The commit 08358a1b introduced a new option, `disable_indexing`. If a user sets this to `True` and then makes a request using some highlighted code added with <kbd>⌘ Command</kbd> + <kbd>M</kbd>, the code will not be included in the query and the returned result will be empty.

- `config.py`
```py
config = ContinueConfig(
    disable_indexing=True,
    …
)
```

### To reproduce

1. Highlight a portion of the code.
2. Press <kbd>⌘ Command</kbd> + <kbd>M</kbd>
3. Ask a question about the selected code.
4. Observe the response indicating no code was highlighted.

**Comment by LangLangBart** [comment]
https://github.com/continuedev/continue/blob/50c243a23c5500437a9e3ea339115f1742b227b8/server/continuedev/server/window_manager.py#L125-L135

**Comment by sestinj** [comment]
@LangLangBart thanks, this was a quick fix for another problem, I see the bug here though. Will fix for next release

**Comment by sestinj** [comment]
Solution is to move this check into `ContextManager.start` so that the providers are initialized, but not indexed

**Comment by LangLangBart** [comment]
0.3.13 Pre-Release  2023-11-07T20:55:39.627Z
