### ISSUE TITLE
Jira Context Provider

### ISSUE THREAD

**Issue by p91paul** [continuedev/continue#615]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Solution

Please provide a Jira Context Provider, similar to the Github context provider to retrieve context from Jira issues. Ideally, both Cloud and Server/Datacenter Jira instances should be supported.

**Comment by sestinj** [comment]
@p91paul I like the idea - curious about something else as well - would you be interested in not just a "read" action (context provider) but a slash command that could _write_ a Jira ticket for you?

**Comment by p91paul** [comment]
I did not think about it, what would it be capable of? just creating tickets with my input, or would in enrich them with additional info?

**Comment by sestinj** [comment]
I haven't yet looked into what the Jira API allows, but probably could generate title, body, metadata, maybe select a few relevant files, and create a draft for you to review. Just an idea. Curious if a painful amount of time is spent doing this, or if it wouldn't be so huge a help

**Comment by p91paul** [comment]
I do not think it would be a game changer. Jira is not a tool, it's a framework on which you build a tool. TL;DR: the more painful it is to create a jira issue, the more unlikely it is a generic tool will be able to solve the problem :)

Organization have all sorts of custom fields that might or not be mandatory, validations, automations, internal rules, etc. Reading data from a few standard fields to create context should be fine, but creating an issue might be more complicated.

For a specific company, a tool able to categorize unstructured text into its structured way of representing an issue, with all custom fields, components, labels respecting all conventions could have value... but every company would need to fine-tune their model on their fields and categories I think.

**Comment by sestinj** [comment]
@p91paul we now have a Jira context provider!: https://continue.dev/docs/customization/context-providers#jira-issues
