### ISSUE TITLE
feedback on settings and credentials approach

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#62]
Right now, there is a `continue.json` for settings  / configuration. Can we rename this to `config` to make it more clear what it is for and make it a yaml or toml file since developers will be manually editing it and that is much easier to work with in an editor than json?There is also `.env` for API keys somewhere that is unclear. Can we rename this to `credentials.toml` or `secrets.toml`? And place it somewhere sensible, so developers can find and edit it when needed? Maybe we also just pick one file type for both so if someone is unfamiliar they don't have to learn two new file types? Also, can both files exist by default, so users don't have to figure out where to create them and can just edit them as needed (and we can make sure that credentials are gitignored)?

**Comment by sestinj** [comment]
On the credentials side, I made it so these are entered and stored through VS Code settings. Safer, more intuitive, and Marcin expected it. I also prefer.

On the other, how would you feel about naming it config.json and placing it in a .continue folder in the root of the workspace? (by workspace I mean the top level folder of the VS Code window you have open. This is a VS Code concept that permeates pretty deeply and I'm trying to mirror their .vscode folder)

**Comment by TyDunn** [comment]
@sestinj We should strive to provide the best UX while simplifying how much code we need to maintain, how much docs (and other education materials) we need to maintain, and how much developers need to learn to be successful with Continue across all the places it will exist. In some cases, perhaps it makes sense to use VS Code / Codespaces native things and accept the maintence costs of having a unique way of doing it there (e.g. how credentials are handled). That said, in many other places, we should avoid it (e.g. we should not require people to understand a VS Code concept like workspace)
