### ISSUE TITLE
Problems using Local model with llama_cpp_python[server]

### ISSUE THREAD

**Issue by acd424** [continuedev/continue#620]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MAC os 13.0 (22A380)
- Continue: 0.6.0
- llama_cpp_python 0.2.17
- model "models/codellama-13b.Q4_K_M.gguf"
```

### Description

I have installed continue with VS code and it worked well. 

I then tried to use a local model using the server function of llama_cpp_python.

I changed the continue config file to account for this: 

```
from continuedev.libs.llm.llamacpp import LlamaCpp

config = ContinueConfig(
    allow_anonymous_telemetry=True,
    models=Models(
        default=LlamaCpp(max_context_length=4096, server_url="http://localhost:8080")
    )
```

However I get the following error message when I try to use the model with continue

 ```
 File "/var/folders/3q/nv3m69nx4kdfvz9byqd9fbk80000gn/T/_MEIXSUcVo/continuedev/libs/llm/llamacpp.py", line 83, in server_generator
    yield json.loads(content[6:])["content"]
          ^^^^^^^^^^^^^^^^^^^^^^^

  File "json/__init__.py", line 346, in loads

  File "json/decoder.py", line 337, in decode

  File "json/decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

### To reproduce

use llama_cpp_python server, change config file then use continue in VS code

### Log output

```Shell
[2023-11-12 23:05:00] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "server/continuedev/core/autopilot.py", line 221, in _run_singular_step

  File "server/continuedev/plugins/steps/chat.py", line 55, in run

  File "/var/folders/3q/nv3m69nx4kdfvz9byqd9fbk80000gn/T/_MEIXSUcVo/continuedev/libs/llm/base.py", line 483, in stream_chat
    async for chunk in self._stream_complete(prompt=prompt, options=options):

  File "/var/folders/3q/nv3m69nx4kdfvz9byqd9fbk80000gn/T/_MEIXSUcVo/continuedev/libs/llm/llamacpp.py", line 85, in _stream_complete
    async for chunk in server_generator():

  File "/var/folders/3q/nv3m69nx4kdfvz9byqd9fbk80000gn/T/_MEIXSUcVo/continuedev/libs/llm/llamacpp.py", line 83, in server_generator
    yield json.loads(content[6:])["content"]
          ^^^^^^^^^^^^^^^^^^^^^^^

  File "json/__init__.py", line 346, in loads

  File "json/decoder.py", line 337, in decode

  File "json/decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0)
```

**Comment by sestinj** [comment]
@acd424 The LlamaCpp class is intended for the built-in server with the llama.cpp repository, which is different from the llama_cpp_python server. Try setting up your config to look like this:

```python
from continuedev.libs.llm.openai import OpenAI

config = ContinueConfig(
    allow_anonymous_telemetry=True,
    models=Models(
        default=OpenAI(context_length=4096, api_base="http://localhost:8080", api_key="EMPTY")
    )
```

Also very aware that this probably wasn't the most obvious setup process. We're actually trying to do an overhaul of this in the next few days so if there was anything in particular about it that was confusing, or if you had any "I'd change this if I had a magic wand" ideas, let me know : )

**Comment by acd424** [comment]
> @acd424 The LlamaCpp class is intended for the built-in server with the llama.cpp repository, which is different from the llama_cpp_python server. Try setting up your config to look like this:
> 
> ```python
> from continuedev.libs.llm.openai import OpenAI
> 
> config = ContinueConfig(
>     allow_anonymous_telemetry=True,
>     models=Models(
>         default=OpenAI(context_length=4096, api_base="http://localhost:8080", api_key="EMPTY")
>     )
> ```
> 
> Also very aware that this probably wasn't the most obvious setup process. We're actually trying to do an overhaul of this in the next few days so if there was anything in particular about it that was confusing, or if you had any "I'd change this if I had a magic wand" ideas, let me know : )

That worked. Thanks. Apart from that issues I think the process was pretty clear. Although I do seem to have to shut down and reopen VS code every time I change the config file rather than just start a new session. In terms of changing the only thing that would be nice would be a token counter so it's easier to track the context going into the LLM.

Its really good though - thanks for building it.

**Comment by sestinj** [comment]
@acd424 Glad it worked! I'm updating how we load config files today, so I'll make sure to fix whatever issues there might have been with auto-reloading (you're supposed to be able to just save config.py and have the UI automatically update, might just not always be working).

And actually really like the token counter idea. The closest we have right now is a) a warning symbol that will show up if you are approaching the context limit and b) an "Inspect Prompt" button that will show you the exact input that was given to the LLM (if you hover an old input box it's an arrow pointing up and left)

I'm going to close this issue since the core problem is solved, but keep an eye out for improvements to these items!
