### ISSUE TITLE
Temperature minimum value

### ISSUE THREAD

**Issue by pechaut78** [continuedev/continue#623]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi,

I can not set a temperature of 0.001 for instance, as the step of the slider is 0.1 and I can set a temperature of 0 which is an invalid value

**Comment by sestinj** [comment]
@pechaut78 OpenAI allows 0 as a value. While it's possible they are converting this to a small number to avoid the $e^{-1/T}$ division by zero, I think it is fairly common for users to want to just set it to zero without thinking about this. Are you running into a problem with a provider that throws an error on a value of zero?

As far as the 0.001, we have to set the step limit somewhere and two decimal places seems like the most natural place. If you want to use a more fine-grained value, you can set this through the config file. (which, as of the latest pre-releases, will be in ~/.continue/config.json)
