### ISSUE TITLE
Top_p Top_K values are mixed ?

### ISSUE THREAD

**Issue by pechaut78** [continuedev/continue#624]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:windows
- Continue:latest
```

### Description

When definig a custom LM Studio Model, I try to set to_k to 40 but it goes red and only accepts values between 0 and 1 which is, correct me if I'm wrong, correct for top_p but not top_k

**Comment by sestinj** [comment]
@pechaut78 You are correct! I've updated this and it will be ready in the next version to be released
