### ISSUE TITLE
'NoneType' object has no attribute 'getHighlightedCode'

### ISSUE THREAD

**Issue by behnamazimi** [continuedev/continue#626]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: 0.0.18
- IDE: Jetbrains Webstorm 2023.2.5
```

### Description

Hey! I get this error when I use I use `/edit` command.

> Traceback (most recent call last):
> 
>   File "server/continuedev/core/autopilot.py", line 221, in _run_singular_step
> 
>   File "server/continuedev/plugins/steps/main.py", line 311, in run
> 
> AttributeError: 'NoneType' object has no attribute 'getHighlightedCode'
> + Add Context

**Comment by sestinj** [comment]
@behnamazimi Thanks for sharing this. Does it happen every single time you use /edit or only sometimes?

**Comment by behnamazimi** [comment]
> @behnamazimi Thanks for sharing this. Does it happen every single time you use /edit or only sometimes?
> 
> 

Hey, 
It happens every time I use `/edit`.

**Comment by sestinj** [comment]
@behnamazimi We've made many changes since this issue was brought up, which with certainty does not allow this exact error to occur. If you come across other problems, please open a fresh issue : )
