### ISSUE TITLE
Unable to Stop Continue Server (besides directly killing process)

### ISSUE THREAD

**Issue by kidusnegesse** [continuedev/continue#628]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I installed Continue in VSCode to test it out for my workflow. It's really neat! But sadly, since I use an aging computer, it was making my fans spin since I was also doing a lot of other things (I understand why it's resource-intensive, so this isn't a ding on performance, but it's a reality I have to work with):

<img width="843" alt="Screen Shot 2023-11-15 at 15 17 48" src="https://github.com/continuedev/continue/assets/41457482/0439ce29-0690-4436-add5-f5c584b5a197">
<img width="838" alt="Screen Shot 2023-11-15 at 15 25 58" src="https://github.com/continuedev/continue/assets/41457482/2ec0df42-613a-4a9b-9a46-17b38dbf2f50">

I still want to use Continue but want to be able to stop/start the Continue server so I can choose when I want to use it. 

- Can't find any way to stop Continue in its VSCode panel or settings
- I tried disabling the Continue extension entirely on its VSCode extension page, but that didn't kill the process
- Reloading VSCode didn't stop it
- Quitting VSCode didn't stop it

So I had to resort to directly killing the process. This is disruptive for my workflow, and moreover don't see a reason why the server continues to operate even when the extension has been disabled and VSCode isn't running. 

### Solution

An option in the settings of the extension to stop the Continue server.

**Comment by sestinj** [comment]
@kidusnegesse We're currently working on a solution to automatically stopping the server, but in the meantime one way to stop it would be
1. Find the process ID (PID) with `lsof -i :65432`
2. Kill the process with `kill <PID>`

Are you finding that Continue is resource intensive only when it is indexing, or is it always problematic?

If the former, you can optionally disable indexing by setting `disable_indexing=True` in `~/.continue/config.py`.

If the latter, I wouldn't expect this so maybe there's something we can do to improve

**Comment by sestinj** [comment]
@kidusnegesse the Continue Python server is no longer used at all, which means there is no process to kill
