### ISSUE TITLE
Improve VS Code command approach

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#63]
Right now, to open the `Continue GUI` in VS Code, you need to open the command pallet with `cmd+shift+p` and then select `Continue: Open Debug Panel`. When a user sees this, we are going to confuse them... What is a Continue Debug Panel? How is that the same or different than the Continue GUI? Why are there so many other commands? How come there is no documentation about what these commands do?

**Comment by sestinj** [comment]
Changed to "Open Continue GUI". It should open automatically on startup, can also be opened with cmd+k. We can also consider the left panel ("explorer")
