### ISSUE TITLE
Cmd + M pasting incorrect information for .ipynb

### ISSUE THREAD

**Issue by daanvdweijden** [continuedev/continue#633]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14.1
- IDE: VSCode 1.84.2
```

### Description

Using cmd+M will copy the code as it appears in the notebook skeleton, instead of the code that is highlighted in the cell. It shows the correct code in the GUI, but the model receives the raw skeleton code. 

### To reproduce

1. Highlight code in notebook, and press cmd+M
<img width="502" alt="image" src="https://github.com/continuedev/continue/assets/50364399/aa2ff5fa-8d37-4d3b-9271-9aea1de95fff">

2. See it appear in the GUI as intented.
<img width="431" alt="image" src="https://github.com/continuedev/continue/assets/50364399/433b0164-9346-48e2-95d4-100cc100d73e">

3. Run inference on model, the incorrect information is put through. The information provided to the model is equal to the raw notebook editor code. 
<img width="431" alt="image" src="https://github.com/continuedev/continue/assets/50364399/ff62e80e-9057-4c7c-8ae2-7b6b0f09573b">
<img width="548" alt="image" src="https://github.com/continuedev/continue/assets/50364399/cf2d5c08-8445-4f60-9413-fdca956c4876">

**Comment by sestinj** [comment]
Looks like we need to do something special to keep track of lines in an ipynb since vscode reports the line only in the current cell. I'll let you know, hopefully in the next couple days, about progress on this.

**Comment by sestinj** [comment]
thx for the reminder - I just made a fix. Only limitation is that if you update the code in that range, then the context item won't include the fresh contents, but this is mostly okay given an update we're going to make soon to how context is managed

**Comment by sestinj** [comment]
(fix is being published now, [here](https://github.com/continuedev/continue/actions/runs/6974095932), will be in the next pre-release)
