### ISSUE TITLE
Error: 'IdeProtocolServer' object has no attribute 'unique_id' with GPT-3.5-Turbo from AzureAI API

### ISSUE THREAD

**Issue by FPrz** [continuedev/continue#634]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue:v0.6.3
- IDE: VSCode 1.84.0
```

### Description

Hello, 
With a GPT-3.5-Turbo model from AzureAI API, I get this issue when I try to use any "/" Continue function. But when I ask something directly to Continue without "/", I get an answer from Continue. I didn't see anyone having the same issue...

[2023-11-17 15:50:01] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "server\continuedev\core\autopilot.py", line 221, in _run_singular_step

  File "server\continuedev\core\steps.py", line 766, in run

  File "server\continuedev\core\steps.py", line 391, in stream_rif

  File "server\continuedev\core\steps.py", line 248, in get_prompt_parts

  File "server\continuedev\core\sdk.py", line 83, in start_model

AttributeError: 'IdeProtocolServer' object has no attribute 'unique_id'

'IdeProtocolServer' object has no attribute 'unique_id'

Thanks in advance!

**Comment by sestinj** [comment]
Hi @FPrz, thanks for sharing this, it was a quick fix and I'll have it ready in the next release today. Will update you once that's ready!

**Comment by FPrz** [comment]
Hi @sestinj! Do you have news from this fix? I just tried again and I still get the same error... Thanks in advance!

**Comment by sestinj** [comment]
@FPrz sorry I didn't update you. It might have been on the pre-release only at the time when you tried. I just updated the main version to 0.6.5 this morning. Can you let me know if you're still seeing it there?

**Comment by FPrz** [comment]
@sestinj I updated Continue and now it works! It seems that it is better with the config.json file instead of the previous python config file. 
Thanks for your support!

**Comment by sestinj** [comment]
Glad to hear it!!
