### ISSUE TITLE
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for

### ISSUE THREAD

**Issue by MrChen2510** [continuedev/continue#640]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Microsoft Windows 11
- Continue:0.6.4
- Python:3.9.13
- IDE:VSCode latest
- llama.cpp:latest 13B-Instruct
```

### Description

I configured llama.cpp/server http:\\x.x.x.x and opened port 8080 in the remote server, and then I tried to access it from continue in the local VSCode.
I configured config.json according to the instructions and was ready to use it. But continue does not show any result.
![error](https://github.com/continuedev/continue/assets/74651204/fc55bbad-7d8d-4e1c-9e48-370705261a52)
And I found aiohttp error in the log: aiohttp.client_exceptions.ClientOSError:[Errno None] Can not write request body for http://x.x.x.x: 8080/completion.
By the way, I noticed that I can't find any aiohttp related files in the local system, but I can see the aiohttp related files in the tracebacks logs and the final error reported is aiohttp.client_exceptions.ClientOSError.
Is the lack of aiohttp files causing this issue or is the Has the aiohttp been integrated into another file?

### Log output

```Shell
[2023-11-23 11:06:53] [INFO] Meilisearch started at http://localhost:7700
[2023-11-23 11:07:15] [INFO] There are 1 sessions currently open
[2023-11-23 11:07:16] [INFO] Loaded Meilisearch index in 0.370 seconds
[2023-11-23 11:09:19] [DEBUG] Health check
[2023-11-23 11:09:54] [INFO] There are 1 sessions currently open
[2023-11-23 11:09:54] [INFO] Loaded Meilisearch index in 0.346 seconds
[2023-11-23 11:12:47] [INFO] There are 1 sessions currently open
[2023-11-23 11:12:47] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "aiohttp\client_reqrep.py", line 625, in write_bytes

  File "aiohttp\payload.py", line 245, in write

  File "aiohttp\http_writer.py", line 115, in write

  File "aiohttp\http_writer.py", line 75, in _write

ConnectionResetError: Cannot write to closing transport


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "server\continuedev\core\autopilot.py", line 217, in _run_singular_step

  File "server\continuedev\plugins\steps\chat.py", line 54, in run

  File "server\continuedev\libs\llm\base.py", line 402, in stream_chat

  File "server\continuedev\libs\llm\llamacpp.py", line 82, in _stream_complete

  File "server\continuedev\libs\llm\llamacpp.py", line 70, in server_generator

  File "aiohttp\client.py", line 1187, in __aenter__

  File "aiohttp\client.py", line 601, in _request

  File "aiohttp\client_reqrep.py", line 965, in start

  File "aiohttp\streams.py", line 622, in read

  File "asyncio\futures.py", line 287, in __await__

  File "asyncio\tasks.py", line 349, in __wakeup

  File "asyncio\futures.py", line 203, in result

aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://10.167.48.16:8080/completion

[Errno None] Can not write request body for http://x.x.x.x:8080/completion
```

**Comment by sestinj** [comment]
@MrChen2510 aiohttp is being used in continuedev/libs/llm/base.py to create the session, and then this session is used in continuedev/libs/llm/llamacpp.py, which matches this traceback.

Are you running the `python -m continuedev` manually? I'm wondering whether this is a versioning issue that could be resolved by using a virtual environment or different python version.

The other thing I could check is your config.py/config.json if you wanted to share this - that way I could do some testing on my own to try and replicate

**Comment by MrChen2510** [comment]
The local environment is limited because it is a corporate environment, changing the virtual environment is more difficult, but I will try that.
I'm not executing it manually, I'm executing it directly by running the continue plugin in Vscode, and the continue service should be working fine in my opinion.
And in the attachment this is my config.json file. 
Thanks!
[config.json](https://github.com/continuedev/continue/files/13454115/config.json)

**Comment by MrChen2510** [comment]
There is an another question, I don't have any local "aiohttp" related files, why does Traceback show a record like File "aiohttp\client.py"?

**Comment by sestinj** [comment]
It shows aiohttp because they are a part of a library that Continue uses. Most of what is shown there would be from the Continue source code / libraries, packaged in our binary.

Nothing looks wrong in your config file to me. From a bit of research there's some chance that this happens if multiple requests are made in a short period of time. I'm wondering if "disable_summaries": true in config.json would solve anything.

Also want to make sure: this is happening on every single request, right?

If the above isn't a solution I can try "force closing" TCP Connectors. Slightly a shot-in-the dark solution.

Another thing to try might be checking whether you are able to make the same request from a blank python file. (https://github.com/continuedev/continue/blob/f1a4ca81ba5172edd2448491af1dc28d9f175429/server/continuedev/libs/llm/llamacpp.py#L70)

**Comment by MrChen2510** [comment]
Yes, this problem happens every time. Can I ask you for more details on what ports are used in total in continue (e.g. llama.cpp needs to have port 8080 open)? I suspect that group policy is shutting down some of the ports causing this issue. I need to test this.
Also, when I changed to another environment (changed to another server), I found that the server of llama.cpp receives the request packet normally and works fine, but the Continue  is not able to show the reply from llama.cpp (could this be due to the plugin not receiving the reply packet?)

**Comment by sestinj** [comment]
@MrChen2510 My answer to your above question is changed now that we've made a change to remove the Python server. My guess is that this will be a good first step to solving your problems, but not a complete solution. Would recommend trying the new version (0.7.x on VS Code).

As of this newer version, Continue only needs whichever port you are using to connect to the LLM as well as localhost:65433 which is just a proxy we use to communicate between webview (side panel) and extension

**Comment by sestinj** [comment]
I haven't heard back in a while and this issue is solved with the move away from the Python server. If you are still running into any problems please open a new issue and I'll gladly help!
