### ISSUE TITLE
Authorization Bearer token

### ISSUE THREAD

**Issue by alfredwallace7** [continuedev/continue#643]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I'm using a remote llama.cpp server but I need to specify an API_KEY token.
It would be very useful to secure the access to the endpoint so it can be publish on the internet and accessed from anywhere.
I see in:
/continuedev/continue/tree/main/server/continuedev/libs/llm/ggml.py line 67: 
`headers["Authorization"] = f"Bearer {self.api_key}"`
But llamacpp.py do not implement this.
I cannot use the GGML provider "openai-aiohttp" as it expects openAI API compatibility.
Would you have a suggestion?
Would it be possible to make the modification?

### Solution

implement:
`headers["Authorization"] = f"Bearer {self.api_key}"`
in llamacpp.py

**Comment by sestinj** [comment]
@alfredwallace7 We have a 'headers' property in config.json that you can use for this. For example:

```json
{
  "models": [{
    "provider": "llamacpp",
    "model": "...",
    "request_options": {
      "headers": {
        "Authorization": "Bearer <API_KEY>"
      }
    }]
}
```

**Comment by alfredwallace7** [comment]
Awesome! Thanks you so much for the tip!

**Comment by alfredwallace7** [comment]
Awesome! Thanks you so much for the tip!

**Comment by venugopal-kandru** [comment]
We are using Basic auth instead of Bearer. what needs to be done in this case?
