### ISSUE TITLE
Support llamafile

### ISSUE THREAD

**Issue by ItsVRK** [continuedev/continue#645]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

It would be great if continue could support llamafile as a provider engine https://github.com/Mozilla-Ocho/llamafile

**Comment by sestinj** [comment]
@ItsVRK yes! yes! yes! I'm literally working on this as we speak, super excited about llamafiles. Will update you soon : )

**Comment by sestinj** [comment]
@ItsVRK This is now ready in the pre-release of the VS Code extension. Releasing soon to main.

Thank you for the suggestion!

**Comment by sestinj** [comment]
Now ready in main!

**Comment by frostworx** [comment]
thanks a lot! :} :100:
