### ISSUE TITLE
Continue becomes very slow for local LLM

### ISSUE THREAD

**Issue by dany-nonstop** [continuedev/continue#647]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: windows 10
- Continue: v0.6.8
- IDE: VSCode 1.84.2
```

### Description

Continue becomes extremely slow, even "/clear" command takes 10s to complete. A different computer with out-of-the-box configuration however does not have this problem, switching to GPT-4 API does not have this problem either.

the local LLM is hosted with vLLM OpenAI API, if it matters. We observed that any prompt would take up to 10s until it arrives at the API, and 10s after the server has returned the response, the continue UI was still not updated, then it starts to stream the response at about 1 word per second. it's unlikely the LLM server's problem.

rolling back to 0.65 fixed the issue.

the config.json file
```json
{
  "allow_anonymous_telemetry": false,
  "models": [
    {
      "title": "abc",
      "provider": "openai",
      "model": "abc",
      "api_key": "",
      "api_base": "http://ourapibase/v1"
    }
  ],
  "model_roles": {
    "default": "abc",
    "edit": "abc",
    "summarize": "abc"
  },
  "system_message": "you are a helpful AI assistant",
  "slash_commands": [
    {
      "name": "edit",
      "description": "Edit code in the current file or the highlighted code",
      "step": "EditHighlightedCodeStep"
    },
    {
      "name": "comment",
      "description": "Write comments for the current file or highlighted code",
      "step": "CommentCodeStep"
    },
    {
      "name": "clear",
      "description": "Clear step history",
      "step": "ClearHistoryStep"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command",
      "step": "GenerateShellCommandStep"
    }
  ],
  "context_providers": [
    {
      "name": "search"
    },
    {
      "name": "diff"
    },
    {
      "name": "terminal"
    }
  ]
}
```

### Log output

```Shell
this is the developer window output, the log window has very similar output without the websocket errors listed here.

stderr: [2023-12-01 21:21:19] [CRITICAL] Exception caught from async task: Traceback (most recent call last):

  File "asyncio\tasks.py", line 500, in wait_for

  File "asyncio\tasks.py", line 279, in __step

  File "server\continuedev\core\context.py", line 397, in safe_load

  File "asyncio\tasks.py", line 495, in wait_for

  File "asyncio\tasks.py", line 562, in _cancel_and_wait

  File "asyncio\futures.py", line 287, in __await__

  File "asyncio\tasks.py", line 349, in __wakeup

  File "asyncio\futures.py", line 198, in result

asyncio.exceptions.CancelledError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "server\continuedev\core\context.py", line 423, in load_index

  File "asyncio\tasks.py", line 502, in wait_for

TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "server\continuedev\libs\util\create_async_task.py", line 17, in callback

  File "asyncio\futures.py", line 203, in result

  File "asyncio\tasks.py", line 277, in __step

  File "server\continuedev\core\context.py", line 282, in load_index

  File "server\continuedev\core\context.py", line 429, in load_index

  File "server\continuedev\server\meilisearch_server.py", line 205, in restart_meilisearch

  File "server\continuedev\server\meilisearch_server.py", line 191, in kill_proc

AttributeError: module 'signal' has no attribute 'SIGKILL'


console.ts:137 [Extension Host] stderr: [2023-12-01 21:21:19] [WARNING] Error loading meilisearch index: module 'signal' has no attribute 'SIGKILL'

console.ts:137 [Extension Host] stderr: INFO:     ('127.0.0.1', 59574) - "WebSocket /socket.io/?window_info=%7B%22window_id%22%3A%22e27f4f8e-667b-4144-b38c-585d76858462%22%2C%22workspace_directory%22%3A%22C%3A%5C%5CUsers%5C%5Cz000rp5m%22%2C%22unique_id%22%3A%22c47aae75152d5a307a15f9beb6a46ecaa67d3c611662bfe5025b552ac5b35423%22%2C%22ide_info%22%3A%7B%22name%22%3A%22vscode%22%2C%22version%22%3A%221.84.2%22%7D%7D&EIO=4&transport=websocket" [accepted]

console.ts:137 [Extension Host] stderr: INFO:     connection open

console.ts:137 [Extension Host] stderr: [2023-12-01 21:21:20] [INFO] There are 2 sessions currently open

console.ts:137 [Extension Host] stderr: fatal: not a git repository (or any of the parent directories): .git

2console.ts:137 [Extension Host] stderr: INFO:     connection closed

console.ts:137 [Extension Host] stderr: INFO:     ('127.0.0.1', 59593) - "WebSocket /socket.io/?window_info=%7B%22window_id%22%3A%22e27f4f8e-667b-4144-b38c-585d76858462%22%2C%22workspace_directory%22%3A%22C%3A%5C%5CUsers%5C%5Cz000rp5m%22%2C%22unique_id%22%3A%22c47aae75152d5a307a15f9beb6a46ecaa67d3c611662bfe5025b552ac5b35423%22%2C%22ide_info%22%3A%7B%22name%22%3A%22vscode%22%2C%22version%22%3A%221.84.2%22%7D%7D&EIO=4&transport=websocket" [accepted]

console.ts:137 [Extension Host] stderr: INFO:     connection open

console.ts:137 [Extension Host] stderr: [2023-12-01 21:21:31] [INFO] There are 2 sessions currently open

console.ts:137 [Extension Host] stderr: fatal: not a git repository (or any of the parent directories): .git

console.ts:137 [Extension Host] stderr: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019D096E4F50>
```

**Comment by dany-nonstop** [comment]
changing the provider in the model configuration to `openai-aiohttp` however fixed the problem, but then I need to change the api_base definition as well, to remove `/v1` from it. I don't find anything in the current documentation. The document page about it in "customization" was deleted.

```json
{
"models": [{
...
    "provider": "openai-aiohttp",
    "api_base": "http://ourapibase"
...
}]
```

**Comment by yaoyasong** [comment]
@dany-nonstop thanks，it worked for me.

**Comment by prabuvnc** [comment]
> changing the provider in the model configuration to `openai-aiohttp` however fixed the problem, but then I need to change the api_base definition as well, to remove `/v1` from it. I don't find anything in the current documentation. The document page about it in "customization" was deleted.
> 
> ```json
> {
> "models": [{
> ...
>     "provider": "openai-aiohttp",
>     "api_base": "http://ourapibase"
> ...
> }]
> ```

Tried changing to this as it was too slow , but started getting error like " unable to connect to endpoint chat/completions

I am running codellama via vllm openai server. Any suggestions 
TIA

**Comment by sestinj** [comment]
@prabuvnc @yaoyasong @ntaylor-ads @dany-nonstop Thanks all for finding the solution here. Starting in the current pre-release versions of VS Code, we are removing the provider name "openai-aiohttp" and will just make its behavior the default when you use the "openai" provider.

There have also been a number of changes that might additionally speed up responses (no more proxying through the Python server) so I'd be eager to hear if this works well for you.

**Comment by sestinj** [comment]
And I hear you on the documentation part. Working on getting them completely up-to-date this week

**Comment by dany-nonstop** [comment]
@sestinj thanks for working on it and share this powerful tool with the community. I have watched your rating on VSCode marketplace dropping from 4.5 to 3.6. You can do better, don't rush. You rolled out 5 versions in the last 24 hrs. I see how hard you are working, but also how badly tested those releases are.

However I feel you guys can use some better test before rolling out a release. Every new release you break something, and I have to seek a fix. This hurts everyone's experiences. May I suggest:
* Have more thorough tests, and have more pre-release tests. 
* Respect semantic versioning, and keep it stable within one major release as long as possible. 
* Better plan your major release roadmap, push carefully and make sure you don't have so many breaking changes from release to release.

bless you!

**Comment by sestinj** [comment]
Thank you for the kind words. You're right that being overly earnest must be causing an overwhelming experience. I appreciate and will take this advice to heart!

**Comment by AwaisBinKaleem** [comment]
it is also very slow with ollama

**Comment by martinbarilik** [comment]
autocomplete and chat seems to be super slow with local ollama models

i had an impression that with my setup, 96GB RAM and 7950X it would be amost instantious .. but nope. Waiting for autocomplete for ever no matter what model i use.

**Comment by arturbacilla** [comment]
@AwaisBinKaleem Yeah, I realized that with ollama its pretty slow just for the first usage. I've set to keep alive my model for up to 30 min, so the model stays loaded thus increase the Continue response speed.
