### ISSUE TITLE
Diff Context Provider Not Working When 'disable_indexing' is Set to True

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#648]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: v0.7.23    
- IDE: VSCode 1.84.2
```

### Description

The issue appears when the user sets `disable_indexing` to `true`, causing the diff context provider to malfunction. The first problematic commit was identified as 08358a1b, part of `v0.3.10`. The error message from the `continue.log` file differs slightly from the one the user currently receives in the latest version. Since `v0.3.13`, the user has been seeing the error messages as displayed in the Log Output at the end of this issue report.

- log output for `v0.3.10`
```log
[2023-12-02 06:03:29] [CRITICAL] Error handling message: Traceback (most recent call last):

  File "server/continuedev/server/gui.py", line 46, in message

  File "server/continuedev/server/protocols/gui.py", line 73, in handle_json

  File "server/continuedev/core/context.py", line 418, in get_context_item

ValueError: Context provider with title diff not found
```

### To reproduce

1. modify your `config.json` by setting `disable_indexing` to `true`
2. open VSCode and type `@diff`
    - you might need to add `{ "name": "diff" }` to `context_providers` if it's not already there.
3. notice the spinner never stops 

<img src="https://github.com/continuedev/continue/assets/92653266/564fced6-306f-4535-90e9-2a448cb5efd2)" width="600">

4. check the logs (see below)

### Log output

```Shell
[2023-12-02 07:44:50] [CRITICAL] Error handling message: Traceback (most recent call last):

  File "server/continuedev/server/gui.py", line 47, in message

  File "server/continuedev/server/protocols/gui.py", line 62, in handle_json

  File "server/continuedev/core/context.py", line 464, in get_context_item

  File "server/continuedev/plugins/context_providers/diff.py", line 59, in get_item

server.continuedev.core.main.ContinueCustomException
```

**Comment by sestinj** [comment]
@LangLangBart Thanks for sharing. Looks likely related to a new bug where diff shows up under the @ files dropdown.

**Comment by sestinj** [comment]
@LangLangBart Finally solved, but as a byproduct of a large refactor that we did this week. If you try the latest pre-release you'll notice that there is no more dependency on the Continue Python server, and @ diff is working very reliably.

Indexing has been removed temporarily until we redo it in the next couple weeks, but I think any overlap between that and diff is very unlikely, so going to go ahead and close this issue

**Comment by LangLangBart** [comment]
> and @ diff is working very reliably.

Yes, it is. I tested it with the `0.7.54 Pre-Release` version, but my custom slash command for generating a commit message no longer appears, similar to issue #632. I will see if I also need to update my `config.py`. If that doesn't resolve the issue, I will create a new bug report.
