### ISSUE TITLE
Activation Event: onStartupFinished

### ISSUE THREAD

**Issue by astanez** [continuedev/continue#651]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
  Red Hat OpenShift Dev Spaces, Version 3.9
- Continue: 0.7.25
```

### Description

Activation Event:onStartupFinished. It breaks with following error: 
Terminal/context is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["terminalContextMenu"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api Continue.continue

Screenshot attached:
![Screenshot 2023-12-03 at 13 08 11](https://github.com/continuedev/continue/assets/112002170/48744ea3-891e-421d-97db-ee6eddfed348)

**Comment by astanez** [comment]
Hello sestinj, 
thanks for fast reaction. Unfortunately, new version produces similar error. 
Do you have any idea?  

<img width="1570" alt="Screenshot 2023-12-04 at 16 12 11" src="https://github.com/continuedev/continue/assets/112002170/d51ad043-23aa-486b-b9fb-41bf592676b6">

**Comment by sestinj** [comment]
@astanez sorry I just want to be sure since the bottom of this image looks to be cut off - you're still seeing "terminal/context is a proposed menu identifier. It requires...."?

I'm wondering if quitting VS Code and re-opening would have any effect

**Comment by astanez** [comment]
Hello, 
the message "terminal/context is a proposed menu identifier. It requires...." is not there anymore. The message window is empty. Restart of VS Code did not help.
