### ISSUE TITLE
Deleting a model from dropdown deletes the wrong model

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#657]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Mac
- Continue: Pre-release today
```

### Description

Deleting models from the config via the GUI does not work as expected

### To reproduce

1. I have two models: "GPT-4" and "Deepseek"
2. When I click the trash can button next to the "GPT-4" in the dropdown, it deletes "Deepseek" from the list and removes it's information from `config.json` (instead of doing this for GPT-4 like I intended)

**Comment by TyDunn** [comment]
It also presents a trash can icon when there is only one model, even though you are unable to delete a model when there is only one listed in the config

**Comment by sestinj** [comment]
Solved as a byproduct of the migration, and I additionally removed the trash icon when there's only one model
