### ISSUE TITLE
workspace not indexed in meilisearch

### ISSUE THREAD

**Issue by victorserbu2709** [continuedev/continue#658]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: linux
- Continue: master( commit 503e0ebae446d528d44b15e0a90ad080ba9903bf)

In /server/continuedev/libs/index/indices/meilisearch_index.py I have added following debug 

     async def add_chunks(self, chunks: List[Chunk], index: Index, offset: int):
-        await index.add_documents(
-            [
+        print("add_chunks ****", index, offset)
+        documents =             [
                 self.chunk_to_meilisearch_document(chunk, j + offset)
                 for j, chunk in enumerate(chunks)
             ]
-        )
+        task_status = await index.add_documents(documents)
+        print("task_status", task_status)
```
Output
```
...
task_status task_uid=33 index_uid='rootplaycontinuesite_base_ctrhel9' status='enqueued' task_type='documentAdditionOrUpdate' enqueued_at=datetime.datetime(2023, 12, 5, 20, 45, 20, 63998)
XXXXXXXXXXXXXXXXXXXXXXXX DONE BUILD_INDEX
```

```
curl http://localhost:7700/tasks/33  | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   735  100   735    0     0   717k      0 --:--:-- --:--:-- --:--:--  717k
{
  "uid": 33,
  "indexUid": "rootplaycontinuesite_base_ctrhel9",
  "status": "failed",
  "type": "documentAdditionOrUpdate",
  "canceledBy": null,
  "details": {
    "receivedDocuments": 15,
    "indexedDocuments": 0
  },
  "error": {
    "message": "The primary key inference failed as the engine found 2 fields ending with `id` in their names: 'id' and 'document_id'. Please specify the primary key manually using the `primaryKey` query parameter.",
    "code": "index_primary_key_multiple_candidates_found",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#index_primary_key_multiple_candidates_found"
  },
  "duration": "PT0.001105517S",
  "enqueuedAt": "2023-12-05T20:45:20.063998599Z",
  "startedAt": "2023-12-05T20:45:20.06468686Z",
  "finishedAt": "2023-12-05T20:45:20.065792377Z"
}
```
```


### Description

_No response_

### To reproduce

_No response_

### Log output

_No response_

**Comment by sestinj** [comment]
thanks for sharing this. Meilisearch currently isn't critical to the codebase retrieval so this will likely have minimal effect, but we are also working on finding alternatives. I'll keep this issue updated as that progresses, but it might end up solved via subtraction

**Comment by victorserbu2709** [comment]
Also on the master version i think that is a mistake:

https://github.com/continuedev/continue/blob/main/server/continuedev/libs/index/indices/meilisearch_index.py#L22
actual id is document_id + :: + chunk index

https://github.com/continuedev/continue/blob/main/server/continuedev/libs/index/indices/meilisearch_index.py#L76 ()
but when added
id = int(chunk.digest, 16)

**Comment by sestinj** [comment]
@victorserbu2709 We've now removed the dependency on meilisearch as of our latest VS Code pre-release, which means that this bug won't be possible.

It played such a minimal role in indexing (and wasn't improving performance) that it made more sense to use a native javascript library to power the @ files dropdown feature instead.
