### ISSUE TITLE
errors, when starting continue server with a custom configuration file

### ISSUE THREAD

**Issue by astanez** [continuedev/continue#659]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14.1.1 
- VS Code: 1.84.2 (Universal)
- Continue ext: 0.7.26
```

### Description

Hello,

I get two errors, when starting continue server with a custom configuration file:

[2023-12-05 18:28:32] [WARNING] Failed to load config modifier from /Users/yyeryomi/.continue/config.py: 1 validation error for ContinueConfig
models
value is not a valid list (type=type_error.list)
[2023-12-05 18:28:32] [WARNING] Error adding document to meilisearch: MeilisearchApiError.index_not_found Error message: Index continue_context_items not found. invalid_request Error documentation: https://docs.meilisearch.com/errors#index_not_found

### To reproduce

.

### Log output

```Shell
Below is configuration file content:
cat ./continue/python.py
"""
This is the Continue configuration file.

See https://continue.dev/docs/customization to for documentation of the available options.
"""

from continuedev.core.models import Models
from continuedev.core.config import CustomCommand, SlashCommand, ContinueConfig
from continuedev.libs.llm.ollama import Ollama

from continuedev.plugins.context_providers import (
DiffContextProvider,
TerminalContextProvider,
URLContextProvider,
GitHubIssuesContextProvider
)
from continuedev.plugins.steps import (
ClearHistoryStep,
CommentCodeStep,
EditHighlightedCodeStep,
GenerateShellCommandStep,
OpenConfigStep,
)
from continuedev.plugins.steps.share_session import ShareSessionStep

config = ContinueConfig(
allow_anonymous_telemetry=False,
models=Models(
default=Ollama(
model="codellama:13b",
server_url="http://route-to-olama-user1-devspaces.apps.cluster-l4gcq.sandbox2938.opentlc.com/"
)
),
system_message=None,
temperature=0.5,
custom_commands=[
CustomCommand(
name="test",
description="Write unit tests for highlighted code",
prompt="Write a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
)
],
slash_commands=[
SlashCommand(
name="edit",
description="Edit highlighted code",
step=EditHighlightedCodeStep,
),
SlashCommand(
name="config",
description="Customize Continue",
step=OpenConfigStep,
),
SlashCommand(
name="comment",
description="Write comments for the highlighted code",
step=CommentCodeStep,
),
SlashCommand(
name="clear",
description="Clear step history",
step=ClearHistoryStep,
),
SlashCommand(
name="share",
description="Download and share this session",
step=ShareSessionStep,
),
SlashCommand(
name="cmd",
description="Generate a shell command",
step=GenerateShellCommandStep,
)
],
context_providers=[
# GitHubIssuesContextProvider(
# repo_name="/",
# auth_token=""
# ),
DiffContextProvider(),
URLContextProvider(
preset_urls = [
# Add any common urls you reference here so they appear in autocomplete
]
),
TerminalContextProvider(),
],
)
```

**Comment by sestinj** [comment]
@astanez In the most recent VS Code pre-release (v0.7.x) we have removed the dependencies on both the Python server and Meilisearch, which I think should solve the errors here. Let me know if you're still having any problems, but otherwise I'll close this issue in a few days as the errors above are quite literally not possible in the new setup
