### ISSUE TITLE
Supporting min-p sampling setting on llama.cpp

### ISSUE THREAD

**Issue by Azeirah** [continuedev/continue#660]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

min-p is an alternative sampling method that is supported by llama.cpp (I believe exllama also supports it). In my experience it's both way easier and way better than any other sampling method out there.

As an example using deepseek-coder 33b in llama.cpp

Prompt: "Write the fibonacci function in Python3"

min_p 0.05

```
def fibonacci(n:int, memo={}) -> int:
    if n <=2 : return 1 # base case 1, 2 => 1 

    if n not in memo:  
        memo[n] = fibonacci(n-1, memo) + fibonacci(n-2,memo) # store the result
    
    return memo[n]
# Test cases 
print("Test case 1")
print(f"The 5th Fibonacci is {fibonacci(5)} ")  
print(f"The 9th Fibonacci is {fibonacci(9)} ")
```

Default sampling settings

```
def fibonacci(n):
  if n == 0:
      return 0
  elif n ==1:
      return 1
  else :
      return (fibonacci(n - 1) + fibonacci(n -2))
n = int(input())
print(fibonacci(n))
```

### Solution

For more details on the sampling method itself: https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/

The llama.cpp server supports min-p in a similar way to any other sampling method

**Comment by sestinj** [comment]
@Azeirah Nice! That was a good read, learned some things and might actually change our defaults to this.

To set min-p, assuming you are using "provider": "llama.cpp" in your config.json, you can do this:

```json
{
  "model": "deepseek-33b",
  "provider": "llama.cpp",
  "title": "Deepseek Coder",
  "llama_cpp_args": { "min-p": 0.05}
}
```

and we will pass the llama_cpp_args to the server like [here](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#api-endpoints)

**Comment by sestinj** [comment]
Though I do notice that the docs there don't list min-p, so it could be that they are just out of date, but if it doesn't work then maybe a PR is in order.

I'll also make a point to add min-p to our completion_options object

**Comment by sestinj** [comment]
@Azeirah `minP` is added as an option [here](https://github.com/continuedev/continue/commit/52cc97cd6332beda53a9e5b5214254ca62b61b5a). It will work with the llama.cpp provider, but doesn't look like any of the others support this option
