### ISSUE TITLE
`/config` command is not available in VSCode Extension

### ISSUE THREAD

**Issue by FabianHertwig** [continuedev/continue#662]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:macOS 14.1.2
- Continue: v0.7.29 (VS Code extension)
- IDE: VSCode 1.85.0
```

### Description

The [docs mention](https://continue.dev/docs/customization/context-providers#built-in-context-providers), that you can open the `config.json` with the `/config` command. When I put `/config` in the chat input, then it is treated as normal input to the model. The command is also not shown in the command dropdown.

### To reproduce

Type `/config` in the chat input.

![image](https://github.com/continuedev/continue/assets/32016596/7f2203a3-6778-4344-96a9-3781ee6b7ba3)

### Log output

```Shell
[2023-12-09 08:42:35] [WARNING] Failed to load config from /Users/fabianhertwig/.continue/config.py: module 'config' has no attribute 'config'
[2023-12-09 08:42:35] [DEBUG] ------ Begin Logs ------
[2023-12-09 08:42:36] [DEBUG] Downloading MeiliSearch with curl...
[2023-12-09 08:42:46] [DEBUG] ------ End logs ------
```

**Comment by sestinj** [comment]
@FabianHertwig This is a mistake in the docs since we removed the /config slash command and I'll be sure to fix it. You can now access config.json either by clicking the gear in the bottom right corner, and then the "config.json" button in the upper right, _or_ by opening the file at `~/.continue/config.json`,

**Comment by FabianHertwig** [comment]
Ok, thanks. Are the docs up to date for the context providers? These commands (e.g. `@tree`, `@issue`) do also not work for me.

**Comment by sestinj** [comment]
@FabianHertwig I'm not certain of their state as of the old Python server versions, but these are two of the remaining pieces that I still need to implement in the new VS Code pre-release versions (0.7.x). I'll let you know once I get them done.

**Comment by sestinj** [comment]
@FabianHertwig the issue context provider is now completed: https://continue.dev/docs/customization/context-providers#github-issues

**Comment by sestinj** [comment]
Just going through older issues and noticed that this one looks mostly resolved. Going to close, but let me know if there's something still going on!
