### ISSUE TITLE
Cannot start server, no existing method works. Proxy cannot be set.

### ISSUE THREAD

**Issue by Feiyang** [continuedev/continue#663]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS Intel
- Continue: Continue server version 0.0.350
```

### Description

I am using a proxy to connect to Github, Azure, OpenAI, etc. Therefore, when starting the Continue server, it first hangs at "Downloading MeiliSearch with curl...". My first attempt is to manually start the server in my terminal where the environment variable includes `http_proxy`. Next, when using the extension, it still cannot send requests to Azure OpenAI. I have seen error messages like `Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "https", use "https://"`. For most of the times, it just hangs forever. As for the trouble shooting guide, nothing works for me.

**Comment by sestinj** [comment]
@Feiyang As of the most recent pre-release extension versions (0.7.x) Continue no longer requires a separate Python server or Meilisearch. This should solve at least the first of your problems here.

As for the proxy, I expect there might be 1-2 back and forths to get this working, but we have a new `proxyServerUrl` in VS Code settings that you can use and all requests will be sent through that. This is also only in the newer versions.

**Comment by Feiyang** [comment]
> @Feiyang Apologies for the slow response here. We've been working on big changes that I think will pretty directly address this issue. As of the most recent pre-release extension versions (0.7.x) Continue no longer requires a separate Python server or Meilisearch. This should solve at least the first of your problems here.
> 
> As for the proxy, I expect there might be 1-2 back and forths to get this working, but we have a new `proxyServerUrl` in VS Code settings that you can use and all requests will be sent through that. This is also only in the newer versions.

Thanks for your reply. I am so glad to hear that there will be new versions. Here is my development environment, and I wish to see that the new version will work.

- Client OS: Mac OS
- Remote SSH Server OS: Ubuntu
- Model deployment: On some other server where the remote SSH server can connect to. For example, if I deploy a model on the same remote SSH server, the vscode-server should send requests to http://localhost:port directly. If I want to switch to using Azure OpenAI API, I should use an HTTP proxy **on the server**, by setting some environment variable like `http_proxy` or `https_proxy`.

**Comment by sestinj** [comment]
This issue is now solved as we are no longer using meilisearch or the local proxy. If you have any other problems, please don't hesitate to open another issue, but I'll close this one so we can have clean separation
