### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by FabianHertwig** [continuedev/continue#670]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

We are looking for a GitHub Copilot / Cursor.sh like software engineering assistant, that keeps our codebases private, e.g. does not process it on their own servers. For us, this is the unique selling point of this project, but it is not explicitly written down.

### Solution

Please add a privacy policy that states where the code is processed.

**Comment by sestinj** [comment]
@FabianHertwig The closest thing we have to a privacy policy is [here](https://continue.dev/docs/telemetry). Is this close enough, or is a more formal policy preferred? Happy to create this if so. Would be good to know what specific guarantees you are looking for

**Comment by sestinj** [comment]
Ok great. We can definitely add this. The folks we need to review it won't be able to get back to us until after the holidays though, so we'll get back with an update in the new year. Hopefully this is acceptable with your timelines? The points here are essentially correct, but with such a legal statement we want to do it once and do it right rather than rush one out the door

**Comment by FabianHertwig** [comment]
Thanks. That's alright! Enjoy the holidays! :)

**Comment by sestinj** [comment]
great, you too!

**Comment by Droneradar** [comment]
@sestinj 
Hello! any progress on this?

**Comment by TyDunn** [comment]
@FabianHertwig Sorry for the delay. This took much longer than expected, but we now have a privacy notice, which you can find here: https://continue.dev/privacy. Please let me know if you have any questions or concerns (privacy@continue.dev)

**Comment by CodeToFreedom** [comment]
@TyDunn The privacy link currently gives a 404 error. As full privacy is also crucial for us (and probably many more)  it would be great to fix the broken link. Thanks a lot.

**Comment by TyDunn** [comment]
@CodeToFreedom The link is fixed and should work now: https://continue.dev/privacy. The privacy policy can also be found at https://662b3565781b276a9ffd4057--stunning-panda-f196c1.netlify.app/notice.pdf

**Comment by tcgumus** [comment]
hello, i looked at it and didn't see about my code being processed or not. 

it looks like you collect and process data of everyone that uses your product which in this case it would be your extension.? what am i missing?

> Customer Content, **including any files, documents**, audio, videos, images, data or communications you choose to input, upload or transmit to our products and service. We use this content primarily to provide you with our products and services and to facilitate your requests.

**Comment by DWDuq** [comment]
@tcgumus I think it's referring to files and documents uploaded manually by users, for example as part of an interaction with someone at Continue or on their website.  That being said, it is vague and a clearer distinction from files and documents used by Continue to provide context for the LLMs would be useful for peace of mind. This may be the thing puts me off on using the product tbh as I'm concerned with my code being stored somewhere outside my control or used to train LLMs

**Comment by TyDunn** [comment]
@tcgumus Your code is not being processed by us. Before bullet point you quoted, it states "However, to the extent you choose to interact with us directly or utilize one of our **non-open-source offerings**, we may collect the following categories of personal data you provide in connection with those offerings (once available):".

No data will be sent home if you set "allowAnonymousTelemetry": false in your config. This allows for a completely confidential experience. The docs that explain this as well as what anonymous usage information we collect in the extension by default (i.e. unless a user opts out) can be found [here](https://docs.continue.dev/telemetry). If you want to check for yourself, you can review the code [here](https://github.com/continuedev/continue/blob/main/gui/src/hooks/CustomPostHogProvider.tsx) and / or others in the Continue community have used tools like Little Snitch to see outgoing requests and verify for themselves

**Comment by TyDunn** [comment]
@DWDuq The Continue extension runs entirely locally, unless you connect it to external services in your config (e.g. model APIs). This means your code and context only leave your computer if you decide to let it in your configuration. Please see my most recent reply above this for even more information / suggestions about how to verify this yourself

**Comment by DWDuq** [comment]
@TyDunn Thanks for the response.  If I do connect Coninue to an external service, are the requests sent through Continue and then routed onwards to the service or sent directly from my computer to the service?

**Comment by TyDunn** [comment]
@DWDuq Of course. If you connect the Continue extension to a third-party service with your own API keys, the requests are sent directly from your computer to that service

**Comment by muuvmuuv** [comment]
Thanks for this details. I have just setup our AI-Guidelines for our company and wanted to add Continue to our whitelist. This states its safe together with local llm tools like ollama. Great ✨

**Comment by MMartienssen** [comment]
@TyDunn I'm in a similar situation as muuvmuuv and I personally struggle to conclude from reading the privacy notes, that none of my code or personal data is saved elsewhere. Even if it does technically say that, I personally wouldn't be sure enough to use this in my company and maybe people who are like me would not use the service for the same reason. 
E.g. if I read: "We also collect personal data automatically when an individual interacts with our products and services.", my first thought is: "Ok, so we cannot use this for sensible data". 

It would be very helpful for me, if there was a notice at the top of the Privacy notes that states, that your code/data is not collected by continue.dev and doesn't leave your computer (at least with the right settings), much like FabianHertwig suggested. 

This notice for Azure OpenAI for example was very helpful and reassuring in that regard :
https://learn.microsoft.com/en-us/legal/cognitive-services/openai/data-privacy?context=%2Fazure%2Fai-services%2Fopenai%2Fcontext%2Fcontext&tabs=azure-portal

**Comment by TyDunn** [comment]
@MMartienssen The Privacy Notice states the anonymous telemetry we collect in our open-source extensions under the "Personal Data Automatically Collected" section. As it also states in that section, if you opt out of it, then we don't collect any data. This guarantee can be found in our docs [here](https://docs.continue.dev/telemetry) too. 

You also don't need to trust my word; you can go verify for yourself, since [the code for our extensions is open source, and you can also check all of the network traffic yourself](https://github.com/continuedev/continue/issues/670#issuecomment-2367101220). In addition, many of the most security / privacy conscious organizations across the world are using Continue and constantly verifying this as well

**Comment by AwayahShahid** [comment]
Hi, where can I find information of if prompts and suggestions are retained or not. 
If I am using my own model with an API key, is any data (eg: prompts) sent to Continue, apart from telemetry data.

**Comment by MMartienssen** [comment]
@TyDunn Thank you for your answer. Just to clarify, I didn't mean to say that the privacy notes don't state, that my data isn't collected nor that I didn't believe you that it isn't. I meant this as a feedback, that I personally would have found a note on the top of the page (like in the microsoft case) useful, which I think is also what FabianHertwig was originally asking for.
Continue is an amazing tool, so thank you for the work you have put into it!
