### ISSUE TITLE
Millisearch did not start by changing DEFAULT_MEILISEARCH_URL

### ISSUE THREAD

**Issue by muhammadbaqir1327** [continuedev/continue#671]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.1.2
- Continue: 0.6.15
```

### Description

The issue is when I changed DEFAULT_MEILISEARCH_URL (http://localhost:7700). Meilisearch didn't start. 
By further exploring the `meilisearch_server.py` file, I found that when a subprocess of millisearch is created there is no mention of DEFAULT_MEILISEARCH_URL. So by default millisearch always runs at localhost:7700.

```python
meilisearch_process = subprocess.Popen(
            [binary_name, "--no-analytics"],
            cwd=serverPath,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.STDOUT,
            close_fds=True,
            # start_new_session=True,
            shell=True,
        )
```
[meilisearch_server.py#L162](https://github.com/continuedev/continue/blob/main/server/continuedev/server/meilisearch_server.py#L162)

### To reproduce

1. Open [meilisearch_server.py](https://github.com/continuedev/continue/blob/main/server/continuedev/server/meilisearch_server.py) 
2. Modify Line 102 of the file
```python
 DEFAULT_MEILISEARCH_URL = "http://localhost:8800"
```

### Log output

```Shell
[2023-12-12 22:38:55] [DEBUG] Starting MeiliSearch...
[2023-12-12 22:38:55] [INFO] Meilisearch started at http://localhost:8800
[2023-12-12 22:38:56] [INFO] There are 1 sessions currently open
[2023-12-12 22:38:57] [DEBUG] Starting MeiliSearch...
[2023-12-12 22:38:57] [INFO] Meilisearch started at http://localhost:8800
[2023-12-12 22:38:57] [WARNING] Error while building meilisearch index: MeilisearchCommunicationError, All connection attempts failed
[2023-12-12 22:39:17] [WARNING] Meilisearch did not start in less than 20 seconds. Stopping polling.
```

**Comment by muhammadbaqir1327** [comment]
I fixed this issue by modifying some code.
```python
url_without_http = DEFAULT_MEILISEARCH_URL.split("//")[1]
meilisearch_process = subprocess.Popen(
    [binary_name, "--http-addr", f"{url_without_http}", "--no-analytics"],
    cwd=serverPath,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.STDOUT,
    close_fds=True,
    # start_new_session=True,
    shell=False,
)
```

**Comment by sestinj** [comment]
thanks for finding this fix! We are actually in the process of moving away from meilisearch, but I'll add this to the codebase anyway just in case something changes

If you experience any more problems with meilisearch, or the Continue server in general, I would recommend trying out the new version, which is now in pre-release as 0.7.32 on the VS Code extension marketplace
