### ISSUE TITLE
Tests are not portable

### ISSUE THREAD

**Issue by danieleades** [continuedev/continue#675]
The tests make references to specific user directory paths and therefore cannot be used in CI or on other developers machines.

For example, in `/home/dan/Code/continue/server/src/sync/mod.rs`

the `test_sync` assumes that the filepath is `/Users/natesesti/Desktop/continue`

I've commented out the test portion of the rust workflow in #674 as a result

**Comment by sestinj** [comment]
Good call. /tmp directories like are used in some of the other tests ought to be the solution.

Commenting out is totally fine for now though, I believe those were more of benchmarks than tests, so shouldn't lose any important harness

**Comment by sestinj** [comment]
These were all referencing sub-directories of the continue project mostly for the sake of having a semi-large directory to work with, so just made the paths relative: https://github.com/continuedev/continue/commit/8ccb8fb74eb4604aaa36460912776bc901b3a6fd
