### ISSUE TITLE
Timeout - and the response it has been writing for the past minute or two disappeared. 

### ISSUE THREAD

**Issue by Alumniminium** [continuedev/continue#686]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux
- Continue: v0.6.15
```

### Description

Please disable the timeout while streaming a response. Disable timeouts all-together, really. Earlier today, I had the same issue with it timing out when I sent my entire repo in the context and it had to spend a while processing all the prompt tokens. I have big context models, they do eventually respond :)

Please make timeouts configurable.

**Comment by Alumniminium** [comment]
Nevermind, I found it.

```
"models": [
    {
      "title": "CtxExt DeepSeek Instr Coder 256k",
      "provider": "openai-aiohttp",
      "model": "deepseek-33b-256ctx",
      "api_base": "http://******",
      "context_length": 256000,
      "server_url": "", 
      "request_options": {
       ---> "timeout": 30000 <----
      }
    }
  ],
```

**Comment by sestinj** [comment]
256k 👀

Glad you found it. Starting in pre-release versions timeouts will no longer happen
