### ISSUE TITLE
HuggingFace TGI provider missing from menu

### ISSUE THREAD

**Issue by erezsharon** [continuedev/continue#688]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.6.4 and onward
- Python: 3.11
- IDE: VSCODE 1.85.1
```

### Description

When opening the ""add provider"" menu the option to select HuggingFace TGI is now missing from the menu. This was working fine until version 0.6.4

### To reproduce

Click on the "+" sign and scroll down to the end - no option to select HuggingFace TGI

**Comment by sestinj** [comment]
@erezsharon we've removed this from the visual menu because it's used less frequently than some of the others and tends to be more difficult to set up. But if you type "provider": "huggingface-tgi" in your config.json, the option still exists
