### ISSUE TITLE
Adding full workspace as context

### ISSUE THREAD

**Issue by StephaneAdeso** [continuedev/continue#689]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Is there a way to add the full workspace as context? Will it be possible in the future if it is not possible?

**Comment by sestinj** [comment]
@StephaneAdeso Most codebases will not fit in context entirely, but we have the /codebase slash command (or cmd+enter), which allows Continue to automatically retrieve the most relevant files for any given question. One idea though is to allow the inclusion of entire folders, which I think could be a really good one

**Comment by smyja** [comment]
> @StephaneAdeso Most codebases will not fit in context entirely, but we have the /codebase slash command (or cmd+enter), which allows Continue to automatically retrieve the most relevant files for any given question. One idea though is to allow the inclusion of entire folders, which I think could be a really good one

You can use RAG for it with https://github.com/run-llama/llama_index

**Comment by sestinj** [comment]
@StephaneAdeso I'm going to close this issue now that we have the [codebase retrieval feature](https://continue.dev/docs/walkthroughs/codebase-embeddings). This lets you include the most important files from your codebase automatically. There is also a "folder" context provider so you can reference specific folders. While it will never be possible to include every codebase in its entirety in the prompt, you can configure `nFinal` to be a very large number (if it fits within your model's context window), which should give the LLM all the context it needs
