### ISSUE TITLE
[Bug] All codebase chunks not indexed

### ISSUE THREAD

**Issue by abhinavkulkarni** [continuedev/continue#692]
### Relevant environment info

```Markdown
- OS: MacOS
- Continue: Latest
```

### Description

Hi,

I loaded this project `continuedev/continue` in VSCode and noticed that only 5 chunks were indexed.

```python
from pathlib import Path
import chromadb

chroma_client = chromadb.PersistentClient(Path("~/.continue/index/chroma/default/chroma").expanduser().as_posix())
collection_name = "chroma-default"
collection = chroma_client.get_collection(name=collection_name)
print(collection.count())
```

This prints `5`. There should be lot more than 5 chunks in this project.

Thanks!

**Comment by abhinavkulkarni** [comment]
Hey @sestinj,

Any update on this? Thanks for the great work!

**Comment by sestinj** [comment]
@abhinavkulkarni I happen to be working on it this weekend. Hoping to ship tomorrow, and should at that point be fully reliable. Will also use a filesystem watcher to stay continuously up-to-date

**Comment by sestinj** [comment]
@abhinavkulkarni This is now shipped in the pre-release for VS Code
