### ISSUE TITLE
[Bug] Unable to run server manually

### ISSUE THREAD

**Issue by abhinavkulkarni** [continuedev/continue#693]
Hi,

I checked out the latest `main` branch and am unable to run the server manually. I followed the following steps:

1. I ran `bash install-dependencies.sh`
2. I ran `bash build.sh`
3. I set the Python interpreter to `continuedev/continue/env/bin/python`
4. I opened the Continue preferences and ticked the box that says manually running server
5. I ran the "Server + Extension (VSCode)"
6. Firstly, I had to upgrade `openai` to the latest version to get past the first error `ImportError: cannot import name 'AuthenticationError' from 'openai'`. However, if I upgrade, I get another error `ModuleNotFoundError: No module named 'openai.error'`

Thanks!

**Comment by sestinj** [comment]
@abhinavkulkarni I would try the pre-release for VS Code. We've gotten rid of the need for the Python server, it just runs as a self-contained extension. Only downside is we are still working on transferring over codebase embeddings, but due to the bug you won't be missing much

**Comment by sestinj** [comment]
Closing this issue as the server is no longer used
