### ISSUE TITLE
[BUG] Unexpected Refocus on Textarea After Generating Response

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#704]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.7.58
```

### Description

The user's cursor is automatically refocused into the textarea after the response has been generated.

### bisect
The issue was first observed in commit 892ee87b71f876fccc79066107b4936e6bf0eb99 with the introduction of a ternary condition to either display the `ComboBox` or the `StopButton` based on the `active` state.

```diff
--- a/gui/src/pages/gui.tsx
+++ b/gui/src/pages/gui.tsx
@@ -824,19 +824,30 @@ function GUI(props: GUIProps) {
         </StepsDiv>
 
         <div ref={aboveComboBoxDivRef} />
-        <ComboBox
-          isMainInput={true}
-          ref={mainTextInputRef}
-          onEnter={(e, _) => {
-            onMainTextInput(e);
-            e?.stopPropagation();
-            e?.preventDefault();
-          }}
-          onInputValueChange={() => {}}
-          onToggleAddContext={() => {
-            client?.toggleAddingHighlightedCode();
-          }}
-        />
+        {active ? (
+          <StopButton
+            onClick={() => {
+              client?.stopSession();
+              dispatch(setActive(false));
+            }}
+          >
+            ⌘ ⌫ Cancel
+          </StopButton>
+        ) : (
+          <ComboBox
+            isMainInput={true}
+            ref={mainTextInputRef}
+            onEnter={(e, _) => {
+              onMainTextInput(e);
+              e?.stopPropagation();
+              e?.preventDefault();
+            }}
+            onInputValueChange={() => {}}
+            onToggleAddContext={() => {
+              client?.toggleAddingHighlightedCode();
+            }}
+          />
+        )}
       </div>
     </TopGuiDiv>
   );
```

### possible solution ?
~~The showComboBox local state allows you to control the rendering of ComboBox independently of the Redux active state.~~

~~I will send a PR for you to review.~~

### To reproduce

1. Enter something in the chat, for example, "Hello".
2. Swiftly move your cursor into the terminal and continue typing until the chat response is complete.
3. Observe that when the response is complete, your cursor is automatically placed back into the text area. It shouldn't.

**Comment by LangLangBart** [comment]
> possible solution ?

Attempted to find a simple solution, but haven't succeeded so far.

**Comment by sestinj** [comment]
@LangLangBart This looks to be solved as a byproduct of changes to the input box in version 0.7.59+ (latest pre-release). Can you confirm?

**Comment by LangLangBart** [comment]
Yes, but, if the user didn't move the cursor away, e.g. to the terminal, the cursor would automatically be in the new `ComboBox`. However, this is no longer the case with the latest pre-release. I will create another ticket
