### ISSUE TITLE
Build.cmd is missing call to cd back out of server directory

### ISSUE THREAD

**Issue by blake-howell-sc** [continuedev/continue#706]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: https://github.com/continuedev/continue/commit/2b602635ec4fba7ce74e34b53c6ba7dbef15ea07
```

### Description

Running `build.cmd` was not working for me 

To fix, I manually ran `cd ..` and continued with the rest of the commands (starting with `mkdir .tiktoken_cache`)

Looking at the below commit, I see that the call to `cd ..` was added in the `build.sh` file but not the `build.cmd` file
https://github.com/continuedev/continue/commit/335b1e35474359ce31edbbb2d385f917cb27aa1b

@sestinj

**Comment by sestinj** [comment]
Thanks! fixed [here](https://github.com/continuedev/continue/commit/b2c835cf045ed786316bb44daafdee721bb4d1f9). Probably important piece of info though: we are no longer using the Python server, as all of this logic has been moved into the `core` directory, which is written in Typescript. Closing the issue, but lmk if you have any questions about this
