### ISSUE TITLE
Keep Cursor in New Textarea After Chat Response Unless User Leaves Continue Extension

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#709]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.7.59
```

### Description

Previously, when a response was generated, the cursor would automatically move to the next text area. 

Change came in version `0.7.59` 

Ref: #704

### To reproduce

1. Enter something in the chat, for example, "Hello".
2. Press <kbd>⏎ Enter</kbd> and wait till the response is complete
3. Observe that when the response is complete, your cursor is not in the new text area.

**Comment by sestinj** [comment]
I want to make sure, given the previous issue: the expected behavior is that your cursor ends up in the new text box *unless* you moved your cursor into the editor?

**Comment by LangLangBart** [comment]
yes, please.

**Comment by LangLangBart** [comment]
my attempt 
```diff
--- a/gui/src/components/mainInput/TipTapEditor.tsx
+++ b/gui/src/components/mainInput/TipTapEditor.tsx
@@ -275,6 +275,9 @@ function TipTapEditor(props: TipTapEditorProps) {
     if (!props.isMainInput) {
       return;
     }
+    if (editor && document.hasFocus()) {
+      editor.commands.focus()
+    }
     const handler = async (event: any) => {
       if (!editor) return;
 ```

**Comment by sestinj** [comment]
Merged and tested and works just as expected! Thanks for this
