### ISSUE TITLE
LM Studio config appending /v1/ to url request

### ISSUE THREAD

**Issue by teebu** [continuedev/continue#713]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: v0.6.18
```

### Description

LM Studio url appends /v1/ to url, resulting in:

Error visible in LM Studio logs:
```
[2023-12-28 14:58:31.771] [ERROR] Unexpected endpoint or method. (POST /v1/v1/chat/completions). Returning 200 anyway
```

Standard Config:
```
    {
      "title": "Mistral",
      "model": "dolphin-2.6-mistral-7b",
      "contextLength": 4096,
      "provider": "lmstudio"
    }
```

Fixed by manually adding `apiBase` setting in config:
```
    {
      "title": "Mistral",
      "model": "dolphin-2.6-mistral-7b",
      "contextLength": 4096,
      "provider": "lmstudio",
      "apiBase": "http://localhost:1234"
    }
```

The code set here hard codes the `v1`:
https://github.com/continuedev/continue/blame/b162e8703a357c8d365cd6073bbc7fbb58ad527f/core/llm/llms/LMStudio.ts#L7

**Comment by sestinj** [comment]
Thanks for the report, I fixed it in two ways in [this commit](https://github.com/continuedev/continue/commit/a2188645b9b91559d14a34b14a535d33625c954e), which I will publish a version for later tonight

**Comment by tobiasoberrauch** [comment]
Hi @sestinj 
I'm facing also this issue. Did you already released the fix?
I tried with 0.7.62 Pre-Release

**Comment by Ahmedtronic** [comment]
it's not working for me
