### ISSUE TITLE
Doesn't work with VSCodium that's installed via Flatpack on Fedora 

### ISSUE THREAD

**Issue by zine999** [continuedev/continue#715]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Fedora 39
- Continue: v0.6.17
```

### Description

On Fedora 39, when installing VSCodium via the graphical "Software" app/store thing, and then installing Continue, Continue doesn't work. The symptoms are: clicking the button to edit the "config.json" does absolutely nothing. There is no way to add a configuration for any LLM model/method.

### To reproduce

See above.

**Comment by sestinj** [comment]
@zine999 If you do cmd+shift+p and then select "Toggle Developer Tools", do you see any potentially relevant errors in the console logs when you click the gear button? This would greatly help with debugging.

Another very good thing to know: does ~/.continue/config.json exist at all? If not this would very much explain the problem and would likely be an easy fix

**Comment by zine999** [comment]
Hmm... this is really hard to reproduce now that I've installed the official VSCodium thing via `dnf`. Since doing that, the Flatpack version of VSCodium suddenly works, even when I rename the `.continue` folder. I think I would need to install Fedora afresh to try out your suggestions, which I might do in a VM.

Re `does ~/.continue/config.json exist at all?` - I don't think it did, if memory serves.

**Comment by zine999** [comment]
OK... I'm not sure what's going on. I can't reproduce this, even in a fresh install of Fedora. I don't know why it wasn't working before. I'll close this issue since I can't reproduce anymore. If I'm ever able to reproduce I'll open it again.
