### ISSUE TITLE
Ollama provider in IDEA not working as expected

### ISSUE THREAD

**Issue by azthec** [continuedev/continue#721]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS Ventura 13.5.2
- Continue: 0.0.26
- IDE: IDEA IntelliJ 2023.3.2
- Ollama: 0.1.17
```

### Description

I've setup the continue dev IDEA plugin to query against my local ollama instance.

The instance is working correctly as can be seen by the example curl query:
```bash
curl -X POST http://localhost:11434/api/generate -d '{
    "model": "mistral",
    "prompt": "Why is the sky blue?"
    }'
```

```bash
        {"model":"mistral","created_at":"2024-01-03T09:37:10.715594Z","response":"\n","done":false}
        {"model":"mistral","created_at":"2024-01-03T09:37:10.878788Z","response":"The","done":false}
        {"model":"mistral","created_at":"2024-01-03T09:37:11.037161Z","response":" sky","done":false}
        {"model":"mistral","created_at":"2024-01-03T09:37:11.195304Z","response":" appears","done":false}
        {"model":"mistral","created_at":"2024-01-03T09:37:11.353536Z","response":" blue","done":false}
        {"model":"mistral","created_at":"2024-01-03T09:37:11.511888Z","response":" because","done":false}
        ...
```

Should I purposefully misconfigure the model name I do get the correct JSON error response that the model does not exist.

When properly configured the logs of the `ollama serve` command display correct 200 OK responses when I query the model via the continue UI.

```
...
{"timestamp":1704276614,"level":"INFO","function":"main","line":3097,"message":"HTTP server listening","port":"64785","hostname":"127.0.0.1"}
{"timestamp":1704276614,"level":"INFO","function":"log_server_request","line":2615,"message":"request","remote_addr":"127.0.0.1","remote_port":50368,"status":200,"method":"HEAD","path":"/","params":{}}
2024/01/03 11:10:14 llama.go:508: llama runner started in 1.201600 seconds
2024/01/03 11:10:14 llama.go:577: loaded 0 images
[GIN] 2024/01/03 - 11:10:22 | 200 | 10.009419608s |       127.0.0.1 | POST     "/api/generate"
{"timestamp":1704276627,"level":"INFO","function":"log_server_request","line":2615,"message":"request","remote_addr":"127.0.0.1","remote_port":50368,"status":200,"method":"POST","path":"/completion","params":{}}
{"timestamp":1704276631,"level":"INFO","function":"log_server_request","line":2615,"message":"request","remote_addr":"127.0.0.1","remote_port":50370,"status":200,"method":"HEAD","path":"/","params":{}}
...
```

I have also tailed the IDEA logs and I do not find anything relevant to the continue plugin (`tail -f ~/Library/Logs/JetBrains/IdeaIC2023.3/idea.log`

This is the error I am getting.

<img width="615" alt="image" src="https://github.com/continuedev/continue/assets/13895270/79c68991-f3e7-4c99-84ca-59234093bb8a">

### To reproduce

1. Setup the ollama provider / model on config.json as indicated by the docs
2. Restart IDEA
3. `⌘ Command + J` to open the continue UI
4. Select new model
5. Submit a query
6. See image in the description (Error streaming response error)

### Log output

```Shell
Where can I find continue_logs.txt for IntelliJ IDEA?
```

**Comment by sestinj** [comment]
@azthec I'm having trouble reproducing, would you mind sharing your exact config.json (any API keys excluded)?

**Comment by SommerEngineering** [comment]
I have the same problem using LM Studio as provider and the `CodeLlama` models. No matter which setting I use. Only once did the Continue plugin manage to output the response stream. Every time I tried again, I got the error shown in the screenshot above. However, I can see that LM Studio is generating the responses.

This happens using the default configuration, i.e.:
```
{
      "title": "CodeLlama-7b",
      "model": "codellama-7b",
      "contextLength": 2048.0,
      "apiBase": "http://localhost:1234",
      "completionOptions": {},
      "provider": "lmstudio"
    }
```

Same for the `13b` model 🤷‍♂️.

**Comment by sestinj** [comment]
@SommerEngineering your config looks good, except contextLength should be an integer instead of a float (I understand that Continue is responsible for this, it's something we're fixing for the next version). I don't expect this to break things though.

I'm wondering if the proxy server might have somehow not started or died. Can you `lsof -i :65433` to check whether there is a running process?

We use this so that requests can be made directly from the webview, otherwise they may be blocked depending on CORS policy. If it's not up, then this would certainly cause these errors.

**Comment by jkritzen** [comment]
Hi ,

i have the same issue with the ollama provider.  My config.json:

`    {
      "title": "CodeLlama-7b",
      "model": "codellama-7b",
      "contextLength": 2048.0,
      "completionOptions": {},
      "apiBase": "http://localhost:11434",
      "request_options": { "timeout": 1000 },
      "provider": "ollama"
    },`

GPT 3.5 is working as expected, but "/edit" with intellij is not working. Normal chat is working.

Kind Regards,
Jörg

**Comment by azthec** [comment]
This is my complete config, only the mistral object in the models was added by me, everything else was auto generated.

<details>

```json
{
  "models": [
    {
      "title": "GPT-4",
      "provider": "openai-free-trial",
      "model": "gpt-4"
    },
    {
      "title": "GPT-3.5-Turbo",
      "provider": "openai-free-trial",
      "model": "gpt-3.5-turbo"
    },
    {
      "title": "mistral",
      "provider": "ollama",
      "model": "mistral-7b"
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit highlighted code",
      "step": "EditHighlightedCodeStep"
    },
    {
      "name": "comment",
      "description": "Write comments for the highlighted code",
      "step": "CommentCodeStep"
    },
    {
      "name": "share",
      "description": "Download and share this session",
      "step": "ShareSessionStep"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command",
      "step": "GenerateShellCommandStep"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "Write a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    { "name": "diff", "params": {} },
    {
      "name": "open",
      "params": {}
    },
    { "name": "terminal", "params": {} }
  ]
}
```

</details>

**Comment by sestinj** [comment]
@SommerEngineering @azthec @jkritzen I found the problem with the timeout and have solved it in version 0.0.27. Unfortunately JetBrains tends not to accept plugin updates on weekends, so it won't be available through the store until Monday, but in the meantime you can install manually this .zip file by clicking the gear icon at the top of the plugin settings page and then "Install from Disk".

Would also be useful to get confirmation (or the opposite) that this actually solves the issue for you all

[continue-intellij-extension-0.0.27.zip](https://github.com/continuedev/continue/files/13846879/continue-intellij-extension-0.0.27.zip)

**Comment by azthec** [comment]
@sestinj I can confirm that it works properly now, you can close this issue

On a side note I've noticed its very hard to search the IntelliJ plugin list and find this project, at least in the built in plugin installer, which is what I assume most people use.

**Comment by SommerEngineering** [comment]
Wonderful, it now works flawlessly. Thank you very much.

**Comment by sestinj** [comment]
@azthec Do you mean the plugin store, or something else?

**Comment by azthec** [comment]
Yes, I am not sure if this can be improved with some sort of SEO or tags on your end
