### ISSUE TITLE
VScode extension won't start with versions 0.6.17 and 0.6.18 (lastest release)

### ISSUE THREAD

**Issue by stduhpf** [continuedev/continue#722]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 22H2
- Continue: 0.6.17+
- IDE: VSCode 1.81.1
```

### Description

After updating, the continue tabs shows up on the side, but it keps loading forever. Using any continue commands result in this kind of errors: 
`command 'continue.focusContinuelnput' not found` 
Rolling back to 0.6.15 fixes it.

**Comment by sestinj** [comment]
@stduhpf Before rolling back did you have a chance to look into the logs?

My first guess (though admittedly not much information to go off of) is that this could be a Node version incompatibility. If you click the About menu for VS Code, could you share what version of Node.js it is running on? For example, this is the version information shown for me:


```
Version: 1.86.0-insider (Universal)
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:38:07.020Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by stduhpf** [comment]
Oh, I am on Node 18.15, but I just noticed my VSCode itself was out of date (isn't it supposed to install updates automatically?), I updated VSCode, and now the extension works with recent versions. Thank for making me double check!
