### ISSUE TITLE
`continue_tutorial.py` file opens every time I restart a JetBrainsIDE

### ISSUE THREAD

**Issue by jonmatthis** [continuedev/continue#726]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.0.26
```

### Description

Even when I delete the file, it gets re-downloaded

its driving me crazy lol 

seems to happen in PyCharm and Webstorm, but not VS Code

Presumably related to this: 

https://github.com/continuedev/continue/blob/1cad8b3f4ba54754b383a6d58d731d67b3e7767e/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt#L139

Proposed fix: 

Only open on first install or something like that 

### To reproduce

1. Install Continue Plugin on PyCharm or Webstorm
2. Restart IDE, see that the dang file popped up again
3. Right click, show in explorer, delete
4. Restart IDE, and its back!
5. :despair:

**Comment by sestinj** [comment]
Fixed and will be included in the next version! If anyone comes along before then and is bothered by it, here's a version you can install from disk with the fix:

[Uploading continue-intellij-extension-0.0.27.zip…]()

**Comment by sestinj** [comment]
This version is now available on the store in version 0.0.27
