### ISSUE TITLE
Adding mixtral creates wrong config

### ISSUE THREAD

**Issue by johannesmichael** [continuedev/continue#727]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: WSL2
- Continue: v0.8.0
- IDE: VS Code 1.85.1
- Ollama: 0.1.17
```

### Description

In Ollama I ran `ollama run mixtral`
In Continue I added Mistral 8x7b (MoE). 
It did not work until I changed the config.json  to
`{
      "title": "Mixtral",  
      "model": "mixtral",  
      "contextLength": 2048,  
      "completionOptions": {},  
      "apiBase": "http://localhost:11434",  
      "provider": "ollama"  
    }`

instead of 
`{
      "title": "Mixtral",  
      "model": "mistral-8x7b",  
      ....
    }`

Now working fine

**Comment by sestinj** [comment]
Thanks for the report. I've added the necessary mapping from mistral-8x7b to it's translated name in Ollama to solve the issue. It's now available in version 0.8.2 of the VS Code extension
