### ISSUE TITLE
Using @files fails to get context

### ISSUE THREAD

**Issue by AndrewKahr** [continuedev/continue#746]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10/11
- Continue: v0.8.1
- IDE: VSCode v1.85.1 (Both a system and user install)
- Model: GPT4 Trial and CodeLlama
- Ollama: v0.1.20
```

### Description

When I try to reference a file in the workspace, it fails with the error `Unknown provider <path/to/my/file.txt> Existing providers: file, diff, open, terminal.` This is followed by an info log of my query `What does @file.txt do`. Finally, there's an error message after that saying `Error getting context items from <path/to/my/file.txt>: Cannot read properties of undefined (reading 'description'). This is in a fresh install of continue on both Windows 10 and Windows 11 with VsCode installed in both a user and a system context. Other providers like `open files` work and provide the context correctly. I also randomly get the following error when starting the file query:
```Uncaught (in promise) Error: MiniSearch: duplicate ID <path/to/another/file/in/workspace/file.txt>
   at I.add (index.js:1626:10187)
   at I.addAll (index.js:1626:11130)
   at index.js:1626:31274
```

### To reproduce

1. Install continuedev
2. Open a workspace with files inside
3. Try a query like `What does @file.txt do`
4. Errors should be thrown and the response will have nothing related to the specified file

**Comment by sestinj** [comment]
@AndrewKahr This is now fixed in pre-release version 0.9.15. I'll keep the issue open until you can confirm

**Comment by sestinj** [comment]
Closing the issue, but please let me know if this somehow persists

**Comment by AndrewKahr** [comment]
Can confirm this is now working. Thanks for the fix!
