### ISSUE TITLE
Unable to scroll inside code snippet while generation is in progress

### ISSUE THREAD

**Issue by abhinavkulkarni** [continuedev/continue#747]
Hi,

In VSCode, while a long generation is in progress to a given prompt, I'm unable to scroll up/down (or sideways) in the code snippet.

Often times, the model will output a wordy conclusion after generating the code prefix I'm interested in. I simply want to inspect it and copy it over to my code.

This may be happening because we may be continuously updating the UI while we are receiving output from the model server in a streaming fashion.

Instead of updating the entire UI, we should only update whichever Markdown element is being populated.

Thanks!

**Comment by sestinj** [comment]
> This may be happening because we may be continuously updating the UI while we are receiving output from the model server in a streaming fashion.

This is exactly it. It's in the plans to write incremental Markdown parsing. Wasn't planning this week, but if I happen to find a library that can do it I'll make the update

**Comment by sestinj** [comment]
@abhinavkulkarni This is now solved in version 0.9.30
