### ISSUE TITLE
LMstudio errors on empty assistent message

### ISSUE THREAD

**Issue by thomas9911** [continuedev/continue#750]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: 0.8.1
- Python: 3.11.3
- IDE: 1.85.1
- LMStudio: 0.2.10
```

### Description

continue in vs code seems to send an empty assistant message and lmstudio gives a validation error on it

### To reproduce

1. download any model in LMStudio
2. start local server in LMStudio
3. do any request via vs code to LMStudio
4. error message in the logs of lm studio

### Log output

```Shell
[2024-01-14 14:29:35.808] [INFO] Received POST request to /v1/chat/completions with body: {
  "messages": [
    {
      "role": "user",
      "content": "lol"
    },
    {
      "role": "assistant",
      "content": ""
    },
    {
      "role": "user",
      "content": "lol"
    },
    {
      "role": "assistant",
      "content": ""
    },
    {
      "role": "user",
      "content": "lol"
    },
    {
      "role": "assistant",
      "content": ""
    },
    {
      "role": "user",
      "content": "hallo"
    },
    {
      "role": "assistant",
      "content": ""
    },
    {
      "role": "user",
      "content": "lol"
    }
  ],
  "model": "wizardcoder-7b",
  "max_tokens": 1024,
  "stream": true
}
[2024-01-14 14:29:35.808] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}
```
```

**Comment by sestinj** [comment]
@thomas9911 Is the problem a) that the assistant messages are *not* empty in the UI but become empty in the messages array, or b) that you don't get responses, leading to empty space in the UI *and* the messages array?

**Comment by poldrack** [comment]
I'm having the same problem - @sestinj LMK how to answer that question to @thomas9911  (as I don't see the relevant info in the logs) and I will have a look

**Comment by sestinj** [comment]
@poldrack if (b) is happening then you should see something like this (an empty space with no response between two input boxes):

<img width="469" alt="Screen Shot 2024-01-28 at 2 31 53 PM" src="https://github.com/continuedev/continue/assets/33237525/41f7799b-6366-4374-bfd2-efb28de76dd0">

If that's the case then it's a quick fix, and perhaps I should have even just done this before.

Tangentially, I thought your profile picture was the Unknown Pleasures album cover, but seems it's either a different version or just a very similar display of some random signal?

**Comment by sestinj** [comment]
I just released a new version that would solve (b) by simply replacing any empty messages with `" "`

**Comment by poldrack** [comment]
awesome, just reloaded the VSCode extension and it works properly now.  spaces FTW!  Thanks for fixing this so quickly.

Funny that you noticed the profile picture - it was generated by a member of my group using a [large dataset](http://www.myconnectome.org/) collected from my brain about a decade ago.  I can't remember what it's the distribution of, but each row is based on data from a different day across the study.

**Comment by sestinj** [comment]
Nice!

Oh this is really cool. The member did a good job of transforming to something that resembles pulsar emissions. Rabbit-holing about MyConnectome now...

Closing the issue, cheers!

**Comment by dipteshbosedxc** [comment]
I think this issue requires further investigation. I received this error in LM Studio while using with AutoGen Studio

[2024-02-02 05:19:08.022] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}

**Comment by serkanh** [comment]
Yeah got the same error.
`[2024-02-02 20:07:14.709] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}`
<img width="1371" alt="image" src="https://github.com/continuedev/continue/assets/947426/cbd6a1b5-96b5-4588-9e99-e9a546ceb64c">
