### ISSUE TITLE
Could the continue extension provide suggestions as "ghost text" based on existing code LLMs?

### ISSUE THREAD

**Issue by bill315lee** [continuedev/continue#757]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

**Comment by sestinj** [comment]
Hi @bill315lee, we are beginning work on this feature now in https://github.com/continuedev/continue/pull/758! There's already an open issue for this so I'm going to close this as a duplicate and refer to there, where I'll keep everyone updated on progress. Thanks for the +1!
