### ISSUE TITLE
fetch(...) requests are failing in vscode for external urls

### ISSUE THREAD

**Issue by frblondin** [continuedev/continue#762]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows_NT x64 10.0.19045
- Continue:v0.9.19
- VSCode: 1.85.2 (system setup)
- Electron: 25.9.7
- ElectronBuildId: 26354273
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
```

### Description

window.fetch is [being replaced](https://github.com/continuedev/continue/blob/preview/gui/src/main.tsx) by [proxyFetch](https://github.com/continuedev/continue/blob/preview/core/util/index.ts#L29).

This seems to break access to external urls.

### To reproduce

1. Make sure that url context provider gets declared in config.json
2. Add ```@url https://www.google.com Some text```
3. You should get an error ```TyperError: fetch failed```

**Comment by sestinj** [comment]
@frblondin I made a change so that context providers are now run from the IDE rather than browser, so that proxyFetch isn't needed. Soon I hope to entirely phase out the need for the proxy server. Can you confirm that this resolves the problem?

**Comment by frblondin** [comment]
@sestinj I did a full reset of my ~/.continue folder and I am still getting errors. Please let me know if I did something wrong:
1. Renamed `~/.continue` folder to `~/.continue.old` so that extension extension environment gets re-created
2. Edited the `continue.ts` file with content provided by documentation:
``` js
const RagContextProvider = {
  title: "rag",
  displayTitle: "RAG",
  description:
    "Retrieve snippets from our vector database of internal documents",

  getContextItems: async (query: string, extras: ContextProviderExtras) => {
    const response = await fetch("https://internal_rag_server.com/retrieve", {
      method: "POST",
      body: JSON.stringify({ query }),
    });

    const results = await response.json();

    return results.map((result) => ({
      title: result.title,
      description: result.title,
      content: result.contents,
    }));
  },
};

export function modifyConfig(config: Config): Config {
  // Had to fix this part, see other request #763
  if (config.contextProviders) {
    config.contextProviders.push(RagContextProvider);
  }
  return config;
}
```
3. I am getting following error when trying to use @rag: `Error handling message from Continue side panel: TypeError: fetch failed`

I have to add [node-fetch](https://www.npmjs.com/package/node-fetch) with no success.

**Comment by frblondin** [comment]
Actually, I just saw that I am getting this error even after disabling the custom provider:
- OS:Windows_NT x64 10.0.19045
- Continue: v0.9.23
- VSCode: 1.85.2 (system setup)
- Electron: 25.9.7
- ElectronBuildId: 26354273
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0

**Comment by frblondin** [comment]
My bad, I re-created a new `~/.continue` folder and forgot to re-configure the models properly.
