### ISSUE TITLE
When rejecting the LLM's response before it's finished, the `llama.cpp` server keeps generating tokens

### ISSUE THREAD

**Issue by ibehnam** [continuedev/continue#764]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: 0.8.1
```

### Description

Rejecting the LLM's response while it's streaming doesn't stop the LLM. The LLM still keeps generating the rest of the response (draining battery via high GPU usage).

### To reproduce

1. Ask a question from the LLM served by `llama.cpp`.
2. When it starts streaming, reject the answer via `CMD-BACKSPACE` or your custom shortcut.
3. The `llama.cpp` server keeps generating the rest of the response even though you already rejected it and can't see the rest of the response.

**Comment by D0ctorWh0** [comment]
Same for me with LM Studio

**Comment by sestinj** [comment]
@D0ctorWh0 @ibehnam Working on solving this today - it aligned with a few larger changes we needed to make which is why it's not just being fixed immediately. Hope to update very soon!

**Comment by sestinj** [comment]
@D0ctorWh0 @ibehnam I forgot to update when we fixed this, but it has now been fixed for 1-2 weeks. Let me know if you see any further problems, happy to re-open this if needed!
