### ISSUE TITLE
Quick editing a block of code, when the first line of the selection is empty results in error and empty diff

### ISSUE THREAD

**Issue by TopSalad3530** [continuedev/continue#767]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Arch Linux
- Continue: 0.9.22
```

### Description

Quick editing a block of code, when the first line of the selection is empty, results in empty diff and `TypeError: Cannot read properties of undefined (reading 'length')` in `dedentAndGetCommonWhitespace`.

https://github.com/continuedev/continue/blob/76b9c08e94ad4ac195be079c5eb379bf559926b9/core/util/index.ts#L53 assumes that the first line is non-empty, but https://github.com/continuedev/continue/blob/76b9c08e94ad4ac195be079c5eb379bf559926b9/core/util/index.ts#L48 only guards against the case where exactly one empty line is selected.

### To reproduce

1. Select a block of code, including the leading empty line.
2. Ctrl+Shift+L, any prompt.
3. Press enter.

**Comment by sestinj** [comment]
@TopSalad3530 Thanks for digging into the details here. This is now fixed with https://github.com/continuedev/continue/commit/c2fb247a73af3d5b212f5f1b2237402b713c6dfa and the following commit. Will be released to pre-release extension later today
