### ISSUE TITLE
Adding a built-in "@pinned" context provider for pinned files.

### ISSUE THREAD

**Issue by sndwav** [continuedev/continue#771]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently, we need to play around with closing/opening files in order to use the "@open" context provider.

### Solution

Adding a "@pinned" context provider will allow us to have a lot of opened files, but use only a subset of those (the files that we have pinned).

**Comment by sestinj** [comment]
@sndwav This is now available in the pre-release extension, v0.9.26. I decided to add an option to the existing "open" context provider, so it can be setup like this:

```json
{
      "name": "open",
      "params": {"onlyPinned": true}
}
```
