### ISSUE TITLE
`/share` borks with [object Object] instead of conversation contents

### ISSUE THREAD

**Issue by pcuci** [continuedev/continue#776]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: pre-release version
- IDE: VS Code
```

### Description

On `/share`, this is what gets generated:

``` md
This is a session transcript from [Continue](https://continue.dev) on 1/24/2024, 1:56:33 PM.

## User

[object Object]

## Continue

[object Object]

## User

[object Object]

## Continue

[object Object]

## User

[object Object]

## Continue

### To reproduce

Try `/share` 

```

**Comment by sestinj** [comment]
Yes, yes it does. This would be an unintended consequence of changes for our up and coming image support. Will be solved in next pre-release. Thanks for the heads up! (and for being the original person to suggest doing a pre-release so that problems like this can be caught)
