### ISSUE TITLE
Model Provider config: Mistral 7b generates WizardCoder 

### ISSUE THREAD

**Issue by seplee** [continuedev/continue#781]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: v0.8.3
- IDE: vscode
```

### Description

If I select Mistral 7b, under `Other OpenAI Compatible API`, and I click Mistral 7b, a json object is generated with the WizardCoder template.
I can fix this if you tell me where in the codebase to look.

### To reproduce

![continue-wizard-coder-bug](https://github.com/continuedev/continue/assets/96065267/4b989eef-4a3e-4e78-9ba1-32f82efb52fc)

**Comment by sestinj** [comment]
@seplee Yeah, thanks for finding this! It is in the file `gui/src/modelData.ts`. Actually someone else (unless you are waterbear in Discord) also found this and shared the exact line of code: https://github.com/continuedev/continue/blob/61b90d562554172ad3cde7e83b3b2c8c5a296bb8/gui/src/util/modelData.ts#L295

**Comment by sestinj** [comment]
Solved in 0.9.34!
