### ISSUE TITLE
Slash commands should run in ide just like context provider

### ISSUE THREAD

**Issue by frblondin** [continuedev/continue#787]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

See #762 issue as a reference. As opposed to context providers, slash commands are still executed in the browser. This prevents me from properly using NodeJS libraries.

I need to get the input, use the llm, and also interact with some NodeJS libraries. From within the command, I also need to access the filesystem. This is only possible if running in NodeJS istead of browser.

### Solution

Please improve continue so that slash commands are also run in NodeJS instead of electron browser.

**Comment by sestinj** [comment]
@frblondin Totally agreed. As mentioned in the other issue I'm working on making this happen.

For now, we actually have two options that might partially solve your problem:
1. Use `sdk.ide`, which is passed to the `run` method of a slash command and gives you access to many methods like reading/writing files, running commands, etc...
2. There is a `runInNodeJs` option on slash commands that will do what you want. Same "dynamic import" rules apply until I make the change

```ts
export interface SlashCommand {
  name: string;
  description: string;
  params?: { [key: string]: any };
  run: (sdk: ContinueSDK) => AsyncGenerator<string | undefined>;

  // If true, this command will be run in NodeJs and have access to the filesystem and other Node-only APIs
  // You must make sure to dynamically import any Node-only dependencies in your command so that it doesn't break in the browser
  runInNodeJs?: boolean;
}
```

**Comment by sestinj** [comment]
@frblondin This is now the default behavior. Closing the issue, but we still have the other open in case you run into any related problems
