### ISSUE TITLE
code block font should use editor.fontFamily by default

### ISSUE THREAD

**Issue by yuuuxt** [continuedev/continue#797]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: win10 x64
- Continue: v.0.8.6
- IDE: vscode
```

### Description

currently the code block looks like this (the font is a default font, not what I'm using in vscode):
![图片](https://github.com/continuedev/continue/assets/3153534/2909c4f4-c7db-40e7-9869-519c6809c759)
which applies this css:
![图片](https://github.com/continuedev/continue/assets/3153534/ff7a4b6f-6fbb-45a0-9133-31303b23f745)

so it uses `--monaco-monospace-font` as the default font.  I think the best default setting should be `editor.fontFamily`, i.e. `--vscode-editor-font-family`. 

(I tried to search `--monaco-monospace-font` in this repo but didn't find a match)

### To reproduce

1. use arbitrary model to generate some chat that contains a code block 
2. check the css (and try to modify it as described)

### Log output

```Shell
(NA)
```

**Comment by sestinj** [comment]
@yuuuxt Looks *really* nice after doing this, thanks for taking the time to find the variable! It'll be in the next release today

**Comment by yuuuxt** [comment]
Feels it can also be applied here (inline `<code>`):
![图片](https://github.com/continuedev/continue/assets/3153534/d25c1eab-6c98-429a-b093-4808ef44ecb2)
![图片](https://github.com/continuedev/continue/assets/3153534/e0f7e484-7f38-4565-9585-696bc34b5dfa)
![图片](https://github.com/continuedev/continue/assets/3153534/71ac5ed4-c0a7-4e65-a19a-e5f06d7e018c)

**Comment by yuuuxt** [comment]
Also, I want the chat font to be `var(--vscode-font-family)`, so that it is consistent with the rest of vscode. What do you think?

![图片](https://github.com/continuedev/continue/assets/3153534/d25c1eab-6c98-429a-b093-4808ef44ecb2)

https://github.com/continuedev/continue/blob/e1291969278597febdf0cce7ce3c9e70fe9dbe95/gui/src/components/markdown/StyledMarkdownPreview.tsx#L62
