### ISSUE TITLE
Don't automatically append /v1 to OpenAI API bases which are missing it

### ISSUE THREAD

**Issue by najork** [continuedev/continue#798]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

You're currently automatically appending `/v1` to OpenAI API bases which are missing it [0], which causes issues when the downstream server isn't expecting `/v1` in the path. There's already an exception for `api.perplexity.ai` and we're hitting the same issue at Radiant when trying to route `continue.dev` requests through our backend to OpenAI. 

[0] https://github.com/continuedev/continue/blob/74c1eb5e25c517c575f72d26227d31d5d2ea18ed/core/llm/llms/OpenAI.ts#L90-L92

### Solution

I'd recommend removing this logic in favor of requiring whomever is configuring the API base to include the `/v1` as required.

**Comment by sestinj** [comment]
@najork Fair enough! I thought this was somewhat rare, but two examples is more than enough to convince me otherwise.

And an informative error message is probably the right way to provide users with guide-rails.

Going to push this change to pre-release in just a minute

**Comment by sestinj** [comment]
@najork This is now released in both the main and pre-release extension (changes here: https://github.com/continuedev/continue/commit/de8ccb0ac856bb2a0bf61ac863941c4bd638a09f)

**Comment by najork** [comment]
Woohoo! Thanks for the quick turnaround.

**Comment by anjor** [comment]
@sestinj When do you think this will be released in the jetbrains plugin?

**Comment by sestinj** [comment]
@anjor This is now available in 0.0.33
