### ISSUE TITLE
IntelliJ, control J and control shift J shortcuts removed from custom action

### ISSUE THREAD

**Issue by philstutz** [continuedev/continue#806]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04
- Continue: 0.0.27
- IDE: PhpStorm 2024.1 EAP
```

### Description

Plugin works like a charm :+1: Thanks!

I have the two shortcuts control J and control shift J assigned to other actions, these are unconditionally removed on startup:

```kotlin
        removeShortcutFromAction(getPlatformSpecificKeyStroke("J"))
        removeShortcutFromAction(getPlatformSpecificKeyStroke("shift J"))
```

[ContinuePluginStartupActivity.kt:86
](https://github.com/continuedev/continue/blob/main/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt#L86)

The shortcut definitions [here](https://github.com/continuedev/continue/blob/main/extensions/intellij/src/main/resources/META-INF/plugin.xml) should be sufficient.

### To reproduce

1. Install the extension
2. Reassign control J to another action
3. Restart the IDE
4. Control J is removed from the other action

**Comment by sestinj** [comment]
@philstutz Are you hoping that the other actions will co-exist with Continue, or that they should be overriding Continue?

Because there is by default a built-in shortcut for cmd/ctrl + J, it turned out that we actually had to do more than just setting the definition in the XML file you linked.

**Comment by philstutz** [comment]
Yes, that would be an option. I think it's fine to grab the shortcut unconditionally on install, but not on restart. That feels a bit intrusive.

(There seems to be no unused `ctrl + <alpha>` shortcut in the default keymap, so no other options.)

**Comment by sestinj** [comment]
Great, thanks for your input. Next release is scheduled for roughly early next week, so we'll add that in then

**Comment by sestinj** [comment]
This was released a ways back and I haven't heard anything since, so going to close. If I'm mistaken please feel free to re-open!
