### ISSUE TITLE
Error Installing New Dependency on Intel Mac Due to Unsupported Platform

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#817]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: 0.9.46
- IDE: VSCode
```

### Description

commit 59f4111875fe90562f7ff0b0709096c74a14a1e9 added a new dependency, which causes an error during installation on Intel Mac.

```json
"@lancedb/vectordb-darwin-arm64": "^0.4.8",
```

### To reproduce

1. Git clone this repo
2. Run the task `install-all-dependencies` with an intel mac
3. Notice it fails

### Log output

```Shell
Installing VSCode extension dependencies...
~/Developer/continue/extensions/vscode ~/Developer/continue
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @lancedb/vectordb-darwin-arm64@0.4.8: wanted {"os":"darwin","cpu":"arm64"} (current: {"os":"darwin","cpu":"x64"})
npm ERR! notsup Valid os:   darwin
npm ERR! notsup Actual os:  darwin
npm ERR! notsup Valid cpu:  arm64
npm ERR! notsup Actual cpu: x64

npm ERR! A complete log of this run can be found in: /Users/paria/.npm/_logs/2024-02-03T05_35_09_495Z-debug-0.log
```

**Comment by sestinj** [comment]
Has been removed, thanks
