### ISSUE TITLE
Feat Request: Better prompt iteration with ctrl+shift+L in VSCode

### ISSUE THREAD

**Issue by steverhoades** [continuedev/continue#820]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When typing a long prompt using ctrl+shift+L in VSCode there are times where the LLM doesn't quite get it right. When this happens it often requires some iteration. Currently one needs to start over in order to achieve the desired result.

### Solution

Allow for a continuation of the last prompt e.g. "edit". Especially if the last result was rejected. It could be a nice setting to perhaps have a reject all and edit shortcut?

**Comment by sestinj** [comment]
@steverhoades this feature now exists by using ctrl+shift+L again after generation is complete. It will clear all edits and re-edit the same range

**Comment by peter-ch** [comment]
I'm not sure if this is the same exact thing, but sometimes when using a local LLM or whatever else reason there is an error, the prompt is lost and I need to type it all over again. Can you add some sort of history so I can bring back the last entered prompt with the Up arrow or something?

**Comment by sestinj** [comment]
History now exists, as does cmd+I for re-edits, so I'm going to close this issue
