### ISSUE TITLE
Can't work on remotes anymore with VSCode

### ISSUE THREAD

**Issue by surak** [continuedev/continue#828]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Mac
- Continue: v0.9.49 (pre-release)
- IDE: VSCode
```

### Description

When running in a remote host, Continue tries to get the local config file.

```
Error loading config.json. Please check your config.json file: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, scandir '/p/haicluster/llama/FastChat'
```

where this scandir is actually from the remote and not from where VSCode is running

### To reproduce

Use the pre release version
Connect to an ssh host
things stop working

<img width="788" alt="Screenshot 2024-02-06 at 19 38 02" src="https://github.com/continuedev/continue/assets/878399/36da8843-ba07-4e53-aab6-d478a052846d">

**Comment by surak** [comment]
Also mentioned on #807

**Comment by sestinj** [comment]
@surak thanks for bringing this up, I'll solve this morning if possible.

**Comment by surak** [comment]
Works for me on 0.9.54!
