### ISSUE TITLE
Confirm deletion of models in dialog

### ISSUE THREAD

**Issue by simonbukin** [continuedev/continue#832]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently, deleting a model from the Continue sidebar is as simple as clicking the delete icon in the selection dialog. I accidentally deleted a model this way, as the trash can icon shows up on hover and isn't persist.

![Screenshot 2024-02-07 at 2 37 27 PM](https://github.com/continuedev/continue/assets/8992420/ff9cb131-583d-4011-b6c5-8ef51ae2940b)

### Solution

I think there is a simple solution here, and another that has a better user experience.

- Option 1 -> Show trash can icon persistently, instead of on hover. This is a quick fix, and would solve the accidental click problem if a user isn't expecting something to show up on hover.
- Option 2 -> Show a confirm dialog on deletion. I think this would be a cleaner user experience, as this is a destructive action and should be confirmed before being executed.

I'd be happy to contribute these changes, but just wanted to check if my initial thoughts here were warranted.

**Comment by sestinj** [comment]
@pjv @simonbukin there is now a confirmation dialog in the latest pre-release. Thanks for the suggestion here!
