### ISSUE TITLE
Issue while setting up continue code locally

### ISSUE THREAD

**Issue by samin-batra** [continuedev/continue#837]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: 
- IDE: VS Code
```

### Description

I am trying to setup continue locally by pulling the code and installing the dependencies. I am following the steps mentioned here: https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#environment-setup/
However, when I run the task to install the dependencies, it fails saying that directory extensions/vscode/bin/napi-v3/darwin/arm64 is not empty. However, when I navigate to this directory, I see it is empty. 

### Log output

```Shell
Error: ENOTEMPTY: directory not empty, rmdir 'continue\extensions\vscode\bin\napi-v3\darwin\arm64'
    at Object.rmdirSync (node:fs:1219:11)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmdirSync (node:fs:1213:14)
    at continue\extensions\vscode\scripts\prepackage.js:145:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'continue\\extensions\\vscode\\bin\\napi-v3\\darwin\\arm64'
}

Node.js v20.11.0
```

**Comment by ChristophRaab** [comment]
Any updates on this? I am facing the same issue..

**Comment by sestinj** [comment]
Now solved in both preview and main
