### ISSUE TITLE
Unable to stop Indexing of files via UI

### ISSUE THREAD

**Issue by bufferoverflow** [continuedev/continue#845]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: any
- Continue: v0.9.61 (pre release)
- IDE: vscode
```

### Description

Unable to stop Indexing of files.

### To reproduce

1. setup a large project, e.g. 
https://gitlab.com/gitlab-org/gitlab-development-kit
1. See the indexer using huge amount of CPU
2. Cry because there is no option to stop indexing via UI

**Comment by sestinj** [comment]
@bufferoverflow Currently, you can stop the indexing by setting `"disableIndexing": true` in `config.json`. But you bring up a great point that this should be possible through the UI. I can make this happen, and then hopefully no more need for tears : )

**Comment by bufferoverflow** [comment]
@chasegiunta It's just next to the model selection within the UI

**Comment by sestinj** [comment]
@chasegiunta here is what Continue should look like during indexing. If you try the latest pre-release version you will be able to pause it by clicking. Alternatively you can always set `"disableIndexing": true` in `config.json`. We are working on a way of taking up fewer resources

<img width="424" alt="Screenshot 2024-02-29 at 3 51 06 PM" src="https://github.com/continuedev/continue/assets/33237525/da2ab64a-d8f3-465e-93ad-c455516ed26a">

**Comment by sestinj** [comment]
now that it's possible to pause from the UI, I'm going to close this issue and point to https://github.com/continuedev/continue/issues/856 for the actual underlying issue of using too many resources
