### ISSUE TITLE
Reevaluate method for adding icon for config files

### ISSUE THREAD

**Issue by jaminthorns** [continuedev/continue#848]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Thank you so much for the work on this project!

I was initially going to create a bug report for the appearance of the `config.json` icon on macOS:

![Screenshot 2024-02-12 at 5 06 13 PM](https://github.com/continuedev/continue/assets/6618434/37528f80-9a99-4980-a876-c30fc036c921)

But then I found the code that adds this icon:

https://github.com/continuedev/continue/blob/eeab4fd8b2b905d3277ad6f8376ba77825087bff/extensions/vscode/src/activation/activate.ts#L150-L183

As I read the code, this is editing the icon theme defined in another extension (I'm guessing a core extension when the user has the default icon theme selected). These changes persist even after Continue is uninstalled, since it involves manually editing extension files. Since I use the default icon theme, I'm not even sure how to undo these changes. Maybe the next VS Code update will fix it? I'm not sure.

### Solution

I find this behavior very invasive, and I'd prefer if it were removed. I understand that it might be the only way to get a custom icon for Continue's configuration files, but I don't think this approach is worth it. As this is my first time looking at the source code for this project, I would hope that this is the only instance of code like this (making permanent modifications to files outside of Continue's scope). If there are, then I kindly ask for those to be reevaluated as well.

I don't mean to come off as scolding, as I really do appreciate this extension and the work that's being done on it. It's just that I don't feel comfortable using or recommending an extension that behaves in this way.

**Comment by sestinj** [comment]
@jaminthorns you make a fair point. I also wasn't aware of this ugly trimming, and wouldn't have added the icon if I knew it wouldn't display nicely on all computers. And it is in fact the only place where we make such edits to VS Code-related files (or any files not originally created by Continue).

This will be removed in the pre-release version that I'm shipping later today

If we ever find a more reliable way of icons, perhaps we'll give it another attempt

As for how to remove this, you can find the theme icon extension you are using in `~/.vscode/extensions` and then edit the .json file to remove the continue entries

**Comment by jaminthorns** [comment]
Thank you for seeing my viewpoint and making that change, I really appreciate it!
