### ISSUE TITLE
Code Llama tab completion having EOT Token present

### ISSUE THREAD

**Issue by arthurcohen** [continuedev/continue#867]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS Sonoma 14.3.1
- Continue: v0.9.65 (pre-release)
- IDE: VSCode 1.86.2
- Model: codellama:7b-code
```

### Description

After setting up Continue with the Ollama provider, I enabled Tab Autocomplete and it mostly works fine. The issue is that the autocomplete feature is always adding at the end an `<EOT>` regardless of the settings I tried using. I believe this string is called End-Of-Text token, and it is referenced on the [tokenization file](https://github.com/huggingface/transformers/blob/ce4fff0be7f6464d713f7ac3e0bbaafbc6959ae5/src/transformers/models/code_llama/tokenization_code_llama.py#L92) inside the model repository.

The issue seems to happen with suggestions that usually come up as one-liners and multi-line suggestions are showing up fine so far.

### To reproduce

1. Install [Ollama](https://ollama.com/)
2. Pull the codellama model: `ollama pull codellama:7b-code`
3. Install Continue on VSCode
4. Setup Ollama provider integration:
4.1 For reference
```json
{
  "models": [
    {
      "model": "AUTODETECT",
      "title": "Ollama",
      "completionOptions": {},
      "apiBase": "http://localhost:11434",
      "provider": "ollama"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "ollama",
    "model": "codellama:7b-code",
  },
  ...
}
```
5. Go to any file and start typing, you'll see this:
![image](https://github.com/continuedev/continue/assets/7649727/796ef1a0-faa0-4e1b-b05c-0c63b37a8d31)

```typescript
const UserSchema = object({
  id: z.number(),
  name: z.string(),
  lastName: z.string(), <EOT> // this was added by the autocomplete
  email: z.string(),
  picture: z.string(),
  password: z.string(),
})
```

**Comment by sestinj** [comment]
@arthurcohen I will add this to the list of stop tokens for the next release, but if you want a quick fix you can set "tabAutocompleteModel.completionOptions.stop": ["<EOT>"]

**Comment by arthurcohen** [comment]
Awesome, that suffices my problem. Thanks, @sestinj!
