### ISSUE TITLE
[CON-44] Parse tracebacks in multiple languages - start with python and javascript? Or

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#87]
We have some of this in the DLT thing, just need to make more reliable and include other languages

See ValidatePipelineStep/steps line 91. Write a function that takes the output of a command that was run (str) and returns either None if no traceback, or the string of the traceback if there was. Make a (separate) function like this for javascript and python.

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-44](https://linear.app/continue/issue/CON-44/parse-tracebacks-in-multiple-languages-start-with-python-and)</sub>

**Comment by TyDunn** [comment]
Used Continue to generate first attempts at these
