### ISSUE TITLE
Ollama with  Codellama 7b not working

### ISSUE THREAD

**Issue by ajasingh** [continuedev/continue#882]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
MacOs
- Continue:
- IDE:
VS Code
```

### Description

I tried to configure Configure Ollama with Codellama 7b but i keep on getting http://localhost:11434/v1/api/chat url not found. I have confirmed my ollama server is running

**Comment by MattyRad** [comment]
I was getting 404 errors from using Ollama 0.1.10, I upgraded to Ollama 0.1.28 and the errors messages were improved, giving a better 400 error response description. I suggest checking your ollama version is up to date.

**Comment by sestinj** [comment]
@ajasingh MattyRad is correct that this will be resolved by upgrading your version of Ollama. I'm going to close the issue, but feel free to re-open or message me in Discord if you continue to see problems
