### ISSUE TITLE
Extension doesn't work on Aarch64

### ISSUE THREAD

**Issue by thebabush** [continuedev/continue#887]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: linux-arm64
- Continue: master
- IDE: vscode
```

### Description

`prepackage.js` uses `if (ghAction() && isArm)` then downloads the latest version of your esbuild binary. However, this leads to the following error message on my machine (ubuntu arm64).

Changing to `if (ghAction() && false && isArm)` works, but obviously the real fix would be a better implementation of `ghAction()`.

### Log output

```
$ vsce package
(node:119440) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 INFO  Detected presence of yarn.lock. Using 'yarn' instead of 'npm' (to override this pass '--no-yarn' on the command line).
Executing prepublish script 'yarn run vscode:prepublish'...
yarn run v1.22.21
warning continue@0.8.14: The engine "vscode" appears to be invalid.
$ npm run esbuild-base -- --minify

> continue@0.8.14 esbuild-base
> node esbuild.js --minify

\u2718 [ERROR] Cannot start service: Host version "0.17.19" does not match binary version "0.19.11"

1 error
/home/ubuntu/src/continue/extensions/vscode/node_modules/esbuild/lib/main.js:1073
        return callback(new Error(error), null);
                        ^

Error: The service was stopped: write EPIPE
    at /home/ubuntu/src/continue/extensions/vscode/node_modules/esbuild/lib/main.js:1073:25
    at responseCallbacks.<computed> (/home/ubuntu/src/continue/extensions/vscode/node_modules/esbuild/lib/main.js:697:9)
    at afterClose (/home/ubuntu/src/continue/extensions/vscode/node_modules/esbuild/lib/main.js:687:28)
    at /home/ubuntu/src/continue/extensions/vscode/node_modules/esbuild/lib/main.js:2129:11
    at onwriteError (node:internal/streams/writable:597:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by sestinj** [comment]
@thebabush Thanks for reporting this! I just switched the function to use GitHub's default GITHUB_ACTIONS env variable (https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) in this commit: https://github.com/continuedev/continue/commit/2cf16cb52386c85e5e3c7873671b34c62816f9d2

**Comment by sevetseh28** [comment]
> [@thebabush](https://github.com/thebabush) Thanks for reporting this! I just switched the function to use GitHub's default GITHUB_ACTIONS env variable (https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) in this commit: [2cf16cb](https://github.com/continuedev/continue/commit/2cf16cb52386c85e5e3c7873671b34c62816f9d2)

Why not using the `CI` env var? I think it's not specific to Github Actions but any linux arm64 environment, right?

**Comment by sevetseh28** [comment]
Also, setting GITHUB_ACTIONS to true didn't work for me. Still getting this error
