### ISSUE TITLE
Error in Continue free trial server: 429 You exceeded your current quota

### ISSUE THREAD

**Issue by lokeswaran-aj** [continuedev/continue#891]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.3
- Continue: v0.8.12
- IDE: VS Code version 1.83.1
```

### Description

When I try to use Continue's Chat or code generator with OpenAI LLM, I get the following error:
`HTTP 500 Internal Server Error from https://node-proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_complete Error in Continue free trial server: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors`

### To reproduce

Open the VS code and send a "hi" message to Continue chat with OpenAI as the LLM.

### Log output

```Shell
==========================================================================
==========================================================================
Settings:
contextLength: 4096
model: gpt-4
maxTokens: 1024

############################################

<user>
hi
```

**Comment by sestinj** [comment]
@lokeswaran-aj this is now resolved
