### ISSUE TITLE
LMstudio error from empty content on assistant message

### ISSUE THREAD

**Issue by Phil-meredith** [continuedev/continue#894]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.3
- Continue: 0.0.27
- IDE:IntelliJ IDEA 2023.3.4
```

### Description

There is a closed issue https://github.com/continuedev/continue/issues/750

However - this issue still seems present (see the attached log output on issue) . Is there any work around (e.g. something I can add to the config.json or equiv) that will allow me to progress with this?

### Log output

```Shell
{
      "role": "user",
      "content": "test"
    }
  ],
  "model": "codellama-7b",
  "max_tokens": 1024,
  "stream": true
}
[2024-02-26 11:52:18.920] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}
```

**Comment by sestinj** [comment]
@Phil-meredith This is something that was solved in VS Code, but JetBrains was just behind for some time. We've now caught JetBrains up and will permanently keep it that way, but the newest version is currently available just in Early Access Program (EAP) for the next couple of days.

If you'd like to wait until the new version is fully released, it won't be long. If you'd like to try the EAP version you can download it either from here (https://plugins.jetbrains.com/plugin/22707-continue/edit/versions/eap)

or by going to settings -> plugins -> [gear icon] -> configure repositories -> add 'https://plugins.jetbrains.com/plugins/eap/list' and then you'll see 0.0.33 available after reloading

**Comment by Phil-meredith** [comment]
Heya thanks for the quick reply - I have moved up to the eap and that does indeed fix it!
