### ISSUE TITLE
VSCode Codeium Indexing frezzes on media files.

### ISSUE THREAD

**Issue by DaniGTA** [continuedev/continue#896]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: v0.9.71
- IDE: VSCode 1.87.0-insider
- Ollama v0.1.19
```

### Description

If there is a file of the type mp4,mp3,wav,jpg or png the indexing dont make any progress anymore and freezes. 

And a second bug is while continue is indexing paste in vscode is blocked and every formatter is blocked by this progress. This makes editing while indexing impossible.

A quick fix is currently to ignore these type of files with .continueignore

```
**/*.jpg
**/*.png
**/*.webp
**/*.svg
**/*.mp4
**/*.gif
**/*.wav
**/*.mp3
```

### To reproduce

Add a media file to a reposetory and let codeium indexing.

**Comment by sestinj** [comment]
@DaniGTA I just added .wav and .webp to the list of file types that we were ignoring (https://github.com/continuedev/continue/commit/315d179d829de4df88606af56673e7b4cb3ada0d).

I also triple-checked with breakpoints in multiple places that any file type in this list does not get indexed.
