### ISSUE TITLE
Add support for Jira REST API version 2

### ISSUE THREAD

**Issue by theBenForce** [continuedev/continue#898]
Jira datacenter version only supports REST API v2.

**Actions**
- Investigate the differences between REST API v2 and v3
- Add a parameter to the settings to specify an API version
  - If no parameter is provided, default to v3
- Create a helper that abstracts the differences between v2 and v3
- Update documentation
- Update schema

**References**
- [Jira Data Center REST API](https://docs.atlassian.com/software/jira/docs/api/REST/9.14.0/)

_Originally posted by @benedict-lee in https://github.com/continuedev/continue/issues/860#issuecomment-1965883778_

**Comment by benedict-lee** [comment]
@theBenForce I don't have permission to assign either.

@sestinj Please check this.

**Comment by sestinj** [comment]
@theBenForce Just assigned. Let me know if I can help with this!
