### ISSUE TITLE
Empty messages can break the markup of continued AI replies and might confuse the AI

### ISSUE THREAD

**Issue by TiagoTiago** [continuedev/continue#900]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Linux
- Continue: v0.8.12
- IDE: VSCodium (copy/pasted from the About window:
> Version: 1.86.2
> Release: 24054
> Commit: 1d6ffebc0098f8a61639c4b637922c87a114d4bc
> Date: 2024-02-23T01:31:11.072Z
> Electron: 27.2.3
> ElectronBuildId: undefined
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux x64 5.15.0-97-generic
)
```

### Description

Sometimes when the AI ends the message prematurely for whatever reason, in the lack of a "please do go on" button, it seems the only option is to just send an empty message; but this seems to sometimes mess up the formatting (I imagine due to the empty user message left in the middle and confusions about unclosed or unopened mark-up tags), and might on occasion confuse the AI (seems the issue there would probably be the extraneous tokens of beginning and ending messages and roles and stuff getting injected in the middle of the reply instead of giving the AI the impression it's just continuing it's own reply)

### To reproduce

Not 100% sure how to repro it consistently. But it seems you got great odds if the reply you're gonna get fom the AI will contain long code blocks that might end up getting cut short; and then you just hit Enter on the user follow-up textbox leaving it empty. Like for example, select a long span of uncommented code, Ctrl-M it, and ask the AI to add descriptive comments explaining each line.

**Comment by sestinj** [comment]
Going through old issues, and I believe this has long since been solved. Going to close, but if you experience anything similar, please feel free to re-open!
