### ISSUE TITLE
Please add support for Groq, so that we can enjoy the fastest inference possible :-))

### ISSUE THREAD

**Issue by HakaishinShwet** [continuedev/continue#901]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

No one Right now provides fast inference like groq and they are use best open source models with are more capable than gpt 3.5 plus in some case beat gpt 4 plus there price for token generation is pretty great so many will want to use it and they have api too so in this solution we can use like open ai gpt etc

### Solution

just implement groq api system, they  provide easy api Hope to see it soon in this awesome foss solution  :-))
Thankyou very much

**Comment by sestinj** [comment]
@HakaishinShwet [Groq implements an OpenAI-compatible API](https://console.groq.com/docs/quickstart), which means that you can already use it with Continue if you have an API key by doing something like here: https://continue.dev/docs/reference/Model%20Providers/openai#openai-compatible-servers--apis

As for using Groq by default, we'd love to do this, but will have to wait until we are given access : )

Let me know if you have any questions!

**Comment by HakaishinShwet** [comment]
@sestinj thanks for guiding. was just curious about that "given access" part so if possible can you explain little bit about it :-))

**Comment by sestinj** [comment]
@HakaishinShwet We now have access, but Groq has very low rate limits, so we won't be able to serve it through our free trial. If you can obtain your own API key though, you will be able to use it with Continue by adding something like the following to your config.json:

```json
{
  "models": [
    {
      "title": "Groq",
      "provider": "openai",
      "model": "mixtral-8x7b-32768",
      "apiKey": "EMPTY",
      "apiBase": "https://api.groq.com/openai/v1"
    }
  ]
}
```
