### ISSUE TITLE
Feature Request - Addition of Custom Headers or Support for Authentication in Ollama 

### ISSUE THREAD

**Issue by a8851625** [continuedev/continue#903]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

At present, Ollama provider lacks the functionality to include custom headers or support authentication. This limitation hinders users who require additional customization and authentication methods beyond the current capabilities of the system.

### Solution

I recommend the implementation of a feature that allows users to include custom headers in their requests or supports authentication methods such as openai's API key. This enhancement would significantly improve the flexibility and security of Ollama, catering to a broader range of user requirements.

**Comment by sestinj** [comment]
@a8851625 this is possible using the requestOptions.headers property on any model object in config.json. I've updated the documentation to make this more clear. Going to close the issue, but please let me know if you have any more questions about this!

https://continue.dev/docs/model-setup/configuration#authentication

**Comment by a8851625** [comment]
thanks!!!
