### ISSUE TITLE
VSCodium only offers up to v0.8.2

### ISSUE THREAD

**Issue by carcinocron** [continuedev/continue#924]
### Before submitting your bug report

- [X] I believe this is a bug.
    - [x] not joining a stupid discord 
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.2.1
- Continue: not installed yet
- IDE: VSCodium
```

### Description

<img width="1114" alt="Screenshot 2024-03-03 at 10 57 22 AM" src="https://github.com/continuedev/continue/assets/4094542/8d1e18f5-8cd0-4ffb-91de-c3af219ebb7a">

**Comment by sestinj** [comment]
@carcinocron I just double-checked and verified that all version are available on the Open VSX Registry, which I assume is where VS Codium would download its extensions from: https://open-vsx.org/extension/Continue/continue

Either you may have a separate registry, or is there any chance you are just looking at the changelog, which only shows changes up to version 0.8.2? In the screenshot below you can see that even though this is the latest version, the changelog shows 0.8.2. This is a shortcoming of course, and I'll make sure to update the changelog.

<img width="1099" alt="Screenshot 2024-03-03 at 6 55 52 PM" src="https://github.com/continuedev/continue/assets/33237525/dd9580ae-f07f-47a6-b703-f2c38f0ff17b">

**Comment by sestinj** [comment]
@carcinocron It looks like the latest version is available after double-checking, and I've made sure to update the change log for newer versions (and will continue to do this). Going to close the issue, but if you end up finding out that the latest version is definitely not available, please re-open
