### ISSUE TITLE
Claude 3 Opus uses incorrect endpoint url

### ISSUE THREAD

**Issue by shorn-gnosis** [continuedev/continue#933]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS
- Continue: latest
- IDE: VSCode
```

### Description

When adding anthropic claude 3 opus model, and setting the baseurl in the config, Continue always appends `/completions` which results in an incorrect base URL.

The correct base URL for Opus should be: `"apiBase": "https://api.anthropic.com/v1/messages",` not `/completions`.

See ref docs here: https://docs.anthropic.com/claude/reference/messages_post

### To reproduce

1. add anthropic claude 3 opus as llm model 
2. send user input
3. see attached screengrabs:

![Screenshot 2024-03-06 at 10 15 24](https://github.com/continuedev/continue/assets/141832818/d4094ae0-957c-4b4c-8fa9-b8a12fc4f372)
![Screenshot 2024-03-06 at 10 10 05](https://github.com/continuedev/continue/assets/141832818/039157c1-0482-42ad-96ed-de1a1732cd15)

**Comment by mathiasleroy** [comment]
I switched to pre-release version and I'm getting this:
![image](https://github.com/continuedev/continue/assets/2870437/bde5a339-03e5-4eb6-8d0d-a5a175c7cfbf)

**Comment by sestinj** [comment]
@mathiasleroy I think the empty messages error may be due to an error earlier in the session. It will likely be resolved by starting a new session with cmd/ctrl+L and then trying again, but I also published a fix for that exact bug in the latest pre-release so it should work either way. Please let me know if you still run into this! If not I'll soon close the issue

**Comment by mathiasleroy** [comment]
@sestinj my issue resolved itself a few days later, claude all good now. (gpt4vision not working anymore)

**Comment by sestinj** [comment]
@mathiasleroy I'm closing this since Opus sounds resolved, but if you want please open another issue with the details of gpt-v-vision and we'll gladly help out
