### ISSUE TITLE
Plugin steals focus in all JetBrains IDEs on Linux

### ISSUE THREAD

**Issue by ostapiuk** [continuedev/continue#938]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04.4 (Kubuntu)
- Continue: 0.0.33 and 0.0.34
- IDE: JetBrains PyCharm, RubyMine, IntelliJ, WebStorm - all 2023.3.4
```

### Description

When the plugin's side panel is open, it steals focus preventing me from being able to edit code, copy/paste from the editor pane, or access menus from the top bar.  If I click in the editor, the cursor appears momentarily, then disappears.  If I type after clicking in the editor, the text appears in the plugin panel.  When I close the plugin's side panel, everything works again.  This was not a problem before I upgraded to version 0.0.33.

### To reproduce

1. Open the plugin side panel
2. Click in the editor and start typing or try selecting code to copy

**Comment by thomassteinreiter** [comment]
I can confirm this issue with:
```
- OS: Manjaro 23.1.3 (KDE) and AlmaLinux 8.9 (Gnome)
- Continue: 0.0.34
- IDE: JetBrains IntelliJ and RustRover
```

**Comment by swiatek25** [comment]
Same here: https://github.com/continuedev/continue/issues/961

**Comment by OwenRay** [comment]
same here, makes the plugin pretty much unusable

**Comment by swiatek25** [comment]
@OwenRay I switched to CodeGPT for that reason.

**Comment by sestinj** [comment]
Problem has been solved, and the new version will be available on the store in just a day or two. I'll share another update here when it's ready!

**Comment by thomassteinreiter** [comment]
I can confirm that the focus issue is fixed for me in version 0.0.39. Thank you very much!

**Comment by swiatek25** [comment]
Thanks!

**Comment by ostapiuk** [comment]
0.0.39 is working for me too.  Thanks for the fix!
