### ISSUE TITLE
Support for Google models through Vertexai 

### ISSUE THREAD

**Issue by arian81** [continuedev/continue#942]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

A lot of enterprise have access to Gemini models through Vertexai which doesn't have an api key. It would be very useful to add support for using continue with that.

### Solution

Add support for Vertexai

**Comment by sestinj** [comment]
@arian81 Is that similar to [this](https://github.com/continuedev/continue/blob/main/core/llm/llms/Gemini.ts), or something different? Would love to have this

**Comment by arian81** [comment]
> @arian81 Is that similar to [this](https://github.com/continuedev/continue/blob/main/core/llm/llms/Gemini.ts), or something different? Would love to have this

It should be very similar an access token from gcloud cli can be used as api key. What I don't really get is how to set a region and projectid. Because it's mentioned in the code but can't be set in config file. Also when I tried to run a Gemini model it calls a different endpoint than the one defined in this file.

**Comment by sestinj** [comment]
I'm going to close this in favor of a more recent version that just happens to have a bit more info attached: https://github.com/continuedev/continue/issues/1573
