### ISSUE TITLE
[CON-218] Continue doesn't handle rate-limiting for embeddings providers

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#943]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue:*
- IDE:*
```

### Description

Continue will sometimes receive 429 errors from OpenAI, etc.. when generating embeddings for the entire codebase. Just need to add basic exponential backoff

### To reproduce

Change embeddingsProvider

<sub>[CON-218](https://linear.app/continue/issue/CON-218/continue-doesnt-handle-rate-limiting-for-embeddings-providers)</sub>

**Comment by Iamshankhadeep** [comment]
@sestinj can I have a go on this issue ?

**Comment by sestinj** [comment]
@Iamshankhadeep Absolutely, would love help here! Important files are in core/indexing/embeddings, each just has an embed function. Probably you could get away with making a single rate-limiting utility and using it for all

**Comment by Iamshankhadeep** [comment]
@sestinj we probably don't need exponential backoff for this `TransformersJsEmbeddingsProvider` right?

**Comment by sestinj** [comment]
Yeah, that's correct
