### ISSUE TITLE
vscode - inline tip always shown

### ISSUE THREAD

**Issue by yuuuxt** [continuedev/continue#945]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:win10 x4=64
- Continue:v0.8.16
- IDE: vscode
```

### Description

`continue.showInlineTip` should hide continue tips, but it's always shown.

### To reproduce

![temp](https://github.com/continuedev/continue/assets/3153534/df9bcc5c-221e-4f18-abca-f3231118149c)

**Comment by sestinj** [comment]
@yuuuxt the "Inline Tip" refers to a different thing that shows up when you highlight code, but I see why these would be expected to go together. Fixed in this commit: https://github.com/continuedev/continue/commit/f218eacce38cbd6b94b594d4ab63ee0ef2318794
