### ISSUE TITLE
Link config.json sections to relevant documentation

### ISSUE THREAD

**Issue by chriscerie** [continuedev/continue#949]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Manually navigating to the relevant documentation for `config.json` sections (e.g., `customCommands`, `contextProviders`) takes a nontrivial amount of time.

### Solution

The hover text should include links to the relevant documentation.

![image](https://github.com/continuedev/continue/assets/51393127/34dc55a3-63ae-40b3-be7f-10e29b1a2b88)

**Comment by sestinj** [comment]
@chriscerie this is a great detail to improve! thanks for the idea

changes made here: https://github.com/continuedev/continue/commit/b7997b8ec66932f5d7ee6bca8bf12b034ba983e2
