### ISSUE TITLE
Remove paste and cut options from vscode right click

### ISSUE THREAD

**Issue by chriscerie** [continuedev/continue#950]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

It's not obvious what paste and cut options do when you right click in the Continue window as the llm's outputted text is immutable.

![image](https://github.com/continuedev/continue/assets/51393127/7e8f1903-c36c-4c88-a77d-e5de5f207fd4)

### Solution

Remove the cut and paste options when right clicking inside the Continue window but outside the input box.

**Comment by sestinj** [comment]
@chriscerie Unfortunately this is a detail determined by VS Code. While we can add something custom like "Share Session", we can't remove the default options. Going to close the issue as unsolvable for the foreseeable future, but thanks for bringing it up!
