### ISSUE TITLE
A way to disable hints inlined in the code

### ISSUE THREAD

**Issue by tomaszs** [continuedev/continue#954]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

![image](https://github.com/continuedev/continue/assets/834977/940e1dcb-d7ec-457e-a377-0dc22f85c294)

### Solution

A checkbox or parameter to disable these hints, they ruin zen mode

**Comment by sestinj** [comment]
@tomaszs If you hover over the tooltip there is a link you can click to disable it. This is also possible in VS Code settings

**Comment by sestinj** [comment]
Good call, I made it a bit more clear: https://github.com/continuedev/continue/commit/740d03467c1ef5801664638204f2fcae3456a4d2
