### ISSUE TITLE
Releases on Github

### ISSUE THREAD

**Issue by tmibkr** [continuedev/continue#958]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Upgrading to new versions in a restricted work environment is terribly slow due to bureaucracy. However, there is a fast path to upgrade through pre-approved Github release channels (https://github.com/continuedev/continue/releases)

### Solution

Plugin/extension releases for VSCode and IntelliJ should be made available via Github releases (in addition to how they are currently released through the respective marketplaces).

**Comment by sestinj** [comment]
@tmibkr you can now find the most recent JetBrains and VS Code versions on GitHub Releases (https://github.com/continuedev/continue/releases). We'll continue to publish all main (not pre-release) versions automatically on this page

**Comment by tmibkr** [comment]
This is great, already have gotten value from having releases here. Thank you!
