### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by pykeras** [continuedev/continue#962]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Custom font size for extension

### Solution

It would be very helpful if there was a way to change the font size of the output.

**Comment by figuerascarlos** [comment]
would be really nice to be able to set the font size independently. we can use cmd+ or cmd- but that affects the entire UI in the editor.

**Comment by CodeToFreedom** [comment]
If adding a font size option in the GUI is too complex, I would appreciate adding it to the ContinueDev text file config settings as a quick fix. 

I use PyCharm on Linux, and the sidebar chat panel for ContinueDev Chat is extremely small. In my case adjusting the Pycharm editor font size does not affect the chat window at all, which appears to be around size 8 or 10.
The font size makes it hard to read and nearly unusable. 

I spent multiple hours changing every font size setting in linux that I could find as well as every font size setting in pycharm but without any effect. I also restartet the IDE after making changes. Thanks a lot for your efforts.

**Comment by sestinj** [comment]
Appreciate all of the feedback on this! I'll be adding it for the next release of JetBrains, as well as VS Code around the same time

**Comment by shagratt** [comment]
I totally agree!! I barely see the answers. I keep using the models outside because of this.
Just add a custom font size in the configuration please!!!

**Comment by mystico53** [comment]
I still cant find a fonz size setting. thanks!

**Comment by sestinj** [comment]
@mystico53 this can be edited in "ui.fontSize" in config.json: https://docs.continue.dev/reference/config

**Comment by levicki** [comment]
@sestinj There seems to be a bug with this setting (or I might be doing something wrong):

 - I set the `ui.fontSize` as described in `config.json`.
 - I start VSCode and nothing changes when Continue is shown &mdash; the font size is the same
 - I close VSCode and start it again and only on second launch the font size actually changes

I tried this multiple times with existing session and font size only changes every second VSCode launch after editing `config.json`.

**Comment by chrisjohneder** [comment]
how about font style or type of the code block can i change it?

**Comment by nrgbistro** [comment]
I agree here, I don't like the default Times New Roman font used for displaying code in the chat window, it would be nice if I could set a custom font instead

![Image](https://github.com/user-attachments/assets/046c1d93-9c8a-489f-81cd-edcaf839fa94)

**Comment by corgan2222** [comment]
and i thought it was a bug :)
the code display in Times New Roman bothers me too. 
Would be great if you could change it!

**Comment by donwrightdesigns** [comment]
> ### Validations
> * [x]  I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions[x]  I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement
> 
> ### Problem
> Custom font size for extension
> 
> ### Solution
> It would be very helpful if there was a way to change the font size of the output.

I can't "see" changes I try to make - but managed to (somehow) accidentally change my chat window font to 144px - now its totally unusable -

**Comment by donwrightdesigns** [comment]
### scratch that - after restarting - its now at  1441 px font size

**Comment by levpa** [comment]
This thing just not working ))) on Windows/WSL, e.t.c.

<img width="896" height="203" alt="Image" src="https://github.com/user-attachments/assets/1f1b7bbc-aeef-4cd5-af70-c1be54471724" />

**Comment by baydemirytu** [comment]
> This thing just not working ))) on Windows/WSL, e.t.c.
> 
> <img width="896" height="203" alt="Image" src="https://github.com/user-attachments/assets/1f1b7bbc-aeef-4cd5-af70-c1be54471724" />

This works but it does not show what you type. If you type something and reload the VS Code font size actually changes 😄
