### ISSUE TITLE
Fully opt out of telemetry and prompt/completion data collection

### ISSUE THREAD

**Issue by Ludecan** [continuedev/continue#965]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi, we're evaluating adopting the use of Continue for having locally hosted code assistants in clients having strict no code sharing policies, which rule-out options such as Github Copilot.

We're analyzing the telemetry and logging functionalities currently present in Continue, particularly [useChatHandler.ts](https://github.com/continuedev/continue/blob/main/gui/src/hooks/useChatHandler.ts) which seems to do the hooking on the chat UI, and found the following:

1. Logging User Inputs and LLM Prompts: The [streamResponse](https://github.com/continuedev/continue/blob/16c9b34e6005f3f9ae7be40f0ff0b221b32d09ca/gui/src/hooks/useChatHandler.ts#L170) function captures user inputs and, potentially, the prompts sent to the LLM, which could include both input and output code.

2. Logging LLM Responses: In the [_streamNormalInput](https://github.com/continuedev/continue/blob/16c9b34e6005f3f9ae7be40f0ff0b221b32d09ca/gui/src/hooks/useChatHandler.ts#L68) functions, the prompts and completions received from the LLM (or the result of executing slash commands) are logged via `addLogs`.

3. Error Logging: The streamResponse function also has a catch block that captures and logs errors to the IDE and other potential listeners. This indicates that not just successful interactions but also errors encountered during the communication with the LLM are logged, which could include errors related to LLM prompts/responses.

4. In the [stateSlice.ts](https://github.com/continuedev/continue/blob/main/gui/src/redux/slices/stateSlice.ts) file, another use of the `addLogs` function seems to [log the history of user prompts](https://github.com/continuedev/continue/blob/16c9b34e6005f3f9ae7be40f0ff0b221b32d09ca/gui/src/redux/slices/stateSlice.ts#L157).

Would it be possible to implement a mechanism to fully opt out of these and remove the LLM input/response from the exception caching to adhere to these security principles?

### Solution

Add an extension setting to allow opting out of prompt/completion data collection and remove the LLM response from exception catching.

**Comment by sestinj** [comment]
Hi @Ludecan, first just to address each point-by-point:

1. As of this commit (https://github.com/continuedev/continue/commit/09c24b4f89a73a7116efd98b51f4d8cef79a276d), which is currently in pre-release and will be fully released tomorrow, we will no longer collect any prompts. Even before, this info wasn't used and was just legacy code from many months ago.
2. You can see [here](https://github.com/continuedev/continue/blob/16c9b34e6005f3f9ae7be40f0ff0b221b32d09ca/gui/src/redux/slices/stateSlice.ts#L151) in the definition of addLogs that this is not actually related to telemetry, though it is perhaps poorly named. The purpose of this function is to collect prompt/completion pairs only for the end user to view in the UI
3. I believe you are asking about [these two lines](https://github.com/continuedev/continue/blob/16c9b34e6005f3f9ae7be40f0ff0b221b32d09ca/gui/src/hooks/useChatHandler.ts#L204-L207) in the catch block. These are logged only to the developer tools console, never leaving the machine. Could you help me understand why you would like to avoid print statements?
4. See above about addLogs. If it would make the meaning of this function more clear, I am happy to rename it

And assuming you want to opt-out of all telemetry, this can be done by setting `"allowAnonymousTelemetry": false` in `config.json`, *or* by going to VS Code settings and unchecking the box for "Telemetry Enabled"

<img width="920" alt="Screenshot 2024-03-15 at 12 40 44 AM" src="https://github.com/continuedev/continue/assets/33237525/1f12cdbe-697f-4d6f-915d-30d3aab9892e">

**Comment by Ludecan** [comment]
Nice, it's great to hear about 1!

Regarding 2 and 4, ok, I see, the name and dispatch to the redux store threw me off, but if I get what you're saying correctly, the addLogs function is adding the prompt/response to the UI's state?

Regarding 3, the issue was if there was something like a global exception handler that could be catching the error, but I just followed through the code and indeed as you say, the `postToIDE` function never leaves the system. This should be fine too.

I think with the PR you mentioned for 1 and the clarifications for 2, 3 and 4 we should be good to go.

Thanks for your quick responses, we'll be waiting for tomorrow's release.
