### ISSUE TITLE
Endless prompts for GitHub authentication

### ISSUE THREAD

**Issue by andrewbrey** [continuedev/continue#966]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Linux (Pop_OS! 22.04)
- Continue: v0.9.85 prerelease
- IDE:VS Code (1.87.2)
```

### Description

Every time I launch vscode and the extension activates, I am prompted to allow Continue to sign in to GitHub, even when I choose `Cancel`. I have no idea _why this extension even wants to sign in to GitHub_ (was a feature recently added that demands it? If so, why am I being prompted for authentication without ever telling me about a feature that leverages it..).

I would prefer if the extension did not prompt me to sign in every time I sign in, and if I choose not to allow sign in, it should respect that choice until I take action to change my mind.

![auth](https://github.com/continuedev/continue/assets/34140052/772df5cb-7039-4bbd-98b0-673afbae9c33)

### To reproduce

Simply open vscode and let the extension activate.

**Comment by catdalfonso** [comment]
I'm seeing likewise on MacOS on the `v0.9.85 prerelease` release.  I'm also not sure why this is requesting Github login.

**Comment by sestinj** [comment]
@andrewbrey @catdalfonso Just fixed and pushing a new release in a minute, thank you for the report! This was for an optional config syncing service we are working on, and were mistakenly triggering login for.

Login is not necessary to use Continue, and that is not the plan. Sorry for the distraction!

And no need to disable remote config sync—other than this mistake you've noted, we won't sync unless a valid URL+token is provided by the user.

**Comment by andrewbrey** [comment]
@sestinj thank you very much for the quick fix! :rocket:

**Comment by PierreMesure** [comment]
Still getting this popup, not sure how to deactivate it.

**Comment by fpreiss** [comment]
> Still getting this popup, not sure how to deactivate it.

Same here on linux (both: v0.8.25 and v0.9.124 (pre-release))

**Comment by diyfr** [comment]
Same problem on Windows  :  v0.9.147 (pre-release)
![image](https://github.com/continuedev/continue/assets/12012402/06b3dce0-0306-4cb2-9067-f3e315307e87)

**Comment by pjv** [comment]
Macos v0.9.147 (pre-release)

<img width="251" alt="SCR-20240530-gadd" src="https://github.com/continuedev/continue/assets/327716/0e163f38-77a4-4b3c-831e-e574f5755451">

**Comment by vikramsg** [comment]
Getting this on Mac, v0.8.38. This is becoming annoying enough for me to consider disabling this extension.

**Comment by pjv** [comment]
For me with `v0.9.150 (pre-release)` this issue seems to be kinda fixed except that after leading me through a wizard that let me tell the plugin that I wasn’t interested in entering my github or openAI credentials, the update re-wrote parts of my `config.json` assuming that the ollama instance I wanted to connect to was running on my workstation (it’s not) and so I needed to hand-modify the config to use the appropriate `apiBase` for where I have ollama running.

**Comment by sestinj** [comment]
This should all actually be cleaned up now, and since there hasn't been another update in 3 weeks I think that's probably proven true.  If for some reason I'm wrong, please tag me here and we'll re-open to get it fixed right away

**Comment by Kaschi14** [comment]
@sestinj 
On macOS with version 0.8.46 the bug still appears for my colleague. For me, also on a mac, it works as expected. I've the same  continue version as he does. We're both using vscode.
