### ISSUE TITLE
[CON-53] Little things we've noticed

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#97]
* [ ] Text input not cleared when Continue button pressed
* [X] Command-K doesn't show the panel if it isn't open
* [ ] Tabbing sometimes wrong on completion?
* [X] Arrow up for past commands
* Replay button?
* [ ] Step in progress, expected wait time \[predict from length of highlighted range being generated\]
* [X] If you send another message before the description of previous has loaded, does it maybe not load? Or rate limiting? Need to display "Error loading description" and some fallback.
* [X] Deterministic fix for when it outputs triple-ticks surrounding code
* Handle errors higher up - should still show output, at least to us. Maybe make this happen in server folder.
* [X] Use same Continue logo from website for button in extension
* [X] move clear button to a slash command
* move docs button to a slash command
* [X] move feedback button to a slash command
* [X] update side bar icon to be play icon from website
* [X] allow shift enter to create new lines in the box (instead of having it click the `continue` button like it does currently)
* [X] you can't exit feedback box without submitting feedback

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-53](https://linear.app/continue/issue/CON-53/little-things-weve-noticed)</sub>

**Comment by sestinj** [comment]
@TyDunn we'll probably notice small issues as we're completing our tasks. Let's accumulate them here, then can prioritize a bit later.

**Comment by TyDunn** [comment]
@sestinj I moved my little things here, since I had accidentally put them somewhere else
