### ISSUE TITLE
intelliJ plug-in packaging steps

### ISSUE THREAD

**Issue by Andyxion** [continuedev/continue#981]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hello, I would like to know the intellij plug-in packaging steps. I modified a question and wanted to try to see if it was successful. I used ./gradlew buildPlugin to package it. After installation, I found that darwin-arm64, darwin-x64, win32-x64, build, index.js and other files were missing from the core folder in the installation directory. , making it unusable. When importing intelliJ IDEA, the following error message appears
<img width="1102" alt="截屏2024-03-18 11 30 54" src="https://github.com/continuedev/continue/assets/18701369/4989fcdc-29be-4963-b1bf-340710f903a8">

**Comment by sestinj** [comment]
@Andyxion I just added a section to our CONTRIBUTING.md: https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#jetbrains

Hopefully this is helpful! It's new so if you think I missed anything or the setup process still doesn't work, please let me know

**Comment by hu2013** [comment]
> @Andyxion I just added a section to our CONTRIBUTING.md: https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#jetbrains
> 
> Hopefully this is helpful! It's new so if you think I missed anything or the setup process still doesn't work, please let me know

Hi,

**Comment by shuidie888** [comment]
在 Intellij IDE 打包时core 包下的内容缺失是什么问题

**Comment by sestinj** [comment]
I made some further updates a ways back that I think will allow "Build Plugin" to automatically show up, but another way to trigger this is `./gradlew build` from the extensions/intellij directory
