### ISSUE TITLE
Debug build error

### ISSUE THREAD

**Issue by pzaback** [continuedev/continue#985]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.4
- Continue: 0.9.90
- IDE:
```

### Description

![ContinueDebugBuildError](https://github.com/continuedev/continue/assets/5798247/9e13e0c1-bf5c-4970-a5c8-b568d7092b7a)
When trying to run the extension in debug mode, the attached error message appears in the terminal

### To reproduce

1. Enter Run and Debug Mode
2. Select Extension (VSCode)
3. Click the button to Start Debugging
4. After some time, error appears

**Comment by sestinj** [comment]
Thanks for the PR on this! Just a merge gone wrong
