### ISSUE TITLE
Too manu Request pop not handled 

### ISSUE THREAD

**Issue by RohitHattimare** [continuedev/continue#993]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: windows 
- Continue:0.90.0
- IDE:VSCode
```

### Description

notificationsAlerts.ts:42 Continue error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat  {"message":"Too many requests. Please try again later."}

### To reproduce

when asking prompt its showing this issue

**Comment by sestinj** [comment]
@RohitHattimare this should now be resolved, can you verify that the problem is gone?

**Comment by SoumyaSubhrajit** [comment]
I got the same error, I think this issue is not solve yet.

**Comment by RohitHattimare** [comment]
> I got the same error, I think this issue is not solve yet.

No problem still persists, unable to prompt anything

**Comment by ameetqyrus** [comment]
Yes. Same here. Still encountering this issue.

**Comment by sestinj** [comment]
@RohitHattimare @ameetqyrus sorry for the confusion. This should now truly be solved, as long as you are on the latest version. This was a false positive on a safeguard to prevent abuse.

If you use your own API key or a local LLM, this will never happen

**Comment by RohitHattimare** [comment]
working Fine now

**Comment by gabrielboeker** [comment]
i still have the issue even when providing my own mistral/codestral API key

**Comment by DucDuong97** [comment]
Just caught the same issue
```
HTTP 429 Too Many Requests from https://codestral.mistral.ai/v1/fim/completions {"message":"API rate limit exceeded"}
```

**Comment by soundnotation** [comment]
Same here:
```
HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim Rate exceeded.
```

**Comment by ArsenicBismuth** [comment]
Still got this issue with DeepSeek API (my own).

**Comment by mcpeixoto** [comment]
Any updates?

**Comment by robertschulze** [comment]
We have the same issue with GPT-4o on Azure (own API key).
